#include "StdAfx.h"
const char * (theNameVar_addon_ParamChantierPhotogram[65]) = {
"<GenCpp>\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"#include \"StdAfx.h\"\n",
"</Verbatim>\n",
"\n",
"<Verbatim File=\".cpp\">\n",
"#include \"addon_ParamChantierPhotogram.h\"\n",
"</Verbatim>\n",
"\n",
"  <Verbatim File=\".h.cpp\">\n",
"namespace NS_ParamChantierPhotogram{\n",
"</Verbatim>\n",
"\n",
"  <ParamFusionSift  Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"    <dossier Nb=\"1\" Type=\"string\"> </dossier>\n",
"    <dossierImg Nb=\"1\" Type=\"string\"> </dossierImg>\n",
"    <extensionSortie Nb=\"?\" Type=\"std::string\" Def=\"filtre\"> </extensionSortie>\n",
"    <firstfichier Nb=\"?\" Type=\"int\" Def=\"1\"> </firstfichier>	\n",
"    <lastfichier Nb=\"?\" Type=\"int\"> </lastfichier>	\n",
"    <SzMin Nb=\"?\" Type=\"int\" Def=\"50\"> </SzMin>	\n",
"    <NbObjMax Nb=\"?\" Type=\"int\" Def=\"10\"> </NbObjMax>\n",
"    <box Nb=\"?\" Type=\"Box2dr\" Def=\"Pt2dr(0.0,0.0),Pt2dr(10000.0,10000.0)\"> </box>\n",
"    <distIsol Nb=\"?\" Type=\"REAL\" Def=\"300\"> </distIsol>\n",
"    <ptppi Nb=\"?\" Type=\"int\" Def=\"10\"> </ptppi>	\n",
"    <mindistalign Nb=\"?\" Type=\"double\" Def=\"4\"> </mindistalign>	\n",
"    <filtre1 Nb=\"?\" Type=\"bool\" Def=\"false\"> </filtre1>\n",
"    <filtre2 Nb=\"?\" Type=\"bool\" Def=\"true\"> </filtre2>\n",
"    <filtre3 Nb=\"?\" Type=\"bool\" Def=\"false\"> </filtre3>\n",
"    <distIsol2 Nb=\"?\" Type=\"REAL\" Def=\"1000\"> </distIsol2>\n",
"    <rapide Nb=\"?\" Type=\"bool\" Def=\"false\"> </rapide>\n",
"    <aDistInitVois Nb=\"?\" Type=\"double\" Def=\"1\"> </aDistInitVois>\n",
"    <aFact Nb=\"?\" Type=\"double\" Def=\"10.0\"> </aFact>\n",
"    <aNbMax Nb=\"?\" Type=\"int\" Def=\"100\"> </aNbMax>\n",
"    <aNb1 Nb=\"?\" Type=\"int\" Def=\"10\"> </aNb1>\n",
"    <aNb2 Nb=\"?\" Type=\"int\" Def=\"20\"> </aNb2>\n",
"    <seuilCoherenceVois Nb=\"?\" Type=\"double\" Def=\"0.9\"> </seuilCoherenceVois>\n",
"    <seuilCoherenceCarre Nb=\"?\" Type=\"double\" Def=\"0.5\"> </seuilCoherenceCarre>	\n",
"    <aNb Nb=\"?\" Type=\"int\" Def=\"50\"> </aNb>\n",
"    <nbEssais Nb=\"?\" Type=\"int\" Def=\"25\"> </nbEssais>\n",
"    \n",
"    <affichImg Nb=\"*\">\n",
"      <image Nb=\"1\" Type=\"int\"> </image>\n",
"      <fichier Nb=\"1\" Type=\"std::string\"> </fichier>\n",
"    </affichImg>\n",
"    \n",
"    <affichPaire Nb=\"*\">\n",
"      <image1 Nb=\"1\" Type=\"int\"> </image1>\n",
"      <fichier1 Nb=\"1\" Type=\"std::string\"> </fichier1>\n",
"      <image2 Nb=\"1\" Type=\"int\"> </image2>\n",
"      <fichier2 Nb=\"1\" Type=\"std::string\"> </fichier2>\n",
"      <liste Nb=\"1\" Type=\"int\"> </liste>\n",
"      <trait Nb=\"?\" Type=\"bool\" Def=\"true\"> </trait>\n",
"    </affichPaire>	\n",
"  </ParamFusionSift>\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"};\n",
"</Verbatim>\n",
"  \n",
"</GenCpp>\n",
"\n",
"\n",
"","//#_-=+{}@$##$##@"};
