// File Automatically generated by eLiSe
#include "StdAfx.h"


class cEqAppui_PTInc_M2CStereographique_FishEye_10_5_5: public cElCompiledFonc
{
   public :

      cEqAppui_PTInc_M2CStereographique_FishEye_10_5_5();
      void ComputeVal();
      void ComputeValDeriv();
      void ComputeValDerivHessian();
      double * AdrVarLocFromString(const std::string &);
      void SetScNorm(double);
      void SetStereographique_FishEye_10_5_5_State_0_0(double);
      void SetXIm(double);
      void SetYIm(double);


      static cAutoAddEntry  mTheAuto;
      static cElCompiledFonc *  Alloc();
   private :

      double mLocScNorm;
      double mLocStereographique_FishEye_10_5_5_State_0_0;
      double mLocXIm;
      double mLocYIm;
};
