// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cEqAppui_Droite_NoDist__PProjInc_M2CDRad5.h"


cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::cEqAppui_Droite_NoDist__PProjInc_M2CDRad5():
    cElCompiledFonc(1)
{
   AddIntRef (cIncIntervale("Intr",0,10));
   AddIntRef (cIncIntervale("Orient",10,16));
   AddIntRef (cIncIntervale("Tmp_PTer",16,19));
   Close(false);
}



void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::ComputeVal()
{
   double tmp0_ = mCompCoord[10];
   double tmp1_ = mCompCoord[11];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = mCompCoord[16];
   double tmp4_ = mCompCoord[17];
   double tmp5_ = mCompCoord[18];
   double tmp6_ = sin(tmp0_);
   double tmp7_ = cos(tmp0_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = mCompCoord[12];
   double tmp10_ = mLocProjI_x*tmp3_;
   double tmp11_ = mLocProjP0_x+tmp10_;
   double tmp12_ = mLocProjJ_x*tmp4_;
   double tmp13_ = tmp11_+tmp12_;
   double tmp14_ = mLocProjK_x*tmp5_;
   double tmp15_ = tmp13_+tmp14_;
   double tmp16_ = mCompCoord[13];
   double tmp17_ = (tmp15_)-tmp16_;
   double tmp18_ = sin(tmp9_);
   double tmp19_ = -(tmp18_);
   double tmp20_ = -(tmp8_);
   double tmp21_ = cos(tmp9_);
   double tmp22_ = mLocProjI_y*tmp3_;
   double tmp23_ = mLocProjP0_y+tmp22_;
   double tmp24_ = mLocProjJ_y*tmp4_;
   double tmp25_ = tmp23_+tmp24_;
   double tmp26_ = mLocProjK_y*tmp5_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = mCompCoord[14];
   double tmp29_ = (tmp27_)-tmp28_;
   double tmp30_ = mLocProjI_z*tmp3_;
   double tmp31_ = mLocProjP0_z+tmp30_;
   double tmp32_ = mLocProjJ_z*tmp4_;
   double tmp33_ = tmp31_+tmp32_;
   double tmp34_ = mLocProjK_z*tmp5_;
   double tmp35_ = tmp33_+tmp34_;
   double tmp36_ = mCompCoord[15];
   double tmp37_ = (tmp35_)-tmp36_;
   double tmp38_ = -(tmp6_);
   double tmp39_ = tmp7_*tmp20_;
   double tmp40_ = tmp6_*tmp20_;
   double tmp41_ = tmp38_*tmp19_;
   double tmp42_ = tmp39_*tmp21_;
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = (tmp43_)*(tmp17_);
   double tmp45_ = tmp7_*tmp19_;
   double tmp46_ = tmp40_*tmp21_;
   double tmp47_ = tmp45_+tmp46_;
   double tmp48_ = (tmp47_)*(tmp29_);
   double tmp49_ = tmp44_+tmp48_;
   double tmp50_ = tmp2_*tmp21_;
   double tmp51_ = tmp50_*(tmp37_);
   double tmp52_ = tmp49_+tmp51_;
   double tmp53_ = tmp7_*tmp2_;
   double tmp54_ = tmp53_*(tmp17_);
   double tmp55_ = tmp6_*tmp2_;
   double tmp56_ = tmp55_*(tmp29_);
   double tmp57_ = tmp54_+tmp56_;
   double tmp58_ = tmp8_*(tmp37_);
   double tmp59_ = tmp57_+tmp58_;
   double tmp60_ = (tmp59_)/(tmp52_);
   double tmp61_ = tmp38_*tmp21_;
   double tmp62_ = tmp39_*tmp18_;
   double tmp63_ = tmp61_+tmp62_;
   double tmp64_ = (tmp63_)*(tmp17_);
   double tmp65_ = tmp7_*tmp21_;
   double tmp66_ = tmp40_*tmp18_;
   double tmp67_ = tmp65_+tmp66_;
   double tmp68_ = (tmp67_)*(tmp29_);
   double tmp69_ = tmp64_+tmp68_;
   double tmp70_ = tmp2_*tmp18_;
   double tmp71_ = tmp70_*(tmp37_);
   double tmp72_ = tmp69_+tmp71_;
   double tmp73_ = (tmp72_)/(tmp52_);

  mVal[0] = (mLocXIm-cos(mLocYIm)*(mLocNDP0_x+mLocNDdx_x*(tmp60_)+mLocNDdy_x*(tmp73_))-sin(mLocYIm)*(mLocNDP0_y+mLocNDdx_y*(tmp60_)+mLocNDdy_y*(tmp73_)))*mLocScNorm;

}


void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[10];
   double tmp1_ = mCompCoord[11];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = mCompCoord[16];
   double tmp4_ = mCompCoord[17];
   double tmp5_ = mCompCoord[18];
   double tmp6_ = sin(tmp0_);
   double tmp7_ = cos(tmp0_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = mCompCoord[12];
   double tmp10_ = mLocProjI_x*tmp3_;
   double tmp11_ = mLocProjP0_x+tmp10_;
   double tmp12_ = mLocProjJ_x*tmp4_;
   double tmp13_ = tmp11_+tmp12_;
   double tmp14_ = mLocProjK_x*tmp5_;
   double tmp15_ = tmp13_+tmp14_;
   double tmp16_ = mCompCoord[13];
   double tmp17_ = (tmp15_)-tmp16_;
   double tmp18_ = sin(tmp9_);
   double tmp19_ = -(tmp18_);
   double tmp20_ = -(tmp8_);
   double tmp21_ = cos(tmp9_);
   double tmp22_ = mLocProjI_y*tmp3_;
   double tmp23_ = mLocProjP0_y+tmp22_;
   double tmp24_ = mLocProjJ_y*tmp4_;
   double tmp25_ = tmp23_+tmp24_;
   double tmp26_ = mLocProjK_y*tmp5_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = mCompCoord[14];
   double tmp29_ = (tmp27_)-tmp28_;
   double tmp30_ = mLocProjI_z*tmp3_;
   double tmp31_ = mLocProjP0_z+tmp30_;
   double tmp32_ = mLocProjJ_z*tmp4_;
   double tmp33_ = tmp31_+tmp32_;
   double tmp34_ = mLocProjK_z*tmp5_;
   double tmp35_ = tmp33_+tmp34_;
   double tmp36_ = mCompCoord[15];
   double tmp37_ = (tmp35_)-tmp36_;
   double tmp38_ = -(tmp6_);
   double tmp39_ = tmp7_*tmp20_;
   double tmp40_ = tmp6_*tmp20_;
   double tmp41_ = tmp38_*tmp19_;
   double tmp42_ = tmp39_*tmp21_;
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = (tmp43_)*(tmp17_);
   double tmp45_ = tmp7_*tmp19_;
   double tmp46_ = tmp40_*tmp21_;
   double tmp47_ = tmp45_+tmp46_;
   double tmp48_ = (tmp47_)*(tmp29_);
   double tmp49_ = tmp44_+tmp48_;
   double tmp50_ = tmp2_*tmp21_;
   double tmp51_ = tmp50_*(tmp37_);
   double tmp52_ = tmp49_+tmp51_;
   double tmp53_ = tmp7_*tmp2_;
   double tmp54_ = tmp53_*(tmp17_);
   double tmp55_ = tmp6_*tmp2_;
   double tmp56_ = tmp55_*(tmp29_);
   double tmp57_ = tmp54_+tmp56_;
   double tmp58_ = tmp8_*(tmp37_);
   double tmp59_ = tmp57_+tmp58_;
   double tmp60_ = (tmp59_)/(tmp52_);
   double tmp61_ = tmp38_*tmp21_;
   double tmp62_ = tmp39_*tmp18_;
   double tmp63_ = tmp61_+tmp62_;
   double tmp64_ = (tmp63_)*(tmp17_);
   double tmp65_ = tmp7_*tmp21_;
   double tmp66_ = tmp40_*tmp18_;
   double tmp67_ = tmp65_+tmp66_;
   double tmp68_ = (tmp67_)*(tmp29_);
   double tmp69_ = tmp64_+tmp68_;
   double tmp70_ = tmp2_*tmp18_;
   double tmp71_ = tmp70_*(tmp37_);
   double tmp72_ = tmp69_+tmp71_;
   double tmp73_ = (tmp72_)/(tmp52_);
   double tmp74_ = -(1);
   double tmp75_ = tmp74_*tmp6_;
   double tmp76_ = -(tmp7_);
   double tmp77_ = tmp75_*tmp20_;
   double tmp78_ = tmp76_*tmp19_;
   double tmp79_ = tmp77_*tmp21_;
   double tmp80_ = tmp78_+tmp79_;
   double tmp81_ = (tmp80_)*(tmp17_);
   double tmp82_ = tmp75_*tmp19_;
   double tmp83_ = tmp82_+tmp42_;
   double tmp84_ = (tmp83_)*(tmp29_);
   double tmp85_ = tmp81_+tmp84_;
   double tmp86_ = ElSquare(tmp52_);
   double tmp87_ = cos(mLocYIm);
   double tmp88_ = tmp75_*tmp2_;
   double tmp89_ = tmp88_*(tmp17_);
   double tmp90_ = tmp53_*(tmp29_);
   double tmp91_ = tmp89_+tmp90_;
   double tmp92_ = (tmp91_)*(tmp52_);
   double tmp93_ = (tmp59_)*(tmp85_);
   double tmp94_ = tmp92_-tmp93_;
   double tmp95_ = (tmp94_)/tmp86_;
   double tmp96_ = tmp76_*tmp21_;
   double tmp97_ = tmp77_*tmp18_;
   double tmp98_ = tmp96_+tmp97_;
   double tmp99_ = (tmp98_)*(tmp17_);
   double tmp100_ = tmp75_*tmp21_;
   double tmp101_ = tmp100_+tmp62_;
   double tmp102_ = (tmp101_)*(tmp29_);
   double tmp103_ = tmp99_+tmp102_;
   double tmp104_ = (tmp103_)*(tmp52_);
   double tmp105_ = (tmp72_)*(tmp85_);
   double tmp106_ = tmp104_-tmp105_;
   double tmp107_ = (tmp106_)/tmp86_;
   double tmp108_ = sin(mLocYIm);
   double tmp109_ = tmp74_*tmp8_;
   double tmp110_ = -(tmp2_);
   double tmp111_ = tmp110_*tmp7_;
   double tmp112_ = tmp110_*tmp6_;
   double tmp113_ = tmp111_*tmp21_;
   double tmp114_ = tmp113_*(tmp17_);
   double tmp115_ = tmp112_*tmp21_;
   double tmp116_ = tmp115_*(tmp29_);
   double tmp117_ = tmp114_+tmp116_;
   double tmp118_ = tmp109_*tmp21_;
   double tmp119_ = tmp118_*(tmp37_);
   double tmp120_ = tmp117_+tmp119_;
   double tmp121_ = tmp109_*tmp7_;
   double tmp122_ = tmp121_*(tmp17_);
   double tmp123_ = tmp109_*tmp6_;
   double tmp124_ = tmp123_*(tmp29_);
   double tmp125_ = tmp122_+tmp124_;
   double tmp126_ = tmp2_*(tmp37_);
   double tmp127_ = tmp125_+tmp126_;
   double tmp128_ = (tmp127_)*(tmp52_);
   double tmp129_ = (tmp59_)*(tmp120_);
   double tmp130_ = tmp128_-tmp129_;
   double tmp131_ = (tmp130_)/tmp86_;
   double tmp132_ = tmp111_*tmp18_;
   double tmp133_ = tmp132_*(tmp17_);
   double tmp134_ = tmp112_*tmp18_;
   double tmp135_ = tmp134_*(tmp29_);
   double tmp136_ = tmp133_+tmp135_;
   double tmp137_ = tmp109_*tmp18_;
   double tmp138_ = tmp137_*(tmp37_);
   double tmp139_ = tmp136_+tmp138_;
   double tmp140_ = (tmp139_)*(tmp52_);
   double tmp141_ = (tmp72_)*(tmp120_);
   double tmp142_ = tmp140_-tmp141_;
   double tmp143_ = (tmp142_)/tmp86_;
   double tmp144_ = -(tmp21_);
   double tmp145_ = tmp74_*tmp18_;
   double tmp146_ = tmp144_*tmp38_;
   double tmp147_ = tmp145_*tmp39_;
   double tmp148_ = tmp146_+tmp147_;
   double tmp149_ = (tmp148_)*(tmp17_);
   double tmp150_ = tmp144_*tmp7_;
   double tmp151_ = tmp145_*tmp40_;
   double tmp152_ = tmp150_+tmp151_;
   double tmp153_ = (tmp152_)*(tmp29_);
   double tmp154_ = tmp149_+tmp153_;
   double tmp155_ = tmp145_*tmp2_;
   double tmp156_ = tmp155_*(tmp37_);
   double tmp157_ = tmp154_+tmp156_;
   double tmp158_ = (tmp59_)*(tmp157_);
   double tmp159_ = -(tmp158_);
   double tmp160_ = tmp159_/tmp86_;
   double tmp161_ = tmp145_*tmp38_;
   double tmp162_ = tmp21_*tmp39_;
   double tmp163_ = tmp161_+tmp162_;
   double tmp164_ = (tmp163_)*(tmp17_);
   double tmp165_ = tmp145_*tmp7_;
   double tmp166_ = tmp21_*tmp40_;
   double tmp167_ = tmp165_+tmp166_;
   double tmp168_ = (tmp167_)*(tmp29_);
   double tmp169_ = tmp164_+tmp168_;
   double tmp170_ = tmp21_*tmp2_;
   double tmp171_ = tmp170_*(tmp37_);
   double tmp172_ = tmp169_+tmp171_;
   double tmp173_ = (tmp172_)*(tmp52_);
   double tmp174_ = (tmp72_)*(tmp157_);
   double tmp175_ = tmp173_-tmp174_;
   double tmp176_ = (tmp175_)/tmp86_;
   double tmp177_ = tmp74_*(tmp43_);
   double tmp178_ = tmp74_*tmp53_;
   double tmp179_ = tmp178_*(tmp52_);
   double tmp180_ = (tmp59_)*tmp177_;
   double tmp181_ = tmp179_-tmp180_;
   double tmp182_ = (tmp181_)/tmp86_;
   double tmp183_ = tmp74_*(tmp63_);
   double tmp184_ = tmp183_*(tmp52_);
   double tmp185_ = (tmp72_)*tmp177_;
   double tmp186_ = tmp184_-tmp185_;
   double tmp187_ = (tmp186_)/tmp86_;
   double tmp188_ = tmp74_*(tmp47_);
   double tmp189_ = tmp74_*tmp55_;
   double tmp190_ = tmp189_*(tmp52_);
   double tmp191_ = (tmp59_)*tmp188_;
   double tmp192_ = tmp190_-tmp191_;
   double tmp193_ = (tmp192_)/tmp86_;
   double tmp194_ = tmp74_*(tmp67_);
   double tmp195_ = tmp194_*(tmp52_);
   double tmp196_ = (tmp72_)*tmp188_;
   double tmp197_ = tmp195_-tmp196_;
   double tmp198_ = (tmp197_)/tmp86_;
   double tmp199_ = tmp74_*tmp50_;
   double tmp200_ = tmp109_*(tmp52_);
   double tmp201_ = (tmp59_)*tmp199_;
   double tmp202_ = tmp200_-tmp201_;
   double tmp203_ = (tmp202_)/tmp86_;
   double tmp204_ = tmp74_*tmp70_;
   double tmp205_ = tmp204_*(tmp52_);
   double tmp206_ = (tmp72_)*tmp199_;
   double tmp207_ = tmp205_-tmp206_;
   double tmp208_ = (tmp207_)/tmp86_;
   double tmp209_ = mLocProjI_x*(tmp43_);
   double tmp210_ = mLocProjI_y*(tmp47_);
   double tmp211_ = tmp209_+tmp210_;
   double tmp212_ = mLocProjI_z*tmp50_;
   double tmp213_ = tmp211_+tmp212_;
   double tmp214_ = mLocProjI_x*tmp53_;
   double tmp215_ = mLocProjI_y*tmp55_;
   double tmp216_ = tmp214_+tmp215_;
   double tmp217_ = mLocProjI_z*tmp8_;
   double tmp218_ = tmp216_+tmp217_;
   double tmp219_ = (tmp218_)*(tmp52_);
   double tmp220_ = (tmp59_)*(tmp213_);
   double tmp221_ = tmp219_-tmp220_;
   double tmp222_ = (tmp221_)/tmp86_;
   double tmp223_ = mLocProjI_x*(tmp63_);
   double tmp224_ = mLocProjI_y*(tmp67_);
   double tmp225_ = tmp223_+tmp224_;
   double tmp226_ = mLocProjI_z*tmp70_;
   double tmp227_ = tmp225_+tmp226_;
   double tmp228_ = (tmp227_)*(tmp52_);
   double tmp229_ = (tmp72_)*(tmp213_);
   double tmp230_ = tmp228_-tmp229_;
   double tmp231_ = (tmp230_)/tmp86_;
   double tmp232_ = mLocProjJ_x*(tmp43_);
   double tmp233_ = mLocProjJ_y*(tmp47_);
   double tmp234_ = tmp232_+tmp233_;
   double tmp235_ = mLocProjJ_z*tmp50_;
   double tmp236_ = tmp234_+tmp235_;
   double tmp237_ = mLocProjJ_x*tmp53_;
   double tmp238_ = mLocProjJ_y*tmp55_;
   double tmp239_ = tmp237_+tmp238_;
   double tmp240_ = mLocProjJ_z*tmp8_;
   double tmp241_ = tmp239_+tmp240_;
   double tmp242_ = (tmp241_)*(tmp52_);
   double tmp243_ = (tmp59_)*(tmp236_);
   double tmp244_ = tmp242_-tmp243_;
   double tmp245_ = (tmp244_)/tmp86_;
   double tmp246_ = mLocProjJ_x*(tmp63_);
   double tmp247_ = mLocProjJ_y*(tmp67_);
   double tmp248_ = tmp246_+tmp247_;
   double tmp249_ = mLocProjJ_z*tmp70_;
   double tmp250_ = tmp248_+tmp249_;
   double tmp251_ = (tmp250_)*(tmp52_);
   double tmp252_ = (tmp72_)*(tmp236_);
   double tmp253_ = tmp251_-tmp252_;
   double tmp254_ = (tmp253_)/tmp86_;
   double tmp255_ = mLocProjK_x*(tmp43_);
   double tmp256_ = mLocProjK_y*(tmp47_);
   double tmp257_ = tmp255_+tmp256_;
   double tmp258_ = mLocProjK_z*tmp50_;
   double tmp259_ = tmp257_+tmp258_;
   double tmp260_ = mLocProjK_x*tmp53_;
   double tmp261_ = mLocProjK_y*tmp55_;
   double tmp262_ = tmp260_+tmp261_;
   double tmp263_ = mLocProjK_z*tmp8_;
   double tmp264_ = tmp262_+tmp263_;
   double tmp265_ = (tmp264_)*(tmp52_);
   double tmp266_ = (tmp59_)*(tmp259_);
   double tmp267_ = tmp265_-tmp266_;
   double tmp268_ = (tmp267_)/tmp86_;
   double tmp269_ = mLocProjK_x*(tmp63_);
   double tmp270_ = mLocProjK_y*(tmp67_);
   double tmp271_ = tmp269_+tmp270_;
   double tmp272_ = mLocProjK_z*tmp70_;
   double tmp273_ = tmp271_+tmp272_;
   double tmp274_ = (tmp273_)*(tmp52_);
   double tmp275_ = (tmp72_)*(tmp259_);
   double tmp276_ = tmp274_-tmp275_;
   double tmp277_ = (tmp276_)/tmp86_;

  mVal[0] = (mLocXIm-tmp87_*(mLocNDP0_x+mLocNDdx_x*(tmp60_)+mLocNDdy_x*(tmp73_))-tmp108_*(mLocNDP0_y+mLocNDdx_y*(tmp60_)+mLocNDdy_y*(tmp73_)))*mLocScNorm;

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = 0;
  mCompDer[0][4] = 0;
  mCompDer[0][5] = 0;
  mCompDer[0][6] = 0;
  mCompDer[0][7] = 0;
  mCompDer[0][8] = 0;
  mCompDer[0][9] = 0;
  mCompDer[0][10] = (-(((tmp95_)*mLocNDdx_x+(tmp107_)*mLocNDdy_x)*tmp87_)-((tmp95_)*mLocNDdx_y+(tmp107_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][11] = (-(((tmp131_)*mLocNDdx_x+(tmp143_)*mLocNDdy_x)*tmp87_)-((tmp131_)*mLocNDdx_y+(tmp143_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][12] = (-(((tmp160_)*mLocNDdx_x+(tmp176_)*mLocNDdy_x)*tmp87_)-((tmp160_)*mLocNDdx_y+(tmp176_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][13] = (-(((tmp182_)*mLocNDdx_x+(tmp187_)*mLocNDdy_x)*tmp87_)-((tmp182_)*mLocNDdx_y+(tmp187_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][14] = (-(((tmp193_)*mLocNDdx_x+(tmp198_)*mLocNDdy_x)*tmp87_)-((tmp193_)*mLocNDdx_y+(tmp198_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][15] = (-(((tmp203_)*mLocNDdx_x+(tmp208_)*mLocNDdy_x)*tmp87_)-((tmp203_)*mLocNDdx_y+(tmp208_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][16] = (-(((tmp222_)*mLocNDdx_x+(tmp231_)*mLocNDdy_x)*tmp87_)-((tmp222_)*mLocNDdx_y+(tmp231_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][17] = (-(((tmp245_)*mLocNDdx_x+(tmp254_)*mLocNDdy_x)*tmp87_)-((tmp245_)*mLocNDdx_y+(tmp254_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
  mCompDer[0][18] = (-(((tmp268_)*mLocNDdx_x+(tmp277_)*mLocNDdy_x)*tmp87_)-((tmp268_)*mLocNDdx_y+(tmp277_)*mLocNDdy_y)*tmp108_)*mLocScNorm;
}


void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_Droite_NoDist__PProjInc_M2CDRad5 Has no Der Sec");
}

void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDP0_x(double aVal){ mLocNDP0_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDP0_y(double aVal){ mLocNDP0_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDdx_x(double aVal){ mLocNDdx_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDdx_y(double aVal){ mLocNDdx_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDdy_x(double aVal){ mLocNDdy_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetNDdy_y(double aVal){ mLocNDdy_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjI_x(double aVal){ mLocProjI_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjI_y(double aVal){ mLocProjI_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjI_z(double aVal){ mLocProjI_z = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjJ_x(double aVal){ mLocProjJ_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjJ_y(double aVal){ mLocProjJ_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjJ_z(double aVal){ mLocProjJ_z = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjK_x(double aVal){ mLocProjK_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjK_y(double aVal){ mLocProjK_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjK_z(double aVal){ mLocProjK_z = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjP0_x(double aVal){ mLocProjP0_x = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjP0_y(double aVal){ mLocProjP0_y = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetProjP0_z(double aVal){ mLocProjP0_z = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetScNorm(double aVal){ mLocScNorm = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "NDP0_x") return & mLocNDP0_x;
   if (aName == "NDP0_y") return & mLocNDP0_y;
   if (aName == "NDdx_x") return & mLocNDdx_x;
   if (aName == "NDdx_y") return & mLocNDdx_y;
   if (aName == "NDdy_x") return & mLocNDdy_x;
   if (aName == "NDdy_y") return & mLocNDdy_y;
   if (aName == "ProjI_x") return & mLocProjI_x;
   if (aName == "ProjI_y") return & mLocProjI_y;
   if (aName == "ProjI_z") return & mLocProjI_z;
   if (aName == "ProjJ_x") return & mLocProjJ_x;
   if (aName == "ProjJ_y") return & mLocProjJ_y;
   if (aName == "ProjJ_z") return & mLocProjJ_z;
   if (aName == "ProjK_x") return & mLocProjK_x;
   if (aName == "ProjK_y") return & mLocProjK_y;
   if (aName == "ProjK_z") return & mLocProjK_z;
   if (aName == "ProjP0_x") return & mLocProjP0_x;
   if (aName == "ProjP0_y") return & mLocProjP0_y;
   if (aName == "ProjP0_z") return & mLocProjP0_z;
   if (aName == "ScNorm") return & mLocScNorm;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::mTheAuto("cEqAppui_Droite_NoDist__PProjInc_M2CDRad5",cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::Alloc);


cElCompiledFonc *  cEqAppui_Droite_NoDist__PProjInc_M2CDRad5::Alloc()
{  return new cEqAppui_Droite_NoDist__PProjInc_M2CDRad5();
}


