// File Automatically generated by eLiSe
#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_PTInc_C2MNoDist.h"


cEqAppui_PTInc_C2MNoDist::cEqAppui_PTInc_C2MNoDist():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,3));
   AddIntRef (cIncIntervale("Orient",3,9));
   AddIntRef (cIncIntervale("Tmp_PTer",9,12));
   Close(false);
}



void cEqAppui_PTInc_C2MNoDist::ComputeVal()
{
   double tmp0_ = mCompCoord[3];
   double tmp1_ = mCompCoord[4];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[5];
   double tmp7_ = mCompCoord[9];
   double tmp8_ = mCompCoord[6];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[10];
   double tmp15_ = mCompCoord[7];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[11];
   double tmp18_ = mCompCoord[8];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = mCompCoord[0];
   double tmp21_ = -(tmp3_);
   double tmp22_ = tmp4_*tmp12_;
   double tmp23_ = tmp3_*tmp12_;
   double tmp24_ = tmp21_*tmp11_;
   double tmp25_ = tmp22_*tmp13_;
   double tmp26_ = tmp24_+tmp25_;
   double tmp27_ = (tmp26_)*(tmp9_);
   double tmp28_ = tmp4_*tmp11_;
   double tmp29_ = tmp23_*tmp13_;
   double tmp30_ = tmp28_+tmp29_;
   double tmp31_ = (tmp30_)*(tmp16_);
   double tmp32_ = tmp27_+tmp31_;
   double tmp33_ = tmp2_*tmp13_;
   double tmp34_ = tmp33_*(tmp19_);
   double tmp35_ = tmp32_+tmp34_;

  mVal[0] = (mCompCoord[1]+tmp20_*((tmp4_*tmp2_*(tmp9_)+tmp3_*tmp2_*(tmp16_)+tmp5_*(tmp19_))/(tmp35_)))-mLocXIm;

  mVal[1] = (mCompCoord[2]+tmp20_*(((tmp21_*tmp13_+tmp22_*tmp10_)*(tmp9_)+(tmp4_*tmp13_+tmp23_*tmp10_)*(tmp16_)+tmp2_*tmp10_*(tmp19_))/(tmp35_)))-mLocYIm;

}


void cEqAppui_PTInc_C2MNoDist::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[3];
   double tmp1_ = mCompCoord[4];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[5];
   double tmp7_ = mCompCoord[9];
   double tmp8_ = mCompCoord[6];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[10];
   double tmp15_ = mCompCoord[7];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[11];
   double tmp18_ = mCompCoord[8];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = tmp4_*tmp2_;
   double tmp21_ = tmp20_*(tmp9_);
   double tmp22_ = tmp3_*tmp2_;
   double tmp23_ = tmp22_*(tmp16_);
   double tmp24_ = tmp21_+tmp23_;
   double tmp25_ = tmp5_*(tmp19_);
   double tmp26_ = tmp24_+tmp25_;
   double tmp27_ = -(tmp3_);
   double tmp28_ = tmp27_*tmp11_;
   double tmp29_ = tmp4_*tmp12_;
   double tmp30_ = tmp29_*tmp13_;
   double tmp31_ = tmp28_+tmp30_;
   double tmp32_ = (tmp31_)*(tmp9_);
   double tmp33_ = tmp4_*tmp11_;
   double tmp34_ = tmp3_*tmp12_;
   double tmp35_ = tmp34_*tmp13_;
   double tmp36_ = tmp33_+tmp35_;
   double tmp37_ = (tmp36_)*(tmp16_);
   double tmp38_ = tmp32_+tmp37_;
   double tmp39_ = tmp2_*tmp13_;
   double tmp40_ = tmp39_*(tmp19_);
   double tmp41_ = tmp38_+tmp40_;
   double tmp42_ = (tmp26_)/(tmp41_);
   double tmp43_ = -(1);
   double tmp44_ = tmp43_*tmp3_;
   double tmp45_ = mCompCoord[0];
   double tmp46_ = tmp43_*tmp5_;
   double tmp47_ = -(tmp2_);
   double tmp48_ = ElSquare(tmp41_);
   double tmp49_ = -(tmp13_);
   double tmp50_ = tmp43_*tmp10_;
   double tmp51_ = tmp27_*tmp13_;
   double tmp52_ = tmp29_*tmp10_;
   double tmp53_ = tmp51_+tmp52_;
   double tmp54_ = (tmp53_)*(tmp9_);
   double tmp55_ = tmp4_*tmp13_;
   double tmp56_ = tmp34_*tmp10_;
   double tmp57_ = tmp55_+tmp56_;
   double tmp58_ = (tmp57_)*(tmp16_);
   double tmp59_ = tmp54_+tmp58_;
   double tmp60_ = tmp2_*tmp10_;
   double tmp61_ = tmp60_*(tmp19_);
   double tmp62_ = tmp59_+tmp61_;
   double tmp63_ = (tmp62_)/(tmp41_);
   double tmp64_ = -(tmp4_);
   double tmp65_ = tmp44_*tmp12_;
   double tmp66_ = tmp64_*tmp11_;
   double tmp67_ = tmp65_*tmp13_;
   double tmp68_ = tmp66_+tmp67_;
   double tmp69_ = (tmp68_)*(tmp9_);
   double tmp70_ = tmp44_*tmp11_;
   double tmp71_ = tmp70_+tmp30_;
   double tmp72_ = (tmp71_)*(tmp16_);
   double tmp73_ = tmp69_+tmp72_;
   double tmp74_ = tmp47_*tmp4_;
   double tmp75_ = tmp47_*tmp3_;
   double tmp76_ = tmp74_*tmp13_;
   double tmp77_ = tmp76_*(tmp9_);
   double tmp78_ = tmp75_*tmp13_;
   double tmp79_ = tmp78_*(tmp16_);
   double tmp80_ = tmp77_+tmp79_;
   double tmp81_ = tmp46_*tmp13_;
   double tmp82_ = tmp81_*(tmp19_);
   double tmp83_ = tmp80_+tmp82_;
   double tmp84_ = tmp49_*tmp27_;
   double tmp85_ = tmp50_*tmp29_;
   double tmp86_ = tmp84_+tmp85_;
   double tmp87_ = (tmp86_)*(tmp9_);
   double tmp88_ = tmp49_*tmp4_;
   double tmp89_ = tmp50_*tmp34_;
   double tmp90_ = tmp88_+tmp89_;
   double tmp91_ = (tmp90_)*(tmp16_);
   double tmp92_ = tmp87_+tmp91_;
   double tmp93_ = tmp50_*tmp2_;
   double tmp94_ = tmp93_*(tmp19_);
   double tmp95_ = tmp92_+tmp94_;
   double tmp96_ = tmp43_*(tmp31_);
   double tmp97_ = tmp43_*(tmp36_);
   double tmp98_ = tmp43_*tmp39_;

  mVal[0] = (mCompCoord[1]+tmp45_*(tmp42_))-mLocXIm;

  mCompDer[0][0] = tmp42_;
  mCompDer[0][1] = 1;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = (((tmp44_*tmp2_*(tmp9_)+tmp20_*(tmp16_))*(tmp41_)-(tmp26_)*(tmp73_))/tmp48_)*tmp45_;
  mCompDer[0][4] = (((tmp46_*tmp4_*(tmp9_)+tmp46_*tmp3_*(tmp16_)+tmp2_*(tmp19_))*(tmp41_)-(tmp26_)*(tmp83_))/tmp48_)*tmp45_;
  mCompDer[0][5] = (-((tmp26_)*(tmp95_))/tmp48_)*tmp45_;
  mCompDer[0][6] = ((tmp43_*tmp20_*(tmp41_)-(tmp26_)*tmp96_)/tmp48_)*tmp45_;
  mCompDer[0][7] = ((tmp43_*tmp22_*(tmp41_)-(tmp26_)*tmp97_)/tmp48_)*tmp45_;
  mCompDer[0][8] = ((tmp46_*(tmp41_)-(tmp26_)*tmp98_)/tmp48_)*tmp45_;
  mCompDer[0][9] = ((tmp20_*(tmp41_)-(tmp26_)*(tmp31_))/tmp48_)*tmp45_;
  mCompDer[0][10] = ((tmp22_*(tmp41_)-(tmp26_)*(tmp36_))/tmp48_)*tmp45_;
  mCompDer[0][11] = ((tmp5_*(tmp41_)-(tmp26_)*tmp39_)/tmp48_)*tmp45_;
  mVal[1] = (mCompCoord[2]+tmp45_*(tmp63_))-mLocYIm;

  mCompDer[1][0] = tmp63_;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 1;
  mCompDer[1][3] = ((((tmp64_*tmp13_+tmp65_*tmp10_)*(tmp9_)+(tmp44_*tmp13_+tmp52_)*(tmp16_))*(tmp41_)-(tmp62_)*(tmp73_))/tmp48_)*tmp45_;
  mCompDer[1][4] = (((tmp74_*tmp10_*(tmp9_)+tmp75_*tmp10_*(tmp16_)+tmp46_*tmp10_*(tmp19_))*(tmp41_)-(tmp62_)*(tmp83_))/tmp48_)*tmp45_;
  mCompDer[1][5] = ((((tmp50_*tmp27_+tmp13_*tmp29_)*(tmp9_)+(tmp50_*tmp4_+tmp13_*tmp34_)*(tmp16_)+tmp13_*tmp2_*(tmp19_))*(tmp41_)-(tmp62_)*(tmp95_))/tmp48_)*tmp45_;
  mCompDer[1][6] = ((tmp43_*(tmp53_)*(tmp41_)-(tmp62_)*tmp96_)/tmp48_)*tmp45_;
  mCompDer[1][7] = ((tmp43_*(tmp57_)*(tmp41_)-(tmp62_)*tmp97_)/tmp48_)*tmp45_;
  mCompDer[1][8] = ((tmp43_*tmp60_*(tmp41_)-(tmp62_)*tmp98_)/tmp48_)*tmp45_;
  mCompDer[1][9] = (((tmp53_)*(tmp41_)-(tmp62_)*(tmp31_))/tmp48_)*tmp45_;
  mCompDer[1][10] = (((tmp57_)*(tmp41_)-(tmp62_)*(tmp36_))/tmp48_)*tmp45_;
  mCompDer[1][11] = ((tmp60_*(tmp41_)-(tmp62_)*tmp39_)/tmp48_)*tmp45_;
}


void cEqAppui_PTInc_C2MNoDist::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_PTInc_C2MNoDist Has no Der Sec");
}

void cEqAppui_PTInc_C2MNoDist::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_PTInc_C2MNoDist::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_PTInc_C2MNoDist::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_PTInc_C2MNoDist::mTheAuto("cEqAppui_PTInc_C2MNoDist",cEqAppui_PTInc_C2MNoDist::Alloc);


cElCompiledFonc *  cEqAppui_PTInc_C2MNoDist::Alloc()
{  return new cEqAppui_PTInc_C2MNoDist();
}


