// File Automatically generated by eLiSe
#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_PTInc_C2MPolyn5.h"


cEqAppui_PTInc_C2MPolyn5::cEqAppui_PTInc_C2MPolyn5():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,39));
   AddIntRef (cIncIntervale("Orient",39,45));
   AddIntRef (cIncIntervale("Tmp_PTer",45,48));
   Close(false);
}



void cEqAppui_PTInc_C2MPolyn5::ComputeVal()
{
   double tmp0_ = mCompCoord[39];
   double tmp1_ = mCompCoord[40];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[41];
   double tmp7_ = mCompCoord[45];
   double tmp8_ = mCompCoord[42];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[46];
   double tmp15_ = mCompCoord[43];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[47];
   double tmp18_ = mCompCoord[44];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = mLocXIm/mLocPolyn5_State_0_0;
   double tmp21_ = mLocYIm/mLocPolyn5_State_0_0;
   double tmp22_ = (tmp20_)*(tmp20_);
   double tmp23_ = (tmp21_)*(tmp21_);
   double tmp24_ = tmp22_*(tmp20_);
   double tmp25_ = (tmp21_)*(tmp20_);
   double tmp26_ = tmp25_*(tmp20_);
   double tmp27_ = tmp23_*(tmp20_);
   double tmp28_ = (tmp21_)*tmp23_;
   double tmp29_ = tmp24_*(tmp20_);
   double tmp30_ = tmp26_*(tmp20_);
   double tmp31_ = tmp27_*(tmp20_);
   double tmp32_ = tmp28_*(tmp20_);
   double tmp33_ = (tmp21_)*tmp28_;
   double tmp34_ = mCompCoord[0];
   double tmp35_ = -(tmp3_);
   double tmp36_ = tmp4_*tmp12_;
   double tmp37_ = tmp3_*tmp12_;
   double tmp38_ = tmp35_*tmp11_;
   double tmp39_ = tmp36_*tmp13_;
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = (tmp40_)*(tmp9_);
   double tmp42_ = tmp4_*tmp11_;
   double tmp43_ = tmp37_*tmp13_;
   double tmp44_ = tmp42_+tmp43_;
   double tmp45_ = (tmp44_)*(tmp16_);
   double tmp46_ = tmp41_+tmp45_;
   double tmp47_ = tmp2_*tmp13_;
   double tmp48_ = tmp47_*(tmp19_);
   double tmp49_ = tmp46_+tmp48_;
   double tmp50_ = mCompCoord[3];
   double tmp51_ = mCompCoord[4];
   double tmp52_ = mCompCoord[5];
   double tmp53_ = (tmp20_)*(tmp21_);
   double tmp54_ = mCompCoord[6];
   double tmp55_ = tmp29_*(tmp20_);
   double tmp56_ = tmp30_*(tmp20_);
   double tmp57_ = tmp31_*(tmp20_);
   double tmp58_ = tmp32_*(tmp20_);
   double tmp59_ = tmp33_*(tmp20_);
   double tmp60_ = (tmp21_)*tmp33_;

  mVal[0] = (mCompCoord[1]+tmp34_*((tmp4_*tmp2_*(tmp9_)+tmp3_*tmp2_*(tmp16_)+tmp5_*(tmp19_))/(tmp49_)))-((((1+tmp50_)*(tmp20_)+tmp51_*(tmp21_))-tmp52_*2*tmp22_+tmp54_*tmp53_+mCompCoord[7]*tmp23_)*mLocPolyn5_State_0_0+(mCompCoord[9]*tmp24_+mCompCoord[10]*tmp26_+mCompCoord[11]*tmp27_+mCompCoord[12]*tmp28_+mCompCoord[17]*tmp29_+mCompCoord[18]*tmp30_+mCompCoord[19]*tmp31_+mCompCoord[20]*tmp32_+mCompCoord[21]*tmp33_+mCompCoord[27]*tmp55_+mCompCoord[28]*tmp56_+mCompCoord[29]*tmp57_+mCompCoord[30]*tmp58_+mCompCoord[31]*tmp59_+mCompCoord[32]*tmp60_)*mLocPolyn5_State_0_0);

  mVal[1] = (mCompCoord[2]+tmp34_*(((tmp35_*tmp13_+tmp36_*tmp10_)*(tmp9_)+(tmp4_*tmp13_+tmp37_*tmp10_)*(tmp16_)+tmp2_*tmp10_*(tmp19_))/(tmp49_)))-((((1-tmp50_)*(tmp21_)+tmp51_*(tmp20_)+tmp52_*tmp53_)-tmp54_*2*tmp23_+mCompCoord[8]*tmp22_)*mLocPolyn5_State_0_0+(mCompCoord[13]*tmp24_+mCompCoord[14]*tmp26_+mCompCoord[15]*tmp27_+mCompCoord[16]*tmp28_+mCompCoord[22]*tmp29_+mCompCoord[23]*tmp30_+mCompCoord[24]*tmp31_+mCompCoord[25]*tmp32_+mCompCoord[26]*tmp33_+mCompCoord[33]*tmp55_+mCompCoord[34]*tmp56_+mCompCoord[35]*tmp57_+mCompCoord[36]*tmp58_+mCompCoord[37]*tmp59_+mCompCoord[38]*tmp60_)*mLocPolyn5_State_0_0);

}


void cEqAppui_PTInc_C2MPolyn5::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[39];
   double tmp1_ = mCompCoord[40];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[41];
   double tmp7_ = mCompCoord[45];
   double tmp8_ = mCompCoord[42];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[46];
   double tmp15_ = mCompCoord[43];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[47];
   double tmp18_ = mCompCoord[44];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = mLocXIm/mLocPolyn5_State_0_0;
   double tmp21_ = mLocYIm/mLocPolyn5_State_0_0;
   double tmp22_ = (tmp20_)*(tmp20_);
   double tmp23_ = (tmp21_)*(tmp21_);
   double tmp24_ = tmp22_*(tmp20_);
   double tmp25_ = (tmp21_)*(tmp20_);
   double tmp26_ = tmp25_*(tmp20_);
   double tmp27_ = tmp23_*(tmp20_);
   double tmp28_ = (tmp21_)*tmp23_;
   double tmp29_ = tmp24_*(tmp20_);
   double tmp30_ = tmp26_*(tmp20_);
   double tmp31_ = tmp27_*(tmp20_);
   double tmp32_ = tmp28_*(tmp20_);
   double tmp33_ = (tmp21_)*tmp28_;
   double tmp34_ = tmp4_*tmp2_;
   double tmp35_ = tmp34_*(tmp9_);
   double tmp36_ = tmp3_*tmp2_;
   double tmp37_ = tmp36_*(tmp16_);
   double tmp38_ = tmp35_+tmp37_;
   double tmp39_ = tmp5_*(tmp19_);
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = -(tmp3_);
   double tmp42_ = tmp41_*tmp11_;
   double tmp43_ = tmp4_*tmp12_;
   double tmp44_ = tmp43_*tmp13_;
   double tmp45_ = tmp42_+tmp44_;
   double tmp46_ = (tmp45_)*(tmp9_);
   double tmp47_ = tmp4_*tmp11_;
   double tmp48_ = tmp3_*tmp12_;
   double tmp49_ = tmp48_*tmp13_;
   double tmp50_ = tmp47_+tmp49_;
   double tmp51_ = (tmp50_)*(tmp16_);
   double tmp52_ = tmp46_+tmp51_;
   double tmp53_ = tmp2_*tmp13_;
   double tmp54_ = tmp53_*(tmp19_);
   double tmp55_ = tmp52_+tmp54_;
   double tmp56_ = (tmp40_)/(tmp55_);
   double tmp57_ = (tmp20_)*(tmp21_);
   double tmp58_ = tmp29_*(tmp20_);
   double tmp59_ = tmp30_*(tmp20_);
   double tmp60_ = tmp31_*(tmp20_);
   double tmp61_ = tmp32_*(tmp20_);
   double tmp62_ = tmp33_*(tmp20_);
   double tmp63_ = (tmp21_)*tmp33_;
   double tmp64_ = -(1);
   double tmp65_ = tmp64_*tmp3_;
   double tmp66_ = mCompCoord[0];
   double tmp67_ = tmp64_*tmp5_;
   double tmp68_ = -(tmp2_);
   double tmp69_ = ElSquare(tmp55_);
   double tmp70_ = -(tmp13_);
   double tmp71_ = tmp64_*tmp10_;
   double tmp72_ = mCompCoord[3];
   double tmp73_ = mCompCoord[4];
   double tmp74_ = mCompCoord[5];
   double tmp75_ = mCompCoord[6];
   double tmp76_ = tmp41_*tmp13_;
   double tmp77_ = tmp43_*tmp10_;
   double tmp78_ = tmp76_+tmp77_;
   double tmp79_ = (tmp78_)*(tmp9_);
   double tmp80_ = tmp4_*tmp13_;
   double tmp81_ = tmp48_*tmp10_;
   double tmp82_ = tmp80_+tmp81_;
   double tmp83_ = (tmp82_)*(tmp16_);
   double tmp84_ = tmp79_+tmp83_;
   double tmp85_ = tmp2_*tmp10_;
   double tmp86_ = tmp85_*(tmp19_);
   double tmp87_ = tmp84_+tmp86_;
   double tmp88_ = (tmp87_)/(tmp55_);
   double tmp89_ = (tmp20_)*mLocPolyn5_State_0_0;
   double tmp90_ = -(tmp89_);
   double tmp91_ = tmp57_*mLocPolyn5_State_0_0;
   double tmp92_ = -(tmp91_);
   double tmp93_ = tmp24_*mLocPolyn5_State_0_0;
   double tmp94_ = -(tmp93_);
   double tmp95_ = tmp26_*mLocPolyn5_State_0_0;
   double tmp96_ = -(tmp95_);
   double tmp97_ = tmp27_*mLocPolyn5_State_0_0;
   double tmp98_ = -(tmp97_);
   double tmp99_ = tmp28_*mLocPolyn5_State_0_0;
   double tmp100_ = -(tmp99_);
   double tmp101_ = tmp29_*mLocPolyn5_State_0_0;
   double tmp102_ = -(tmp101_);
   double tmp103_ = tmp30_*mLocPolyn5_State_0_0;
   double tmp104_ = -(tmp103_);
   double tmp105_ = tmp31_*mLocPolyn5_State_0_0;
   double tmp106_ = -(tmp105_);
   double tmp107_ = tmp32_*mLocPolyn5_State_0_0;
   double tmp108_ = -(tmp107_);
   double tmp109_ = tmp33_*mLocPolyn5_State_0_0;
   double tmp110_ = -(tmp109_);
   double tmp111_ = tmp58_*mLocPolyn5_State_0_0;
   double tmp112_ = -(tmp111_);
   double tmp113_ = tmp59_*mLocPolyn5_State_0_0;
   double tmp114_ = -(tmp113_);
   double tmp115_ = tmp60_*mLocPolyn5_State_0_0;
   double tmp116_ = -(tmp115_);
   double tmp117_ = tmp61_*mLocPolyn5_State_0_0;
   double tmp118_ = -(tmp117_);
   double tmp119_ = tmp62_*mLocPolyn5_State_0_0;
   double tmp120_ = -(tmp119_);
   double tmp121_ = tmp63_*mLocPolyn5_State_0_0;
   double tmp122_ = -(tmp121_);
   double tmp123_ = -(tmp4_);
   double tmp124_ = tmp65_*tmp12_;
   double tmp125_ = tmp123_*tmp11_;
   double tmp126_ = tmp124_*tmp13_;
   double tmp127_ = tmp125_+tmp126_;
   double tmp128_ = (tmp127_)*(tmp9_);
   double tmp129_ = tmp65_*tmp11_;
   double tmp130_ = tmp129_+tmp44_;
   double tmp131_ = (tmp130_)*(tmp16_);
   double tmp132_ = tmp128_+tmp131_;
   double tmp133_ = tmp68_*tmp4_;
   double tmp134_ = tmp68_*tmp3_;
   double tmp135_ = tmp133_*tmp13_;
   double tmp136_ = tmp135_*(tmp9_);
   double tmp137_ = tmp134_*tmp13_;
   double tmp138_ = tmp137_*(tmp16_);
   double tmp139_ = tmp136_+tmp138_;
   double tmp140_ = tmp67_*tmp13_;
   double tmp141_ = tmp140_*(tmp19_);
   double tmp142_ = tmp139_+tmp141_;
   double tmp143_ = tmp70_*tmp41_;
   double tmp144_ = tmp71_*tmp43_;
   double tmp145_ = tmp143_+tmp144_;
   double tmp146_ = (tmp145_)*(tmp9_);
   double tmp147_ = tmp70_*tmp4_;
   double tmp148_ = tmp71_*tmp48_;
   double tmp149_ = tmp147_+tmp148_;
   double tmp150_ = (tmp149_)*(tmp16_);
   double tmp151_ = tmp146_+tmp150_;
   double tmp152_ = tmp71_*tmp2_;
   double tmp153_ = tmp152_*(tmp19_);
   double tmp154_ = tmp151_+tmp153_;
   double tmp155_ = tmp64_*(tmp45_);
   double tmp156_ = tmp64_*(tmp50_);
   double tmp157_ = tmp64_*tmp53_;

  mVal[0] = (mCompCoord[1]+tmp66_*(tmp56_))-((((1+tmp72_)*(tmp20_)+tmp73_*(tmp21_))-tmp74_*2*tmp22_+tmp75_*tmp57_+mCompCoord[7]*tmp23_)*mLocPolyn5_State_0_0+(mCompCoord[9]*tmp24_+mCompCoord[10]*tmp26_+mCompCoord[11]*tmp27_+mCompCoord[12]*tmp28_+mCompCoord[17]*tmp29_+mCompCoord[18]*tmp30_+mCompCoord[19]*tmp31_+mCompCoord[20]*tmp32_+mCompCoord[21]*tmp33_+mCompCoord[27]*tmp58_+mCompCoord[28]*tmp59_+mCompCoord[29]*tmp60_+mCompCoord[30]*tmp61_+mCompCoord[31]*tmp62_+mCompCoord[32]*tmp63_)*mLocPolyn5_State_0_0);

  mCompDer[0][0] = tmp56_;
  mCompDer[0][1] = 1;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = tmp90_;
  mCompDer[0][4] = -((tmp21_)*mLocPolyn5_State_0_0);
  mCompDer[0][5] = -(-(2*tmp22_)*mLocPolyn5_State_0_0);
  mCompDer[0][6] = tmp92_;
  mCompDer[0][7] = -(tmp23_*mLocPolyn5_State_0_0);
  mCompDer[0][8] = 0;
  mCompDer[0][9] = tmp94_;
  mCompDer[0][10] = tmp96_;
  mCompDer[0][11] = tmp98_;
  mCompDer[0][12] = tmp100_;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = 0;
  mCompDer[0][16] = 0;
  mCompDer[0][17] = tmp102_;
  mCompDer[0][18] = tmp104_;
  mCompDer[0][19] = tmp106_;
  mCompDer[0][20] = tmp108_;
  mCompDer[0][21] = tmp110_;
  mCompDer[0][22] = 0;
  mCompDer[0][23] = 0;
  mCompDer[0][24] = 0;
  mCompDer[0][25] = 0;
  mCompDer[0][26] = 0;
  mCompDer[0][27] = tmp112_;
  mCompDer[0][28] = tmp114_;
  mCompDer[0][29] = tmp116_;
  mCompDer[0][30] = tmp118_;
  mCompDer[0][31] = tmp120_;
  mCompDer[0][32] = tmp122_;
  mCompDer[0][33] = 0;
  mCompDer[0][34] = 0;
  mCompDer[0][35] = 0;
  mCompDer[0][36] = 0;
  mCompDer[0][37] = 0;
  mCompDer[0][38] = 0;
  mCompDer[0][39] = (((tmp65_*tmp2_*(tmp9_)+tmp34_*(tmp16_))*(tmp55_)-(tmp40_)*(tmp132_))/tmp69_)*tmp66_;
  mCompDer[0][40] = (((tmp67_*tmp4_*(tmp9_)+tmp67_*tmp3_*(tmp16_)+tmp2_*(tmp19_))*(tmp55_)-(tmp40_)*(tmp142_))/tmp69_)*tmp66_;
  mCompDer[0][41] = (-((tmp40_)*(tmp154_))/tmp69_)*tmp66_;
  mCompDer[0][42] = ((tmp64_*tmp34_*(tmp55_)-(tmp40_)*tmp155_)/tmp69_)*tmp66_;
  mCompDer[0][43] = ((tmp64_*tmp36_*(tmp55_)-(tmp40_)*tmp156_)/tmp69_)*tmp66_;
  mCompDer[0][44] = ((tmp67_*(tmp55_)-(tmp40_)*tmp157_)/tmp69_)*tmp66_;
  mCompDer[0][45] = ((tmp34_*(tmp55_)-(tmp40_)*(tmp45_))/tmp69_)*tmp66_;
  mCompDer[0][46] = ((tmp36_*(tmp55_)-(tmp40_)*(tmp50_))/tmp69_)*tmp66_;
  mCompDer[0][47] = ((tmp5_*(tmp55_)-(tmp40_)*tmp53_)/tmp69_)*tmp66_;
  mVal[1] = (mCompCoord[2]+tmp66_*(tmp88_))-((((1-tmp72_)*(tmp21_)+tmp73_*(tmp20_)+tmp74_*tmp57_)-tmp75_*2*tmp23_+mCompCoord[8]*tmp22_)*mLocPolyn5_State_0_0+(mCompCoord[13]*tmp24_+mCompCoord[14]*tmp26_+mCompCoord[15]*tmp27_+mCompCoord[16]*tmp28_+mCompCoord[22]*tmp29_+mCompCoord[23]*tmp30_+mCompCoord[24]*tmp31_+mCompCoord[25]*tmp32_+mCompCoord[26]*tmp33_+mCompCoord[33]*tmp58_+mCompCoord[34]*tmp59_+mCompCoord[35]*tmp60_+mCompCoord[36]*tmp61_+mCompCoord[37]*tmp62_+mCompCoord[38]*tmp63_)*mLocPolyn5_State_0_0);

  mCompDer[1][0] = tmp88_;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 1;
  mCompDer[1][3] = -(tmp64_*(tmp21_)*mLocPolyn5_State_0_0);
  mCompDer[1][4] = tmp90_;
  mCompDer[1][5] = tmp92_;
  mCompDer[1][6] = -(-(2*tmp23_)*mLocPolyn5_State_0_0);
  mCompDer[1][7] = 0;
  mCompDer[1][8] = -(tmp22_*mLocPolyn5_State_0_0);
  mCompDer[1][9] = 0;
  mCompDer[1][10] = 0;
  mCompDer[1][11] = 0;
  mCompDer[1][12] = 0;
  mCompDer[1][13] = tmp94_;
  mCompDer[1][14] = tmp96_;
  mCompDer[1][15] = tmp98_;
  mCompDer[1][16] = tmp100_;
  mCompDer[1][17] = 0;
  mCompDer[1][18] = 0;
  mCompDer[1][19] = 0;
  mCompDer[1][20] = 0;
  mCompDer[1][21] = 0;
  mCompDer[1][22] = tmp102_;
  mCompDer[1][23] = tmp104_;
  mCompDer[1][24] = tmp106_;
  mCompDer[1][25] = tmp108_;
  mCompDer[1][26] = tmp110_;
  mCompDer[1][27] = 0;
  mCompDer[1][28] = 0;
  mCompDer[1][29] = 0;
  mCompDer[1][30] = 0;
  mCompDer[1][31] = 0;
  mCompDer[1][32] = 0;
  mCompDer[1][33] = tmp112_;
  mCompDer[1][34] = tmp114_;
  mCompDer[1][35] = tmp116_;
  mCompDer[1][36] = tmp118_;
  mCompDer[1][37] = tmp120_;
  mCompDer[1][38] = tmp122_;
  mCompDer[1][39] = ((((tmp123_*tmp13_+tmp124_*tmp10_)*(tmp9_)+(tmp65_*tmp13_+tmp77_)*(tmp16_))*(tmp55_)-(tmp87_)*(tmp132_))/tmp69_)*tmp66_;
  mCompDer[1][40] = (((tmp133_*tmp10_*(tmp9_)+tmp134_*tmp10_*(tmp16_)+tmp67_*tmp10_*(tmp19_))*(tmp55_)-(tmp87_)*(tmp142_))/tmp69_)*tmp66_;
  mCompDer[1][41] = ((((tmp71_*tmp41_+tmp13_*tmp43_)*(tmp9_)+(tmp71_*tmp4_+tmp13_*tmp48_)*(tmp16_)+tmp13_*tmp2_*(tmp19_))*(tmp55_)-(tmp87_)*(tmp154_))/tmp69_)*tmp66_;
  mCompDer[1][42] = ((tmp64_*(tmp78_)*(tmp55_)-(tmp87_)*tmp155_)/tmp69_)*tmp66_;
  mCompDer[1][43] = ((tmp64_*(tmp82_)*(tmp55_)-(tmp87_)*tmp156_)/tmp69_)*tmp66_;
  mCompDer[1][44] = ((tmp64_*tmp85_*(tmp55_)-(tmp87_)*tmp157_)/tmp69_)*tmp66_;
  mCompDer[1][45] = (((tmp78_)*(tmp55_)-(tmp87_)*(tmp45_))/tmp69_)*tmp66_;
  mCompDer[1][46] = (((tmp82_)*(tmp55_)-(tmp87_)*(tmp50_))/tmp69_)*tmp66_;
  mCompDer[1][47] = ((tmp85_*(tmp55_)-(tmp87_)*tmp53_)/tmp69_)*tmp66_;
}


void cEqAppui_PTInc_C2MPolyn5::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_PTInc_C2MPolyn5 Has no Der Sec");
}

void cEqAppui_PTInc_C2MPolyn5::SetPolyn5_State_0_0(double aVal){ mLocPolyn5_State_0_0 = aVal;}
void cEqAppui_PTInc_C2MPolyn5::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_PTInc_C2MPolyn5::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_PTInc_C2MPolyn5::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Polyn5_State_0_0") return & mLocPolyn5_State_0_0;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_PTInc_C2MPolyn5::mTheAuto("cEqAppui_PTInc_C2MPolyn5",cEqAppui_PTInc_C2MPolyn5::Alloc);


cElCompiledFonc *  cEqAppui_PTInc_C2MPolyn5::Alloc()
{  return new cEqAppui_PTInc_C2MPolyn5();
}


