// File Automatically generated by eLiSe

#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_PTInc_M2CDPol3.h"


cEqAppui_PTInc_M2CDPol3::cEqAppui_PTInc_M2CDPol3():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,20));
   AddIntRef (cIncIntervale("Orient",20,26));
   AddIntRef (cIncIntervale("Tmp_PTer",26,29));
   Close(false);
}



void cEqAppui_PTInc_M2CDPol3::ComputeVal()
{
   double tmp0_ = mCompCoord[20];
   double tmp1_ = mCompCoord[22];
   double tmp2_ = cos(tmp0_);
   double tmp3_ = cos(tmp1_);
   double tmp4_ = sin(tmp0_);
   double tmp5_ = mCompCoord[21];
   double tmp6_ = sin(tmp5_);
   double tmp7_ = -(tmp6_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = -(tmp4_);
   double tmp10_ = tmp2_*tmp7_;
   double tmp11_ = mCompCoord[26];
   double tmp12_ = mCompCoord[23];
   double tmp13_ = tmp11_-tmp12_;
   double tmp14_ = -(tmp8_);
   double tmp15_ = tmp4_*tmp7_;
   double tmp16_ = mCompCoord[27];
   double tmp17_ = mCompCoord[24];
   double tmp18_ = tmp16_-tmp17_;
   double tmp19_ = cos(tmp5_);
   double tmp20_ = mCompCoord[28];
   double tmp21_ = mCompCoord[25];
   double tmp22_ = tmp20_-tmp21_;
   double tmp23_ = tmp9_*tmp14_;
   double tmp24_ = tmp10_*tmp3_;
   double tmp25_ = tmp23_+tmp24_;
   double tmp26_ = (tmp25_)*(tmp13_);
   double tmp27_ = tmp2_*tmp14_;
   double tmp28_ = tmp15_*tmp3_;
   double tmp29_ = tmp27_+tmp28_;
   double tmp30_ = (tmp29_)*(tmp18_);
   double tmp31_ = tmp26_+tmp30_;
   double tmp32_ = tmp19_*tmp3_;
   double tmp33_ = tmp32_*(tmp22_);
   double tmp34_ = tmp31_+tmp33_;
   double tmp35_ = tmp9_*tmp3_;
   double tmp36_ = tmp10_*tmp8_;
   double tmp37_ = tmp35_+tmp36_;
   double tmp38_ = (tmp37_)*(tmp13_);
   double tmp39_ = tmp2_*tmp3_;
   double tmp40_ = tmp15_*tmp8_;
   double tmp41_ = tmp39_+tmp40_;
   double tmp42_ = (tmp41_)*(tmp18_);
   double tmp43_ = tmp38_+tmp42_;
   double tmp44_ = tmp19_*tmp8_;
   double tmp45_ = tmp44_*(tmp22_);
   double tmp46_ = tmp43_+tmp45_;
   double tmp47_ = (tmp46_)/(tmp34_);
   double tmp48_ = tmp2_*tmp19_;
   double tmp49_ = tmp48_*(tmp13_);
   double tmp50_ = tmp4_*tmp19_;
   double tmp51_ = tmp50_*(tmp18_);
   double tmp52_ = tmp49_+tmp51_;
   double tmp53_ = tmp6_*(tmp22_);
   double tmp54_ = tmp52_+tmp53_;
   double tmp55_ = (tmp54_)/(tmp34_);
   double tmp56_ = ElSquare(tmp47_);
   double tmp57_ = ElSquare(tmp55_);
   double tmp58_ = VCube(tmp47_);
   double tmp59_ = VCube(tmp55_);

  mVal[0] = (mCompCoord[0]+mCompCoord[1]*(tmp47_)+mCompCoord[2]*(tmp55_)+mCompCoord[3]*tmp56_+mCompCoord[4]*(tmp55_)*(tmp47_)+mCompCoord[5]*tmp57_+mCompCoord[6]*tmp58_+mCompCoord[7]*(tmp55_)*tmp56_+mCompCoord[8]*tmp57_*(tmp47_)+mCompCoord[9]*tmp59_)-mLocXIm;

  mVal[1] = (mCompCoord[10]+mCompCoord[11]*(tmp47_)+mCompCoord[12]*(tmp55_)+mCompCoord[13]*tmp56_+mCompCoord[14]*(tmp55_)*(tmp47_)+mCompCoord[15]*tmp57_+mCompCoord[16]*tmp58_+mCompCoord[17]*(tmp55_)*tmp56_+mCompCoord[18]*tmp57_*(tmp47_)+mCompCoord[19]*tmp59_)-mLocYIm;

}


void cEqAppui_PTInc_M2CDPol3::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[20];
   double tmp1_ = mCompCoord[22];
   double tmp2_ = cos(tmp0_);
   double tmp3_ = cos(tmp1_);
   double tmp4_ = sin(tmp0_);
   double tmp5_ = mCompCoord[21];
   double tmp6_ = sin(tmp5_);
   double tmp7_ = -(tmp6_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = -(tmp4_);
   double tmp10_ = tmp2_*tmp7_;
   double tmp11_ = mCompCoord[26];
   double tmp12_ = mCompCoord[23];
   double tmp13_ = tmp11_-tmp12_;
   double tmp14_ = -(tmp8_);
   double tmp15_ = tmp4_*tmp7_;
   double tmp16_ = mCompCoord[27];
   double tmp17_ = mCompCoord[24];
   double tmp18_ = tmp16_-tmp17_;
   double tmp19_ = cos(tmp5_);
   double tmp20_ = mCompCoord[28];
   double tmp21_ = mCompCoord[25];
   double tmp22_ = tmp20_-tmp21_;
   double tmp23_ = tmp9_*tmp14_;
   double tmp24_ = tmp10_*tmp3_;
   double tmp25_ = tmp23_+tmp24_;
   double tmp26_ = (tmp25_)*(tmp13_);
   double tmp27_ = tmp2_*tmp14_;
   double tmp28_ = tmp15_*tmp3_;
   double tmp29_ = tmp27_+tmp28_;
   double tmp30_ = (tmp29_)*(tmp18_);
   double tmp31_ = tmp26_+tmp30_;
   double tmp32_ = tmp19_*tmp3_;
   double tmp33_ = tmp32_*(tmp22_);
   double tmp34_ = tmp31_+tmp33_;
   double tmp35_ = tmp9_*tmp3_;
   double tmp36_ = tmp10_*tmp8_;
   double tmp37_ = tmp35_+tmp36_;
   double tmp38_ = (tmp37_)*(tmp13_);
   double tmp39_ = tmp2_*tmp3_;
   double tmp40_ = tmp15_*tmp8_;
   double tmp41_ = tmp39_+tmp40_;
   double tmp42_ = (tmp41_)*(tmp18_);
   double tmp43_ = tmp38_+tmp42_;
   double tmp44_ = tmp19_*tmp8_;
   double tmp45_ = tmp44_*(tmp22_);
   double tmp46_ = tmp43_+tmp45_;
   double tmp47_ = (tmp46_)/(tmp34_);
   double tmp48_ = tmp2_*tmp19_;
   double tmp49_ = tmp48_*(tmp13_);
   double tmp50_ = tmp4_*tmp19_;
   double tmp51_ = tmp50_*(tmp18_);
   double tmp52_ = tmp49_+tmp51_;
   double tmp53_ = tmp6_*(tmp22_);
   double tmp54_ = tmp52_+tmp53_;
   double tmp55_ = (tmp54_)/(tmp34_);
   double tmp56_ = ElSquare(tmp47_);
   double tmp57_ = ElSquare(tmp55_);
   double tmp58_ = VCube(tmp47_);
   double tmp59_ = VCube(tmp55_);
   double tmp60_ = -(1);
   double tmp61_ = tmp60_*tmp4_;
   double tmp62_ = -(tmp2_);
   double tmp63_ = tmp61_*tmp7_;
   double tmp64_ = mCompCoord[1];
   double tmp65_ = tmp62_*tmp14_;
   double tmp66_ = tmp63_*tmp3_;
   double tmp67_ = tmp65_+tmp66_;
   double tmp68_ = (tmp67_)*(tmp13_);
   double tmp69_ = tmp61_*tmp14_;
   double tmp70_ = tmp69_+tmp24_;
   double tmp71_ = (tmp70_)*(tmp18_);
   double tmp72_ = tmp68_+tmp71_;
   double tmp73_ = ElSquare(tmp34_);
   double tmp74_ = mCompCoord[2];
   double tmp75_ = tmp62_*tmp3_;
   double tmp76_ = tmp63_*tmp8_;
   double tmp77_ = tmp75_+tmp76_;
   double tmp78_ = (tmp77_)*(tmp13_);
   double tmp79_ = tmp61_*tmp3_;
   double tmp80_ = tmp79_+tmp36_;
   double tmp81_ = (tmp80_)*(tmp18_);
   double tmp82_ = tmp78_+tmp81_;
   double tmp83_ = (tmp82_)*(tmp34_);
   double tmp84_ = (tmp46_)*(tmp72_);
   double tmp85_ = tmp83_-tmp84_;
   double tmp86_ = (tmp85_)/tmp73_;
   double tmp87_ = mCompCoord[3];
   double tmp88_ = tmp61_*tmp19_;
   double tmp89_ = tmp88_*(tmp13_);
   double tmp90_ = tmp48_*(tmp18_);
   double tmp91_ = tmp89_+tmp90_;
   double tmp92_ = (tmp91_)*(tmp34_);
   double tmp93_ = (tmp54_)*(tmp72_);
   double tmp94_ = tmp92_-tmp93_;
   double tmp95_ = (tmp94_)/tmp73_;
   double tmp96_ = mCompCoord[4];
   double tmp97_ = tmp96_*(tmp55_);
   double tmp98_ = mCompCoord[5];
   double tmp99_ = mCompCoord[6];
   double tmp100_ = mCompCoord[7];
   double tmp101_ = 2*(tmp86_);
   double tmp102_ = tmp101_*(tmp47_);
   double tmp103_ = tmp100_*(tmp55_);
   double tmp104_ = 2*(tmp95_);
   double tmp105_ = tmp104_*(tmp55_);
   double tmp106_ = mCompCoord[8];
   double tmp107_ = tmp106_*tmp57_;
   double tmp108_ = mCompCoord[9];
   double tmp109_ = -(tmp19_);
   double tmp110_ = tmp109_*tmp2_;
   double tmp111_ = tmp109_*tmp4_;
   double tmp112_ = tmp60_*tmp6_;
   double tmp113_ = tmp110_*tmp3_;
   double tmp114_ = tmp113_*(tmp13_);
   double tmp115_ = tmp111_*tmp3_;
   double tmp116_ = tmp115_*(tmp18_);
   double tmp117_ = tmp114_+tmp116_;
   double tmp118_ = tmp112_*tmp3_;
   double tmp119_ = tmp118_*(tmp22_);
   double tmp120_ = tmp117_+tmp119_;
   double tmp121_ = tmp110_*tmp8_;
   double tmp122_ = tmp121_*(tmp13_);
   double tmp123_ = tmp111_*tmp8_;
   double tmp124_ = tmp123_*(tmp18_);
   double tmp125_ = tmp122_+tmp124_;
   double tmp126_ = tmp112_*tmp8_;
   double tmp127_ = tmp126_*(tmp22_);
   double tmp128_ = tmp125_+tmp127_;
   double tmp129_ = (tmp128_)*(tmp34_);
   double tmp130_ = (tmp46_)*(tmp120_);
   double tmp131_ = tmp129_-tmp130_;
   double tmp132_ = (tmp131_)/tmp73_;
   double tmp133_ = tmp112_*tmp2_;
   double tmp134_ = tmp133_*(tmp13_);
   double tmp135_ = tmp112_*tmp4_;
   double tmp136_ = tmp135_*(tmp18_);
   double tmp137_ = tmp134_+tmp136_;
   double tmp138_ = tmp19_*(tmp22_);
   double tmp139_ = tmp137_+tmp138_;
   double tmp140_ = (tmp139_)*(tmp34_);
   double tmp141_ = (tmp54_)*(tmp120_);
   double tmp142_ = tmp140_-tmp141_;
   double tmp143_ = (tmp142_)/tmp73_;
   double tmp144_ = 2*(tmp132_);
   double tmp145_ = tmp144_*(tmp47_);
   double tmp146_ = 2*(tmp143_);
   double tmp147_ = tmp146_*(tmp55_);
   double tmp148_ = tmp60_*tmp8_;
   double tmp149_ = -(tmp3_);
   double tmp150_ = tmp149_*tmp9_;
   double tmp151_ = tmp148_*tmp10_;
   double tmp152_ = tmp150_+tmp151_;
   double tmp153_ = (tmp152_)*(tmp13_);
   double tmp154_ = tmp149_*tmp2_;
   double tmp155_ = tmp148_*tmp15_;
   double tmp156_ = tmp154_+tmp155_;
   double tmp157_ = (tmp156_)*(tmp18_);
   double tmp158_ = tmp153_+tmp157_;
   double tmp159_ = tmp148_*tmp19_;
   double tmp160_ = tmp159_*(tmp22_);
   double tmp161_ = tmp158_+tmp160_;
   double tmp162_ = tmp148_*tmp9_;
   double tmp163_ = tmp3_*tmp10_;
   double tmp164_ = tmp162_+tmp163_;
   double tmp165_ = (tmp164_)*(tmp13_);
   double tmp166_ = tmp148_*tmp2_;
   double tmp167_ = tmp3_*tmp15_;
   double tmp168_ = tmp166_+tmp167_;
   double tmp169_ = (tmp168_)*(tmp18_);
   double tmp170_ = tmp165_+tmp169_;
   double tmp171_ = tmp3_*tmp19_;
   double tmp172_ = tmp171_*(tmp22_);
   double tmp173_ = tmp170_+tmp172_;
   double tmp174_ = (tmp173_)*(tmp34_);
   double tmp175_ = (tmp46_)*(tmp161_);
   double tmp176_ = tmp174_-tmp175_;
   double tmp177_ = (tmp176_)/tmp73_;
   double tmp178_ = (tmp54_)*(tmp161_);
   double tmp179_ = -(tmp178_);
   double tmp180_ = tmp179_/tmp73_;
   double tmp181_ = 2*(tmp177_);
   double tmp182_ = tmp181_*(tmp47_);
   double tmp183_ = 2*(tmp180_);
   double tmp184_ = tmp183_*(tmp55_);
   double tmp185_ = tmp60_*(tmp25_);
   double tmp186_ = tmp60_*(tmp37_);
   double tmp187_ = tmp186_*(tmp34_);
   double tmp188_ = (tmp46_)*tmp185_;
   double tmp189_ = tmp187_-tmp188_;
   double tmp190_ = (tmp189_)/tmp73_;
   double tmp191_ = tmp60_*tmp48_;
   double tmp192_ = tmp191_*(tmp34_);
   double tmp193_ = (tmp54_)*tmp185_;
   double tmp194_ = tmp192_-tmp193_;
   double tmp195_ = (tmp194_)/tmp73_;
   double tmp196_ = 2*(tmp190_);
   double tmp197_ = tmp196_*(tmp47_);
   double tmp198_ = 2*(tmp195_);
   double tmp199_ = tmp198_*(tmp55_);
   double tmp200_ = tmp60_*(tmp29_);
   double tmp201_ = tmp60_*(tmp41_);
   double tmp202_ = tmp201_*(tmp34_);
   double tmp203_ = (tmp46_)*tmp200_;
   double tmp204_ = tmp202_-tmp203_;
   double tmp205_ = (tmp204_)/tmp73_;
   double tmp206_ = tmp60_*tmp50_;
   double tmp207_ = tmp206_*(tmp34_);
   double tmp208_ = (tmp54_)*tmp200_;
   double tmp209_ = tmp207_-tmp208_;
   double tmp210_ = (tmp209_)/tmp73_;
   double tmp211_ = 2*(tmp205_);
   double tmp212_ = tmp211_*(tmp47_);
   double tmp213_ = 2*(tmp210_);
   double tmp214_ = tmp213_*(tmp55_);
   double tmp215_ = tmp60_*tmp32_;
   double tmp216_ = tmp60_*tmp44_;
   double tmp217_ = tmp216_*(tmp34_);
   double tmp218_ = (tmp46_)*tmp215_;
   double tmp219_ = tmp217_-tmp218_;
   double tmp220_ = (tmp219_)/tmp73_;
   double tmp221_ = tmp112_*(tmp34_);
   double tmp222_ = (tmp54_)*tmp215_;
   double tmp223_ = tmp221_-tmp222_;
   double tmp224_ = (tmp223_)/tmp73_;
   double tmp225_ = 2*(tmp220_);
   double tmp226_ = tmp225_*(tmp47_);
   double tmp227_ = 2*(tmp224_);
   double tmp228_ = tmp227_*(tmp55_);
   double tmp229_ = (tmp37_)*(tmp34_);
   double tmp230_ = (tmp46_)*(tmp25_);
   double tmp231_ = tmp229_-tmp230_;
   double tmp232_ = (tmp231_)/tmp73_;
   double tmp233_ = tmp48_*(tmp34_);
   double tmp234_ = (tmp54_)*(tmp25_);
   double tmp235_ = tmp233_-tmp234_;
   double tmp236_ = (tmp235_)/tmp73_;
   double tmp237_ = 2*(tmp232_);
   double tmp238_ = tmp237_*(tmp47_);
   double tmp239_ = 2*(tmp236_);
   double tmp240_ = tmp239_*(tmp55_);
   double tmp241_ = (tmp41_)*(tmp34_);
   double tmp242_ = (tmp46_)*(tmp29_);
   double tmp243_ = tmp241_-tmp242_;
   double tmp244_ = (tmp243_)/tmp73_;
   double tmp245_ = tmp50_*(tmp34_);
   double tmp246_ = (tmp54_)*(tmp29_);
   double tmp247_ = tmp245_-tmp246_;
   double tmp248_ = (tmp247_)/tmp73_;
   double tmp249_ = 2*(tmp244_);
   double tmp250_ = tmp249_*(tmp47_);
   double tmp251_ = 2*(tmp248_);
   double tmp252_ = tmp251_*(tmp55_);
   double tmp253_ = tmp44_*(tmp34_);
   double tmp254_ = (tmp46_)*tmp32_;
   double tmp255_ = tmp253_-tmp254_;
   double tmp256_ = (tmp255_)/tmp73_;
   double tmp257_ = tmp6_*(tmp34_);
   double tmp258_ = (tmp54_)*tmp32_;
   double tmp259_ = tmp257_-tmp258_;
   double tmp260_ = (tmp259_)/tmp73_;
   double tmp261_ = 2*(tmp256_);
   double tmp262_ = tmp261_*(tmp47_);
   double tmp263_ = 2*(tmp260_);
   double tmp264_ = tmp263_*(tmp55_);
   double tmp265_ = (tmp55_)*(tmp47_);
   double tmp266_ = (tmp55_)*tmp56_;
   double tmp267_ = tmp57_*(tmp47_);
   double tmp268_ = mCompCoord[11];
   double tmp269_ = mCompCoord[12];
   double tmp270_ = mCompCoord[13];
   double tmp271_ = mCompCoord[14];
   double tmp272_ = tmp271_*(tmp55_);
   double tmp273_ = mCompCoord[15];
   double tmp274_ = 3*(tmp86_);
   double tmp275_ = tmp274_*tmp56_;
   double tmp276_ = mCompCoord[16];
   double tmp277_ = mCompCoord[17];
   double tmp278_ = tmp277_*(tmp55_);
   double tmp279_ = mCompCoord[18];
   double tmp280_ = tmp279_*tmp57_;
   double tmp281_ = 3*(tmp95_);
   double tmp282_ = tmp281_*tmp57_;
   double tmp283_ = mCompCoord[19];
   double tmp284_ = 3*(tmp132_);
   double tmp285_ = tmp284_*tmp56_;
   double tmp286_ = 3*(tmp143_);
   double tmp287_ = tmp286_*tmp57_;
   double tmp288_ = 3*(tmp177_);
   double tmp289_ = tmp288_*tmp56_;
   double tmp290_ = 3*(tmp180_);
   double tmp291_ = tmp290_*tmp57_;
   double tmp292_ = 3*(tmp190_);
   double tmp293_ = tmp292_*tmp56_;
   double tmp294_ = 3*(tmp195_);
   double tmp295_ = tmp294_*tmp57_;
   double tmp296_ = 3*(tmp205_);
   double tmp297_ = tmp296_*tmp56_;
   double tmp298_ = 3*(tmp210_);
   double tmp299_ = tmp298_*tmp57_;
   double tmp300_ = 3*(tmp220_);
   double tmp301_ = tmp300_*tmp56_;
   double tmp302_ = 3*(tmp224_);
   double tmp303_ = tmp302_*tmp57_;
   double tmp304_ = 3*(tmp232_);
   double tmp305_ = tmp304_*tmp56_;
   double tmp306_ = 3*(tmp236_);
   double tmp307_ = tmp306_*tmp57_;
   double tmp308_ = 3*(tmp244_);
   double tmp309_ = tmp308_*tmp56_;
   double tmp310_ = 3*(tmp248_);
   double tmp311_ = tmp310_*tmp57_;
   double tmp312_ = 3*(tmp256_);
   double tmp313_ = tmp312_*tmp56_;
   double tmp314_ = 3*(tmp260_);
   double tmp315_ = tmp314_*tmp57_;

  mVal[0] = (mCompCoord[0]+tmp64_*(tmp47_)+tmp74_*(tmp55_)+tmp87_*tmp56_+tmp97_*(tmp47_)+tmp98_*tmp57_+tmp99_*tmp58_+tmp103_*tmp56_+tmp107_*(tmp47_)+tmp108_*tmp59_)-mLocXIm;

  mCompDer[0][0] = 1;
  mCompDer[0][1] = tmp47_;
  mCompDer[0][2] = tmp55_;
  mCompDer[0][3] = tmp56_;
  mCompDer[0][4] = tmp265_;
  mCompDer[0][5] = tmp57_;
  mCompDer[0][6] = tmp58_;
  mCompDer[0][7] = tmp266_;
  mCompDer[0][8] = tmp267_;
  mCompDer[0][9] = tmp59_;
  mCompDer[0][10] = 0;
  mCompDer[0][11] = 0;
  mCompDer[0][12] = 0;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = 0;
  mCompDer[0][16] = 0;
  mCompDer[0][17] = 0;
  mCompDer[0][18] = 0;
  mCompDer[0][19] = 0;
  mCompDer[0][20] = (tmp86_)*tmp64_+(tmp95_)*tmp74_+tmp102_*tmp87_+(tmp95_)*tmp96_*(tmp47_)+(tmp86_)*tmp97_+tmp105_*tmp98_+tmp275_*tmp99_+(tmp95_)*tmp100_*tmp56_+tmp102_*tmp103_+tmp105_*tmp106_*(tmp47_)+(tmp86_)*tmp107_+tmp282_*tmp108_;
  mCompDer[0][21] = (tmp132_)*tmp64_+(tmp143_)*tmp74_+tmp145_*tmp87_+(tmp143_)*tmp96_*(tmp47_)+(tmp132_)*tmp97_+tmp147_*tmp98_+tmp285_*tmp99_+(tmp143_)*tmp100_*tmp56_+tmp145_*tmp103_+tmp147_*tmp106_*(tmp47_)+(tmp132_)*tmp107_+tmp287_*tmp108_;
  mCompDer[0][22] = (tmp177_)*tmp64_+(tmp180_)*tmp74_+tmp182_*tmp87_+(tmp180_)*tmp96_*(tmp47_)+(tmp177_)*tmp97_+tmp184_*tmp98_+tmp289_*tmp99_+(tmp180_)*tmp100_*tmp56_+tmp182_*tmp103_+tmp184_*tmp106_*(tmp47_)+(tmp177_)*tmp107_+tmp291_*tmp108_;
  mCompDer[0][23] = (tmp190_)*tmp64_+(tmp195_)*tmp74_+tmp197_*tmp87_+(tmp195_)*tmp96_*(tmp47_)+(tmp190_)*tmp97_+tmp199_*tmp98_+tmp293_*tmp99_+(tmp195_)*tmp100_*tmp56_+tmp197_*tmp103_+tmp199_*tmp106_*(tmp47_)+(tmp190_)*tmp107_+tmp295_*tmp108_;
  mCompDer[0][24] = (tmp205_)*tmp64_+(tmp210_)*tmp74_+tmp212_*tmp87_+(tmp210_)*tmp96_*(tmp47_)+(tmp205_)*tmp97_+tmp214_*tmp98_+tmp297_*tmp99_+(tmp210_)*tmp100_*tmp56_+tmp212_*tmp103_+tmp214_*tmp106_*(tmp47_)+(tmp205_)*tmp107_+tmp299_*tmp108_;
  mCompDer[0][25] = (tmp220_)*tmp64_+(tmp224_)*tmp74_+tmp226_*tmp87_+(tmp224_)*tmp96_*(tmp47_)+(tmp220_)*tmp97_+tmp228_*tmp98_+tmp301_*tmp99_+(tmp224_)*tmp100_*tmp56_+tmp226_*tmp103_+tmp228_*tmp106_*(tmp47_)+(tmp220_)*tmp107_+tmp303_*tmp108_;
  mCompDer[0][26] = (tmp232_)*tmp64_+(tmp236_)*tmp74_+tmp238_*tmp87_+(tmp236_)*tmp96_*(tmp47_)+(tmp232_)*tmp97_+tmp240_*tmp98_+tmp305_*tmp99_+(tmp236_)*tmp100_*tmp56_+tmp238_*tmp103_+tmp240_*tmp106_*(tmp47_)+(tmp232_)*tmp107_+tmp307_*tmp108_;
  mCompDer[0][27] = (tmp244_)*tmp64_+(tmp248_)*tmp74_+tmp250_*tmp87_+(tmp248_)*tmp96_*(tmp47_)+(tmp244_)*tmp97_+tmp252_*tmp98_+tmp309_*tmp99_+(tmp248_)*tmp100_*tmp56_+tmp250_*tmp103_+tmp252_*tmp106_*(tmp47_)+(tmp244_)*tmp107_+tmp311_*tmp108_;
  mCompDer[0][28] = (tmp256_)*tmp64_+(tmp260_)*tmp74_+tmp262_*tmp87_+(tmp260_)*tmp96_*(tmp47_)+(tmp256_)*tmp97_+tmp264_*tmp98_+tmp313_*tmp99_+(tmp260_)*tmp100_*tmp56_+tmp262_*tmp103_+tmp264_*tmp106_*(tmp47_)+(tmp256_)*tmp107_+tmp315_*tmp108_;
  mVal[1] = (mCompCoord[10]+tmp268_*(tmp47_)+tmp269_*(tmp55_)+tmp270_*tmp56_+tmp272_*(tmp47_)+tmp273_*tmp57_+tmp276_*tmp58_+tmp278_*tmp56_+tmp280_*(tmp47_)+tmp283_*tmp59_)-mLocYIm;

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = 0;
  mCompDer[1][4] = 0;
  mCompDer[1][5] = 0;
  mCompDer[1][6] = 0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = 0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = 1;
  mCompDer[1][11] = tmp47_;
  mCompDer[1][12] = tmp55_;
  mCompDer[1][13] = tmp56_;
  mCompDer[1][14] = tmp265_;
  mCompDer[1][15] = tmp57_;
  mCompDer[1][16] = tmp58_;
  mCompDer[1][17] = tmp266_;
  mCompDer[1][18] = tmp267_;
  mCompDer[1][19] = tmp59_;
  mCompDer[1][20] = (tmp86_)*tmp268_+(tmp95_)*tmp269_+tmp102_*tmp270_+(tmp95_)*tmp271_*(tmp47_)+(tmp86_)*tmp272_+tmp105_*tmp273_+tmp275_*tmp276_+(tmp95_)*tmp277_*tmp56_+tmp102_*tmp278_+tmp105_*tmp279_*(tmp47_)+(tmp86_)*tmp280_+tmp282_*tmp283_;
  mCompDer[1][21] = (tmp132_)*tmp268_+(tmp143_)*tmp269_+tmp145_*tmp270_+(tmp143_)*tmp271_*(tmp47_)+(tmp132_)*tmp272_+tmp147_*tmp273_+tmp285_*tmp276_+(tmp143_)*tmp277_*tmp56_+tmp145_*tmp278_+tmp147_*tmp279_*(tmp47_)+(tmp132_)*tmp280_+tmp287_*tmp283_;
  mCompDer[1][22] = (tmp177_)*tmp268_+(tmp180_)*tmp269_+tmp182_*tmp270_+(tmp180_)*tmp271_*(tmp47_)+(tmp177_)*tmp272_+tmp184_*tmp273_+tmp289_*tmp276_+(tmp180_)*tmp277_*tmp56_+tmp182_*tmp278_+tmp184_*tmp279_*(tmp47_)+(tmp177_)*tmp280_+tmp291_*tmp283_;
  mCompDer[1][23] = (tmp190_)*tmp268_+(tmp195_)*tmp269_+tmp197_*tmp270_+(tmp195_)*tmp271_*(tmp47_)+(tmp190_)*tmp272_+tmp199_*tmp273_+tmp293_*tmp276_+(tmp195_)*tmp277_*tmp56_+tmp197_*tmp278_+tmp199_*tmp279_*(tmp47_)+(tmp190_)*tmp280_+tmp295_*tmp283_;
  mCompDer[1][24] = (tmp205_)*tmp268_+(tmp210_)*tmp269_+tmp212_*tmp270_+(tmp210_)*tmp271_*(tmp47_)+(tmp205_)*tmp272_+tmp214_*tmp273_+tmp297_*tmp276_+(tmp210_)*tmp277_*tmp56_+tmp212_*tmp278_+tmp214_*tmp279_*(tmp47_)+(tmp205_)*tmp280_+tmp299_*tmp283_;
  mCompDer[1][25] = (tmp220_)*tmp268_+(tmp224_)*tmp269_+tmp226_*tmp270_+(tmp224_)*tmp271_*(tmp47_)+(tmp220_)*tmp272_+tmp228_*tmp273_+tmp301_*tmp276_+(tmp224_)*tmp277_*tmp56_+tmp226_*tmp278_+tmp228_*tmp279_*(tmp47_)+(tmp220_)*tmp280_+tmp303_*tmp283_;
  mCompDer[1][26] = (tmp232_)*tmp268_+(tmp236_)*tmp269_+tmp238_*tmp270_+(tmp236_)*tmp271_*(tmp47_)+(tmp232_)*tmp272_+tmp240_*tmp273_+tmp305_*tmp276_+(tmp236_)*tmp277_*tmp56_+tmp238_*tmp278_+tmp240_*tmp279_*(tmp47_)+(tmp232_)*tmp280_+tmp307_*tmp283_;
  mCompDer[1][27] = (tmp244_)*tmp268_+(tmp248_)*tmp269_+tmp250_*tmp270_+(tmp248_)*tmp271_*(tmp47_)+(tmp244_)*tmp272_+tmp252_*tmp273_+tmp309_*tmp276_+(tmp248_)*tmp277_*tmp56_+tmp250_*tmp278_+tmp252_*tmp279_*(tmp47_)+(tmp244_)*tmp280_+tmp311_*tmp283_;
  mCompDer[1][28] = (tmp256_)*tmp268_+(tmp260_)*tmp269_+tmp262_*tmp270_+(tmp260_)*tmp271_*(tmp47_)+(tmp256_)*tmp272_+tmp264_*tmp273_+tmp313_*tmp276_+(tmp260_)*tmp277_*tmp56_+tmp262_*tmp278_+tmp264_*tmp279_*(tmp47_)+(tmp256_)*tmp280_+tmp315_*tmp283_;
}


void cEqAppui_PTInc_M2CDPol3::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_PTInc_M2CDPol3 Has no Der Sec");
}

void cEqAppui_PTInc_M2CDPol3::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_PTInc_M2CDPol3::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_PTInc_M2CDPol3::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_PTInc_M2CDPol3::mTheAuto("cEqAppui_PTInc_M2CDPol3",cEqAppui_PTInc_M2CDPol3::Alloc);


cElCompiledFonc *  cEqAppui_PTInc_M2CDPol3::Alloc()
{  return new cEqAppui_PTInc_M2CDPol3();
}


