// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar.h"


cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar():
    cElCompiledFonc(1)
{
   AddIntRef (cIncIntervale("Orient",0,6));
   AddIntRef (cIncIntervale("Tmp_PTer",6,9));
   Close(false);
}



void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::ComputeVal()
{
   double tmp0_ = mCompCoord[0];
   double tmp1_ = mCompCoord[1];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = cos(tmp0_);
   double tmp4_ = tmp3_*tmp2_;
   double tmp5_ = sin(tmp0_);
   double tmp6_ = tmp5_*tmp2_;
   double tmp7_ = sin(tmp1_);
   double tmp8_ = mCompCoord[2];
   double tmp9_ = sin(tmp8_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp7_);
   double tmp12_ = cos(tmp8_);
   double tmp13_ = mCompCoord[6];
   double tmp14_ = mCompCoord[3];
   double tmp15_ = tmp13_-tmp14_;
   double tmp16_ = -(tmp5_);
   double tmp17_ = tmp16_*tmp10_;
   double tmp18_ = tmp3_*tmp11_;
   double tmp19_ = tmp18_*tmp12_;
   double tmp20_ = tmp17_+tmp19_;
   double tmp21_ = tmp3_*tmp10_;
   double tmp22_ = tmp5_*tmp11_;
   double tmp23_ = tmp22_*tmp12_;
   double tmp24_ = tmp21_+tmp23_;
   double tmp25_ = tmp2_*tmp12_;
   double tmp26_ = mCompCoord[7];
   double tmp27_ = mCompCoord[4];
   double tmp28_ = tmp26_-tmp27_;
   double tmp29_ = mCompCoord[8];
   double tmp30_ = mCompCoord[5];
   double tmp31_ = tmp29_-tmp30_;
   double tmp32_ = tmp16_*tmp12_;
   double tmp33_ = tmp18_*tmp9_;
   double tmp34_ = tmp32_+tmp33_;
   double tmp35_ = tmp3_*tmp12_;
   double tmp36_ = tmp22_*tmp9_;
   double tmp37_ = tmp35_+tmp36_;
   double tmp38_ = tmp2_*tmp9_;
   double tmp39_ = (tmp20_)*mLocGL_0_0;
   double tmp40_ = (tmp24_)*mLocGL_1_0;
   double tmp41_ = tmp39_+tmp40_;
   double tmp42_ = tmp25_*mLocGL_2_0;
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = (tmp43_)*(tmp15_);
   double tmp45_ = (tmp20_)*mLocGL_0_1;
   double tmp46_ = (tmp24_)*mLocGL_1_1;
   double tmp47_ = tmp45_+tmp46_;
   double tmp48_ = tmp25_*mLocGL_2_1;
   double tmp49_ = tmp47_+tmp48_;
   double tmp50_ = (tmp49_)*(tmp28_);
   double tmp51_ = tmp44_+tmp50_;
   double tmp52_ = (tmp20_)*mLocGL_0_2;
   double tmp53_ = (tmp24_)*mLocGL_1_2;
   double tmp54_ = tmp52_+tmp53_;
   double tmp55_ = tmp25_*mLocGL_2_2;
   double tmp56_ = tmp54_+tmp55_;
   double tmp57_ = (tmp56_)*(tmp31_);
   double tmp58_ = tmp51_+tmp57_;
   double tmp59_ = tmp4_*mLocGL_0_0;
   double tmp60_ = tmp6_*mLocGL_1_0;
   double tmp61_ = tmp59_+tmp60_;
   double tmp62_ = tmp7_*mLocGL_2_0;
   double tmp63_ = tmp61_+tmp62_;
   double tmp64_ = (tmp63_)*(tmp15_);
   double tmp65_ = tmp4_*mLocGL_0_1;
   double tmp66_ = tmp6_*mLocGL_1_1;
   double tmp67_ = tmp65_+tmp66_;
   double tmp68_ = tmp7_*mLocGL_2_1;
   double tmp69_ = tmp67_+tmp68_;
   double tmp70_ = (tmp69_)*(tmp28_);
   double tmp71_ = tmp64_+tmp70_;
   double tmp72_ = tmp4_*mLocGL_0_2;
   double tmp73_ = tmp6_*mLocGL_1_2;
   double tmp74_ = tmp72_+tmp73_;
   double tmp75_ = tmp7_*mLocGL_2_2;
   double tmp76_ = tmp74_+tmp75_;
   double tmp77_ = (tmp76_)*(tmp31_);
   double tmp78_ = tmp71_+tmp77_;
   double tmp79_ = (tmp78_)/(tmp58_);
   double tmp80_ = (tmp34_)*mLocGL_0_0;
   double tmp81_ = (tmp37_)*mLocGL_1_0;
   double tmp82_ = tmp80_+tmp81_;
   double tmp83_ = tmp38_*mLocGL_2_0;
   double tmp84_ = tmp82_+tmp83_;
   double tmp85_ = (tmp84_)*(tmp15_);
   double tmp86_ = (tmp34_)*mLocGL_0_1;
   double tmp87_ = (tmp37_)*mLocGL_1_1;
   double tmp88_ = tmp86_+tmp87_;
   double tmp89_ = tmp38_*mLocGL_2_1;
   double tmp90_ = tmp88_+tmp89_;
   double tmp91_ = (tmp90_)*(tmp28_);
   double tmp92_ = tmp85_+tmp91_;
   double tmp93_ = (tmp34_)*mLocGL_0_2;
   double tmp94_ = (tmp37_)*mLocGL_1_2;
   double tmp95_ = tmp93_+tmp94_;
   double tmp96_ = tmp38_*mLocGL_2_2;
   double tmp97_ = tmp95_+tmp96_;
   double tmp98_ = (tmp97_)*(tmp31_);
   double tmp99_ = tmp92_+tmp98_;
   double tmp100_ = (tmp99_)/(tmp58_);

  mVal[0] = (mLocXIm-cos(mLocYIm)*(mLocNDP0_x+mLocNDdx_x*(tmp79_)+mLocNDdy_x*(tmp100_))-sin(mLocYIm)*(mLocNDP0_y+mLocNDdx_y*(tmp79_)+mLocNDdy_y*(tmp100_)))*mLocScNorm;

}


void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[0];
   double tmp1_ = mCompCoord[1];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = cos(tmp0_);
   double tmp4_ = tmp3_*tmp2_;
   double tmp5_ = sin(tmp0_);
   double tmp6_ = tmp5_*tmp2_;
   double tmp7_ = sin(tmp1_);
   double tmp8_ = mCompCoord[2];
   double tmp9_ = sin(tmp8_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp7_);
   double tmp12_ = cos(tmp8_);
   double tmp13_ = mCompCoord[6];
   double tmp14_ = mCompCoord[3];
   double tmp15_ = tmp13_-tmp14_;
   double tmp16_ = -(tmp5_);
   double tmp17_ = tmp16_*tmp10_;
   double tmp18_ = tmp3_*tmp11_;
   double tmp19_ = tmp18_*tmp12_;
   double tmp20_ = tmp17_+tmp19_;
   double tmp21_ = tmp3_*tmp10_;
   double tmp22_ = tmp5_*tmp11_;
   double tmp23_ = tmp22_*tmp12_;
   double tmp24_ = tmp21_+tmp23_;
   double tmp25_ = tmp2_*tmp12_;
   double tmp26_ = mCompCoord[7];
   double tmp27_ = mCompCoord[4];
   double tmp28_ = tmp26_-tmp27_;
   double tmp29_ = mCompCoord[8];
   double tmp30_ = mCompCoord[5];
   double tmp31_ = tmp29_-tmp30_;
   double tmp32_ = tmp16_*tmp12_;
   double tmp33_ = tmp18_*tmp9_;
   double tmp34_ = tmp32_+tmp33_;
   double tmp35_ = tmp3_*tmp12_;
   double tmp36_ = tmp22_*tmp9_;
   double tmp37_ = tmp35_+tmp36_;
   double tmp38_ = tmp2_*tmp9_;
   double tmp39_ = (tmp20_)*mLocGL_0_0;
   double tmp40_ = (tmp24_)*mLocGL_1_0;
   double tmp41_ = tmp39_+tmp40_;
   double tmp42_ = tmp25_*mLocGL_2_0;
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = (tmp43_)*(tmp15_);
   double tmp45_ = (tmp20_)*mLocGL_0_1;
   double tmp46_ = (tmp24_)*mLocGL_1_1;
   double tmp47_ = tmp45_+tmp46_;
   double tmp48_ = tmp25_*mLocGL_2_1;
   double tmp49_ = tmp47_+tmp48_;
   double tmp50_ = (tmp49_)*(tmp28_);
   double tmp51_ = tmp44_+tmp50_;
   double tmp52_ = (tmp20_)*mLocGL_0_2;
   double tmp53_ = (tmp24_)*mLocGL_1_2;
   double tmp54_ = tmp52_+tmp53_;
   double tmp55_ = tmp25_*mLocGL_2_2;
   double tmp56_ = tmp54_+tmp55_;
   double tmp57_ = (tmp56_)*(tmp31_);
   double tmp58_ = tmp51_+tmp57_;
   double tmp59_ = tmp4_*mLocGL_0_0;
   double tmp60_ = tmp6_*mLocGL_1_0;
   double tmp61_ = tmp59_+tmp60_;
   double tmp62_ = tmp7_*mLocGL_2_0;
   double tmp63_ = tmp61_+tmp62_;
   double tmp64_ = (tmp63_)*(tmp15_);
   double tmp65_ = tmp4_*mLocGL_0_1;
   double tmp66_ = tmp6_*mLocGL_1_1;
   double tmp67_ = tmp65_+tmp66_;
   double tmp68_ = tmp7_*mLocGL_2_1;
   double tmp69_ = tmp67_+tmp68_;
   double tmp70_ = (tmp69_)*(tmp28_);
   double tmp71_ = tmp64_+tmp70_;
   double tmp72_ = tmp4_*mLocGL_0_2;
   double tmp73_ = tmp6_*mLocGL_1_2;
   double tmp74_ = tmp72_+tmp73_;
   double tmp75_ = tmp7_*mLocGL_2_2;
   double tmp76_ = tmp74_+tmp75_;
   double tmp77_ = (tmp76_)*(tmp31_);
   double tmp78_ = tmp71_+tmp77_;
   double tmp79_ = (tmp78_)/(tmp58_);
   double tmp80_ = (tmp34_)*mLocGL_0_0;
   double tmp81_ = (tmp37_)*mLocGL_1_0;
   double tmp82_ = tmp80_+tmp81_;
   double tmp83_ = tmp38_*mLocGL_2_0;
   double tmp84_ = tmp82_+tmp83_;
   double tmp85_ = (tmp84_)*(tmp15_);
   double tmp86_ = (tmp34_)*mLocGL_0_1;
   double tmp87_ = (tmp37_)*mLocGL_1_1;
   double tmp88_ = tmp86_+tmp87_;
   double tmp89_ = tmp38_*mLocGL_2_1;
   double tmp90_ = tmp88_+tmp89_;
   double tmp91_ = (tmp90_)*(tmp28_);
   double tmp92_ = tmp85_+tmp91_;
   double tmp93_ = (tmp34_)*mLocGL_0_2;
   double tmp94_ = (tmp37_)*mLocGL_1_2;
   double tmp95_ = tmp93_+tmp94_;
   double tmp96_ = tmp38_*mLocGL_2_2;
   double tmp97_ = tmp95_+tmp96_;
   double tmp98_ = (tmp97_)*(tmp31_);
   double tmp99_ = tmp92_+tmp98_;
   double tmp100_ = (tmp99_)/(tmp58_);
   double tmp101_ = -(1);
   double tmp102_ = tmp101_*tmp5_;
   double tmp103_ = tmp102_*tmp2_;
   double tmp104_ = -(tmp3_);
   double tmp105_ = tmp104_*tmp10_;
   double tmp106_ = tmp102_*tmp11_;
   double tmp107_ = tmp106_*tmp12_;
   double tmp108_ = tmp105_+tmp107_;
   double tmp109_ = tmp102_*tmp10_;
   double tmp110_ = tmp109_+tmp19_;
   double tmp111_ = tmp104_*tmp12_;
   double tmp112_ = tmp106_*tmp9_;
   double tmp113_ = tmp111_+tmp112_;
   double tmp114_ = tmp102_*tmp12_;
   double tmp115_ = tmp114_+tmp33_;
   double tmp116_ = (tmp108_)*mLocGL_0_0;
   double tmp117_ = (tmp110_)*mLocGL_1_0;
   double tmp118_ = tmp116_+tmp117_;
   double tmp119_ = (tmp118_)*(tmp15_);
   double tmp120_ = (tmp108_)*mLocGL_0_1;
   double tmp121_ = (tmp110_)*mLocGL_1_1;
   double tmp122_ = tmp120_+tmp121_;
   double tmp123_ = (tmp122_)*(tmp28_);
   double tmp124_ = tmp119_+tmp123_;
   double tmp125_ = (tmp108_)*mLocGL_0_2;
   double tmp126_ = (tmp110_)*mLocGL_1_2;
   double tmp127_ = tmp125_+tmp126_;
   double tmp128_ = (tmp127_)*(tmp31_);
   double tmp129_ = tmp124_+tmp128_;
   double tmp130_ = ElSquare(tmp58_);
   double tmp131_ = cos(mLocYIm);
   double tmp132_ = tmp103_*mLocGL_0_0;
   double tmp133_ = tmp4_*mLocGL_1_0;
   double tmp134_ = tmp132_+tmp133_;
   double tmp135_ = (tmp134_)*(tmp15_);
   double tmp136_ = tmp103_*mLocGL_0_1;
   double tmp137_ = tmp4_*mLocGL_1_1;
   double tmp138_ = tmp136_+tmp137_;
   double tmp139_ = (tmp138_)*(tmp28_);
   double tmp140_ = tmp135_+tmp139_;
   double tmp141_ = tmp103_*mLocGL_0_2;
   double tmp142_ = tmp4_*mLocGL_1_2;
   double tmp143_ = tmp141_+tmp142_;
   double tmp144_ = (tmp143_)*(tmp31_);
   double tmp145_ = tmp140_+tmp144_;
   double tmp146_ = (tmp145_)*(tmp58_);
   double tmp147_ = (tmp78_)*(tmp129_);
   double tmp148_ = tmp146_-tmp147_;
   double tmp149_ = (tmp148_)/tmp130_;
   double tmp150_ = (tmp113_)*mLocGL_0_0;
   double tmp151_ = (tmp115_)*mLocGL_1_0;
   double tmp152_ = tmp150_+tmp151_;
   double tmp153_ = (tmp152_)*(tmp15_);
   double tmp154_ = (tmp113_)*mLocGL_0_1;
   double tmp155_ = (tmp115_)*mLocGL_1_1;
   double tmp156_ = tmp154_+tmp155_;
   double tmp157_ = (tmp156_)*(tmp28_);
   double tmp158_ = tmp153_+tmp157_;
   double tmp159_ = (tmp113_)*mLocGL_0_2;
   double tmp160_ = (tmp115_)*mLocGL_1_2;
   double tmp161_ = tmp159_+tmp160_;
   double tmp162_ = (tmp161_)*(tmp31_);
   double tmp163_ = tmp158_+tmp162_;
   double tmp164_ = (tmp163_)*(tmp58_);
   double tmp165_ = (tmp99_)*(tmp129_);
   double tmp166_ = tmp164_-tmp165_;
   double tmp167_ = (tmp166_)/tmp130_;
   double tmp168_ = sin(mLocYIm);
   double tmp169_ = tmp101_*tmp7_;
   double tmp170_ = tmp169_*tmp3_;
   double tmp171_ = tmp169_*tmp5_;
   double tmp172_ = -(tmp2_);
   double tmp173_ = tmp172_*tmp3_;
   double tmp174_ = tmp173_*tmp12_;
   double tmp175_ = tmp172_*tmp5_;
   double tmp176_ = tmp175_*tmp12_;
   double tmp177_ = tmp169_*tmp12_;
   double tmp178_ = tmp173_*tmp9_;
   double tmp179_ = tmp175_*tmp9_;
   double tmp180_ = tmp169_*tmp9_;
   double tmp181_ = tmp174_*mLocGL_0_0;
   double tmp182_ = tmp176_*mLocGL_1_0;
   double tmp183_ = tmp181_+tmp182_;
   double tmp184_ = tmp177_*mLocGL_2_0;
   double tmp185_ = tmp183_+tmp184_;
   double tmp186_ = (tmp185_)*(tmp15_);
   double tmp187_ = tmp174_*mLocGL_0_1;
   double tmp188_ = tmp176_*mLocGL_1_1;
   double tmp189_ = tmp187_+tmp188_;
   double tmp190_ = tmp177_*mLocGL_2_1;
   double tmp191_ = tmp189_+tmp190_;
   double tmp192_ = (tmp191_)*(tmp28_);
   double tmp193_ = tmp186_+tmp192_;
   double tmp194_ = tmp174_*mLocGL_0_2;
   double tmp195_ = tmp176_*mLocGL_1_2;
   double tmp196_ = tmp194_+tmp195_;
   double tmp197_ = tmp177_*mLocGL_2_2;
   double tmp198_ = tmp196_+tmp197_;
   double tmp199_ = (tmp198_)*(tmp31_);
   double tmp200_ = tmp193_+tmp199_;
   double tmp201_ = tmp170_*mLocGL_0_0;
   double tmp202_ = tmp171_*mLocGL_1_0;
   double tmp203_ = tmp201_+tmp202_;
   double tmp204_ = tmp2_*mLocGL_2_0;
   double tmp205_ = tmp203_+tmp204_;
   double tmp206_ = (tmp205_)*(tmp15_);
   double tmp207_ = tmp170_*mLocGL_0_1;
   double tmp208_ = tmp171_*mLocGL_1_1;
   double tmp209_ = tmp207_+tmp208_;
   double tmp210_ = tmp2_*mLocGL_2_1;
   double tmp211_ = tmp209_+tmp210_;
   double tmp212_ = (tmp211_)*(tmp28_);
   double tmp213_ = tmp206_+tmp212_;
   double tmp214_ = tmp170_*mLocGL_0_2;
   double tmp215_ = tmp171_*mLocGL_1_2;
   double tmp216_ = tmp214_+tmp215_;
   double tmp217_ = tmp2_*mLocGL_2_2;
   double tmp218_ = tmp216_+tmp217_;
   double tmp219_ = (tmp218_)*(tmp31_);
   double tmp220_ = tmp213_+tmp219_;
   double tmp221_ = (tmp220_)*(tmp58_);
   double tmp222_ = (tmp78_)*(tmp200_);
   double tmp223_ = tmp221_-tmp222_;
   double tmp224_ = (tmp223_)/tmp130_;
   double tmp225_ = tmp178_*mLocGL_0_0;
   double tmp226_ = tmp179_*mLocGL_1_0;
   double tmp227_ = tmp225_+tmp226_;
   double tmp228_ = tmp180_*mLocGL_2_0;
   double tmp229_ = tmp227_+tmp228_;
   double tmp230_ = (tmp229_)*(tmp15_);
   double tmp231_ = tmp178_*mLocGL_0_1;
   double tmp232_ = tmp179_*mLocGL_1_1;
   double tmp233_ = tmp231_+tmp232_;
   double tmp234_ = tmp180_*mLocGL_2_1;
   double tmp235_ = tmp233_+tmp234_;
   double tmp236_ = (tmp235_)*(tmp28_);
   double tmp237_ = tmp230_+tmp236_;
   double tmp238_ = tmp178_*mLocGL_0_2;
   double tmp239_ = tmp179_*mLocGL_1_2;
   double tmp240_ = tmp238_+tmp239_;
   double tmp241_ = tmp180_*mLocGL_2_2;
   double tmp242_ = tmp240_+tmp241_;
   double tmp243_ = (tmp242_)*(tmp31_);
   double tmp244_ = tmp237_+tmp243_;
   double tmp245_ = (tmp244_)*(tmp58_);
   double tmp246_ = (tmp99_)*(tmp200_);
   double tmp247_ = tmp245_-tmp246_;
   double tmp248_ = (tmp247_)/tmp130_;
   double tmp249_ = -(tmp12_);
   double tmp250_ = tmp101_*tmp9_;
   double tmp251_ = tmp249_*tmp16_;
   double tmp252_ = tmp250_*tmp18_;
   double tmp253_ = tmp251_+tmp252_;
   double tmp254_ = tmp249_*tmp3_;
   double tmp255_ = tmp250_*tmp22_;
   double tmp256_ = tmp254_+tmp255_;
   double tmp257_ = tmp250_*tmp2_;
   double tmp258_ = tmp250_*tmp16_;
   double tmp259_ = tmp12_*tmp18_;
   double tmp260_ = tmp258_+tmp259_;
   double tmp261_ = tmp250_*tmp3_;
   double tmp262_ = tmp12_*tmp22_;
   double tmp263_ = tmp261_+tmp262_;
   double tmp264_ = tmp12_*tmp2_;
   double tmp265_ = (tmp253_)*mLocGL_0_0;
   double tmp266_ = (tmp256_)*mLocGL_1_0;
   double tmp267_ = tmp265_+tmp266_;
   double tmp268_ = tmp257_*mLocGL_2_0;
   double tmp269_ = tmp267_+tmp268_;
   double tmp270_ = (tmp269_)*(tmp15_);
   double tmp271_ = (tmp253_)*mLocGL_0_1;
   double tmp272_ = (tmp256_)*mLocGL_1_1;
   double tmp273_ = tmp271_+tmp272_;
   double tmp274_ = tmp257_*mLocGL_2_1;
   double tmp275_ = tmp273_+tmp274_;
   double tmp276_ = (tmp275_)*(tmp28_);
   double tmp277_ = tmp270_+tmp276_;
   double tmp278_ = (tmp253_)*mLocGL_0_2;
   double tmp279_ = (tmp256_)*mLocGL_1_2;
   double tmp280_ = tmp278_+tmp279_;
   double tmp281_ = tmp257_*mLocGL_2_2;
   double tmp282_ = tmp280_+tmp281_;
   double tmp283_ = (tmp282_)*(tmp31_);
   double tmp284_ = tmp277_+tmp283_;
   double tmp285_ = (tmp78_)*(tmp284_);
   double tmp286_ = -(tmp285_);
   double tmp287_ = tmp286_/tmp130_;
   double tmp288_ = (tmp260_)*mLocGL_0_0;
   double tmp289_ = (tmp263_)*mLocGL_1_0;
   double tmp290_ = tmp288_+tmp289_;
   double tmp291_ = tmp264_*mLocGL_2_0;
   double tmp292_ = tmp290_+tmp291_;
   double tmp293_ = (tmp292_)*(tmp15_);
   double tmp294_ = (tmp260_)*mLocGL_0_1;
   double tmp295_ = (tmp263_)*mLocGL_1_1;
   double tmp296_ = tmp294_+tmp295_;
   double tmp297_ = tmp264_*mLocGL_2_1;
   double tmp298_ = tmp296_+tmp297_;
   double tmp299_ = (tmp298_)*(tmp28_);
   double tmp300_ = tmp293_+tmp299_;
   double tmp301_ = (tmp260_)*mLocGL_0_2;
   double tmp302_ = (tmp263_)*mLocGL_1_2;
   double tmp303_ = tmp301_+tmp302_;
   double tmp304_ = tmp264_*mLocGL_2_2;
   double tmp305_ = tmp303_+tmp304_;
   double tmp306_ = (tmp305_)*(tmp31_);
   double tmp307_ = tmp300_+tmp306_;
   double tmp308_ = (tmp307_)*(tmp58_);
   double tmp309_ = (tmp99_)*(tmp284_);
   double tmp310_ = tmp308_-tmp309_;
   double tmp311_ = (tmp310_)/tmp130_;
   double tmp312_ = tmp101_*(tmp43_);
   double tmp313_ = tmp101_*(tmp63_);
   double tmp314_ = tmp313_*(tmp58_);
   double tmp315_ = (tmp78_)*tmp312_;
   double tmp316_ = tmp314_-tmp315_;
   double tmp317_ = (tmp316_)/tmp130_;
   double tmp318_ = tmp101_*(tmp84_);
   double tmp319_ = tmp318_*(tmp58_);
   double tmp320_ = (tmp99_)*tmp312_;
   double tmp321_ = tmp319_-tmp320_;
   double tmp322_ = (tmp321_)/tmp130_;
   double tmp323_ = tmp101_*(tmp49_);
   double tmp324_ = tmp101_*(tmp69_);
   double tmp325_ = tmp324_*(tmp58_);
   double tmp326_ = (tmp78_)*tmp323_;
   double tmp327_ = tmp325_-tmp326_;
   double tmp328_ = (tmp327_)/tmp130_;
   double tmp329_ = tmp101_*(tmp90_);
   double tmp330_ = tmp329_*(tmp58_);
   double tmp331_ = (tmp99_)*tmp323_;
   double tmp332_ = tmp330_-tmp331_;
   double tmp333_ = (tmp332_)/tmp130_;
   double tmp334_ = tmp101_*(tmp56_);
   double tmp335_ = tmp101_*(tmp76_);
   double tmp336_ = tmp335_*(tmp58_);
   double tmp337_ = (tmp78_)*tmp334_;
   double tmp338_ = tmp336_-tmp337_;
   double tmp339_ = (tmp338_)/tmp130_;
   double tmp340_ = tmp101_*(tmp97_);
   double tmp341_ = tmp340_*(tmp58_);
   double tmp342_ = (tmp99_)*tmp334_;
   double tmp343_ = tmp341_-tmp342_;
   double tmp344_ = (tmp343_)/tmp130_;
   double tmp345_ = (tmp63_)*(tmp58_);
   double tmp346_ = (tmp78_)*(tmp43_);
   double tmp347_ = tmp345_-tmp346_;
   double tmp348_ = (tmp347_)/tmp130_;
   double tmp349_ = (tmp84_)*(tmp58_);
   double tmp350_ = (tmp99_)*(tmp43_);
   double tmp351_ = tmp349_-tmp350_;
   double tmp352_ = (tmp351_)/tmp130_;
   double tmp353_ = (tmp69_)*(tmp58_);
   double tmp354_ = (tmp78_)*(tmp49_);
   double tmp355_ = tmp353_-tmp354_;
   double tmp356_ = (tmp355_)/tmp130_;
   double tmp357_ = (tmp90_)*(tmp58_);
   double tmp358_ = (tmp99_)*(tmp49_);
   double tmp359_ = tmp357_-tmp358_;
   double tmp360_ = (tmp359_)/tmp130_;
   double tmp361_ = (tmp76_)*(tmp58_);
   double tmp362_ = (tmp78_)*(tmp56_);
   double tmp363_ = tmp361_-tmp362_;
   double tmp364_ = (tmp363_)/tmp130_;
   double tmp365_ = (tmp97_)*(tmp58_);
   double tmp366_ = (tmp99_)*(tmp56_);
   double tmp367_ = tmp365_-tmp366_;
   double tmp368_ = (tmp367_)/tmp130_;

  mVal[0] = (mLocXIm-tmp131_*(mLocNDP0_x+mLocNDdx_x*(tmp79_)+mLocNDdy_x*(tmp100_))-tmp168_*(mLocNDP0_y+mLocNDdx_y*(tmp79_)+mLocNDdy_y*(tmp100_)))*mLocScNorm;

  mCompDer[0][0] = (-(((tmp149_)*mLocNDdx_x+(tmp167_)*mLocNDdy_x)*tmp131_)-((tmp149_)*mLocNDdx_y+(tmp167_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][1] = (-(((tmp224_)*mLocNDdx_x+(tmp248_)*mLocNDdy_x)*tmp131_)-((tmp224_)*mLocNDdx_y+(tmp248_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][2] = (-(((tmp287_)*mLocNDdx_x+(tmp311_)*mLocNDdy_x)*tmp131_)-((tmp287_)*mLocNDdx_y+(tmp311_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][3] = (-(((tmp317_)*mLocNDdx_x+(tmp322_)*mLocNDdy_x)*tmp131_)-((tmp317_)*mLocNDdx_y+(tmp322_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][4] = (-(((tmp328_)*mLocNDdx_x+(tmp333_)*mLocNDdy_x)*tmp131_)-((tmp328_)*mLocNDdx_y+(tmp333_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][5] = (-(((tmp339_)*mLocNDdx_x+(tmp344_)*mLocNDdy_x)*tmp131_)-((tmp339_)*mLocNDdx_y+(tmp344_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][6] = (-(((tmp348_)*mLocNDdx_x+(tmp352_)*mLocNDdy_x)*tmp131_)-((tmp348_)*mLocNDdx_y+(tmp352_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][7] = (-(((tmp356_)*mLocNDdx_x+(tmp360_)*mLocNDdy_x)*tmp131_)-((tmp356_)*mLocNDdx_y+(tmp360_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
  mCompDer[0][8] = (-(((tmp364_)*mLocNDdx_x+(tmp368_)*mLocNDdy_x)*tmp131_)-((tmp364_)*mLocNDdx_y+(tmp368_)*mLocNDdy_y)*tmp168_)*mLocScNorm;
}


void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar Has no Der Sec");
}

void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_0_0(double aVal){ mLocGL_0_0 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_0_1(double aVal){ mLocGL_0_1 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_0_2(double aVal){ mLocGL_0_2 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_1_0(double aVal){ mLocGL_1_0 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_1_1(double aVal){ mLocGL_1_1 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_1_2(double aVal){ mLocGL_1_2 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_2_0(double aVal){ mLocGL_2_0 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_2_1(double aVal){ mLocGL_2_1 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetGL_2_2(double aVal){ mLocGL_2_2 = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDP0_x(double aVal){ mLocNDP0_x = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDP0_y(double aVal){ mLocNDP0_y = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDdx_x(double aVal){ mLocNDdx_x = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDdx_y(double aVal){ mLocNDdx_y = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDdy_x(double aVal){ mLocNDdy_x = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetNDdy_y(double aVal){ mLocNDdy_y = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetScNorm(double aVal){ mLocScNorm = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "GL_0_0") return & mLocGL_0_0;
   if (aName == "GL_0_1") return & mLocGL_0_1;
   if (aName == "GL_0_2") return & mLocGL_0_2;
   if (aName == "GL_1_0") return & mLocGL_1_0;
   if (aName == "GL_1_1") return & mLocGL_1_1;
   if (aName == "GL_1_2") return & mLocGL_1_2;
   if (aName == "GL_2_0") return & mLocGL_2_0;
   if (aName == "GL_2_1") return & mLocGL_2_1;
   if (aName == "GL_2_2") return & mLocGL_2_2;
   if (aName == "NDP0_x") return & mLocNDP0_x;
   if (aName == "NDP0_y") return & mLocNDP0_y;
   if (aName == "NDdx_x") return & mLocNDdx_x;
   if (aName == "NDdx_y") return & mLocNDdx_y;
   if (aName == "NDdy_x") return & mLocNDdy_x;
   if (aName == "NDdy_y") return & mLocNDdy_y;
   if (aName == "ScNorm") return & mLocScNorm;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::mTheAuto("cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar",cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::Alloc);


cElCompiledFonc *  cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar::Alloc()
{  return new cEqAppui_Droite_NoDist__GL__PTInc_M2CNoVar();
}


