// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cEqAppui_GL__PTInc_M2CPolyn0.h"


cEqAppui_GL__PTInc_M2CPolyn0::cEqAppui_GL__PTInc_M2CPolyn0():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,3));
   AddIntRef (cIncIntervale("Orient",3,9));
   AddIntRef (cIncIntervale("Tmp_PTer",9,12));
   Close(false);
}



void cEqAppui_GL__PTInc_M2CPolyn0::ComputeVal()
{
   double tmp0_ = mCompCoord[3];
   double tmp1_ = mCompCoord[4];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = cos(tmp0_);
   double tmp4_ = tmp3_ * tmp2_;
   double tmp5_ = sin(tmp0_);
   double tmp6_ = tmp5_ * tmp2_;
   double tmp7_ = sin(tmp1_);
   double tmp8_ = mCompCoord[5];
   double tmp9_ = sin(tmp8_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp7_);
   double tmp12_ = cos(tmp8_);
   double tmp13_ = mCompCoord[9];
   double tmp14_ = mCompCoord[6];
   double tmp15_ = tmp13_ - tmp14_;
   double tmp16_ = -(tmp5_);
   double tmp17_ = tmp16_ * tmp10_;
   double tmp18_ = tmp3_ * tmp11_;
   double tmp19_ = tmp18_ * tmp12_;
   double tmp20_ = tmp17_ + tmp19_;
   double tmp21_ = tmp3_ * tmp10_;
   double tmp22_ = tmp5_ * tmp11_;
   double tmp23_ = tmp22_ * tmp12_;
   double tmp24_ = tmp21_ + tmp23_;
   double tmp25_ = tmp2_ * tmp12_;
   double tmp26_ = mCompCoord[10];
   double tmp27_ = mCompCoord[7];
   double tmp28_ = tmp26_ - tmp27_;
   double tmp29_ = mCompCoord[11];
   double tmp30_ = mCompCoord[8];
   double tmp31_ = tmp29_ - tmp30_;
   double tmp32_ = tmp16_ * tmp12_;
   double tmp33_ = tmp18_ * tmp9_;
   double tmp34_ = tmp32_ + tmp33_;
   double tmp35_ = tmp3_ * tmp12_;
   double tmp36_ = tmp22_ * tmp9_;
   double tmp37_ = tmp35_ + tmp36_;
   double tmp38_ = tmp2_ * tmp9_;
   double tmp39_ = mCompCoord[0];
   double tmp40_ = (tmp20_) * mLocGL_0_0;
   double tmp41_ = (tmp24_) * mLocGL_1_0;
   double tmp42_ = tmp40_ + tmp41_;
   double tmp43_ = tmp25_ * mLocGL_2_0;
   double tmp44_ = tmp42_ + tmp43_;
   double tmp45_ = (tmp44_) * (tmp15_);
   double tmp46_ = (tmp20_) * mLocGL_0_1;
   double tmp47_ = (tmp24_) * mLocGL_1_1;
   double tmp48_ = tmp46_ + tmp47_;
   double tmp49_ = tmp25_ * mLocGL_2_1;
   double tmp50_ = tmp48_ + tmp49_;
   double tmp51_ = (tmp50_) * (tmp28_);
   double tmp52_ = tmp45_ + tmp51_;
   double tmp53_ = (tmp20_) * mLocGL_0_2;
   double tmp54_ = (tmp24_) * mLocGL_1_2;
   double tmp55_ = tmp53_ + tmp54_;
   double tmp56_ = tmp25_ * mLocGL_2_2;
   double tmp57_ = tmp55_ + tmp56_;
   double tmp58_ = (tmp57_) * (tmp31_);
   double tmp59_ = tmp52_ + tmp58_;
   double tmp60_ = tmp39_ / (tmp59_);

  mVal[0] = ((((tmp4_ * mLocGL_0_0 + tmp6_ * mLocGL_1_0 + tmp7_ * mLocGL_2_0) * (tmp15_) + (tmp4_ * mLocGL_0_1 + tmp6_ * mLocGL_1_1 + tmp7_ * mLocGL_2_1) * (tmp28_) + (tmp4_ * mLocGL_0_2 + tmp6_ * mLocGL_1_2 + tmp7_ * mLocGL_2_2) * (tmp31_)) * (tmp60_) + mCompCoord[1]) - mLocXIm) * mLocScNorm;

  mVal[1] = (((((tmp34_) * mLocGL_0_0 + (tmp37_) * mLocGL_1_0 + tmp38_ * mLocGL_2_0) * (tmp15_) + ((tmp34_) * mLocGL_0_1 + (tmp37_) * mLocGL_1_1 + tmp38_ * mLocGL_2_1) * (tmp28_) + ((tmp34_) * mLocGL_0_2 + (tmp37_) * mLocGL_1_2 + tmp38_ * mLocGL_2_2) * (tmp31_)) * (tmp60_) + mCompCoord[2]) - mLocYIm) * mLocScNorm;

}


void cEqAppui_GL__PTInc_M2CPolyn0::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[3];
   double tmp1_ = mCompCoord[4];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = cos(tmp0_);
   double tmp4_ = tmp3_ * tmp2_;
   double tmp5_ = sin(tmp0_);
   double tmp6_ = tmp5_ * tmp2_;
   double tmp7_ = sin(tmp1_);
   double tmp8_ = mCompCoord[5];
   double tmp9_ = sin(tmp8_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp7_);
   double tmp12_ = cos(tmp8_);
   double tmp13_ = mCompCoord[9];
   double tmp14_ = mCompCoord[6];
   double tmp15_ = tmp13_ - tmp14_;
   double tmp16_ = -(tmp5_);
   double tmp17_ = tmp16_ * tmp10_;
   double tmp18_ = tmp3_ * tmp11_;
   double tmp19_ = tmp18_ * tmp12_;
   double tmp20_ = tmp17_ + tmp19_;
   double tmp21_ = tmp3_ * tmp10_;
   double tmp22_ = tmp5_ * tmp11_;
   double tmp23_ = tmp22_ * tmp12_;
   double tmp24_ = tmp21_ + tmp23_;
   double tmp25_ = tmp2_ * tmp12_;
   double tmp26_ = mCompCoord[10];
   double tmp27_ = mCompCoord[7];
   double tmp28_ = tmp26_ - tmp27_;
   double tmp29_ = mCompCoord[11];
   double tmp30_ = mCompCoord[8];
   double tmp31_ = tmp29_ - tmp30_;
   double tmp32_ = (tmp20_) * mLocGL_0_0;
   double tmp33_ = (tmp24_) * mLocGL_1_0;
   double tmp34_ = tmp32_ + tmp33_;
   double tmp35_ = tmp25_ * mLocGL_2_0;
   double tmp36_ = tmp34_ + tmp35_;
   double tmp37_ = (tmp36_) * (tmp15_);
   double tmp38_ = (tmp20_) * mLocGL_0_1;
   double tmp39_ = (tmp24_) * mLocGL_1_1;
   double tmp40_ = tmp38_ + tmp39_;
   double tmp41_ = tmp25_ * mLocGL_2_1;
   double tmp42_ = tmp40_ + tmp41_;
   double tmp43_ = (tmp42_) * (tmp28_);
   double tmp44_ = tmp37_ + tmp43_;
   double tmp45_ = (tmp20_) * mLocGL_0_2;
   double tmp46_ = (tmp24_) * mLocGL_1_2;
   double tmp47_ = tmp45_ + tmp46_;
   double tmp48_ = tmp25_ * mLocGL_2_2;
   double tmp49_ = tmp47_ + tmp48_;
   double tmp50_ = (tmp49_) * (tmp31_);
   double tmp51_ = tmp44_ + tmp50_;
   double tmp52_ = tmp4_ * mLocGL_0_0;
   double tmp53_ = tmp6_ * mLocGL_1_0;
   double tmp54_ = tmp52_ + tmp53_;
   double tmp55_ = tmp7_ * mLocGL_2_0;
   double tmp56_ = tmp54_ + tmp55_;
   double tmp57_ = (tmp56_) * (tmp15_);
   double tmp58_ = tmp4_ * mLocGL_0_1;
   double tmp59_ = tmp6_ * mLocGL_1_1;
   double tmp60_ = tmp58_ + tmp59_;
   double tmp61_ = tmp7_ * mLocGL_2_1;
   double tmp62_ = tmp60_ + tmp61_;
   double tmp63_ = (tmp62_) * (tmp28_);
   double tmp64_ = tmp57_ + tmp63_;
   double tmp65_ = tmp4_ * mLocGL_0_2;
   double tmp66_ = tmp6_ * mLocGL_1_2;
   double tmp67_ = tmp65_ + tmp66_;
   double tmp68_ = tmp7_ * mLocGL_2_2;
   double tmp69_ = tmp67_ + tmp68_;
   double tmp70_ = (tmp69_) * (tmp31_);
   double tmp71_ = tmp64_ + tmp70_;
   double tmp72_ = -(1);
   double tmp73_ = tmp72_ * tmp5_;
   double tmp74_ = tmp73_ * tmp2_;
   double tmp75_ = mCompCoord[0];
   double tmp76_ = tmp75_ / (tmp51_);
   double tmp77_ = -(tmp3_);
   double tmp78_ = tmp77_ * tmp10_;
   double tmp79_ = tmp73_ * tmp11_;
   double tmp80_ = tmp79_ * tmp12_;
   double tmp81_ = tmp78_ + tmp80_;
   double tmp82_ = tmp73_ * tmp10_;
   double tmp83_ = tmp82_ + tmp19_;
   double tmp84_ = ElSquare(tmp51_);
   double tmp85_ = tmp72_ * tmp7_;
   double tmp86_ = tmp85_ * tmp3_;
   double tmp87_ = tmp85_ * tmp5_;
   double tmp88_ = -(tmp2_);
   double tmp89_ = tmp88_ * tmp3_;
   double tmp90_ = tmp89_ * tmp12_;
   double tmp91_ = tmp88_ * tmp5_;
   double tmp92_ = tmp91_ * tmp12_;
   double tmp93_ = tmp85_ * tmp12_;
   double tmp94_ = -(tmp12_);
   double tmp95_ = tmp72_ * tmp9_;
   double tmp96_ = tmp94_ * tmp16_;
   double tmp97_ = tmp95_ * tmp18_;
   double tmp98_ = tmp96_ + tmp97_;
   double tmp99_ = tmp94_ * tmp3_;
   double tmp100_ = tmp95_ * tmp22_;
   double tmp101_ = tmp99_ + tmp100_;
   double tmp102_ = tmp95_ * tmp2_;
   double tmp103_ = tmp16_ * tmp12_;
   double tmp104_ = tmp18_ * tmp9_;
   double tmp105_ = tmp103_ + tmp104_;
   double tmp106_ = tmp3_ * tmp12_;
   double tmp107_ = tmp22_ * tmp9_;
   double tmp108_ = tmp106_ + tmp107_;
   double tmp109_ = tmp2_ * tmp9_;
   double tmp110_ = (tmp51_) / tmp84_;
   double tmp111_ = (tmp105_) * mLocGL_0_0;
   double tmp112_ = (tmp108_) * mLocGL_1_0;
   double tmp113_ = tmp111_ + tmp112_;
   double tmp114_ = tmp109_ * mLocGL_2_0;
   double tmp115_ = tmp113_ + tmp114_;
   double tmp116_ = (tmp115_) * (tmp15_);
   double tmp117_ = (tmp105_) * mLocGL_0_1;
   double tmp118_ = (tmp108_) * mLocGL_1_1;
   double tmp119_ = tmp117_ + tmp118_;
   double tmp120_ = tmp109_ * mLocGL_2_1;
   double tmp121_ = tmp119_ + tmp120_;
   double tmp122_ = (tmp121_) * (tmp28_);
   double tmp123_ = tmp116_ + tmp122_;
   double tmp124_ = (tmp105_) * mLocGL_0_2;
   double tmp125_ = (tmp108_) * mLocGL_1_2;
   double tmp126_ = tmp124_ + tmp125_;
   double tmp127_ = tmp109_ * mLocGL_2_2;
   double tmp128_ = tmp126_ + tmp127_;
   double tmp129_ = (tmp128_) * (tmp31_);
   double tmp130_ = tmp123_ + tmp129_;
   double tmp131_ = tmp77_ * tmp12_;
   double tmp132_ = tmp79_ * tmp9_;
   double tmp133_ = tmp131_ + tmp132_;
   double tmp134_ = tmp73_ * tmp12_;
   double tmp135_ = tmp134_ + tmp104_;
   double tmp136_ = (tmp81_) * mLocGL_0_0;
   double tmp137_ = (tmp83_) * mLocGL_1_0;
   double tmp138_ = tmp136_ + tmp137_;
   double tmp139_ = (tmp138_) * (tmp15_);
   double tmp140_ = (tmp81_) * mLocGL_0_1;
   double tmp141_ = (tmp83_) * mLocGL_1_1;
   double tmp142_ = tmp140_ + tmp141_;
   double tmp143_ = (tmp142_) * (tmp28_);
   double tmp144_ = tmp139_ + tmp143_;
   double tmp145_ = (tmp81_) * mLocGL_0_2;
   double tmp146_ = (tmp83_) * mLocGL_1_2;
   double tmp147_ = tmp145_ + tmp146_;
   double tmp148_ = (tmp147_) * (tmp31_);
   double tmp149_ = tmp144_ + tmp148_;
   double tmp150_ = tmp75_ * (tmp149_);
   double tmp151_ = -(tmp150_);
   double tmp152_ = tmp151_ / tmp84_;
   double tmp153_ = tmp89_ * tmp9_;
   double tmp154_ = tmp91_ * tmp9_;
   double tmp155_ = tmp85_ * tmp9_;
   double tmp156_ = tmp90_ * mLocGL_0_0;
   double tmp157_ = tmp92_ * mLocGL_1_0;
   double tmp158_ = tmp156_ + tmp157_;
   double tmp159_ = tmp93_ * mLocGL_2_0;
   double tmp160_ = tmp158_ + tmp159_;
   double tmp161_ = (tmp160_) * (tmp15_);
   double tmp162_ = tmp90_ * mLocGL_0_1;
   double tmp163_ = tmp92_ * mLocGL_1_1;
   double tmp164_ = tmp162_ + tmp163_;
   double tmp165_ = tmp93_ * mLocGL_2_1;
   double tmp166_ = tmp164_ + tmp165_;
   double tmp167_ = (tmp166_) * (tmp28_);
   double tmp168_ = tmp161_ + tmp167_;
   double tmp169_ = tmp90_ * mLocGL_0_2;
   double tmp170_ = tmp92_ * mLocGL_1_2;
   double tmp171_ = tmp169_ + tmp170_;
   double tmp172_ = tmp93_ * mLocGL_2_2;
   double tmp173_ = tmp171_ + tmp172_;
   double tmp174_ = (tmp173_) * (tmp31_);
   double tmp175_ = tmp168_ + tmp174_;
   double tmp176_ = tmp75_ * (tmp175_);
   double tmp177_ = -(tmp176_);
   double tmp178_ = tmp177_ / tmp84_;
   double tmp179_ = tmp95_ * tmp16_;
   double tmp180_ = tmp12_ * tmp18_;
   double tmp181_ = tmp179_ + tmp180_;
   double tmp182_ = tmp95_ * tmp3_;
   double tmp183_ = tmp12_ * tmp22_;
   double tmp184_ = tmp182_ + tmp183_;
   double tmp185_ = tmp12_ * tmp2_;
   double tmp186_ = (tmp98_) * mLocGL_0_0;
   double tmp187_ = (tmp101_) * mLocGL_1_0;
   double tmp188_ = tmp186_ + tmp187_;
   double tmp189_ = tmp102_ * mLocGL_2_0;
   double tmp190_ = tmp188_ + tmp189_;
   double tmp191_ = (tmp190_) * (tmp15_);
   double tmp192_ = (tmp98_) * mLocGL_0_1;
   double tmp193_ = (tmp101_) * mLocGL_1_1;
   double tmp194_ = tmp192_ + tmp193_;
   double tmp195_ = tmp102_ * mLocGL_2_1;
   double tmp196_ = tmp194_ + tmp195_;
   double tmp197_ = (tmp196_) * (tmp28_);
   double tmp198_ = tmp191_ + tmp197_;
   double tmp199_ = (tmp98_) * mLocGL_0_2;
   double tmp200_ = (tmp101_) * mLocGL_1_2;
   double tmp201_ = tmp199_ + tmp200_;
   double tmp202_ = tmp102_ * mLocGL_2_2;
   double tmp203_ = tmp201_ + tmp202_;
   double tmp204_ = (tmp203_) * (tmp31_);
   double tmp205_ = tmp198_ + tmp204_;
   double tmp206_ = tmp75_ * (tmp205_);
   double tmp207_ = -(tmp206_);
   double tmp208_ = tmp207_ / tmp84_;
   double tmp209_ = tmp72_ * (tmp36_);
   double tmp210_ = tmp75_ * tmp209_;
   double tmp211_ = -(tmp210_);
   double tmp212_ = tmp211_ / tmp84_;
   double tmp213_ = tmp72_ * (tmp42_);
   double tmp214_ = tmp75_ * tmp213_;
   double tmp215_ = -(tmp214_);
   double tmp216_ = tmp215_ / tmp84_;
   double tmp217_ = tmp72_ * (tmp49_);
   double tmp218_ = tmp75_ * tmp217_;
   double tmp219_ = -(tmp218_);
   double tmp220_ = tmp219_ / tmp84_;
   double tmp221_ = tmp75_ * (tmp36_);
   double tmp222_ = -(tmp221_);
   double tmp223_ = tmp222_ / tmp84_;
   double tmp224_ = tmp75_ * (tmp42_);
   double tmp225_ = -(tmp224_);
   double tmp226_ = tmp225_ / tmp84_;
   double tmp227_ = tmp75_ * (tmp49_);
   double tmp228_ = -(tmp227_);
   double tmp229_ = tmp228_ / tmp84_;

  mVal[0] = (((tmp71_) * (tmp76_) + mCompCoord[1]) - mLocXIm) * mLocScNorm;

  mCompDer[0][0] = (tmp110_) * (tmp71_) * mLocScNorm;
  mCompDer[0][1] = mLocScNorm;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = (((tmp74_ * mLocGL_0_0 + tmp4_ * mLocGL_1_0) * (tmp15_) + (tmp74_ * mLocGL_0_1 + tmp4_ * mLocGL_1_1) * (tmp28_) + (tmp74_ * mLocGL_0_2 + tmp4_ * mLocGL_1_2) * (tmp31_)) * (tmp76_) + (tmp152_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][4] = (((tmp86_ * mLocGL_0_0 + tmp87_ * mLocGL_1_0 + tmp2_ * mLocGL_2_0) * (tmp15_) + (tmp86_ * mLocGL_0_1 + tmp87_ * mLocGL_1_1 + tmp2_ * mLocGL_2_1) * (tmp28_) + (tmp86_ * mLocGL_0_2 + tmp87_ * mLocGL_1_2 + tmp2_ * mLocGL_2_2) * (tmp31_)) * (tmp76_) + (tmp178_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][5] = (tmp208_) * (tmp71_) * mLocScNorm;
  mCompDer[0][6] = (tmp72_ * (tmp56_) * (tmp76_) + (tmp212_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][7] = (tmp72_ * (tmp62_) * (tmp76_) + (tmp216_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][8] = (tmp72_ * (tmp69_) * (tmp76_) + (tmp220_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][9] = ((tmp56_) * (tmp76_) + (tmp223_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][10] = ((tmp62_) * (tmp76_) + (tmp226_) * (tmp71_)) * mLocScNorm;
  mCompDer[0][11] = ((tmp69_) * (tmp76_) + (tmp229_) * (tmp71_)) * mLocScNorm;
  mVal[1] = (((tmp130_) * (tmp76_) + mCompCoord[2]) - mLocYIm) * mLocScNorm;

  mCompDer[1][0] = (tmp110_) * (tmp130_) * mLocScNorm;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = mLocScNorm;
  mCompDer[1][3] = ((((tmp133_) * mLocGL_0_0 + (tmp135_) * mLocGL_1_0) * (tmp15_) + ((tmp133_) * mLocGL_0_1 + (tmp135_) * mLocGL_1_1) * (tmp28_) + ((tmp133_) * mLocGL_0_2 + (tmp135_) * mLocGL_1_2) * (tmp31_)) * (tmp76_) + (tmp152_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][4] = (((tmp153_ * mLocGL_0_0 + tmp154_ * mLocGL_1_0 + tmp155_ * mLocGL_2_0) * (tmp15_) + (tmp153_ * mLocGL_0_1 + tmp154_ * mLocGL_1_1 + tmp155_ * mLocGL_2_1) * (tmp28_) + (tmp153_ * mLocGL_0_2 + tmp154_ * mLocGL_1_2 + tmp155_ * mLocGL_2_2) * (tmp31_)) * (tmp76_) + (tmp178_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][5] = ((((tmp181_) * mLocGL_0_0 + (tmp184_) * mLocGL_1_0 + tmp185_ * mLocGL_2_0) * (tmp15_) + ((tmp181_) * mLocGL_0_1 + (tmp184_) * mLocGL_1_1 + tmp185_ * mLocGL_2_1) * (tmp28_) + ((tmp181_) * mLocGL_0_2 + (tmp184_) * mLocGL_1_2 + tmp185_ * mLocGL_2_2) * (tmp31_)) * (tmp76_) + (tmp208_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][6] = (tmp72_ * (tmp115_) * (tmp76_) + (tmp212_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][7] = (tmp72_ * (tmp121_) * (tmp76_) + (tmp216_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][8] = (tmp72_ * (tmp128_) * (tmp76_) + (tmp220_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][9] = ((tmp115_) * (tmp76_) + (tmp223_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][10] = ((tmp121_) * (tmp76_) + (tmp226_) * (tmp130_)) * mLocScNorm;
  mCompDer[1][11] = ((tmp128_) * (tmp76_) + (tmp229_) * (tmp130_)) * mLocScNorm;
}


void cEqAppui_GL__PTInc_M2CPolyn0::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_GL__PTInc_M2CPolyn0 Has no Der Sec");
}

void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_0_0(double aVal){ mLocGL_0_0 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_0_1(double aVal){ mLocGL_0_1 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_0_2(double aVal){ mLocGL_0_2 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_1_0(double aVal){ mLocGL_1_0 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_1_1(double aVal){ mLocGL_1_1 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_1_2(double aVal){ mLocGL_1_2 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_2_0(double aVal){ mLocGL_2_0 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_2_1(double aVal){ mLocGL_2_1 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetGL_2_2(double aVal){ mLocGL_2_2 = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetScNorm(double aVal){ mLocScNorm = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_GL__PTInc_M2CPolyn0::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_GL__PTInc_M2CPolyn0::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "GL_0_0") return & mLocGL_0_0;
   if (aName == "GL_0_1") return & mLocGL_0_1;
   if (aName == "GL_0_2") return & mLocGL_0_2;
   if (aName == "GL_1_0") return & mLocGL_1_0;
   if (aName == "GL_1_1") return & mLocGL_1_1;
   if (aName == "GL_1_2") return & mLocGL_1_2;
   if (aName == "GL_2_0") return & mLocGL_2_0;
   if (aName == "GL_2_1") return & mLocGL_2_1;
   if (aName == "GL_2_2") return & mLocGL_2_2;
   if (aName == "ScNorm") return & mLocScNorm;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_GL__PTInc_M2CPolyn0::mTheAuto("cEqAppui_GL__PTInc_M2CPolyn0",cEqAppui_GL__PTInc_M2CPolyn0::Alloc);


cElCompiledFonc *  cEqAppui_GL__PTInc_M2CPolyn0::Alloc()
{  return new cEqAppui_GL__PTInc_M2CPolyn0();
}


