// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cEqAppui_TerFix_M2CCamBilin.h"


cEqAppui_TerFix_M2CCamBilin::cEqAppui_TerFix_M2CCamBilin():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Bil0_0",3,5));
   AddIntRef (cIncIntervale("Bil0_1",7,9));
   AddIntRef (cIncIntervale("Bil1_0",5,7));
   AddIntRef (cIncIntervale("Bil1_1",9,11));
   AddIntRef (cIncIntervale("Intr",0,3));
   AddIntRef (cIncIntervale("Orient",11,17));
   Close(false);
}



void cEqAppui_TerFix_M2CCamBilin::ComputeVal()
{
   double tmp0_ = mCompCoord[11];
   double tmp1_ = mCompCoord[12];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[13];
   double tmp7_ = mCompCoord[14];
   double tmp8_ = mLocXTer-tmp7_;
   double tmp9_ = sin(tmp6_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp5_);
   double tmp12_ = cos(tmp6_);
   double tmp13_ = mCompCoord[15];
   double tmp14_ = mLocYTer-tmp13_;
   double tmp15_ = mCompCoord[16];
   double tmp16_ = mLocZTer-tmp15_;
   double tmp17_ = -(tmp3_);
   double tmp18_ = tmp4_*tmp11_;
   double tmp19_ = tmp3_*tmp11_;
   double tmp20_ = mCompCoord[0];
   double tmp21_ = tmp17_*tmp10_;
   double tmp22_ = tmp18_*tmp12_;
   double tmp23_ = tmp21_+tmp22_;
   double tmp24_ = (tmp23_)*(tmp8_);
   double tmp25_ = tmp4_*tmp10_;
   double tmp26_ = tmp19_*tmp12_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = (tmp27_)*(tmp14_);
   double tmp29_ = tmp24_+tmp28_;
   double tmp30_ = tmp2_*tmp12_;
   double tmp31_ = tmp30_*(tmp16_);
   double tmp32_ = tmp29_+tmp31_;
   double tmp33_ = tmp20_/(tmp32_);
   double tmp34_ = tmp4_*tmp2_;
   double tmp35_ = tmp34_*(tmp8_);
   double tmp36_ = tmp3_*tmp2_;
   double tmp37_ = tmp36_*(tmp14_);
   double tmp38_ = tmp35_+tmp37_;
   double tmp39_ = tmp5_*(tmp16_);
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = (tmp40_)*(tmp33_);
   double tmp42_ = mCompCoord[1];
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = mLocPts1_x-(tmp43_);
   double tmp45_ = mLocPts1_x-mLocPts0_x;
   double tmp46_ = (tmp44_)/(tmp45_);
   double tmp47_ = tmp17_*tmp12_;
   double tmp48_ = tmp18_*tmp9_;
   double tmp49_ = tmp47_+tmp48_;
   double tmp50_ = (tmp49_)*(tmp8_);
   double tmp51_ = tmp4_*tmp12_;
   double tmp52_ = tmp19_*tmp9_;
   double tmp53_ = tmp51_+tmp52_;
   double tmp54_ = (tmp53_)*(tmp14_);
   double tmp55_ = tmp50_+tmp54_;
   double tmp56_ = tmp2_*tmp9_;
   double tmp57_ = tmp56_*(tmp16_);
   double tmp58_ = tmp55_+tmp57_;
   double tmp59_ = (tmp58_)*(tmp33_);
   double tmp60_ = mCompCoord[2];
   double tmp61_ = tmp59_+tmp60_;
   double tmp62_ = mLocPts2_y-(tmp61_);
   double tmp63_ = mLocPts2_y-mLocPts0_y;
   double tmp64_ = (tmp62_)/(tmp63_);
   double tmp65_ = 1-tmp46_;
   double tmp66_ = 1-tmp64_;
   double tmp67_ = (tmp46_)*(tmp64_);
   double tmp68_ = (tmp65_)*(tmp64_);
   double tmp69_ = (tmp46_)*(tmp66_);
   double tmp70_ = (tmp65_)*(tmp66_);

  mVal[0] = ((mCompCoord[3]*tmp67_+mCompCoord[5]*tmp68_+mCompCoord[7]*tmp69_+mCompCoord[9]*tmp70_)-mLocXIm)*mLocScNorm;

  mVal[1] = ((mCompCoord[4]*tmp67_+mCompCoord[6]*tmp68_+mCompCoord[8]*tmp69_+mCompCoord[10]*tmp70_)-mLocYIm)*mLocScNorm;

}


void cEqAppui_TerFix_M2CCamBilin::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[11];
   double tmp1_ = mCompCoord[12];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[13];
   double tmp7_ = mCompCoord[14];
   double tmp8_ = mLocXTer-tmp7_;
   double tmp9_ = sin(tmp6_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp5_);
   double tmp12_ = cos(tmp6_);
   double tmp13_ = mCompCoord[15];
   double tmp14_ = mLocYTer-tmp13_;
   double tmp15_ = mCompCoord[16];
   double tmp16_ = mLocZTer-tmp15_;
   double tmp17_ = -(tmp3_);
   double tmp18_ = tmp4_*tmp11_;
   double tmp19_ = tmp3_*tmp11_;
   double tmp20_ = mCompCoord[0];
   double tmp21_ = tmp17_*tmp10_;
   double tmp22_ = tmp18_*tmp12_;
   double tmp23_ = tmp21_+tmp22_;
   double tmp24_ = (tmp23_)*(tmp8_);
   double tmp25_ = tmp4_*tmp10_;
   double tmp26_ = tmp19_*tmp12_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = (tmp27_)*(tmp14_);
   double tmp29_ = tmp24_+tmp28_;
   double tmp30_ = tmp2_*tmp12_;
   double tmp31_ = tmp30_*(tmp16_);
   double tmp32_ = tmp29_+tmp31_;
   double tmp33_ = tmp20_/(tmp32_);
   double tmp34_ = tmp4_*tmp2_;
   double tmp35_ = tmp34_*(tmp8_);
   double tmp36_ = tmp3_*tmp2_;
   double tmp37_ = tmp36_*(tmp14_);
   double tmp38_ = tmp35_+tmp37_;
   double tmp39_ = tmp5_*(tmp16_);
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = (tmp40_)*(tmp33_);
   double tmp42_ = mCompCoord[1];
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = mLocPts1_x-(tmp43_);
   double tmp45_ = mLocPts1_x-mLocPts0_x;
   double tmp46_ = (tmp44_)/(tmp45_);
   double tmp47_ = tmp17_*tmp12_;
   double tmp48_ = tmp18_*tmp9_;
   double tmp49_ = tmp47_+tmp48_;
   double tmp50_ = (tmp49_)*(tmp8_);
   double tmp51_ = tmp4_*tmp12_;
   double tmp52_ = tmp19_*tmp9_;
   double tmp53_ = tmp51_+tmp52_;
   double tmp54_ = (tmp53_)*(tmp14_);
   double tmp55_ = tmp50_+tmp54_;
   double tmp56_ = tmp2_*tmp9_;
   double tmp57_ = tmp56_*(tmp16_);
   double tmp58_ = tmp55_+tmp57_;
   double tmp59_ = (tmp58_)*(tmp33_);
   double tmp60_ = mCompCoord[2];
   double tmp61_ = tmp59_+tmp60_;
   double tmp62_ = mLocPts2_y-(tmp61_);
   double tmp63_ = mLocPts2_y-mLocPts0_y;
   double tmp64_ = (tmp62_)/(tmp63_);
   double tmp65_ = 1-tmp46_;
   double tmp66_ = 1-tmp64_;
   double tmp67_ = ElSquare(tmp32_);
   double tmp68_ = (tmp32_)/tmp67_;
   double tmp69_ = mCompCoord[3];
   double tmp70_ = (tmp68_)*(tmp40_);
   double tmp71_ = -(tmp70_);
   double tmp72_ = tmp71_*(tmp45_);
   double tmp73_ = ElSquare(tmp45_);
   double tmp74_ = (tmp72_)/tmp73_;
   double tmp75_ = (tmp68_)*(tmp58_);
   double tmp76_ = -(tmp75_);
   double tmp77_ = tmp76_*(tmp63_);
   double tmp78_ = ElSquare(tmp63_);
   double tmp79_ = (tmp77_)/tmp78_;
   double tmp80_ = mCompCoord[5];
   double tmp81_ = mCompCoord[7];
   double tmp82_ = -(tmp74_);
   double tmp83_ = -(tmp79_);
   double tmp84_ = mCompCoord[9];
   double tmp85_ = -(1);
   double tmp86_ = tmp85_*(tmp45_);
   double tmp87_ = (tmp86_)/tmp73_;
   double tmp88_ = -(tmp87_);
   double tmp89_ = tmp85_*(tmp63_);
   double tmp90_ = (tmp89_)/tmp78_;
   double tmp91_ = -(tmp90_);
   double tmp92_ = (tmp46_)*(tmp64_);
   double tmp93_ = (tmp65_)*(tmp64_);
   double tmp94_ = (tmp46_)*(tmp66_);
   double tmp95_ = (tmp65_)*(tmp66_);
   double tmp96_ = tmp85_*tmp3_;
   double tmp97_ = -(tmp4_);
   double tmp98_ = tmp96_*tmp11_;
   double tmp99_ = tmp97_*tmp10_;
   double tmp100_ = tmp98_*tmp12_;
   double tmp101_ = tmp99_+tmp100_;
   double tmp102_ = (tmp101_)*(tmp8_);
   double tmp103_ = tmp96_*tmp10_;
   double tmp104_ = tmp103_+tmp22_;
   double tmp105_ = (tmp104_)*(tmp14_);
   double tmp106_ = tmp102_+tmp105_;
   double tmp107_ = tmp20_*(tmp106_);
   double tmp108_ = -(tmp107_);
   double tmp109_ = tmp108_/tmp67_;
   double tmp110_ = tmp96_*tmp2_;
   double tmp111_ = tmp110_*(tmp8_);
   double tmp112_ = tmp34_*(tmp14_);
   double tmp113_ = tmp111_+tmp112_;
   double tmp114_ = (tmp113_)*(tmp33_);
   double tmp115_ = (tmp109_)*(tmp40_);
   double tmp116_ = tmp114_+tmp115_;
   double tmp117_ = -(tmp116_);
   double tmp118_ = tmp117_*(tmp45_);
   double tmp119_ = (tmp118_)/tmp73_;
   double tmp120_ = tmp97_*tmp12_;
   double tmp121_ = tmp98_*tmp9_;
   double tmp122_ = tmp120_+tmp121_;
   double tmp123_ = (tmp122_)*(tmp8_);
   double tmp124_ = tmp96_*tmp12_;
   double tmp125_ = tmp124_+tmp48_;
   double tmp126_ = (tmp125_)*(tmp14_);
   double tmp127_ = tmp123_+tmp126_;
   double tmp128_ = (tmp127_)*(tmp33_);
   double tmp129_ = (tmp109_)*(tmp58_);
   double tmp130_ = tmp128_+tmp129_;
   double tmp131_ = -(tmp130_);
   double tmp132_ = tmp131_*(tmp63_);
   double tmp133_ = (tmp132_)/tmp78_;
   double tmp134_ = -(tmp119_);
   double tmp135_ = -(tmp133_);
   double tmp136_ = tmp85_*tmp5_;
   double tmp137_ = -(tmp2_);
   double tmp138_ = tmp137_*tmp4_;
   double tmp139_ = tmp137_*tmp3_;
   double tmp140_ = tmp138_*tmp12_;
   double tmp141_ = tmp140_*(tmp8_);
   double tmp142_ = tmp139_*tmp12_;
   double tmp143_ = tmp142_*(tmp14_);
   double tmp144_ = tmp141_+tmp143_;
   double tmp145_ = tmp136_*tmp12_;
   double tmp146_ = tmp145_*(tmp16_);
   double tmp147_ = tmp144_+tmp146_;
   double tmp148_ = tmp20_*(tmp147_);
   double tmp149_ = -(tmp148_);
   double tmp150_ = tmp149_/tmp67_;
   double tmp151_ = tmp136_*tmp4_;
   double tmp152_ = tmp151_*(tmp8_);
   double tmp153_ = tmp136_*tmp3_;
   double tmp154_ = tmp153_*(tmp14_);
   double tmp155_ = tmp152_+tmp154_;
   double tmp156_ = tmp2_*(tmp16_);
   double tmp157_ = tmp155_+tmp156_;
   double tmp158_ = (tmp157_)*(tmp33_);
   double tmp159_ = (tmp150_)*(tmp40_);
   double tmp160_ = tmp158_+tmp159_;
   double tmp161_ = -(tmp160_);
   double tmp162_ = tmp161_*(tmp45_);
   double tmp163_ = (tmp162_)/tmp73_;
   double tmp164_ = tmp138_*tmp9_;
   double tmp165_ = tmp164_*(tmp8_);
   double tmp166_ = tmp139_*tmp9_;
   double tmp167_ = tmp166_*(tmp14_);
   double tmp168_ = tmp165_+tmp167_;
   double tmp169_ = tmp136_*tmp9_;
   double tmp170_ = tmp169_*(tmp16_);
   double tmp171_ = tmp168_+tmp170_;
   double tmp172_ = (tmp171_)*(tmp33_);
   double tmp173_ = (tmp150_)*(tmp58_);
   double tmp174_ = tmp172_+tmp173_;
   double tmp175_ = -(tmp174_);
   double tmp176_ = tmp175_*(tmp63_);
   double tmp177_ = (tmp176_)/tmp78_;
   double tmp178_ = -(tmp163_);
   double tmp179_ = -(tmp177_);
   double tmp180_ = -(tmp12_);
   double tmp181_ = tmp85_*tmp9_;
   double tmp182_ = tmp180_*tmp17_;
   double tmp183_ = tmp181_*tmp18_;
   double tmp184_ = tmp182_+tmp183_;
   double tmp185_ = (tmp184_)*(tmp8_);
   double tmp186_ = tmp180_*tmp4_;
   double tmp187_ = tmp181_*tmp19_;
   double tmp188_ = tmp186_+tmp187_;
   double tmp189_ = (tmp188_)*(tmp14_);
   double tmp190_ = tmp185_+tmp189_;
   double tmp191_ = tmp181_*tmp2_;
   double tmp192_ = tmp191_*(tmp16_);
   double tmp193_ = tmp190_+tmp192_;
   double tmp194_ = tmp20_*(tmp193_);
   double tmp195_ = -(tmp194_);
   double tmp196_ = tmp195_/tmp67_;
   double tmp197_ = (tmp196_)*(tmp40_);
   double tmp198_ = -(tmp197_);
   double tmp199_ = tmp198_*(tmp45_);
   double tmp200_ = (tmp199_)/tmp73_;
   double tmp201_ = tmp181_*tmp17_;
   double tmp202_ = tmp12_*tmp18_;
   double tmp203_ = tmp201_+tmp202_;
   double tmp204_ = (tmp203_)*(tmp8_);
   double tmp205_ = tmp181_*tmp4_;
   double tmp206_ = tmp12_*tmp19_;
   double tmp207_ = tmp205_+tmp206_;
   double tmp208_ = (tmp207_)*(tmp14_);
   double tmp209_ = tmp204_+tmp208_;
   double tmp210_ = tmp12_*tmp2_;
   double tmp211_ = tmp210_*(tmp16_);
   double tmp212_ = tmp209_+tmp211_;
   double tmp213_ = (tmp212_)*(tmp33_);
   double tmp214_ = (tmp196_)*(tmp58_);
   double tmp215_ = tmp213_+tmp214_;
   double tmp216_ = -(tmp215_);
   double tmp217_ = tmp216_*(tmp63_);
   double tmp218_ = (tmp217_)/tmp78_;
   double tmp219_ = -(tmp200_);
   double tmp220_ = -(tmp218_);
   double tmp221_ = tmp85_*(tmp23_);
   double tmp222_ = tmp20_*tmp221_;
   double tmp223_ = -(tmp222_);
   double tmp224_ = tmp223_/tmp67_;
   double tmp225_ = tmp85_*tmp34_;
   double tmp226_ = tmp225_*(tmp33_);
   double tmp227_ = (tmp224_)*(tmp40_);
   double tmp228_ = tmp226_+tmp227_;
   double tmp229_ = -(tmp228_);
   double tmp230_ = tmp229_*(tmp45_);
   double tmp231_ = (tmp230_)/tmp73_;
   double tmp232_ = tmp85_*(tmp49_);
   double tmp233_ = tmp232_*(tmp33_);
   double tmp234_ = (tmp224_)*(tmp58_);
   double tmp235_ = tmp233_+tmp234_;
   double tmp236_ = -(tmp235_);
   double tmp237_ = tmp236_*(tmp63_);
   double tmp238_ = (tmp237_)/tmp78_;
   double tmp239_ = -(tmp231_);
   double tmp240_ = -(tmp238_);
   double tmp241_ = tmp85_*(tmp27_);
   double tmp242_ = tmp20_*tmp241_;
   double tmp243_ = -(tmp242_);
   double tmp244_ = tmp243_/tmp67_;
   double tmp245_ = tmp85_*tmp36_;
   double tmp246_ = tmp245_*(tmp33_);
   double tmp247_ = (tmp244_)*(tmp40_);
   double tmp248_ = tmp246_+tmp247_;
   double tmp249_ = -(tmp248_);
   double tmp250_ = tmp249_*(tmp45_);
   double tmp251_ = (tmp250_)/tmp73_;
   double tmp252_ = tmp85_*(tmp53_);
   double tmp253_ = tmp252_*(tmp33_);
   double tmp254_ = (tmp244_)*(tmp58_);
   double tmp255_ = tmp253_+tmp254_;
   double tmp256_ = -(tmp255_);
   double tmp257_ = tmp256_*(tmp63_);
   double tmp258_ = (tmp257_)/tmp78_;
   double tmp259_ = -(tmp251_);
   double tmp260_ = -(tmp258_);
   double tmp261_ = tmp85_*tmp30_;
   double tmp262_ = tmp20_*tmp261_;
   double tmp263_ = -(tmp262_);
   double tmp264_ = tmp263_/tmp67_;
   double tmp265_ = tmp136_*(tmp33_);
   double tmp266_ = (tmp264_)*(tmp40_);
   double tmp267_ = tmp265_+tmp266_;
   double tmp268_ = -(tmp267_);
   double tmp269_ = tmp268_*(tmp45_);
   double tmp270_ = (tmp269_)/tmp73_;
   double tmp271_ = tmp85_*tmp56_;
   double tmp272_ = tmp271_*(tmp33_);
   double tmp273_ = (tmp264_)*(tmp58_);
   double tmp274_ = tmp272_+tmp273_;
   double tmp275_ = -(tmp274_);
   double tmp276_ = tmp275_*(tmp63_);
   double tmp277_ = (tmp276_)/tmp78_;
   double tmp278_ = -(tmp270_);
   double tmp279_ = -(tmp277_);
   double tmp280_ = (tmp74_)*(tmp64_);
   double tmp281_ = (tmp79_)*(tmp46_);
   double tmp282_ = tmp280_+tmp281_;
   double tmp283_ = mCompCoord[4];
   double tmp284_ = tmp82_*(tmp64_);
   double tmp285_ = (tmp79_)*(tmp65_);
   double tmp286_ = tmp284_+tmp285_;
   double tmp287_ = mCompCoord[6];
   double tmp288_ = (tmp74_)*(tmp66_);
   double tmp289_ = tmp83_*(tmp46_);
   double tmp290_ = tmp288_+tmp289_;
   double tmp291_ = mCompCoord[8];
   double tmp292_ = tmp82_*(tmp66_);
   double tmp293_ = tmp83_*(tmp65_);
   double tmp294_ = tmp292_+tmp293_;
   double tmp295_ = mCompCoord[10];
   double tmp296_ = (tmp87_)*(tmp64_);
   double tmp297_ = tmp88_*(tmp64_);
   double tmp298_ = (tmp87_)*(tmp66_);
   double tmp299_ = tmp88_*(tmp66_);
   double tmp300_ = (tmp90_)*(tmp46_);
   double tmp301_ = (tmp90_)*(tmp65_);
   double tmp302_ = tmp91_*(tmp46_);
   double tmp303_ = tmp91_*(tmp65_);
   double tmp304_ = tmp92_*mLocScNorm;
   double tmp305_ = tmp93_*mLocScNorm;
   double tmp306_ = tmp94_*mLocScNorm;
   double tmp307_ = tmp95_*mLocScNorm;
   double tmp308_ = (tmp119_)*(tmp64_);
   double tmp309_ = (tmp133_)*(tmp46_);
   double tmp310_ = tmp308_+tmp309_;
   double tmp311_ = tmp134_*(tmp64_);
   double tmp312_ = (tmp133_)*(tmp65_);
   double tmp313_ = tmp311_+tmp312_;
   double tmp314_ = (tmp119_)*(tmp66_);
   double tmp315_ = tmp135_*(tmp46_);
   double tmp316_ = tmp314_+tmp315_;
   double tmp317_ = tmp134_*(tmp66_);
   double tmp318_ = tmp135_*(tmp65_);
   double tmp319_ = tmp317_+tmp318_;
   double tmp320_ = (tmp163_)*(tmp64_);
   double tmp321_ = (tmp177_)*(tmp46_);
   double tmp322_ = tmp320_+tmp321_;
   double tmp323_ = tmp178_*(tmp64_);
   double tmp324_ = (tmp177_)*(tmp65_);
   double tmp325_ = tmp323_+tmp324_;
   double tmp326_ = (tmp163_)*(tmp66_);
   double tmp327_ = tmp179_*(tmp46_);
   double tmp328_ = tmp326_+tmp327_;
   double tmp329_ = tmp178_*(tmp66_);
   double tmp330_ = tmp179_*(tmp65_);
   double tmp331_ = tmp329_+tmp330_;
   double tmp332_ = (tmp200_)*(tmp64_);
   double tmp333_ = (tmp218_)*(tmp46_);
   double tmp334_ = tmp332_+tmp333_;
   double tmp335_ = tmp219_*(tmp64_);
   double tmp336_ = (tmp218_)*(tmp65_);
   double tmp337_ = tmp335_+tmp336_;
   double tmp338_ = (tmp200_)*(tmp66_);
   double tmp339_ = tmp220_*(tmp46_);
   double tmp340_ = tmp338_+tmp339_;
   double tmp341_ = tmp219_*(tmp66_);
   double tmp342_ = tmp220_*(tmp65_);
   double tmp343_ = tmp341_+tmp342_;
   double tmp344_ = (tmp231_)*(tmp64_);
   double tmp345_ = (tmp238_)*(tmp46_);
   double tmp346_ = tmp344_+tmp345_;
   double tmp347_ = tmp239_*(tmp64_);
   double tmp348_ = (tmp238_)*(tmp65_);
   double tmp349_ = tmp347_+tmp348_;
   double tmp350_ = (tmp231_)*(tmp66_);
   double tmp351_ = tmp240_*(tmp46_);
   double tmp352_ = tmp350_+tmp351_;
   double tmp353_ = tmp239_*(tmp66_);
   double tmp354_ = tmp240_*(tmp65_);
   double tmp355_ = tmp353_+tmp354_;
   double tmp356_ = (tmp251_)*(tmp64_);
   double tmp357_ = (tmp258_)*(tmp46_);
   double tmp358_ = tmp356_+tmp357_;
   double tmp359_ = tmp259_*(tmp64_);
   double tmp360_ = (tmp258_)*(tmp65_);
   double tmp361_ = tmp359_+tmp360_;
   double tmp362_ = (tmp251_)*(tmp66_);
   double tmp363_ = tmp260_*(tmp46_);
   double tmp364_ = tmp362_+tmp363_;
   double tmp365_ = tmp259_*(tmp66_);
   double tmp366_ = tmp260_*(tmp65_);
   double tmp367_ = tmp365_+tmp366_;
   double tmp368_ = (tmp270_)*(tmp64_);
   double tmp369_ = (tmp277_)*(tmp46_);
   double tmp370_ = tmp368_+tmp369_;
   double tmp371_ = tmp278_*(tmp64_);
   double tmp372_ = (tmp277_)*(tmp65_);
   double tmp373_ = tmp371_+tmp372_;
   double tmp374_ = (tmp270_)*(tmp66_);
   double tmp375_ = tmp279_*(tmp46_);
   double tmp376_ = tmp374_+tmp375_;
   double tmp377_ = tmp278_*(tmp66_);
   double tmp378_ = tmp279_*(tmp65_);
   double tmp379_ = tmp377_+tmp378_;

  mVal[0] = ((tmp69_*tmp92_+tmp80_*tmp93_+tmp81_*tmp94_+tmp84_*tmp95_)-mLocXIm)*mLocScNorm;

  mCompDer[0][0] = ((tmp282_)*tmp69_+(tmp286_)*tmp80_+(tmp290_)*tmp81_+(tmp294_)*tmp84_)*mLocScNorm;
  mCompDer[0][1] = (tmp296_*tmp69_+tmp297_*tmp80_+tmp298_*tmp81_+tmp299_*tmp84_)*mLocScNorm;
  mCompDer[0][2] = (tmp300_*tmp69_+tmp301_*tmp80_+tmp302_*tmp81_+tmp303_*tmp84_)*mLocScNorm;
  mCompDer[0][3] = tmp304_;
  mCompDer[0][4] = 0;
  mCompDer[0][5] = tmp305_;
  mCompDer[0][6] = 0;
  mCompDer[0][7] = tmp306_;
  mCompDer[0][8] = 0;
  mCompDer[0][9] = tmp307_;
  mCompDer[0][10] = 0;
  mCompDer[0][11] = ((tmp310_)*tmp69_+(tmp313_)*tmp80_+(tmp316_)*tmp81_+(tmp319_)*tmp84_)*mLocScNorm;
  mCompDer[0][12] = ((tmp322_)*tmp69_+(tmp325_)*tmp80_+(tmp328_)*tmp81_+(tmp331_)*tmp84_)*mLocScNorm;
  mCompDer[0][13] = ((tmp334_)*tmp69_+(tmp337_)*tmp80_+(tmp340_)*tmp81_+(tmp343_)*tmp84_)*mLocScNorm;
  mCompDer[0][14] = ((tmp346_)*tmp69_+(tmp349_)*tmp80_+(tmp352_)*tmp81_+(tmp355_)*tmp84_)*mLocScNorm;
  mCompDer[0][15] = ((tmp358_)*tmp69_+(tmp361_)*tmp80_+(tmp364_)*tmp81_+(tmp367_)*tmp84_)*mLocScNorm;
  mCompDer[0][16] = ((tmp370_)*tmp69_+(tmp373_)*tmp80_+(tmp376_)*tmp81_+(tmp379_)*tmp84_)*mLocScNorm;
  mVal[1] = ((tmp283_*tmp92_+tmp287_*tmp93_+tmp291_*tmp94_+tmp295_*tmp95_)-mLocYIm)*mLocScNorm;

  mCompDer[1][0] = ((tmp282_)*tmp283_+(tmp286_)*tmp287_+(tmp290_)*tmp291_+(tmp294_)*tmp295_)*mLocScNorm;
  mCompDer[1][1] = (tmp296_*tmp283_+tmp297_*tmp287_+tmp298_*tmp291_+tmp299_*tmp295_)*mLocScNorm;
  mCompDer[1][2] = (tmp300_*tmp283_+tmp301_*tmp287_+tmp302_*tmp291_+tmp303_*tmp295_)*mLocScNorm;
  mCompDer[1][3] = 0;
  mCompDer[1][4] = tmp304_;
  mCompDer[1][5] = 0;
  mCompDer[1][6] = tmp305_;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = tmp306_;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = tmp307_;
  mCompDer[1][11] = ((tmp310_)*tmp283_+(tmp313_)*tmp287_+(tmp316_)*tmp291_+(tmp319_)*tmp295_)*mLocScNorm;
  mCompDer[1][12] = ((tmp322_)*tmp283_+(tmp325_)*tmp287_+(tmp328_)*tmp291_+(tmp331_)*tmp295_)*mLocScNorm;
  mCompDer[1][13] = ((tmp334_)*tmp283_+(tmp337_)*tmp287_+(tmp340_)*tmp291_+(tmp343_)*tmp295_)*mLocScNorm;
  mCompDer[1][14] = ((tmp346_)*tmp283_+(tmp349_)*tmp287_+(tmp352_)*tmp291_+(tmp355_)*tmp295_)*mLocScNorm;
  mCompDer[1][15] = ((tmp358_)*tmp283_+(tmp361_)*tmp287_+(tmp364_)*tmp291_+(tmp367_)*tmp295_)*mLocScNorm;
  mCompDer[1][16] = ((tmp370_)*tmp283_+(tmp373_)*tmp287_+(tmp376_)*tmp291_+(tmp379_)*tmp295_)*mLocScNorm;
}


void cEqAppui_TerFix_M2CCamBilin::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_TerFix_M2CCamBilin Has no Der Sec");
}

void cEqAppui_TerFix_M2CCamBilin::SetPts0_x(double aVal){ mLocPts0_x = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetPts0_y(double aVal){ mLocPts0_y = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetPts1_x(double aVal){ mLocPts1_x = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetPts2_y(double aVal){ mLocPts2_y = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetScNorm(double aVal){ mLocScNorm = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetXTer(double aVal){ mLocXTer = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetYIm(double aVal){ mLocYIm = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetYTer(double aVal){ mLocYTer = aVal;}
void cEqAppui_TerFix_M2CCamBilin::SetZTer(double aVal){ mLocZTer = aVal;}



double * cEqAppui_TerFix_M2CCamBilin::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Pts0_x") return & mLocPts0_x;
   if (aName == "Pts0_y") return & mLocPts0_y;
   if (aName == "Pts1_x") return & mLocPts1_x;
   if (aName == "Pts2_y") return & mLocPts2_y;
   if (aName == "ScNorm") return & mLocScNorm;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "XTer") return & mLocXTer;
   if (aName == "YIm") return & mLocYIm;
   if (aName == "YTer") return & mLocYTer;
   if (aName == "ZTer") return & mLocZTer;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_TerFix_M2CCamBilin::mTheAuto("cEqAppui_TerFix_M2CCamBilin",cEqAppui_TerFix_M2CCamBilin::Alloc);


cElCompiledFonc *  cEqAppui_TerFix_M2CCamBilin::Alloc()
{  return new cEqAppui_TerFix_M2CCamBilin();
}


