// File Automatically generated by eLiSe
#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_TerFix_M2CDCBrown.h"


cEqAppui_TerFix_M2CDCBrown::cEqAppui_TerFix_M2CDCBrown():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,17));
   AddIntRef (cIncIntervale("Orient",17,23));
   Close(false);
}



void cEqAppui_TerFix_M2CDCBrown::ComputeVal()
{
   double tmp0_ = mCompCoord[17];
   double tmp1_ = mCompCoord[18];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[19];
   double tmp7_ = mCompCoord[20];
   double tmp8_ = mLocXTer-tmp7_;
   double tmp9_ = sin(tmp6_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp5_);
   double tmp12_ = cos(tmp6_);
   double tmp13_ = mCompCoord[21];
   double tmp14_ = mLocYTer-tmp13_;
   double tmp15_ = mCompCoord[22];
   double tmp16_ = mLocZTer-tmp15_;
   double tmp17_ = -(tmp3_);
   double tmp18_ = tmp4_*tmp11_;
   double tmp19_ = tmp3_*tmp11_;
   double tmp20_ = mCompCoord[0];
   double tmp21_ = tmp17_*tmp10_;
   double tmp22_ = tmp18_*tmp12_;
   double tmp23_ = tmp21_+tmp22_;
   double tmp24_ = (tmp23_)*(tmp8_);
   double tmp25_ = tmp4_*tmp10_;
   double tmp26_ = tmp19_*tmp12_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = (tmp27_)*(tmp14_);
   double tmp29_ = tmp24_+tmp28_;
   double tmp30_ = tmp2_*tmp12_;
   double tmp31_ = tmp30_*(tmp16_);
   double tmp32_ = tmp29_+tmp31_;
   double tmp33_ = tmp20_/(tmp32_);
   double tmp34_ = tmp4_*tmp2_;
   double tmp35_ = tmp34_*(tmp8_);
   double tmp36_ = tmp3_*tmp2_;
   double tmp37_ = tmp36_*(tmp14_);
   double tmp38_ = tmp35_+tmp37_;
   double tmp39_ = tmp5_*(tmp16_);
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = (tmp40_)*(tmp33_);
   double tmp42_ = mCompCoord[1];
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = tmp17_*tmp12_;
   double tmp45_ = tmp18_*tmp9_;
   double tmp46_ = tmp44_+tmp45_;
   double tmp47_ = (tmp46_)*(tmp8_);
   double tmp48_ = tmp4_*tmp12_;
   double tmp49_ = tmp19_*tmp9_;
   double tmp50_ = tmp48_+tmp49_;
   double tmp51_ = (tmp50_)*(tmp14_);
   double tmp52_ = tmp47_+tmp51_;
   double tmp53_ = tmp2_*tmp9_;
   double tmp54_ = tmp53_*(tmp16_);
   double tmp55_ = tmp52_+tmp54_;
   double tmp56_ = (tmp55_)*(tmp33_);
   double tmp57_ = mCompCoord[2];
   double tmp58_ = tmp56_+tmp57_;
   double tmp59_ = (tmp58_)*(tmp58_);
   double tmp60_ = (tmp43_)*(tmp43_);
   double tmp61_ = tmp60_*tmp59_;
   double tmp62_ = (tmp43_)*(tmp58_);
   double tmp63_ = tmp60_*(tmp58_);
   double tmp64_ = (tmp43_)*tmp59_;
   double tmp65_ = mCompCoord[15];
   double tmp66_ = mCompCoord[16];
   double tmp67_ = tmp60_+tmp59_;

  mVal[0] = (((1+mCompCoord[3])*(tmp43_)+mCompCoord[4]*(tmp58_)+mCompCoord[5]*tmp62_+mCompCoord[6]*tmp59_+mCompCoord[7]*tmp63_+mCompCoord[8]*tmp64_+mCompCoord[9]*tmp61_+tmp65_*((tmp43_)/mLocDCBrown_State_0_0)*tmp61_+tmp66_*(tmp43_)*(tmp67_))-mLocXIm)*mLocScNorm;

  mVal[1] = ((tmp58_+mCompCoord[10]*tmp62_+mCompCoord[11]*tmp60_+mCompCoord[12]*tmp63_+mCompCoord[13]*tmp64_+mCompCoord[14]*tmp61_+tmp65_*((tmp58_)/mLocDCBrown_State_0_0)*tmp61_+tmp66_*(tmp58_)*(tmp67_))-mLocYIm)*mLocScNorm;

}


void cEqAppui_TerFix_M2CDCBrown::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[17];
   double tmp1_ = mCompCoord[18];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[19];
   double tmp7_ = mCompCoord[20];
   double tmp8_ = mLocXTer-tmp7_;
   double tmp9_ = sin(tmp6_);
   double tmp10_ = -(tmp9_);
   double tmp11_ = -(tmp5_);
   double tmp12_ = cos(tmp6_);
   double tmp13_ = mCompCoord[21];
   double tmp14_ = mLocYTer-tmp13_;
   double tmp15_ = mCompCoord[22];
   double tmp16_ = mLocZTer-tmp15_;
   double tmp17_ = -(tmp3_);
   double tmp18_ = tmp4_*tmp11_;
   double tmp19_ = tmp3_*tmp11_;
   double tmp20_ = mCompCoord[0];
   double tmp21_ = tmp17_*tmp10_;
   double tmp22_ = tmp18_*tmp12_;
   double tmp23_ = tmp21_+tmp22_;
   double tmp24_ = (tmp23_)*(tmp8_);
   double tmp25_ = tmp4_*tmp10_;
   double tmp26_ = tmp19_*tmp12_;
   double tmp27_ = tmp25_+tmp26_;
   double tmp28_ = (tmp27_)*(tmp14_);
   double tmp29_ = tmp24_+tmp28_;
   double tmp30_ = tmp2_*tmp12_;
   double tmp31_ = tmp30_*(tmp16_);
   double tmp32_ = tmp29_+tmp31_;
   double tmp33_ = tmp20_/(tmp32_);
   double tmp34_ = tmp4_*tmp2_;
   double tmp35_ = tmp34_*(tmp8_);
   double tmp36_ = tmp3_*tmp2_;
   double tmp37_ = tmp36_*(tmp14_);
   double tmp38_ = tmp35_+tmp37_;
   double tmp39_ = tmp5_*(tmp16_);
   double tmp40_ = tmp38_+tmp39_;
   double tmp41_ = (tmp40_)*(tmp33_);
   double tmp42_ = mCompCoord[1];
   double tmp43_ = tmp41_+tmp42_;
   double tmp44_ = tmp17_*tmp12_;
   double tmp45_ = tmp18_*tmp9_;
   double tmp46_ = tmp44_+tmp45_;
   double tmp47_ = (tmp46_)*(tmp8_);
   double tmp48_ = tmp4_*tmp12_;
   double tmp49_ = tmp19_*tmp9_;
   double tmp50_ = tmp48_+tmp49_;
   double tmp51_ = (tmp50_)*(tmp14_);
   double tmp52_ = tmp47_+tmp51_;
   double tmp53_ = tmp2_*tmp9_;
   double tmp54_ = tmp53_*(tmp16_);
   double tmp55_ = tmp52_+tmp54_;
   double tmp56_ = (tmp55_)*(tmp33_);
   double tmp57_ = mCompCoord[2];
   double tmp58_ = tmp56_+tmp57_;
   double tmp59_ = (tmp58_)*(tmp58_);
   double tmp60_ = (tmp43_)*(tmp43_);
   double tmp61_ = tmp60_*tmp59_;
   double tmp62_ = mCompCoord[3];
   double tmp63_ = 1+tmp62_;
   double tmp64_ = ElSquare(tmp32_);
   double tmp65_ = (tmp32_)/tmp64_;
   double tmp66_ = mCompCoord[4];
   double tmp67_ = (tmp65_)*(tmp40_);
   double tmp68_ = (tmp65_)*(tmp55_);
   double tmp69_ = mCompCoord[5];
   double tmp70_ = tmp68_*(tmp58_);
   double tmp71_ = mCompCoord[6];
   double tmp72_ = tmp67_*(tmp43_);
   double tmp73_ = mCompCoord[7];
   double tmp74_ = tmp70_+tmp70_;
   double tmp75_ = mCompCoord[8];
   double tmp76_ = tmp72_+tmp72_;
   double tmp77_ = mCompCoord[9];
   double tmp78_ = mCompCoord[15];
   double tmp79_ = (tmp76_)*tmp59_;
   double tmp80_ = (tmp74_)*tmp60_;
   double tmp81_ = tmp79_+tmp80_;
   double tmp82_ = (tmp43_)/mLocDCBrown_State_0_0;
   double tmp83_ = tmp78_*(tmp82_);
   double tmp84_ = mCompCoord[16];
   double tmp85_ = tmp60_+tmp59_;
   double tmp86_ = tmp84_*(tmp43_);
   double tmp87_ = tmp43_+tmp43_;
   double tmp88_ = ElSquare(mLocDCBrown_State_0_0);
   double tmp89_ = (tmp87_)*tmp59_;
   double tmp90_ = tmp58_+tmp58_;
   double tmp91_ = (tmp90_)*tmp60_;
   double tmp92_ = (tmp43_)*(tmp58_);
   double tmp93_ = tmp60_*(tmp58_);
   double tmp94_ = (tmp43_)*tmp59_;
   double tmp95_ = -(1);
   double tmp96_ = tmp95_*tmp3_;
   double tmp97_ = -(tmp4_);
   double tmp98_ = tmp96_*tmp11_;
   double tmp99_ = tmp97_*tmp10_;
   double tmp100_ = tmp98_*tmp12_;
   double tmp101_ = tmp99_+tmp100_;
   double tmp102_ = (tmp101_)*(tmp8_);
   double tmp103_ = tmp96_*tmp10_;
   double tmp104_ = tmp103_+tmp22_;
   double tmp105_ = (tmp104_)*(tmp14_);
   double tmp106_ = tmp102_+tmp105_;
   double tmp107_ = tmp20_*(tmp106_);
   double tmp108_ = -(tmp107_);
   double tmp109_ = tmp108_/tmp64_;
   double tmp110_ = tmp96_*tmp2_;
   double tmp111_ = tmp110_*(tmp8_);
   double tmp112_ = tmp34_*(tmp14_);
   double tmp113_ = tmp111_+tmp112_;
   double tmp114_ = (tmp113_)*(tmp33_);
   double tmp115_ = (tmp109_)*(tmp40_);
   double tmp116_ = tmp114_+tmp115_;
   double tmp117_ = tmp97_*tmp12_;
   double tmp118_ = tmp98_*tmp9_;
   double tmp119_ = tmp117_+tmp118_;
   double tmp120_ = (tmp119_)*(tmp8_);
   double tmp121_ = tmp96_*tmp12_;
   double tmp122_ = tmp121_+tmp45_;
   double tmp123_ = (tmp122_)*(tmp14_);
   double tmp124_ = tmp120_+tmp123_;
   double tmp125_ = (tmp124_)*(tmp33_);
   double tmp126_ = (tmp109_)*(tmp55_);
   double tmp127_ = tmp125_+tmp126_;
   double tmp128_ = (tmp127_)*(tmp58_);
   double tmp129_ = (tmp116_)*(tmp43_);
   double tmp130_ = tmp128_+tmp128_;
   double tmp131_ = tmp129_+tmp129_;
   double tmp132_ = (tmp131_)*tmp59_;
   double tmp133_ = (tmp130_)*tmp60_;
   double tmp134_ = tmp132_+tmp133_;
   double tmp135_ = tmp95_*tmp5_;
   double tmp136_ = -(tmp2_);
   double tmp137_ = tmp136_*tmp4_;
   double tmp138_ = tmp136_*tmp3_;
   double tmp139_ = tmp137_*tmp12_;
   double tmp140_ = tmp139_*(tmp8_);
   double tmp141_ = tmp138_*tmp12_;
   double tmp142_ = tmp141_*(tmp14_);
   double tmp143_ = tmp140_+tmp142_;
   double tmp144_ = tmp135_*tmp12_;
   double tmp145_ = tmp144_*(tmp16_);
   double tmp146_ = tmp143_+tmp145_;
   double tmp147_ = tmp20_*(tmp146_);
   double tmp148_ = -(tmp147_);
   double tmp149_ = tmp148_/tmp64_;
   double tmp150_ = tmp135_*tmp4_;
   double tmp151_ = tmp150_*(tmp8_);
   double tmp152_ = tmp135_*tmp3_;
   double tmp153_ = tmp152_*(tmp14_);
   double tmp154_ = tmp151_+tmp153_;
   double tmp155_ = tmp2_*(tmp16_);
   double tmp156_ = tmp154_+tmp155_;
   double tmp157_ = (tmp156_)*(tmp33_);
   double tmp158_ = (tmp149_)*(tmp40_);
   double tmp159_ = tmp157_+tmp158_;
   double tmp160_ = tmp137_*tmp9_;
   double tmp161_ = tmp160_*(tmp8_);
   double tmp162_ = tmp138_*tmp9_;
   double tmp163_ = tmp162_*(tmp14_);
   double tmp164_ = tmp161_+tmp163_;
   double tmp165_ = tmp135_*tmp9_;
   double tmp166_ = tmp165_*(tmp16_);
   double tmp167_ = tmp164_+tmp166_;
   double tmp168_ = (tmp167_)*(tmp33_);
   double tmp169_ = (tmp149_)*(tmp55_);
   double tmp170_ = tmp168_+tmp169_;
   double tmp171_ = (tmp170_)*(tmp58_);
   double tmp172_ = (tmp159_)*(tmp43_);
   double tmp173_ = tmp171_+tmp171_;
   double tmp174_ = tmp172_+tmp172_;
   double tmp175_ = (tmp174_)*tmp59_;
   double tmp176_ = (tmp173_)*tmp60_;
   double tmp177_ = tmp175_+tmp176_;
   double tmp178_ = -(tmp12_);
   double tmp179_ = tmp95_*tmp9_;
   double tmp180_ = tmp178_*tmp17_;
   double tmp181_ = tmp179_*tmp18_;
   double tmp182_ = tmp180_+tmp181_;
   double tmp183_ = (tmp182_)*(tmp8_);
   double tmp184_ = tmp178_*tmp4_;
   double tmp185_ = tmp179_*tmp19_;
   double tmp186_ = tmp184_+tmp185_;
   double tmp187_ = (tmp186_)*(tmp14_);
   double tmp188_ = tmp183_+tmp187_;
   double tmp189_ = tmp179_*tmp2_;
   double tmp190_ = tmp189_*(tmp16_);
   double tmp191_ = tmp188_+tmp190_;
   double tmp192_ = tmp20_*(tmp191_);
   double tmp193_ = -(tmp192_);
   double tmp194_ = tmp193_/tmp64_;
   double tmp195_ = (tmp194_)*(tmp40_);
   double tmp196_ = tmp179_*tmp17_;
   double tmp197_ = tmp12_*tmp18_;
   double tmp198_ = tmp196_+tmp197_;
   double tmp199_ = (tmp198_)*(tmp8_);
   double tmp200_ = tmp179_*tmp4_;
   double tmp201_ = tmp12_*tmp19_;
   double tmp202_ = tmp200_+tmp201_;
   double tmp203_ = (tmp202_)*(tmp14_);
   double tmp204_ = tmp199_+tmp203_;
   double tmp205_ = tmp12_*tmp2_;
   double tmp206_ = tmp205_*(tmp16_);
   double tmp207_ = tmp204_+tmp206_;
   double tmp208_ = (tmp207_)*(tmp33_);
   double tmp209_ = (tmp194_)*(tmp55_);
   double tmp210_ = tmp208_+tmp209_;
   double tmp211_ = (tmp210_)*(tmp58_);
   double tmp212_ = tmp195_*(tmp43_);
   double tmp213_ = tmp211_+tmp211_;
   double tmp214_ = tmp212_+tmp212_;
   double tmp215_ = (tmp214_)*tmp59_;
   double tmp216_ = (tmp213_)*tmp60_;
   double tmp217_ = tmp215_+tmp216_;
   double tmp218_ = tmp95_*(tmp23_);
   double tmp219_ = tmp20_*tmp218_;
   double tmp220_ = -(tmp219_);
   double tmp221_ = tmp220_/tmp64_;
   double tmp222_ = tmp95_*tmp34_;
   double tmp223_ = tmp222_*(tmp33_);
   double tmp224_ = (tmp221_)*(tmp40_);
   double tmp225_ = tmp223_+tmp224_;
   double tmp226_ = tmp95_*(tmp46_);
   double tmp227_ = tmp226_*(tmp33_);
   double tmp228_ = (tmp221_)*(tmp55_);
   double tmp229_ = tmp227_+tmp228_;
   double tmp230_ = (tmp229_)*(tmp58_);
   double tmp231_ = (tmp225_)*(tmp43_);
   double tmp232_ = tmp230_+tmp230_;
   double tmp233_ = tmp231_+tmp231_;
   double tmp234_ = (tmp233_)*tmp59_;
   double tmp235_ = (tmp232_)*tmp60_;
   double tmp236_ = tmp234_+tmp235_;
   double tmp237_ = tmp95_*(tmp27_);
   double tmp238_ = tmp20_*tmp237_;
   double tmp239_ = -(tmp238_);
   double tmp240_ = tmp239_/tmp64_;
   double tmp241_ = tmp95_*tmp36_;
   double tmp242_ = tmp241_*(tmp33_);
   double tmp243_ = (tmp240_)*(tmp40_);
   double tmp244_ = tmp242_+tmp243_;
   double tmp245_ = tmp95_*(tmp50_);
   double tmp246_ = tmp245_*(tmp33_);
   double tmp247_ = (tmp240_)*(tmp55_);
   double tmp248_ = tmp246_+tmp247_;
   double tmp249_ = (tmp248_)*(tmp58_);
   double tmp250_ = (tmp244_)*(tmp43_);
   double tmp251_ = tmp249_+tmp249_;
   double tmp252_ = tmp250_+tmp250_;
   double tmp253_ = (tmp252_)*tmp59_;
   double tmp254_ = (tmp251_)*tmp60_;
   double tmp255_ = tmp253_+tmp254_;
   double tmp256_ = tmp95_*tmp30_;
   double tmp257_ = tmp20_*tmp256_;
   double tmp258_ = -(tmp257_);
   double tmp259_ = tmp258_/tmp64_;
   double tmp260_ = tmp135_*(tmp33_);
   double tmp261_ = (tmp259_)*(tmp40_);
   double tmp262_ = tmp260_+tmp261_;
   double tmp263_ = tmp95_*tmp53_;
   double tmp264_ = tmp263_*(tmp33_);
   double tmp265_ = (tmp259_)*(tmp55_);
   double tmp266_ = tmp264_+tmp265_;
   double tmp267_ = (tmp266_)*(tmp58_);
   double tmp268_ = (tmp262_)*(tmp43_);
   double tmp269_ = tmp267_+tmp267_;
   double tmp270_ = tmp268_+tmp268_;
   double tmp271_ = (tmp270_)*tmp59_;
   double tmp272_ = (tmp269_)*tmp60_;
   double tmp273_ = tmp271_+tmp272_;
   double tmp274_ = tmp67_*(tmp58_);
   double tmp275_ = tmp68_*(tmp43_);
   double tmp276_ = tmp274_+tmp275_;
   double tmp277_ = mCompCoord[10];
   double tmp278_ = mCompCoord[11];
   double tmp279_ = (tmp76_)*(tmp58_);
   double tmp280_ = tmp68_*tmp60_;
   double tmp281_ = tmp279_+tmp280_;
   double tmp282_ = mCompCoord[12];
   double tmp283_ = tmp67_*tmp59_;
   double tmp284_ = (tmp74_)*(tmp43_);
   double tmp285_ = tmp283_+tmp284_;
   double tmp286_ = mCompCoord[13];
   double tmp287_ = mCompCoord[14];
   double tmp288_ = (tmp58_)/mLocDCBrown_State_0_0;
   double tmp289_ = tmp78_*(tmp288_);
   double tmp290_ = tmp76_+tmp74_;
   double tmp291_ = tmp84_*(tmp58_);
   double tmp292_ = (tmp87_)*(tmp58_);
   double tmp293_ = (tmp90_)*(tmp43_);
   double tmp294_ = mLocDCBrown_State_0_0/tmp88_;
   double tmp295_ = (tmp294_)*tmp78_;
   double tmp296_ = tmp295_*tmp61_;
   double tmp297_ = tmp84_*(tmp85_);
   double tmp298_ = tmp92_*mLocScNorm;
   double tmp299_ = tmp93_*mLocScNorm;
   double tmp300_ = tmp94_*mLocScNorm;
   double tmp301_ = tmp61_*mLocScNorm;
   double tmp302_ = (tmp116_)*(tmp58_);
   double tmp303_ = (tmp127_)*(tmp43_);
   double tmp304_ = tmp302_+tmp303_;
   double tmp305_ = (tmp131_)*(tmp58_);
   double tmp306_ = (tmp127_)*tmp60_;
   double tmp307_ = tmp305_+tmp306_;
   double tmp308_ = (tmp116_)*tmp59_;
   double tmp309_ = (tmp130_)*(tmp43_);
   double tmp310_ = tmp308_+tmp309_;
   double tmp311_ = tmp131_+tmp130_;
   double tmp312_ = (tmp159_)*(tmp58_);
   double tmp313_ = (tmp170_)*(tmp43_);
   double tmp314_ = tmp312_+tmp313_;
   double tmp315_ = (tmp174_)*(tmp58_);
   double tmp316_ = (tmp170_)*tmp60_;
   double tmp317_ = tmp315_+tmp316_;
   double tmp318_ = (tmp159_)*tmp59_;
   double tmp319_ = (tmp173_)*(tmp43_);
   double tmp320_ = tmp318_+tmp319_;
   double tmp321_ = tmp174_+tmp173_;
   double tmp322_ = tmp195_*(tmp58_);
   double tmp323_ = (tmp210_)*(tmp43_);
   double tmp324_ = tmp322_+tmp323_;
   double tmp325_ = (tmp214_)*(tmp58_);
   double tmp326_ = (tmp210_)*tmp60_;
   double tmp327_ = tmp325_+tmp326_;
   double tmp328_ = tmp195_*tmp59_;
   double tmp329_ = (tmp213_)*(tmp43_);
   double tmp330_ = tmp328_+tmp329_;
   double tmp331_ = tmp214_+tmp213_;
   double tmp332_ = (tmp225_)*(tmp58_);
   double tmp333_ = (tmp229_)*(tmp43_);
   double tmp334_ = tmp332_+tmp333_;
   double tmp335_ = (tmp233_)*(tmp58_);
   double tmp336_ = (tmp229_)*tmp60_;
   double tmp337_ = tmp335_+tmp336_;
   double tmp338_ = (tmp225_)*tmp59_;
   double tmp339_ = (tmp232_)*(tmp43_);
   double tmp340_ = tmp338_+tmp339_;
   double tmp341_ = tmp233_+tmp232_;
   double tmp342_ = (tmp244_)*(tmp58_);
   double tmp343_ = (tmp248_)*(tmp43_);
   double tmp344_ = tmp342_+tmp343_;
   double tmp345_ = (tmp252_)*(tmp58_);
   double tmp346_ = (tmp248_)*tmp60_;
   double tmp347_ = tmp345_+tmp346_;
   double tmp348_ = (tmp244_)*tmp59_;
   double tmp349_ = (tmp251_)*(tmp43_);
   double tmp350_ = tmp348_+tmp349_;
   double tmp351_ = tmp252_+tmp251_;
   double tmp352_ = (tmp262_)*(tmp58_);
   double tmp353_ = (tmp266_)*(tmp43_);
   double tmp354_ = tmp352_+tmp353_;
   double tmp355_ = (tmp270_)*(tmp58_);
   double tmp356_ = (tmp266_)*tmp60_;
   double tmp357_ = tmp355_+tmp356_;
   double tmp358_ = (tmp262_)*tmp59_;
   double tmp359_ = (tmp269_)*(tmp43_);
   double tmp360_ = tmp358_+tmp359_;
   double tmp361_ = tmp270_+tmp269_;

  mVal[0] = (((tmp63_)*(tmp43_)+tmp66_*(tmp58_)+tmp69_*tmp92_+tmp71_*tmp59_+tmp73_*tmp93_+tmp75_*tmp94_+tmp77_*tmp61_+tmp83_*tmp61_+tmp86_*(tmp85_))-mLocXIm)*mLocScNorm;

  mCompDer[0][0] = (tmp67_*(tmp63_)+tmp68_*tmp66_+(tmp276_)*tmp69_+(tmp74_)*tmp71_+(tmp281_)*tmp73_+(tmp285_)*tmp75_+(tmp81_)*tmp77_+((tmp67_*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp81_)*tmp83_+tmp67_*tmp84_*(tmp85_)+(tmp290_)*tmp86_)*mLocScNorm;
  mCompDer[0][1] = (tmp63_+(tmp58_)*tmp69_+tmp292_*tmp73_+tmp59_*tmp75_+tmp89_*tmp77_+tmp296_+tmp89_*tmp83_+tmp297_+(tmp87_)*tmp86_)*mLocScNorm;
  mCompDer[0][2] = (tmp66_+(tmp43_)*tmp69_+(tmp90_)*tmp71_+tmp60_*tmp73_+tmp293_*tmp75_+tmp91_*tmp77_+tmp91_*tmp83_+(tmp90_)*tmp86_)*mLocScNorm;
  mCompDer[0][3] = (tmp43_)*mLocScNorm;
  mCompDer[0][4] = (tmp58_)*mLocScNorm;
  mCompDer[0][5] = tmp298_;
  mCompDer[0][6] = tmp59_*mLocScNorm;
  mCompDer[0][7] = tmp299_;
  mCompDer[0][8] = tmp300_;
  mCompDer[0][9] = tmp301_;
  mCompDer[0][10] = 0;
  mCompDer[0][11] = 0;
  mCompDer[0][12] = 0;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = (tmp82_)*tmp61_*mLocScNorm;
  mCompDer[0][16] = (tmp43_)*(tmp85_)*mLocScNorm;
  mCompDer[0][17] = ((tmp116_)*(tmp63_)+(tmp127_)*tmp66_+(tmp304_)*tmp69_+(tmp130_)*tmp71_+(tmp307_)*tmp73_+(tmp310_)*tmp75_+(tmp134_)*tmp77_+(((tmp116_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp134_)*tmp83_+(tmp116_)*tmp84_*(tmp85_)+(tmp311_)*tmp86_)*mLocScNorm;
  mCompDer[0][18] = ((tmp159_)*(tmp63_)+(tmp170_)*tmp66_+(tmp314_)*tmp69_+(tmp173_)*tmp71_+(tmp317_)*tmp73_+(tmp320_)*tmp75_+(tmp177_)*tmp77_+(((tmp159_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp177_)*tmp83_+(tmp159_)*tmp84_*(tmp85_)+(tmp321_)*tmp86_)*mLocScNorm;
  mCompDer[0][19] = (tmp195_*(tmp63_)+(tmp210_)*tmp66_+(tmp324_)*tmp69_+(tmp213_)*tmp71_+(tmp327_)*tmp73_+(tmp330_)*tmp75_+(tmp217_)*tmp77_+((tmp195_*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp217_)*tmp83_+tmp195_*tmp84_*(tmp85_)+(tmp331_)*tmp86_)*mLocScNorm;
  mCompDer[0][20] = ((tmp225_)*(tmp63_)+(tmp229_)*tmp66_+(tmp334_)*tmp69_+(tmp232_)*tmp71_+(tmp337_)*tmp73_+(tmp340_)*tmp75_+(tmp236_)*tmp77_+(((tmp225_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp236_)*tmp83_+(tmp225_)*tmp84_*(tmp85_)+(tmp341_)*tmp86_)*mLocScNorm;
  mCompDer[0][21] = ((tmp244_)*(tmp63_)+(tmp248_)*tmp66_+(tmp344_)*tmp69_+(tmp251_)*tmp71_+(tmp347_)*tmp73_+(tmp350_)*tmp75_+(tmp255_)*tmp77_+(((tmp244_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp255_)*tmp83_+(tmp244_)*tmp84_*(tmp85_)+(tmp351_)*tmp86_)*mLocScNorm;
  mCompDer[0][22] = ((tmp262_)*(tmp63_)+(tmp266_)*tmp66_+(tmp354_)*tmp69_+(tmp269_)*tmp71_+(tmp357_)*tmp73_+(tmp360_)*tmp75_+(tmp273_)*tmp77_+(((tmp262_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp273_)*tmp83_+(tmp262_)*tmp84_*(tmp85_)+(tmp361_)*tmp86_)*mLocScNorm;
  mVal[1] = ((tmp58_+tmp277_*tmp92_+tmp278_*tmp60_+tmp282_*tmp93_+tmp286_*tmp94_+tmp287_*tmp61_+tmp289_*tmp61_+tmp291_*(tmp85_))-mLocYIm)*mLocScNorm;

  mCompDer[1][0] = (tmp68_+(tmp276_)*tmp277_+(tmp76_)*tmp278_+(tmp281_)*tmp282_+(tmp285_)*tmp286_+(tmp81_)*tmp287_+((tmp68_*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp81_)*tmp289_+tmp68_*tmp84_*(tmp85_)+(tmp290_)*tmp291_)*mLocScNorm;
  mCompDer[1][1] = ((tmp58_)*tmp277_+(tmp87_)*tmp278_+tmp292_*tmp282_+tmp59_*tmp286_+tmp89_*tmp287_+tmp89_*tmp289_+(tmp87_)*tmp291_)*mLocScNorm;
  mCompDer[1][2] = (1+(tmp43_)*tmp277_+tmp60_*tmp282_+tmp293_*tmp286_+tmp91_*tmp287_+tmp296_+tmp91_*tmp289_+tmp297_+(tmp90_)*tmp291_)*mLocScNorm;
  mCompDer[1][3] = 0;
  mCompDer[1][4] = 0;
  mCompDer[1][5] = 0;
  mCompDer[1][6] = 0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = 0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = tmp298_;
  mCompDer[1][11] = tmp60_*mLocScNorm;
  mCompDer[1][12] = tmp299_;
  mCompDer[1][13] = tmp300_;
  mCompDer[1][14] = tmp301_;
  mCompDer[1][15] = (tmp288_)*tmp61_*mLocScNorm;
  mCompDer[1][16] = (tmp58_)*(tmp85_)*mLocScNorm;
  mCompDer[1][17] = (tmp127_+(tmp304_)*tmp277_+(tmp131_)*tmp278_+(tmp307_)*tmp282_+(tmp310_)*tmp286_+(tmp134_)*tmp287_+(((tmp127_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp134_)*tmp289_+(tmp127_)*tmp84_*(tmp85_)+(tmp311_)*tmp291_)*mLocScNorm;
  mCompDer[1][18] = (tmp170_+(tmp314_)*tmp277_+(tmp174_)*tmp278_+(tmp317_)*tmp282_+(tmp320_)*tmp286_+(tmp177_)*tmp287_+(((tmp170_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp177_)*tmp289_+(tmp170_)*tmp84_*(tmp85_)+(tmp321_)*tmp291_)*mLocScNorm;
  mCompDer[1][19] = (tmp210_+(tmp324_)*tmp277_+(tmp214_)*tmp278_+(tmp327_)*tmp282_+(tmp330_)*tmp286_+(tmp217_)*tmp287_+(((tmp210_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp217_)*tmp289_+(tmp210_)*tmp84_*(tmp85_)+(tmp331_)*tmp291_)*mLocScNorm;
  mCompDer[1][20] = (tmp229_+(tmp334_)*tmp277_+(tmp233_)*tmp278_+(tmp337_)*tmp282_+(tmp340_)*tmp286_+(tmp236_)*tmp287_+(((tmp229_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp236_)*tmp289_+(tmp229_)*tmp84_*(tmp85_)+(tmp341_)*tmp291_)*mLocScNorm;
  mCompDer[1][21] = (tmp248_+(tmp344_)*tmp277_+(tmp252_)*tmp278_+(tmp347_)*tmp282_+(tmp350_)*tmp286_+(tmp255_)*tmp287_+(((tmp248_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp255_)*tmp289_+(tmp248_)*tmp84_*(tmp85_)+(tmp351_)*tmp291_)*mLocScNorm;
  mCompDer[1][22] = (tmp266_+(tmp354_)*tmp277_+(tmp270_)*tmp278_+(tmp357_)*tmp282_+(tmp360_)*tmp286_+(tmp273_)*tmp287_+(((tmp266_)*mLocDCBrown_State_0_0)/tmp88_)*tmp78_*tmp61_+(tmp273_)*tmp289_+(tmp266_)*tmp84_*(tmp85_)+(tmp361_)*tmp291_)*mLocScNorm;
}


void cEqAppui_TerFix_M2CDCBrown::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_TerFix_M2CDCBrown Has no Der Sec");
}

void cEqAppui_TerFix_M2CDCBrown::SetDCBrown_State_0_0(double aVal){ mLocDCBrown_State_0_0 = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetScNorm(double aVal){ mLocScNorm = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetXTer(double aVal){ mLocXTer = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetYIm(double aVal){ mLocYIm = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetYTer(double aVal){ mLocYTer = aVal;}
void cEqAppui_TerFix_M2CDCBrown::SetZTer(double aVal){ mLocZTer = aVal;}



double * cEqAppui_TerFix_M2CDCBrown::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "DCBrown_State_0_0") return & mLocDCBrown_State_0_0;
   if (aName == "ScNorm") return & mLocScNorm;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "XTer") return & mLocXTer;
   if (aName == "YIm") return & mLocYIm;
   if (aName == "YTer") return & mLocYTer;
   if (aName == "ZTer") return & mLocZTer;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_TerFix_M2CDCBrown::mTheAuto("cEqAppui_TerFix_M2CDCBrown",cEqAppui_TerFix_M2CDCBrown::Alloc);


cElCompiledFonc *  cEqAppui_TerFix_M2CDCBrown::Alloc()
{  return new cEqAppui_TerFix_M2CDCBrown();
}


