// File Automatically generated by eLiSe
#include "StdAfx.h"


class cEqAppui_GL__PTInc_M2CCamBilin: public cElCompiledFonc
{
   public :

      cEqAppui_GL__PTInc_M2CCamBilin();
      void ComputeVal();
      void ComputeValDeriv();
      void ComputeValDerivHessian();
      double * AdrVarLocFromString(const std::string &);
      void SetGL_0_0(double);
      void SetGL_0_1(double);
      void SetGL_0_2(double);
      void SetGL_1_0(double);
      void SetGL_1_1(double);
      void SetGL_1_2(double);
      void SetGL_2_0(double);
      void SetGL_2_1(double);
      void SetGL_2_2(double);
      void SetPts0_x(double);
      void SetPts0_y(double);
      void SetPts1_x(double);
      void SetPts2_y(double);
      void SetScNorm(double);
      void SetXIm(double);
      void SetYIm(double);


      static cAutoAddEntry  mTheAuto;
      static cElCompiledFonc *  Alloc();
   private :

      double mLocGL_0_0;
      double mLocGL_0_1;
      double mLocGL_0_2;
      double mLocGL_1_0;
      double mLocGL_1_1;
      double mLocGL_1_2;
      double mLocGL_2_0;
      double mLocGL_2_1;
      double mLocGL_2_2;
      double mLocPts0_x;
      double mLocPts0_y;
      double mLocPts1_x;
      double mLocPts2_y;
      double mLocScNorm;
      double mLocXIm;
      double mLocYIm;
};
