// File Automatically generated by eLiSe
#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_Y_C2MPolyn7.h"


cEqAppui_Y_C2MPolyn7::cEqAppui_Y_C2MPolyn7():
    cElCompiledFonc(1)
{
   AddIntRef (cIncIntervale("Intr",0,69));
   AddIntRef (cIncIntervale("Orient",69,75));
   Close(false);
}



void cEqAppui_Y_C2MPolyn7::ComputeVal()
{
   double tmp0_ = mCompCoord[69];
   double tmp1_ = mCompCoord[71];
   double tmp2_ = cos(tmp0_);
   double tmp3_ = cos(tmp1_);
   double tmp4_ = sin(tmp0_);
   double tmp5_ = mCompCoord[70];
   double tmp6_ = sin(tmp5_);
   double tmp7_ = -(tmp6_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = -(tmp4_);
   double tmp10_ = tmp2_*tmp7_;
   double tmp11_ = mCompCoord[72];
   double tmp12_ = mLocXTer-tmp11_;
   double tmp13_ = -(tmp8_);
   double tmp14_ = tmp4_*tmp7_;
   double tmp15_ = mCompCoord[73];
   double tmp16_ = mLocYTer-tmp15_;
   double tmp17_ = cos(tmp5_);
   double tmp18_ = mCompCoord[74];
   double tmp19_ = mLocZTer-tmp18_;
   double tmp20_ = mLocXIm/mLocPolyn7_State_0_0;
   double tmp21_ = mLocYIm/mLocPolyn7_State_0_0;
   double tmp22_ = (tmp20_)*(tmp20_);
   double tmp23_ = (tmp21_)*(tmp21_);
   double tmp24_ = tmp22_*(tmp20_);
   double tmp25_ = (tmp21_)*(tmp20_);
   double tmp26_ = tmp25_*(tmp20_);
   double tmp27_ = tmp23_*(tmp20_);
   double tmp28_ = (tmp21_)*tmp23_;
   double tmp29_ = tmp24_*(tmp20_);
   double tmp30_ = tmp26_*(tmp20_);
   double tmp31_ = tmp27_*(tmp20_);
   double tmp32_ = tmp28_*(tmp20_);
   double tmp33_ = (tmp21_)*tmp28_;
   double tmp34_ = tmp29_*(tmp20_);
   double tmp35_ = tmp30_*(tmp20_);
   double tmp36_ = tmp31_*(tmp20_);
   double tmp37_ = tmp32_*(tmp20_);
   double tmp38_ = tmp33_*(tmp20_);
   double tmp39_ = (tmp21_)*tmp33_;
   double tmp40_ = tmp34_*(tmp20_);
   double tmp41_ = tmp35_*(tmp20_);
   double tmp42_ = tmp36_*(tmp20_);
   double tmp43_ = tmp37_*(tmp20_);
   double tmp44_ = tmp38_*(tmp20_);
   double tmp45_ = tmp39_*(tmp20_);
   double tmp46_ = (tmp21_)*tmp39_;

  mVal[0] = (mCompCoord[2]+mCompCoord[0]*(((tmp9_*tmp3_+tmp10_*tmp8_)*(tmp12_)+(tmp2_*tmp3_+tmp14_*tmp8_)*(tmp16_)+tmp17_*tmp8_*(tmp19_))/((tmp9_*tmp13_+tmp10_*tmp3_)*(tmp12_)+(tmp2_*tmp13_+tmp14_*tmp3_)*(tmp16_)+tmp17_*tmp3_*(tmp19_))))-((((1-mCompCoord[3])*(tmp21_)+mCompCoord[4]*(tmp20_)+mCompCoord[5]*(tmp20_)*(tmp21_))-mCompCoord[6]*2*tmp23_+mCompCoord[8]*tmp22_)*mLocPolyn7_State_0_0+(mCompCoord[13]*tmp24_+mCompCoord[14]*tmp26_+mCompCoord[15]*tmp27_+mCompCoord[16]*tmp28_+mCompCoord[22]*tmp29_+mCompCoord[23]*tmp30_+mCompCoord[24]*tmp31_+mCompCoord[25]*tmp32_+mCompCoord[26]*tmp33_+mCompCoord[33]*tmp34_+mCompCoord[34]*tmp35_+mCompCoord[35]*tmp36_+mCompCoord[36]*tmp37_+mCompCoord[37]*tmp38_+mCompCoord[38]*tmp39_+mCompCoord[46]*tmp40_+mCompCoord[47]*tmp41_+mCompCoord[48]*tmp42_+mCompCoord[49]*tmp43_+mCompCoord[50]*tmp44_+mCompCoord[51]*tmp45_+mCompCoord[52]*tmp46_+mCompCoord[61]*tmp40_*(tmp20_)+mCompCoord[62]*tmp41_*(tmp20_)+mCompCoord[63]*tmp42_*(tmp20_)+mCompCoord[64]*tmp43_*(tmp20_)+mCompCoord[65]*tmp44_*(tmp20_)+mCompCoord[66]*tmp45_*(tmp20_)+mCompCoord[67]*tmp46_*(tmp20_)+mCompCoord[68]*(tmp21_)*tmp46_)*mLocPolyn7_State_0_0);

}


void cEqAppui_Y_C2MPolyn7::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[69];
   double tmp1_ = mCompCoord[71];
   double tmp2_ = cos(tmp0_);
   double tmp3_ = cos(tmp1_);
   double tmp4_ = sin(tmp0_);
   double tmp5_ = mCompCoord[70];
   double tmp6_ = sin(tmp5_);
   double tmp7_ = -(tmp6_);
   double tmp8_ = sin(tmp1_);
   double tmp9_ = -(tmp4_);
   double tmp10_ = tmp2_*tmp7_;
   double tmp11_ = mCompCoord[72];
   double tmp12_ = mLocXTer-tmp11_;
   double tmp13_ = -(tmp8_);
   double tmp14_ = tmp4_*tmp7_;
   double tmp15_ = mCompCoord[73];
   double tmp16_ = mLocYTer-tmp15_;
   double tmp17_ = cos(tmp5_);
   double tmp18_ = mCompCoord[74];
   double tmp19_ = mLocZTer-tmp18_;
   double tmp20_ = mLocXIm/mLocPolyn7_State_0_0;
   double tmp21_ = mLocYIm/mLocPolyn7_State_0_0;
   double tmp22_ = (tmp20_)*(tmp20_);
   double tmp23_ = (tmp21_)*(tmp21_);
   double tmp24_ = tmp22_*(tmp20_);
   double tmp25_ = (tmp21_)*(tmp20_);
   double tmp26_ = tmp25_*(tmp20_);
   double tmp27_ = tmp23_*(tmp20_);
   double tmp28_ = (tmp21_)*tmp23_;
   double tmp29_ = tmp24_*(tmp20_);
   double tmp30_ = tmp26_*(tmp20_);
   double tmp31_ = tmp27_*(tmp20_);
   double tmp32_ = tmp28_*(tmp20_);
   double tmp33_ = (tmp21_)*tmp28_;
   double tmp34_ = tmp29_*(tmp20_);
   double tmp35_ = tmp30_*(tmp20_);
   double tmp36_ = tmp31_*(tmp20_);
   double tmp37_ = tmp32_*(tmp20_);
   double tmp38_ = tmp33_*(tmp20_);
   double tmp39_ = (tmp21_)*tmp33_;
   double tmp40_ = tmp34_*(tmp20_);
   double tmp41_ = tmp35_*(tmp20_);
   double tmp42_ = tmp36_*(tmp20_);
   double tmp43_ = tmp37_*(tmp20_);
   double tmp44_ = tmp38_*(tmp20_);
   double tmp45_ = tmp39_*(tmp20_);
   double tmp46_ = (tmp21_)*tmp39_;
   double tmp47_ = tmp9_*tmp3_;
   double tmp48_ = tmp10_*tmp8_;
   double tmp49_ = tmp47_+tmp48_;
   double tmp50_ = (tmp49_)*(tmp12_);
   double tmp51_ = tmp2_*tmp3_;
   double tmp52_ = tmp14_*tmp8_;
   double tmp53_ = tmp51_+tmp52_;
   double tmp54_ = (tmp53_)*(tmp16_);
   double tmp55_ = tmp50_+tmp54_;
   double tmp56_ = tmp17_*tmp8_;
   double tmp57_ = tmp56_*(tmp19_);
   double tmp58_ = tmp55_+tmp57_;
   double tmp59_ = tmp9_*tmp13_;
   double tmp60_ = tmp10_*tmp3_;
   double tmp61_ = tmp59_+tmp60_;
   double tmp62_ = (tmp61_)*(tmp12_);
   double tmp63_ = tmp2_*tmp13_;
   double tmp64_ = tmp14_*tmp3_;
   double tmp65_ = tmp63_+tmp64_;
   double tmp66_ = (tmp65_)*(tmp16_);
   double tmp67_ = tmp62_+tmp66_;
   double tmp68_ = tmp17_*tmp3_;
   double tmp69_ = tmp68_*(tmp19_);
   double tmp70_ = tmp67_+tmp69_;
   double tmp71_ = (tmp58_)/(tmp70_);
   double tmp72_ = (tmp20_)*(tmp21_);
   double tmp73_ = tmp40_*(tmp20_);
   double tmp74_ = tmp41_*(tmp20_);
   double tmp75_ = tmp42_*(tmp20_);
   double tmp76_ = tmp43_*(tmp20_);
   double tmp77_ = tmp44_*(tmp20_);
   double tmp78_ = tmp45_*(tmp20_);
   double tmp79_ = tmp46_*(tmp20_);
   double tmp80_ = (tmp21_)*tmp46_;
   double tmp81_ = -(1);
   double tmp82_ = tmp81_*tmp4_;
   double tmp83_ = -(tmp2_);
   double tmp84_ = tmp82_*tmp7_;
   double tmp85_ = mCompCoord[0];
   double tmp86_ = -(tmp17_);
   double tmp87_ = tmp86_*tmp2_;
   double tmp88_ = tmp86_*tmp4_;
   double tmp89_ = tmp81_*tmp6_;
   double tmp90_ = ElSquare(tmp70_);
   double tmp91_ = tmp81_*tmp8_;
   double tmp92_ = -(tmp3_);

  mVal[0] = (mCompCoord[2]+tmp85_*(tmp71_))-((((1-mCompCoord[3])*(tmp21_)+mCompCoord[4]*(tmp20_)+mCompCoord[5]*tmp72_)-mCompCoord[6]*2*tmp23_+mCompCoord[8]*tmp22_)*mLocPolyn7_State_0_0+(mCompCoord[13]*tmp24_+mCompCoord[14]*tmp26_+mCompCoord[15]*tmp27_+mCompCoord[16]*tmp28_+mCompCoord[22]*tmp29_+mCompCoord[23]*tmp30_+mCompCoord[24]*tmp31_+mCompCoord[25]*tmp32_+mCompCoord[26]*tmp33_+mCompCoord[33]*tmp34_+mCompCoord[34]*tmp35_+mCompCoord[35]*tmp36_+mCompCoord[36]*tmp37_+mCompCoord[37]*tmp38_+mCompCoord[38]*tmp39_+mCompCoord[46]*tmp40_+mCompCoord[47]*tmp41_+mCompCoord[48]*tmp42_+mCompCoord[49]*tmp43_+mCompCoord[50]*tmp44_+mCompCoord[51]*tmp45_+mCompCoord[52]*tmp46_+mCompCoord[61]*tmp73_+mCompCoord[62]*tmp74_+mCompCoord[63]*tmp75_+mCompCoord[64]*tmp76_+mCompCoord[65]*tmp77_+mCompCoord[66]*tmp78_+mCompCoord[67]*tmp79_+mCompCoord[68]*tmp80_)*mLocPolyn7_State_0_0);

  mCompDer[0][0] = tmp71_;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 1;
  mCompDer[0][3] = -(tmp81_*(tmp21_)*mLocPolyn7_State_0_0);
  mCompDer[0][4] = -((tmp20_)*mLocPolyn7_State_0_0);
  mCompDer[0][5] = -(tmp72_*mLocPolyn7_State_0_0);
  mCompDer[0][6] = -(-(2*tmp23_)*mLocPolyn7_State_0_0);
  mCompDer[0][7] = 0;
  mCompDer[0][8] = -(tmp22_*mLocPolyn7_State_0_0);
  mCompDer[0][9] = 0;
  mCompDer[0][10] = 0;
  mCompDer[0][11] = 0;
  mCompDer[0][12] = 0;
  mCompDer[0][13] = -(tmp24_*mLocPolyn7_State_0_0);
  mCompDer[0][14] = -(tmp26_*mLocPolyn7_State_0_0);
  mCompDer[0][15] = -(tmp27_*mLocPolyn7_State_0_0);
  mCompDer[0][16] = -(tmp28_*mLocPolyn7_State_0_0);
  mCompDer[0][17] = 0;
  mCompDer[0][18] = 0;
  mCompDer[0][19] = 0;
  mCompDer[0][20] = 0;
  mCompDer[0][21] = 0;
  mCompDer[0][22] = -(tmp29_*mLocPolyn7_State_0_0);
  mCompDer[0][23] = -(tmp30_*mLocPolyn7_State_0_0);
  mCompDer[0][24] = -(tmp31_*mLocPolyn7_State_0_0);
  mCompDer[0][25] = -(tmp32_*mLocPolyn7_State_0_0);
  mCompDer[0][26] = -(tmp33_*mLocPolyn7_State_0_0);
  mCompDer[0][27] = 0;
  mCompDer[0][28] = 0;
  mCompDer[0][29] = 0;
  mCompDer[0][30] = 0;
  mCompDer[0][31] = 0;
  mCompDer[0][32] = 0;
  mCompDer[0][33] = -(tmp34_*mLocPolyn7_State_0_0);
  mCompDer[0][34] = -(tmp35_*mLocPolyn7_State_0_0);
  mCompDer[0][35] = -(tmp36_*mLocPolyn7_State_0_0);
  mCompDer[0][36] = -(tmp37_*mLocPolyn7_State_0_0);
  mCompDer[0][37] = -(tmp38_*mLocPolyn7_State_0_0);
  mCompDer[0][38] = -(tmp39_*mLocPolyn7_State_0_0);
  mCompDer[0][39] = 0;
  mCompDer[0][40] = 0;
  mCompDer[0][41] = 0;
  mCompDer[0][42] = 0;
  mCompDer[0][43] = 0;
  mCompDer[0][44] = 0;
  mCompDer[0][45] = 0;
  mCompDer[0][46] = -(tmp40_*mLocPolyn7_State_0_0);
  mCompDer[0][47] = -(tmp41_*mLocPolyn7_State_0_0);
  mCompDer[0][48] = -(tmp42_*mLocPolyn7_State_0_0);
  mCompDer[0][49] = -(tmp43_*mLocPolyn7_State_0_0);
  mCompDer[0][50] = -(tmp44_*mLocPolyn7_State_0_0);
  mCompDer[0][51] = -(tmp45_*mLocPolyn7_State_0_0);
  mCompDer[0][52] = -(tmp46_*mLocPolyn7_State_0_0);
  mCompDer[0][53] = 0;
  mCompDer[0][54] = 0;
  mCompDer[0][55] = 0;
  mCompDer[0][56] = 0;
  mCompDer[0][57] = 0;
  mCompDer[0][58] = 0;
  mCompDer[0][59] = 0;
  mCompDer[0][60] = 0;
  mCompDer[0][61] = -(tmp73_*mLocPolyn7_State_0_0);
  mCompDer[0][62] = -(tmp74_*mLocPolyn7_State_0_0);
  mCompDer[0][63] = -(tmp75_*mLocPolyn7_State_0_0);
  mCompDer[0][64] = -(tmp76_*mLocPolyn7_State_0_0);
  mCompDer[0][65] = -(tmp77_*mLocPolyn7_State_0_0);
  mCompDer[0][66] = -(tmp78_*mLocPolyn7_State_0_0);
  mCompDer[0][67] = -(tmp79_*mLocPolyn7_State_0_0);
  mCompDer[0][68] = -(tmp80_*mLocPolyn7_State_0_0);
  mCompDer[0][69] = ((((tmp83_*tmp3_+tmp84_*tmp8_)*(tmp12_)+(tmp82_*tmp3_+tmp48_)*(tmp16_))*(tmp70_)-(tmp58_)*((tmp83_*tmp13_+tmp84_*tmp3_)*(tmp12_)+(tmp82_*tmp13_+tmp60_)*(tmp16_)))/tmp90_)*tmp85_;
  mCompDer[0][70] = (((tmp87_*tmp8_*(tmp12_)+tmp88_*tmp8_*(tmp16_)+tmp89_*tmp8_*(tmp19_))*(tmp70_)-(tmp58_)*(tmp87_*tmp3_*(tmp12_)+tmp88_*tmp3_*(tmp16_)+tmp89_*tmp3_*(tmp19_)))/tmp90_)*tmp85_;
  mCompDer[0][71] = ((((tmp91_*tmp9_+tmp3_*tmp10_)*(tmp12_)+(tmp91_*tmp2_+tmp3_*tmp14_)*(tmp16_)+tmp3_*tmp17_*(tmp19_))*(tmp70_)-(tmp58_)*((tmp92_*tmp9_+tmp91_*tmp10_)*(tmp12_)+(tmp92_*tmp2_+tmp91_*tmp14_)*(tmp16_)+tmp91_*tmp17_*(tmp19_)))/tmp90_)*tmp85_;
  mCompDer[0][72] = ((tmp81_*(tmp49_)*(tmp70_)-(tmp58_)*tmp81_*(tmp61_))/tmp90_)*tmp85_;
  mCompDer[0][73] = ((tmp81_*(tmp53_)*(tmp70_)-(tmp58_)*tmp81_*(tmp65_))/tmp90_)*tmp85_;
  mCompDer[0][74] = ((tmp81_*tmp56_*(tmp70_)-(tmp58_)*tmp81_*tmp68_)/tmp90_)*tmp85_;
}


void cEqAppui_Y_C2MPolyn7::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_Y_C2MPolyn7 Has no Der Sec");
}

void cEqAppui_Y_C2MPolyn7::SetPolyn7_State_0_0(double aVal){ mLocPolyn7_State_0_0 = aVal;}
void cEqAppui_Y_C2MPolyn7::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_Y_C2MPolyn7::SetXTer(double aVal){ mLocXTer = aVal;}
void cEqAppui_Y_C2MPolyn7::SetYIm(double aVal){ mLocYIm = aVal;}
void cEqAppui_Y_C2MPolyn7::SetYTer(double aVal){ mLocYTer = aVal;}
void cEqAppui_Y_C2MPolyn7::SetZTer(double aVal){ mLocZTer = aVal;}



double * cEqAppui_Y_C2MPolyn7::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Polyn7_State_0_0") return & mLocPolyn7_State_0_0;
   if (aName == "XIm") return & mLocXIm;
   if (aName == "XTer") return & mLocXTer;
   if (aName == "YIm") return & mLocYIm;
   if (aName == "YTer") return & mLocYTer;
   if (aName == "ZTer") return & mLocZTer;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_Y_C2MPolyn7::mTheAuto("cEqAppui_Y_C2MPolyn7",cEqAppui_Y_C2MPolyn7::Alloc);


cElCompiledFonc *  cEqAppui_Y_C2MPolyn7::Alloc()
{  return new cEqAppui_Y_C2MPolyn7();
}


