// File Automatically generated by eLiSe
#include "StdAfx.h"


class cEqBBCamSecond: public cElCompiledFonc
{
   public :

      cEqBBCamSecond();
      void ComputeVal();
      void ComputeValDeriv();
      void ComputeValDerivHessian();
      double * AdrVarLocFromString(const std::string &);
      void SetI2_x(double);
      void SetI2_y(double);
      void SetVecB2_x(double);
      void SetVecB2_y(double);
      void SetVecB2_z(double);
      void SetVecC2_x(double);
      void SetVecC2_y(double);
      void SetVecC2_z(double);
      void SetVecD2_x(double);
      void SetVecD2_y(double);
      void SetVecD2_z(double);


      static cAutoAddEntry  mTheAuto;
      static cElCompiledFonc *  Alloc();
   private :

      double mLocI2_x;
      double mLocI2_y;
      double mLocVecB2_x;
      double mLocVecB2_y;
      double mLocVecB2_z;
      double mLocVecC2_x;
      double mLocVecC2_y;
      double mLocVecC2_z;
      double mLocVecD2_x;
      double mLocVecD2_y;
      double mLocVecD2_z;
};
