// File Automatically generated by eLiSe

#include "general/all.h"
#include "private/all.h"
#include "cEqCibleEllipse6.h"


cEqCibleEllipse6::cEqCibleEllipse6():
    cElCompiledFonc(1)
{
   AddIntRef (cIncIntervale("ElIma",0,8));
   Close(false);
}



void cEqCibleEllipse6::ComputeVal()
{
   double tmp0_ = mLocDiam0/mLocDiam0;
   double tmp1_ = mCompCoord[5];
   double tmp2_ = mCompCoord[0];
   double tmp3_ = mCompCoord[1];
   double tmp4_ = mCompCoord[2];
   double tmp5_ = mCompCoord[3];
   double tmp6_ = mLocDiam0/mLocDiam1;
   double tmp7_ = mCompCoord[4];
   double tmp8_ = mLocXPix-tmp1_;
   double tmp9_ = mLocYPix-tmp1_;
   double tmp10_ = mLocXPix+tmp1_;
   double tmp11_ = mLocYPix+tmp1_;
   double tmp12_ = mLocDiam0/mLocDiam2;
   double tmp13_ = mLocDiam0/mLocDiam3;
   double tmp14_ = mLocDiam0/mLocDiam4;
   double tmp15_ = mLocDiam0/mLocDiam5;
   double tmp16_ = tmp4_*(tmp0_);
   double tmp17_ = tmp5_*(tmp0_);
   double tmp18_ = tmp7_*(tmp0_);
   double tmp19_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp20_ = tmp4_*(tmp6_);
   double tmp21_ = tmp5_*(tmp6_);
   double tmp22_ = tmp7_*(tmp6_);
   double tmp23_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp24_ = (tmp23_)*-1;
   double tmp25_ = (tmp19_)+tmp24_;
   double tmp26_ = tmp4_*(tmp12_);
   double tmp27_ = tmp5_*(tmp12_);
   double tmp28_ = tmp7_*(tmp12_);
   double tmp29_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp30_ = tmp25_+(tmp29_);
   double tmp31_ = tmp4_*(tmp13_);
   double tmp32_ = tmp5_*(tmp13_);
   double tmp33_ = tmp7_*(tmp13_);
   double tmp34_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp35_ = (tmp34_)*-1;
   double tmp36_ = tmp30_+tmp35_;
   double tmp37_ = tmp4_*(tmp14_);
   double tmp38_ = tmp5_*(tmp14_);
   double tmp39_ = tmp7_*(tmp14_);
   double tmp40_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp41_ = tmp36_+(tmp40_);
   double tmp42_ = tmp4_*(tmp15_);
   double tmp43_ = tmp5_*(tmp15_);
   double tmp44_ = tmp7_*(tmp15_);
   double tmp45_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp46_ = (tmp45_)*-1;
   double tmp47_ = tmp41_+tmp46_;
   double tmp48_ = 2*tmp1_;
   double tmp49_ = ElSquare(tmp48_);
   double tmp50_ = (tmp47_)/tmp49_;

  mVal[0] = (mCompCoord[7]*(tmp50_)+mCompCoord[6]*(1-tmp50_))-mLocGray;

}


void cEqCibleEllipse6::ComputeValDeriv()
{
   double tmp0_ = mLocDiam0/mLocDiam0;
   double tmp1_ = mCompCoord[5];
   double tmp2_ = mCompCoord[0];
   double tmp3_ = mCompCoord[1];
   double tmp4_ = mCompCoord[2];
   double tmp5_ = mCompCoord[3];
   double tmp6_ = mLocDiam0/mLocDiam1;
   double tmp7_ = mCompCoord[4];
   double tmp8_ = mLocXPix-tmp1_;
   double tmp9_ = mLocYPix-tmp1_;
   double tmp10_ = mLocXPix+tmp1_;
   double tmp11_ = mLocYPix+tmp1_;
   double tmp12_ = mLocDiam0/mLocDiam2;
   double tmp13_ = mLocDiam0/mLocDiam3;
   double tmp14_ = mLocDiam0/mLocDiam4;
   double tmp15_ = mLocDiam0/mLocDiam5;
   double tmp16_ = tmp4_*(tmp0_);
   double tmp17_ = tmp5_*(tmp0_);
   double tmp18_ = tmp7_*(tmp0_);
   double tmp19_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp20_ = tmp4_*(tmp6_);
   double tmp21_ = tmp5_*(tmp6_);
   double tmp22_ = tmp7_*(tmp6_);
   double tmp23_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp24_ = (tmp23_)*-1;
   double tmp25_ = (tmp19_)+tmp24_;
   double tmp26_ = tmp4_*(tmp12_);
   double tmp27_ = tmp5_*(tmp12_);
   double tmp28_ = tmp7_*(tmp12_);
   double tmp29_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp30_ = tmp25_+(tmp29_);
   double tmp31_ = tmp4_*(tmp13_);
   double tmp32_ = tmp5_*(tmp13_);
   double tmp33_ = tmp7_*(tmp13_);
   double tmp34_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp35_ = (tmp34_)*-1;
   double tmp36_ = tmp30_+tmp35_;
   double tmp37_ = tmp4_*(tmp14_);
   double tmp38_ = tmp5_*(tmp14_);
   double tmp39_ = tmp7_*(tmp14_);
   double tmp40_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp41_ = tmp36_+(tmp40_);
   double tmp42_ = tmp4_*(tmp15_);
   double tmp43_ = tmp5_*(tmp15_);
   double tmp44_ = tmp7_*(tmp15_);
   double tmp45_ = SurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp46_ = (tmp45_)*-1;
   double tmp47_ = tmp41_+tmp46_;
   double tmp48_ = 2*tmp1_;
   double tmp49_ = ElSquare(tmp48_);
   double tmp50_ = (tmp47_)/tmp49_;
   double tmp51_ = mCompCoord[7];
   double tmp52_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp53_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp54_ = (tmp53_)*-1;
   double tmp55_ = (tmp52_)+tmp54_;
   double tmp56_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp57_ = tmp55_+(tmp56_);
   double tmp58_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp59_ = (tmp58_)*-1;
   double tmp60_ = tmp57_+tmp59_;
   double tmp61_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp62_ = tmp60_+(tmp61_);
   double tmp63_ = DerCElXSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp64_ = (tmp63_)*-1;
   double tmp65_ = tmp62_+tmp64_;
   double tmp66_ = (tmp65_)*tmp49_;
   double tmp67_ = ElSquare(tmp49_);
   double tmp68_ = (tmp66_)/tmp67_;
   double tmp69_ = mCompCoord[6];
   double tmp70_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp71_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp72_ = (tmp71_)*-1;
   double tmp73_ = (tmp70_)+tmp72_;
   double tmp74_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp75_ = tmp73_+(tmp74_);
   double tmp76_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp77_ = (tmp76_)*-1;
   double tmp78_ = tmp75_+tmp77_;
   double tmp79_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp80_ = tmp78_+(tmp79_);
   double tmp81_ = DerCElYSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp82_ = (tmp81_)*-1;
   double tmp83_ = tmp80_+tmp82_;
   double tmp84_ = (tmp83_)*tmp49_;
   double tmp85_ = (tmp84_)/tmp67_;
   double tmp86_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp87_ = (tmp0_)*(tmp86_);
   double tmp88_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp89_ = (tmp6_)*(tmp88_);
   double tmp90_ = tmp89_*-1;
   double tmp91_ = tmp87_+tmp90_;
   double tmp92_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp93_ = (tmp12_)*(tmp92_);
   double tmp94_ = tmp91_+tmp93_;
   double tmp95_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp96_ = (tmp13_)*(tmp95_);
   double tmp97_ = tmp96_*-1;
   double tmp98_ = tmp94_+tmp97_;
   double tmp99_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp100_ = (tmp14_)*(tmp99_);
   double tmp101_ = tmp98_+tmp100_;
   double tmp102_ = DerASurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp103_ = (tmp15_)*(tmp102_);
   double tmp104_ = tmp103_*-1;
   double tmp105_ = tmp101_+tmp104_;
   double tmp106_ = (tmp105_)*tmp49_;
   double tmp107_ = (tmp106_)/tmp67_;
   double tmp108_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp109_ = (tmp0_)*(tmp108_);
   double tmp110_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp111_ = (tmp6_)*(tmp110_);
   double tmp112_ = tmp111_*-1;
   double tmp113_ = tmp109_+tmp112_;
   double tmp114_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp115_ = (tmp12_)*(tmp114_);
   double tmp116_ = tmp113_+tmp115_;
   double tmp117_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp118_ = (tmp13_)*(tmp117_);
   double tmp119_ = tmp118_*-1;
   double tmp120_ = tmp116_+tmp119_;
   double tmp121_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp122_ = (tmp14_)*(tmp121_);
   double tmp123_ = tmp120_+tmp122_;
   double tmp124_ = DerBSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp125_ = (tmp15_)*(tmp124_);
   double tmp126_ = tmp125_*-1;
   double tmp127_ = tmp123_+tmp126_;
   double tmp128_ = (tmp127_)*tmp49_;
   double tmp129_ = (tmp128_)/tmp67_;
   double tmp130_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp131_ = (tmp0_)*(tmp130_);
   double tmp132_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp133_ = (tmp6_)*(tmp132_);
   double tmp134_ = tmp133_*-1;
   double tmp135_ = tmp131_+tmp134_;
   double tmp136_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp137_ = (tmp12_)*(tmp136_);
   double tmp138_ = tmp135_+tmp137_;
   double tmp139_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp140_ = (tmp13_)*(tmp139_);
   double tmp141_ = tmp140_*-1;
   double tmp142_ = tmp138_+tmp141_;
   double tmp143_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp144_ = (tmp14_)*(tmp143_);
   double tmp145_ = tmp142_+tmp144_;
   double tmp146_ = DerCSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp147_ = (tmp15_)*(tmp146_);
   double tmp148_ = tmp147_*-1;
   double tmp149_ = tmp145_+tmp148_;
   double tmp150_ = (tmp149_)*tmp49_;
   double tmp151_ = (tmp150_)/tmp67_;
   double tmp152_ = -(1);
   double tmp153_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp154_ = tmp152_*(tmp153_);
   double tmp155_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp156_ = tmp152_*(tmp155_);
   double tmp157_ = tmp154_+tmp156_;
   double tmp158_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp159_ = tmp157_+(tmp158_);
   double tmp160_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp16_,tmp17_,tmp18_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp161_ = tmp159_+(tmp160_);
   double tmp162_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp163_ = tmp152_*(tmp162_);
   double tmp164_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp165_ = tmp152_*(tmp164_);
   double tmp166_ = tmp163_+tmp165_;
   double tmp167_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp168_ = tmp166_+(tmp167_);
   double tmp169_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp20_,tmp21_,tmp22_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp170_ = tmp168_+(tmp169_);
   double tmp171_ = (tmp170_)*-1;
   double tmp172_ = tmp161_+tmp171_;
   double tmp173_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp174_ = tmp152_*(tmp173_);
   double tmp175_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp176_ = tmp152_*(tmp175_);
   double tmp177_ = tmp174_+tmp176_;
   double tmp178_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp179_ = tmp177_+(tmp178_);
   double tmp180_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp26_,tmp27_,tmp28_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp181_ = tmp179_+(tmp180_);
   double tmp182_ = tmp172_+tmp181_;
   double tmp183_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp184_ = tmp152_*(tmp183_);
   double tmp185_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp186_ = tmp152_*(tmp185_);
   double tmp187_ = tmp184_+tmp186_;
   double tmp188_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp189_ = tmp187_+(tmp188_);
   double tmp190_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp31_,tmp32_,tmp33_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp191_ = tmp189_+(tmp190_);
   double tmp192_ = (tmp191_)*-1;
   double tmp193_ = tmp182_+tmp192_;
   double tmp194_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp195_ = tmp152_*(tmp194_);
   double tmp196_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp197_ = tmp152_*(tmp196_);
   double tmp198_ = tmp195_+tmp197_;
   double tmp199_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp200_ = tmp198_+(tmp199_);
   double tmp201_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp37_,tmp38_,tmp39_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp202_ = tmp200_+(tmp201_);
   double tmp203_ = tmp193_+tmp202_;
   double tmp204_ = DerP0XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp205_ = tmp152_*(tmp204_);
   double tmp206_ = DerP0YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp207_ = tmp152_*(tmp206_);
   double tmp208_ = tmp205_+tmp207_;
   double tmp209_ = DerP1XSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp210_ = tmp208_+(tmp209_);
   double tmp211_ = DerP1YSurfIER(Pt2dr(tmp2_,tmp3_) ,tmp42_,tmp43_,tmp44_,Pt2dr(tmp8_,tmp9_) ,Pt2dr(tmp10_,tmp11_) );
   double tmp212_ = tmp210_+(tmp211_);
   double tmp213_ = (tmp212_)*-1;
   double tmp214_ = tmp203_+tmp213_;
   double tmp215_ = (tmp214_)*tmp49_;
   double tmp216_ = 4.000000*tmp48_;
   double tmp217_ = (tmp47_)*tmp216_;
   double tmp218_ = tmp215_-tmp217_;
   double tmp219_ = (tmp218_)/tmp67_;
   double tmp220_ = 1-tmp50_;

  mVal[0] = (tmp51_*(tmp50_)+tmp69_*(tmp220_))-mLocGray;

  mCompDer[0][0] = (tmp68_)*tmp51_+-(tmp68_)*tmp69_;
  mCompDer[0][1] = (tmp85_)*tmp51_+-(tmp85_)*tmp69_;
  mCompDer[0][2] = (tmp107_)*tmp51_+-(tmp107_)*tmp69_;
  mCompDer[0][3] = (tmp129_)*tmp51_+-(tmp129_)*tmp69_;
  mCompDer[0][4] = (tmp151_)*tmp51_+-(tmp151_)*tmp69_;
  mCompDer[0][5] = (tmp219_)*tmp51_+-(tmp219_)*tmp69_;
  mCompDer[0][6] = tmp220_;
  mCompDer[0][7] = tmp50_;
}


void cEqCibleEllipse6::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqCibleEllipse6 Has no Der Sec");
}

void cEqCibleEllipse6::SetDiam0(double aVal){ mLocDiam0 = aVal;}
void cEqCibleEllipse6::SetDiam1(double aVal){ mLocDiam1 = aVal;}
void cEqCibleEllipse6::SetDiam2(double aVal){ mLocDiam2 = aVal;}
void cEqCibleEllipse6::SetDiam3(double aVal){ mLocDiam3 = aVal;}
void cEqCibleEllipse6::SetDiam4(double aVal){ mLocDiam4 = aVal;}
void cEqCibleEllipse6::SetDiam5(double aVal){ mLocDiam5 = aVal;}
void cEqCibleEllipse6::SetGray(double aVal){ mLocGray = aVal;}
void cEqCibleEllipse6::SetXPix(double aVal){ mLocXPix = aVal;}
void cEqCibleEllipse6::SetYPix(double aVal){ mLocYPix = aVal;}



double * cEqCibleEllipse6::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Diam0") return & mLocDiam0;
   if (aName == "Diam1") return & mLocDiam1;
   if (aName == "Diam2") return & mLocDiam2;
   if (aName == "Diam3") return & mLocDiam3;
   if (aName == "Diam4") return & mLocDiam4;
   if (aName == "Diam5") return & mLocDiam5;
   if (aName == "Gray") return & mLocGray;
   if (aName == "XPix") return & mLocXPix;
   if (aName == "YPix") return & mLocYPix;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqCibleEllipse6::mTheAuto("cEqCibleEllipse6",cEqCibleEllipse6::Alloc);


cElCompiledFonc *  cEqCibleEllipse6::Alloc()
{  return new cEqCibleEllipse6();
}


