// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cGen2DBundleAtRot_Deg0.h"


cGen2DBundleAtRot_Deg0::cGen2DBundleAtRot_Deg0():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("CX",3,4));
   AddIntRef (cIncIntervale("CY",4,5));
   AddIntRef (cIncIntervale("Tmp_PTer",0,3));
   Close(false);
}



void cGen2DBundleAtRot_Deg0::ComputeVal()
{
   double tmp0_ = mCompCoord[0];
   double tmp1_ = mCompCoord[1];
   double tmp2_ = mCompCoord[2];

  mVal[0] = mCompCoord[3]-mLocDepR1_x*tmp0_-mLocDepR2_x*tmp1_-mLocDepR3_x*tmp2_;

  mVal[1] = mCompCoord[4]-mLocDepR1_y*tmp0_-mLocDepR2_y*tmp1_-mLocDepR3_y*tmp2_;

}


void cGen2DBundleAtRot_Deg0::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[0];
   double tmp1_ = mCompCoord[1];
   double tmp2_ = mCompCoord[2];

  mVal[0] = mCompCoord[3]-mLocDepR1_x*tmp0_-mLocDepR2_x*tmp1_-mLocDepR3_x*tmp2_;

  mCompDer[0][0] = -(mLocDepR1_x);
  mCompDer[0][1] = -(mLocDepR2_x);
  mCompDer[0][2] = -(mLocDepR3_x);
  mCompDer[0][3] = 1;
  mCompDer[0][4] = 0;
  mVal[1] = mCompCoord[4]-mLocDepR1_y*tmp0_-mLocDepR2_y*tmp1_-mLocDepR3_y*tmp2_;

  mCompDer[1][0] = -(mLocDepR1_y);
  mCompDer[1][1] = -(mLocDepR2_y);
  mCompDer[1][2] = -(mLocDepR3_y);
  mCompDer[1][3] = 0;
  mCompDer[1][4] = 1;
}


void cGen2DBundleAtRot_Deg0::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cGen2DBundleAtRot_Deg0 Has no Der Sec");
}

void cGen2DBundleAtRot_Deg0::SetDepR1_x(double aVal){ mLocDepR1_x = aVal;}
void cGen2DBundleAtRot_Deg0::SetDepR1_y(double aVal){ mLocDepR1_y = aVal;}
void cGen2DBundleAtRot_Deg0::SetDepR2_x(double aVal){ mLocDepR2_x = aVal;}
void cGen2DBundleAtRot_Deg0::SetDepR2_y(double aVal){ mLocDepR2_y = aVal;}
void cGen2DBundleAtRot_Deg0::SetDepR3_x(double aVal){ mLocDepR3_x = aVal;}
void cGen2DBundleAtRot_Deg0::SetDepR3_y(double aVal){ mLocDepR3_y = aVal;}



double * cGen2DBundleAtRot_Deg0::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "DepR1_x") return & mLocDepR1_x;
   if (aName == "DepR1_y") return & mLocDepR1_y;
   if (aName == "DepR2_x") return & mLocDepR2_x;
   if (aName == "DepR2_y") return & mLocDepR2_y;
   if (aName == "DepR3_x") return & mLocDepR3_x;
   if (aName == "DepR3_y") return & mLocDepR3_y;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cGen2DBundleAtRot_Deg0::mTheAuto("cGen2DBundleAtRot_Deg0",cGen2DBundleAtRot_Deg0::Alloc);


cElCompiledFonc *  cGen2DBundleAtRot_Deg0::Alloc()
{  return new cGen2DBundleAtRot_Deg0();
}


