// File Automatically generated by eLiSe
#include "general/all.h"
#include "private/all.h"
#include "cEqAppui_NoDist__PTInc_M2CDRad5.h"


cEqAppui_NoDist__PTInc_M2CDRad5::cEqAppui_NoDist__PTInc_M2CDRad5():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,10));
   AddIntRef (cIncIntervale("Orient",10,16));
   AddIntRef (cIncIntervale("Tmp_PTer",16,19));
   Close(false);
}



void cEqAppui_NoDist__PTInc_M2CDRad5::ComputeVal()
{
   double tmp0_ = mCompCoord[10];
   double tmp1_ = mCompCoord[11];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[12];
   double tmp7_ = mCompCoord[16];
   double tmp8_ = mCompCoord[13];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[17];
   double tmp15_ = mCompCoord[14];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[18];
   double tmp18_ = mCompCoord[15];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = -(tmp3_);
   double tmp21_ = tmp4_*tmp12_;
   double tmp22_ = tmp3_*tmp12_;
   double tmp23_ = tmp20_*tmp11_;
   double tmp24_ = tmp21_*tmp13_;
   double tmp25_ = tmp23_+tmp24_;
   double tmp26_ = (tmp25_)*(tmp9_);
   double tmp27_ = tmp4_*tmp11_;
   double tmp28_ = tmp22_*tmp13_;
   double tmp29_ = tmp27_+tmp28_;
   double tmp30_ = (tmp29_)*(tmp16_);
   double tmp31_ = tmp26_+tmp30_;
   double tmp32_ = tmp2_*tmp13_;
   double tmp33_ = tmp32_*(tmp19_);
   double tmp34_ = tmp31_+tmp33_;

  mVal[0] = (tmp4_*tmp2_*(tmp9_)+tmp3_*tmp2_*(tmp16_)+tmp5_*(tmp19_))/(tmp34_)-mLocXIm;

  mVal[1] = ((tmp20_*tmp13_+tmp21_*tmp10_)*(tmp9_)+(tmp4_*tmp13_+tmp22_*tmp10_)*(tmp16_)+tmp2_*tmp10_*(tmp19_))/(tmp34_)-mLocYIm;

}


void cEqAppui_NoDist__PTInc_M2CDRad5::ComputeValDeriv()
{
   double tmp0_ = mCompCoord[10];
   double tmp1_ = mCompCoord[11];
   double tmp2_ = cos(tmp1_);
   double tmp3_ = sin(tmp0_);
   double tmp4_ = cos(tmp0_);
   double tmp5_ = sin(tmp1_);
   double tmp6_ = mCompCoord[12];
   double tmp7_ = mCompCoord[16];
   double tmp8_ = mCompCoord[13];
   double tmp9_ = tmp7_-tmp8_;
   double tmp10_ = sin(tmp6_);
   double tmp11_ = -(tmp10_);
   double tmp12_ = -(tmp5_);
   double tmp13_ = cos(tmp6_);
   double tmp14_ = mCompCoord[17];
   double tmp15_ = mCompCoord[14];
   double tmp16_ = tmp14_-tmp15_;
   double tmp17_ = mCompCoord[18];
   double tmp18_ = mCompCoord[15];
   double tmp19_ = tmp17_-tmp18_;
   double tmp20_ = tmp4_*tmp2_;
   double tmp21_ = -(tmp3_);
   double tmp22_ = tmp21_*tmp11_;
   double tmp23_ = tmp4_*tmp12_;
   double tmp24_ = tmp23_*tmp13_;
   double tmp25_ = tmp22_+tmp24_;
   double tmp26_ = (tmp25_)*(tmp9_);
   double tmp27_ = tmp4_*tmp11_;
   double tmp28_ = tmp3_*tmp12_;
   double tmp29_ = tmp28_*tmp13_;
   double tmp30_ = tmp27_+tmp29_;
   double tmp31_ = (tmp30_)*(tmp16_);
   double tmp32_ = tmp26_+tmp31_;
   double tmp33_ = tmp2_*tmp13_;
   double tmp34_ = tmp33_*(tmp19_);
   double tmp35_ = tmp32_+tmp34_;
   double tmp36_ = tmp20_*(tmp9_);
   double tmp37_ = tmp3_*tmp2_;
   double tmp38_ = tmp37_*(tmp16_);
   double tmp39_ = tmp36_+tmp38_;
   double tmp40_ = tmp5_*(tmp19_);
   double tmp41_ = tmp39_+tmp40_;
   double tmp42_ = -(1);
   double tmp43_ = tmp42_*tmp3_;
   double tmp44_ = tmp42_*tmp5_;
   double tmp45_ = -(tmp2_);
   double tmp46_ = ElSquare(tmp35_);
   double tmp47_ = -(tmp13_);
   double tmp48_ = tmp42_*tmp10_;
   double tmp49_ = -(tmp4_);
   double tmp50_ = tmp43_*tmp12_;
   double tmp51_ = tmp23_*tmp10_;
   double tmp52_ = tmp21_*tmp13_;
   double tmp53_ = tmp52_+tmp51_;
   double tmp54_ = (tmp53_)*(tmp9_);
   double tmp55_ = tmp4_*tmp13_;
   double tmp56_ = tmp28_*tmp10_;
   double tmp57_ = tmp55_+tmp56_;
   double tmp58_ = (tmp57_)*(tmp16_);
   double tmp59_ = tmp54_+tmp58_;
   double tmp60_ = tmp2_*tmp10_;
   double tmp61_ = tmp60_*(tmp19_);
   double tmp62_ = tmp59_+tmp61_;
   double tmp63_ = tmp49_*tmp11_;
   double tmp64_ = tmp50_*tmp13_;
   double tmp65_ = tmp63_+tmp64_;
   double tmp66_ = (tmp65_)*(tmp9_);
   double tmp67_ = tmp43_*tmp11_;
   double tmp68_ = tmp67_+tmp24_;
   double tmp69_ = (tmp68_)*(tmp16_);
   double tmp70_ = tmp66_+tmp69_;
   double tmp71_ = tmp45_*tmp4_;
   double tmp72_ = tmp45_*tmp3_;
   double tmp73_ = tmp71_*tmp13_;
   double tmp74_ = tmp73_*(tmp9_);
   double tmp75_ = tmp72_*tmp13_;
   double tmp76_ = tmp75_*(tmp16_);
   double tmp77_ = tmp74_+tmp76_;
   double tmp78_ = tmp44_*tmp13_;
   double tmp79_ = tmp78_*(tmp19_);
   double tmp80_ = tmp77_+tmp79_;
   double tmp81_ = tmp47_*tmp21_;
   double tmp82_ = tmp48_*tmp23_;
   double tmp83_ = tmp81_+tmp82_;
   double tmp84_ = (tmp83_)*(tmp9_);
   double tmp85_ = tmp47_*tmp4_;
   double tmp86_ = tmp48_*tmp28_;
   double tmp87_ = tmp85_+tmp86_;
   double tmp88_ = (tmp87_)*(tmp16_);
   double tmp89_ = tmp84_+tmp88_;
   double tmp90_ = tmp48_*tmp2_;
   double tmp91_ = tmp90_*(tmp19_);
   double tmp92_ = tmp89_+tmp91_;
   double tmp93_ = tmp42_*(tmp25_);
   double tmp94_ = tmp42_*(tmp30_);
   double tmp95_ = tmp42_*tmp33_;

  mVal[0] = (tmp41_)/(tmp35_)-mLocXIm;

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = 0;
  mCompDer[0][4] = 0;
  mCompDer[0][5] = 0;
  mCompDer[0][6] = 0;
  mCompDer[0][7] = 0;
  mCompDer[0][8] = 0;
  mCompDer[0][9] = 0;
  mCompDer[0][10] = ((tmp43_*tmp2_*(tmp9_)+tmp20_*(tmp16_))*(tmp35_)-(tmp41_)*(tmp70_))/tmp46_;
  mCompDer[0][11] = ((tmp44_*tmp4_*(tmp9_)+tmp44_*tmp3_*(tmp16_)+tmp2_*(tmp19_))*(tmp35_)-(tmp41_)*(tmp80_))/tmp46_;
  mCompDer[0][12] = -((tmp41_)*(tmp92_))/tmp46_;
  mCompDer[0][13] = (tmp42_*tmp20_*(tmp35_)-(tmp41_)*tmp93_)/tmp46_;
  mCompDer[0][14] = (tmp42_*tmp37_*(tmp35_)-(tmp41_)*tmp94_)/tmp46_;
  mCompDer[0][15] = (tmp44_*(tmp35_)-(tmp41_)*tmp95_)/tmp46_;
  mCompDer[0][16] = (tmp20_*(tmp35_)-(tmp41_)*(tmp25_))/tmp46_;
  mCompDer[0][17] = (tmp37_*(tmp35_)-(tmp41_)*(tmp30_))/tmp46_;
  mCompDer[0][18] = (tmp5_*(tmp35_)-(tmp41_)*tmp33_)/tmp46_;
  mVal[1] = (tmp62_)/(tmp35_)-mLocYIm;

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = 0;
  mCompDer[1][4] = 0;
  mCompDer[1][5] = 0;
  mCompDer[1][6] = 0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = 0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = (((tmp49_*tmp13_+tmp50_*tmp10_)*(tmp9_)+(tmp43_*tmp13_+tmp51_)*(tmp16_))*(tmp35_)-(tmp62_)*(tmp70_))/tmp46_;
  mCompDer[1][11] = ((tmp71_*tmp10_*(tmp9_)+tmp72_*tmp10_*(tmp16_)+tmp44_*tmp10_*(tmp19_))*(tmp35_)-(tmp62_)*(tmp80_))/tmp46_;
  mCompDer[1][12] = (((tmp48_*tmp21_+tmp13_*tmp23_)*(tmp9_)+(tmp48_*tmp4_+tmp13_*tmp28_)*(tmp16_)+tmp13_*tmp2_*(tmp19_))*(tmp35_)-(tmp62_)*(tmp92_))/tmp46_;
  mCompDer[1][13] = (tmp42_*(tmp53_)*(tmp35_)-(tmp62_)*tmp93_)/tmp46_;
  mCompDer[1][14] = (tmp42_*(tmp57_)*(tmp35_)-(tmp62_)*tmp94_)/tmp46_;
  mCompDer[1][15] = (tmp42_*tmp60_*(tmp35_)-(tmp62_)*tmp95_)/tmp46_;
  mCompDer[1][16] = ((tmp53_)*(tmp35_)-(tmp62_)*(tmp25_))/tmp46_;
  mCompDer[1][17] = ((tmp57_)*(tmp35_)-(tmp62_)*(tmp30_))/tmp46_;
  mCompDer[1][18] = (tmp60_*(tmp35_)-(tmp62_)*tmp33_)/tmp46_;
}


void cEqAppui_NoDist__PTInc_M2CDRad5::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cEqAppui_NoDist__PTInc_M2CDRad5 Has no Der Sec");
}

void cEqAppui_NoDist__PTInc_M2CDRad5::SetXIm(double aVal){ mLocXIm = aVal;}
void cEqAppui_NoDist__PTInc_M2CDRad5::SetYIm(double aVal){ mLocYIm = aVal;}



double * cEqAppui_NoDist__PTInc_M2CDRad5::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "XIm") return & mLocXIm;
   if (aName == "YIm") return & mLocYIm;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cEqAppui_NoDist__PTInc_M2CDRad5::mTheAuto("cEqAppui_NoDist__PTInc_M2CDRad5",cEqAppui_NoDist__PTInc_M2CDRad5::Alloc);


cElCompiledFonc *  cEqAppui_NoDist__PTInc_M2CDRad5::Alloc()
{  return new cEqAppui_NoDist__PTInc_M2CDRad5();
}


