// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cREgDistDx_Polyn3.h"


cREgDistDx_Polyn3::cREgDistDx_Polyn3():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,17));
   Close(false);
}



void cREgDistDx_Polyn3::ComputeVal()
{
   double tmp0_ = mLocRegDistu1_x - mLocPolyn3_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn3_State_0_0;
   double tmp2_ = mLocRegDistu1_y - mLocPolyn3_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn3_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = mCompCoord[3];
   double tmp7_ = 1 + tmp6_;
   double tmp8_ = mCompCoord[4];
   double tmp9_ = mCompCoord[5];
   double tmp10_ = tmp9_ * 2;
   double tmp11_ = mLocRegDistu2_x - mLocPolyn3_State_1_0;
   double tmp12_ = (tmp11_) / mLocPolyn3_State_0_0;
   double tmp13_ = mCompCoord[6];
   double tmp14_ = mLocRegDistu2_y - mLocPolyn3_State_2_0;
   double tmp15_ = (tmp14_) / mLocPolyn3_State_0_0;
   double tmp16_ = mCompCoord[7];
   double tmp17_ = mCompCoord[9];
   double tmp18_ = (tmp12_) * (tmp12_);
   double tmp19_ = mCompCoord[10];
   double tmp20_ = mCompCoord[11];
   double tmp21_ = (tmp15_) * (tmp15_);
   double tmp22_ = mCompCoord[12];
   double tmp23_ = (tmp1_) * (tmp3_);
   double tmp24_ = tmp4_ * (tmp1_);
   double tmp25_ = (tmp3_) * (tmp1_);
   double tmp26_ = tmp25_ * (tmp1_);
   double tmp27_ = tmp5_ * (tmp1_);
   double tmp28_ = (tmp3_) * tmp5_;
   double tmp29_ = 1 - tmp6_;
   double tmp30_ = (tmp12_) * (tmp15_);
   double tmp31_ = tmp13_ * 2;
   double tmp32_ = mCompCoord[8];
   double tmp33_ = mCompCoord[13];
   double tmp34_ = tmp18_ * (tmp12_);
   double tmp35_ = mCompCoord[14];
   double tmp36_ = (tmp15_) * (tmp12_);
   double tmp37_ = tmp36_ * (tmp12_);
   double tmp38_ = mCompCoord[15];
   double tmp39_ = tmp21_ * (tmp12_);
   double tmp40_ = mCompCoord[16];
   double tmp41_ = (tmp15_) * tmp21_;

  mVal[0] = (mLocPolyn3_State_1_0 + (((tmp7_) * (tmp1_) + tmp8_ * (tmp3_)) - tmp10_ * tmp4_ + tmp13_ * tmp23_ + tmp16_ * tmp5_) * mLocPolyn3_State_0_0 + (tmp17_ * tmp24_ + tmp19_ * tmp26_ + tmp20_ * tmp27_ + tmp22_ * tmp28_) * mLocPolyn3_State_0_0) - (mLocPolyn3_State_1_0 + (((tmp7_) * (tmp12_) + tmp8_ * (tmp15_)) - tmp10_ * tmp18_ + tmp13_ * tmp30_ + tmp16_ * tmp21_) * mLocPolyn3_State_0_0 + (tmp17_ * tmp34_ + tmp19_ * tmp37_ + tmp20_ * tmp39_ + tmp22_ * tmp41_) * mLocPolyn3_State_0_0) - mLocRegDistu3_x;

  mVal[1] = (mLocPolyn3_State_2_0 + (((tmp29_) * (tmp3_) + tmp8_ * (tmp1_) + tmp9_ * tmp23_) - tmp31_ * tmp5_ + tmp32_ * tmp4_) * mLocPolyn3_State_0_0 + (tmp33_ * tmp24_ + tmp35_ * tmp26_ + tmp38_ * tmp27_ + tmp40_ * tmp28_) * mLocPolyn3_State_0_0) - (mLocPolyn3_State_2_0 + (((tmp29_) * (tmp15_) + tmp8_ * (tmp12_) + tmp9_ * tmp30_) - tmp31_ * tmp21_ + tmp32_ * tmp18_) * mLocPolyn3_State_0_0 + (tmp33_ * tmp34_ + tmp35_ * tmp37_ + tmp38_ * tmp39_ + tmp40_ * tmp41_) * mLocPolyn3_State_0_0) - mLocRegDistu3_y;

}


void cREgDistDx_Polyn3::ComputeValDeriv()
{
   double tmp0_ = mLocRegDistu1_x - mLocPolyn3_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn3_State_0_0;
   double tmp2_ = mLocRegDistu1_y - mLocPolyn3_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn3_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = mCompCoord[3];
   double tmp7_ = 1 + tmp6_;
   double tmp8_ = mCompCoord[4];
   double tmp9_ = mCompCoord[5];
   double tmp10_ = tmp9_ * 2;
   double tmp11_ = mLocRegDistu2_x - mLocPolyn3_State_1_0;
   double tmp12_ = (tmp11_) / mLocPolyn3_State_0_0;
   double tmp13_ = mCompCoord[6];
   double tmp14_ = mLocRegDistu2_y - mLocPolyn3_State_2_0;
   double tmp15_ = (tmp14_) / mLocPolyn3_State_0_0;
   double tmp16_ = mCompCoord[7];
   double tmp17_ = mCompCoord[9];
   double tmp18_ = (tmp12_) * (tmp12_);
   double tmp19_ = mCompCoord[10];
   double tmp20_ = mCompCoord[11];
   double tmp21_ = (tmp15_) * (tmp15_);
   double tmp22_ = mCompCoord[12];
   double tmp23_ = (tmp1_) * (tmp3_);
   double tmp24_ = (tmp12_) * (tmp15_);
   double tmp25_ = tmp4_ * (tmp1_);
   double tmp26_ = tmp18_ * (tmp12_);
   double tmp27_ = (tmp3_) * (tmp1_);
   double tmp28_ = tmp27_ * (tmp1_);
   double tmp29_ = (tmp15_) * (tmp12_);
   double tmp30_ = tmp29_ * (tmp12_);
   double tmp31_ = tmp5_ * (tmp1_);
   double tmp32_ = tmp21_ * (tmp12_);
   double tmp33_ = (tmp3_) * tmp5_;
   double tmp34_ = (tmp15_) * tmp21_;
   double tmp35_ = 1 - tmp6_;
   double tmp36_ = tmp13_ * 2;
   double tmp37_ = mCompCoord[8];
   double tmp38_ = mCompCoord[13];
   double tmp39_ = mCompCoord[14];
   double tmp40_ = mCompCoord[15];
   double tmp41_ = mCompCoord[16];
   double tmp42_ = -(1);
   double tmp43_ = (tmp1_) * mLocPolyn3_State_0_0;
   double tmp44_ = (tmp12_) * mLocPolyn3_State_0_0;
   double tmp45_ = tmp43_ - tmp44_;
   double tmp46_ = tmp23_ * mLocPolyn3_State_0_0;
   double tmp47_ = tmp24_ * mLocPolyn3_State_0_0;
   double tmp48_ = tmp46_ - tmp47_;
   double tmp49_ = tmp25_ * mLocPolyn3_State_0_0;
   double tmp50_ = tmp26_ * mLocPolyn3_State_0_0;
   double tmp51_ = tmp49_ - tmp50_;
   double tmp52_ = tmp28_ * mLocPolyn3_State_0_0;
   double tmp53_ = tmp30_ * mLocPolyn3_State_0_0;
   double tmp54_ = tmp52_ - tmp53_;
   double tmp55_ = tmp31_ * mLocPolyn3_State_0_0;
   double tmp56_ = tmp32_ * mLocPolyn3_State_0_0;
   double tmp57_ = tmp55_ - tmp56_;
   double tmp58_ = tmp33_ * mLocPolyn3_State_0_0;
   double tmp59_ = tmp34_ * mLocPolyn3_State_0_0;
   double tmp60_ = tmp58_ - tmp59_;

  mVal[0] = (mLocPolyn3_State_1_0 + (((tmp7_) * (tmp1_) + tmp8_ * (tmp3_)) - tmp10_ * tmp4_ + tmp13_ * tmp23_ + tmp16_ * tmp5_) * mLocPolyn3_State_0_0 + (tmp17_ * tmp25_ + tmp19_ * tmp28_ + tmp20_ * tmp31_ + tmp22_ * tmp33_) * mLocPolyn3_State_0_0) - (mLocPolyn3_State_1_0 + (((tmp7_) * (tmp12_) + tmp8_ * (tmp15_)) - tmp10_ * tmp18_ + tmp13_ * tmp24_ + tmp16_ * tmp21_) * mLocPolyn3_State_0_0 + (tmp17_ * tmp26_ + tmp19_ * tmp30_ + tmp20_ * tmp32_ + tmp22_ * tmp34_) * mLocPolyn3_State_0_0) - mLocRegDistu3_x;

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = tmp45_;
  mCompDer[0][4] = (tmp3_) * mLocPolyn3_State_0_0 - (tmp15_) * mLocPolyn3_State_0_0;
  mCompDer[0][5] = -(2 * tmp4_) * mLocPolyn3_State_0_0 - -(2 * tmp18_) * mLocPolyn3_State_0_0;
  mCompDer[0][6] = tmp48_;
  mCompDer[0][7] = tmp5_ * mLocPolyn3_State_0_0 - tmp21_ * mLocPolyn3_State_0_0;
  mCompDer[0][8] = 0;
  mCompDer[0][9] = tmp51_;
  mCompDer[0][10] = tmp54_;
  mCompDer[0][11] = tmp57_;
  mCompDer[0][12] = tmp60_;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = 0;
  mCompDer[0][16] = 0;
  mVal[1] = (mLocPolyn3_State_2_0 + (((tmp35_) * (tmp3_) + tmp8_ * (tmp1_) + tmp9_ * tmp23_) - tmp36_ * tmp5_ + tmp37_ * tmp4_) * mLocPolyn3_State_0_0 + (tmp38_ * tmp25_ + tmp39_ * tmp28_ + tmp40_ * tmp31_ + tmp41_ * tmp33_) * mLocPolyn3_State_0_0) - (mLocPolyn3_State_2_0 + (((tmp35_) * (tmp15_) + tmp8_ * (tmp12_) + tmp9_ * tmp24_) - tmp36_ * tmp21_ + tmp37_ * tmp18_) * mLocPolyn3_State_0_0 + (tmp38_ * tmp26_ + tmp39_ * tmp30_ + tmp40_ * tmp32_ + tmp41_ * tmp34_) * mLocPolyn3_State_0_0) - mLocRegDistu3_y;

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = tmp42_ * (tmp3_) * mLocPolyn3_State_0_0 - tmp42_ * (tmp15_) * mLocPolyn3_State_0_0;
  mCompDer[1][4] = tmp45_;
  mCompDer[1][5] = tmp48_;
  mCompDer[1][6] = -(2 * tmp5_) * mLocPolyn3_State_0_0 - -(2 * tmp21_) * mLocPolyn3_State_0_0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = tmp4_ * mLocPolyn3_State_0_0 - tmp18_ * mLocPolyn3_State_0_0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = 0;
  mCompDer[1][11] = 0;
  mCompDer[1][12] = 0;
  mCompDer[1][13] = tmp51_;
  mCompDer[1][14] = tmp54_;
  mCompDer[1][15] = tmp57_;
  mCompDer[1][16] = tmp60_;
}


void cREgDistDx_Polyn3::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cREgDistDx_Polyn3 Has no Der Sec");
}

void cREgDistDx_Polyn3::SetPolyn3_State_0_0(double aVal){ mLocPolyn3_State_0_0 = aVal;}
void cREgDistDx_Polyn3::SetPolyn3_State_1_0(double aVal){ mLocPolyn3_State_1_0 = aVal;}
void cREgDistDx_Polyn3::SetPolyn3_State_2_0(double aVal){ mLocPolyn3_State_2_0 = aVal;}
void cREgDistDx_Polyn3::SetRegDistu1_x(double aVal){ mLocRegDistu1_x = aVal;}
void cREgDistDx_Polyn3::SetRegDistu1_y(double aVal){ mLocRegDistu1_y = aVal;}
void cREgDistDx_Polyn3::SetRegDistu2_x(double aVal){ mLocRegDistu2_x = aVal;}
void cREgDistDx_Polyn3::SetRegDistu2_y(double aVal){ mLocRegDistu2_y = aVal;}
void cREgDistDx_Polyn3::SetRegDistu3_x(double aVal){ mLocRegDistu3_x = aVal;}
void cREgDistDx_Polyn3::SetRegDistu3_y(double aVal){ mLocRegDistu3_y = aVal;}



double * cREgDistDx_Polyn3::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Polyn3_State_0_0") return & mLocPolyn3_State_0_0;
   if (aName == "Polyn3_State_1_0") return & mLocPolyn3_State_1_0;
   if (aName == "Polyn3_State_2_0") return & mLocPolyn3_State_2_0;
   if (aName == "RegDistu1_x") return & mLocRegDistu1_x;
   if (aName == "RegDistu1_y") return & mLocRegDistu1_y;
   if (aName == "RegDistu2_x") return & mLocRegDistu2_x;
   if (aName == "RegDistu2_y") return & mLocRegDistu2_y;
   if (aName == "RegDistu3_x") return & mLocRegDistu3_x;
   if (aName == "RegDistu3_y") return & mLocRegDistu3_y;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cREgDistDx_Polyn3::mTheAuto("cREgDistDx_Polyn3",cREgDistDx_Polyn3::Alloc);


cElCompiledFonc *  cREgDistDx_Polyn3::Alloc()
{  return new cREgDistDx_Polyn3();
}


