// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cREgDistDxDy_Polyn5.h"


cREgDistDxDy_Polyn5::cREgDistDxDy_Polyn5():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,39));
   Close(false);
}



void cREgDistDxDy_Polyn5::ComputeVal()
{
   double tmp0_ = mLocRegDistxy1_x - mLocPolyn5_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn5_State_0_0;
   double tmp2_ = mLocRegDistxy1_y - mLocPolyn5_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn5_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = tmp4_ * (tmp1_);
   double tmp7_ = (tmp3_) * (tmp1_);
   double tmp8_ = tmp7_ * (tmp1_);
   double tmp9_ = tmp5_ * (tmp1_);
   double tmp10_ = (tmp3_) * tmp5_;
   double tmp11_ = tmp6_ * (tmp1_);
   double tmp12_ = tmp8_ * (tmp1_);
   double tmp13_ = tmp9_ * (tmp1_);
   double tmp14_ = tmp10_ * (tmp1_);
   double tmp15_ = (tmp3_) * tmp10_;
   double tmp16_ = mCompCoord[3];
   double tmp17_ = 1 + tmp16_;
   double tmp18_ = mCompCoord[4];
   double tmp19_ = mCompCoord[5];
   double tmp20_ = tmp19_ * 2;
   double tmp21_ = mLocRegDistxy2_x - mLocPolyn5_State_1_0;
   double tmp22_ = (tmp21_) / mLocPolyn5_State_0_0;
   double tmp23_ = mCompCoord[6];
   double tmp24_ = mLocRegDistxy2_y - mLocPolyn5_State_2_0;
   double tmp25_ = (tmp24_) / mLocPolyn5_State_0_0;
   double tmp26_ = mCompCoord[7];
   double tmp27_ = mCompCoord[9];
   double tmp28_ = (tmp22_) * (tmp22_);
   double tmp29_ = mCompCoord[10];
   double tmp30_ = mCompCoord[11];
   double tmp31_ = (tmp25_) * (tmp25_);
   double tmp32_ = mCompCoord[12];
   double tmp33_ = mCompCoord[17];
   double tmp34_ = tmp28_ * (tmp22_);
   double tmp35_ = mCompCoord[18];
   double tmp36_ = (tmp25_) * (tmp22_);
   double tmp37_ = tmp36_ * (tmp22_);
   double tmp38_ = mCompCoord[19];
   double tmp39_ = tmp31_ * (tmp22_);
   double tmp40_ = mCompCoord[20];
   double tmp41_ = (tmp25_) * tmp31_;
   double tmp42_ = mCompCoord[21];
   double tmp43_ = mCompCoord[27];
   double tmp44_ = tmp34_ * (tmp22_);
   double tmp45_ = mCompCoord[28];
   double tmp46_ = tmp37_ * (tmp22_);
   double tmp47_ = mCompCoord[29];
   double tmp48_ = tmp39_ * (tmp22_);
   double tmp49_ = mCompCoord[30];
   double tmp50_ = tmp41_ * (tmp22_);
   double tmp51_ = mCompCoord[31];
   double tmp52_ = (tmp25_) * tmp41_;
   double tmp53_ = mCompCoord[32];
   double tmp54_ = mLocRegDistxy3_x - mLocPolyn5_State_1_0;
   double tmp55_ = (tmp54_) / mLocPolyn5_State_0_0;
   double tmp56_ = mLocRegDistxy3_y - mLocPolyn5_State_2_0;
   double tmp57_ = (tmp56_) / mLocPolyn5_State_0_0;
   double tmp58_ = (tmp55_) * (tmp55_);
   double tmp59_ = (tmp57_) * (tmp57_);
   double tmp60_ = tmp58_ * (tmp55_);
   double tmp61_ = (tmp57_) * (tmp55_);
   double tmp62_ = tmp61_ * (tmp55_);
   double tmp63_ = tmp59_ * (tmp55_);
   double tmp64_ = (tmp57_) * tmp59_;
   double tmp65_ = tmp60_ * (tmp55_);
   double tmp66_ = tmp62_ * (tmp55_);
   double tmp67_ = tmp63_ * (tmp55_);
   double tmp68_ = tmp64_ * (tmp55_);
   double tmp69_ = (tmp57_) * tmp64_;
   double tmp70_ = mLocRegDistxy4_x - mLocPolyn5_State_1_0;
   double tmp71_ = (tmp70_) / mLocPolyn5_State_0_0;
   double tmp72_ = mLocRegDistxy4_y - mLocPolyn5_State_2_0;
   double tmp73_ = (tmp72_) / mLocPolyn5_State_0_0;
   double tmp74_ = (tmp71_) * (tmp71_);
   double tmp75_ = (tmp73_) * (tmp73_);
   double tmp76_ = tmp74_ * (tmp71_);
   double tmp77_ = (tmp73_) * (tmp71_);
   double tmp78_ = tmp77_ * (tmp71_);
   double tmp79_ = tmp75_ * (tmp71_);
   double tmp80_ = (tmp73_) * tmp75_;
   double tmp81_ = tmp76_ * (tmp71_);
   double tmp82_ = tmp78_ * (tmp71_);
   double tmp83_ = tmp79_ * (tmp71_);
   double tmp84_ = tmp80_ * (tmp71_);
   double tmp85_ = (tmp73_) * tmp80_;
   double tmp86_ = (tmp1_) * (tmp3_);
   double tmp87_ = tmp11_ * (tmp1_);
   double tmp88_ = tmp12_ * (tmp1_);
   double tmp89_ = tmp13_ * (tmp1_);
   double tmp90_ = tmp14_ * (tmp1_);
   double tmp91_ = tmp15_ * (tmp1_);
   double tmp92_ = (tmp3_) * tmp15_;
   double tmp93_ = 1 - tmp16_;
   double tmp94_ = (tmp22_) * (tmp25_);
   double tmp95_ = tmp23_ * 2;
   double tmp96_ = mCompCoord[8];
   double tmp97_ = mCompCoord[13];
   double tmp98_ = mCompCoord[14];
   double tmp99_ = mCompCoord[15];
   double tmp100_ = mCompCoord[16];
   double tmp101_ = mCompCoord[22];
   double tmp102_ = mCompCoord[23];
   double tmp103_ = mCompCoord[24];
   double tmp104_ = mCompCoord[25];
   double tmp105_ = mCompCoord[26];
   double tmp106_ = mCompCoord[33];
   double tmp107_ = tmp44_ * (tmp22_);
   double tmp108_ = mCompCoord[34];
   double tmp109_ = tmp46_ * (tmp22_);
   double tmp110_ = mCompCoord[35];
   double tmp111_ = tmp48_ * (tmp22_);
   double tmp112_ = mCompCoord[36];
   double tmp113_ = tmp50_ * (tmp22_);
   double tmp114_ = mCompCoord[37];
   double tmp115_ = tmp52_ * (tmp22_);
   double tmp116_ = mCompCoord[38];
   double tmp117_ = (tmp25_) * tmp52_;
   double tmp118_ = (tmp55_) * (tmp57_);
   double tmp119_ = tmp65_ * (tmp55_);
   double tmp120_ = tmp66_ * (tmp55_);
   double tmp121_ = tmp67_ * (tmp55_);
   double tmp122_ = tmp68_ * (tmp55_);
   double tmp123_ = tmp69_ * (tmp55_);
   double tmp124_ = (tmp57_) * tmp69_;
   double tmp125_ = (tmp71_) * (tmp73_);
   double tmp126_ = tmp81_ * (tmp71_);
   double tmp127_ = tmp82_ * (tmp71_);
   double tmp128_ = tmp83_ * (tmp71_);
   double tmp129_ = tmp84_ * (tmp71_);
   double tmp130_ = tmp85_ * (tmp71_);
   double tmp131_ = (tmp73_) * tmp85_;

  mVal[0] = (mLocPolyn5_State_1_0 + (((tmp17_) * (tmp1_) + tmp18_ * (tmp3_)) - tmp20_ * tmp4_ + tmp23_ * tmp86_ + tmp26_ * tmp5_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp6_ + tmp29_ * tmp8_ + tmp30_ * tmp9_ + tmp32_ * tmp10_ + tmp33_ * tmp11_ + tmp35_ * tmp12_ + tmp38_ * tmp13_ + tmp40_ * tmp14_ + tmp42_ * tmp15_ + tmp43_ * tmp87_ + tmp45_ * tmp88_ + tmp47_ * tmp89_ + tmp49_ * tmp90_ + tmp51_ * tmp91_ + tmp53_ * tmp92_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_1_0 + (((tmp17_) * (tmp22_) + tmp18_ * (tmp25_)) - tmp20_ * tmp28_ + tmp23_ * tmp94_ + tmp26_ * tmp31_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp34_ + tmp29_ * tmp37_ + tmp30_ * tmp39_ + tmp32_ * tmp41_ + tmp33_ * tmp44_ + tmp35_ * tmp46_ + tmp38_ * tmp48_ + tmp40_ * tmp50_ + tmp42_ * tmp52_ + tmp43_ * tmp107_ + tmp45_ * tmp109_ + tmp47_ * tmp111_ + tmp49_ * tmp113_ + tmp51_ * tmp115_ + tmp53_ * tmp117_) * mLocPolyn5_State_0_0) - (mLocPolyn5_State_1_0 + (((tmp17_) * (tmp55_) + tmp18_ * (tmp57_)) - tmp20_ * tmp58_ + tmp23_ * tmp118_ + tmp26_ * tmp59_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp60_ + tmp29_ * tmp62_ + tmp30_ * tmp63_ + tmp32_ * tmp64_ + tmp33_ * tmp65_ + tmp35_ * tmp66_ + tmp38_ * tmp67_ + tmp40_ * tmp68_ + tmp42_ * tmp69_ + tmp43_ * tmp119_ + tmp45_ * tmp120_ + tmp47_ * tmp121_ + tmp49_ * tmp122_ + tmp51_ * tmp123_ + tmp53_ * tmp124_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_1_0 + (((tmp17_) * (tmp71_) + tmp18_ * (tmp73_)) - tmp20_ * tmp74_ + tmp23_ * tmp125_ + tmp26_ * tmp75_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp76_ + tmp29_ * tmp78_ + tmp30_ * tmp79_ + tmp32_ * tmp80_ + tmp33_ * tmp81_ + tmp35_ * tmp82_ + tmp38_ * tmp83_ + tmp40_ * tmp84_ + tmp42_ * tmp85_ + tmp43_ * tmp126_ + tmp45_ * tmp127_ + tmp47_ * tmp128_ + tmp49_ * tmp129_ + tmp51_ * tmp130_ + tmp53_ * tmp131_) * mLocPolyn5_State_0_0);

  mVal[1] = (mLocPolyn5_State_2_0 + (((tmp93_) * (tmp3_) + tmp18_ * (tmp1_) + tmp19_ * tmp86_) - tmp95_ * tmp5_ + tmp96_ * tmp4_) * mLocPolyn5_State_0_0 + (tmp97_ * tmp6_ + tmp98_ * tmp8_ + tmp99_ * tmp9_ + tmp100_ * tmp10_ + tmp101_ * tmp11_ + tmp102_ * tmp12_ + tmp103_ * tmp13_ + tmp104_ * tmp14_ + tmp105_ * tmp15_ + tmp106_ * tmp87_ + tmp108_ * tmp88_ + tmp110_ * tmp89_ + tmp112_ * tmp90_ + tmp114_ * tmp91_ + tmp116_ * tmp92_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_2_0 + (((tmp93_) * (tmp25_) + tmp18_ * (tmp22_) + tmp19_ * tmp94_) - tmp95_ * tmp31_ + tmp96_ * tmp28_) * mLocPolyn5_State_0_0 + (tmp97_ * tmp34_ + tmp98_ * tmp37_ + tmp99_ * tmp39_ + tmp100_ * tmp41_ + tmp101_ * tmp44_ + tmp102_ * tmp46_ + tmp103_ * tmp48_ + tmp104_ * tmp50_ + tmp105_ * tmp52_ + tmp106_ * tmp107_ + tmp108_ * tmp109_ + tmp110_ * tmp111_ + tmp112_ * tmp113_ + tmp114_ * tmp115_ + tmp116_ * tmp117_) * mLocPolyn5_State_0_0) - (mLocPolyn5_State_2_0 + (((tmp93_) * (tmp57_) + tmp18_ * (tmp55_) + tmp19_ * tmp118_) - tmp95_ * tmp59_ + tmp96_ * tmp58_) * mLocPolyn5_State_0_0 + (tmp97_ * tmp60_ + tmp98_ * tmp62_ + tmp99_ * tmp63_ + tmp100_ * tmp64_ + tmp101_ * tmp65_ + tmp102_ * tmp66_ + tmp103_ * tmp67_ + tmp104_ * tmp68_ + tmp105_ * tmp69_ + tmp106_ * tmp119_ + tmp108_ * tmp120_ + tmp110_ * tmp121_ + tmp112_ * tmp122_ + tmp114_ * tmp123_ + tmp116_ * tmp124_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_2_0 + (((tmp93_) * (tmp73_) + tmp18_ * (tmp71_) + tmp19_ * tmp125_) - tmp95_ * tmp75_ + tmp96_ * tmp74_) * mLocPolyn5_State_0_0 + (tmp97_ * tmp76_ + tmp98_ * tmp78_ + tmp99_ * tmp79_ + tmp100_ * tmp80_ + tmp101_ * tmp81_ + tmp102_ * tmp82_ + tmp103_ * tmp83_ + tmp104_ * tmp84_ + tmp105_ * tmp85_ + tmp106_ * tmp126_ + tmp108_ * tmp127_ + tmp110_ * tmp128_ + tmp112_ * tmp129_ + tmp114_ * tmp130_ + tmp116_ * tmp131_) * mLocPolyn5_State_0_0);

}


void cREgDistDxDy_Polyn5::ComputeValDeriv()
{
   double tmp0_ = mLocRegDistxy1_x - mLocPolyn5_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn5_State_0_0;
   double tmp2_ = mLocRegDistxy1_y - mLocPolyn5_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn5_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = tmp4_ * (tmp1_);
   double tmp7_ = (tmp3_) * (tmp1_);
   double tmp8_ = tmp7_ * (tmp1_);
   double tmp9_ = tmp5_ * (tmp1_);
   double tmp10_ = (tmp3_) * tmp5_;
   double tmp11_ = tmp6_ * (tmp1_);
   double tmp12_ = tmp8_ * (tmp1_);
   double tmp13_ = tmp9_ * (tmp1_);
   double tmp14_ = tmp10_ * (tmp1_);
   double tmp15_ = (tmp3_) * tmp10_;
   double tmp16_ = mCompCoord[3];
   double tmp17_ = 1 + tmp16_;
   double tmp18_ = mCompCoord[4];
   double tmp19_ = mCompCoord[5];
   double tmp20_ = tmp19_ * 2;
   double tmp21_ = mLocRegDistxy2_x - mLocPolyn5_State_1_0;
   double tmp22_ = (tmp21_) / mLocPolyn5_State_0_0;
   double tmp23_ = mCompCoord[6];
   double tmp24_ = mLocRegDistxy2_y - mLocPolyn5_State_2_0;
   double tmp25_ = (tmp24_) / mLocPolyn5_State_0_0;
   double tmp26_ = mCompCoord[7];
   double tmp27_ = mCompCoord[9];
   double tmp28_ = (tmp22_) * (tmp22_);
   double tmp29_ = mCompCoord[10];
   double tmp30_ = mCompCoord[11];
   double tmp31_ = (tmp25_) * (tmp25_);
   double tmp32_ = mCompCoord[12];
   double tmp33_ = mCompCoord[17];
   double tmp34_ = tmp28_ * (tmp22_);
   double tmp35_ = mCompCoord[18];
   double tmp36_ = (tmp25_) * (tmp22_);
   double tmp37_ = tmp36_ * (tmp22_);
   double tmp38_ = mCompCoord[19];
   double tmp39_ = tmp31_ * (tmp22_);
   double tmp40_ = mCompCoord[20];
   double tmp41_ = (tmp25_) * tmp31_;
   double tmp42_ = mCompCoord[21];
   double tmp43_ = mCompCoord[27];
   double tmp44_ = tmp34_ * (tmp22_);
   double tmp45_ = mCompCoord[28];
   double tmp46_ = tmp37_ * (tmp22_);
   double tmp47_ = mCompCoord[29];
   double tmp48_ = tmp39_ * (tmp22_);
   double tmp49_ = mCompCoord[30];
   double tmp50_ = tmp41_ * (tmp22_);
   double tmp51_ = mCompCoord[31];
   double tmp52_ = (tmp25_) * tmp41_;
   double tmp53_ = mCompCoord[32];
   double tmp54_ = mLocRegDistxy3_x - mLocPolyn5_State_1_0;
   double tmp55_ = (tmp54_) / mLocPolyn5_State_0_0;
   double tmp56_ = mLocRegDistxy3_y - mLocPolyn5_State_2_0;
   double tmp57_ = (tmp56_) / mLocPolyn5_State_0_0;
   double tmp58_ = (tmp55_) * (tmp55_);
   double tmp59_ = (tmp57_) * (tmp57_);
   double tmp60_ = tmp58_ * (tmp55_);
   double tmp61_ = (tmp57_) * (tmp55_);
   double tmp62_ = tmp61_ * (tmp55_);
   double tmp63_ = tmp59_ * (tmp55_);
   double tmp64_ = (tmp57_) * tmp59_;
   double tmp65_ = tmp60_ * (tmp55_);
   double tmp66_ = tmp62_ * (tmp55_);
   double tmp67_ = tmp63_ * (tmp55_);
   double tmp68_ = tmp64_ * (tmp55_);
   double tmp69_ = (tmp57_) * tmp64_;
   double tmp70_ = mLocRegDistxy4_x - mLocPolyn5_State_1_0;
   double tmp71_ = (tmp70_) / mLocPolyn5_State_0_0;
   double tmp72_ = mLocRegDistxy4_y - mLocPolyn5_State_2_0;
   double tmp73_ = (tmp72_) / mLocPolyn5_State_0_0;
   double tmp74_ = (tmp71_) * (tmp71_);
   double tmp75_ = (tmp73_) * (tmp73_);
   double tmp76_ = tmp74_ * (tmp71_);
   double tmp77_ = (tmp73_) * (tmp71_);
   double tmp78_ = tmp77_ * (tmp71_);
   double tmp79_ = tmp75_ * (tmp71_);
   double tmp80_ = (tmp73_) * tmp75_;
   double tmp81_ = tmp76_ * (tmp71_);
   double tmp82_ = tmp78_ * (tmp71_);
   double tmp83_ = tmp79_ * (tmp71_);
   double tmp84_ = tmp80_ * (tmp71_);
   double tmp85_ = (tmp73_) * tmp80_;
   double tmp86_ = (tmp1_) * (tmp3_);
   double tmp87_ = (tmp22_) * (tmp25_);
   double tmp88_ = (tmp55_) * (tmp57_);
   double tmp89_ = (tmp71_) * (tmp73_);
   double tmp90_ = tmp11_ * (tmp1_);
   double tmp91_ = tmp44_ * (tmp22_);
   double tmp92_ = tmp65_ * (tmp55_);
   double tmp93_ = tmp81_ * (tmp71_);
   double tmp94_ = tmp12_ * (tmp1_);
   double tmp95_ = tmp46_ * (tmp22_);
   double tmp96_ = tmp66_ * (tmp55_);
   double tmp97_ = tmp82_ * (tmp71_);
   double tmp98_ = tmp13_ * (tmp1_);
   double tmp99_ = tmp48_ * (tmp22_);
   double tmp100_ = tmp67_ * (tmp55_);
   double tmp101_ = tmp83_ * (tmp71_);
   double tmp102_ = tmp14_ * (tmp1_);
   double tmp103_ = tmp50_ * (tmp22_);
   double tmp104_ = tmp68_ * (tmp55_);
   double tmp105_ = tmp84_ * (tmp71_);
   double tmp106_ = tmp15_ * (tmp1_);
   double tmp107_ = tmp52_ * (tmp22_);
   double tmp108_ = tmp69_ * (tmp55_);
   double tmp109_ = tmp85_ * (tmp71_);
   double tmp110_ = (tmp3_) * tmp15_;
   double tmp111_ = (tmp25_) * tmp52_;
   double tmp112_ = (tmp57_) * tmp69_;
   double tmp113_ = (tmp73_) * tmp85_;
   double tmp114_ = 1 - tmp16_;
   double tmp115_ = tmp23_ * 2;
   double tmp116_ = mCompCoord[8];
   double tmp117_ = mCompCoord[13];
   double tmp118_ = mCompCoord[14];
   double tmp119_ = mCompCoord[15];
   double tmp120_ = mCompCoord[16];
   double tmp121_ = mCompCoord[22];
   double tmp122_ = mCompCoord[23];
   double tmp123_ = mCompCoord[24];
   double tmp124_ = mCompCoord[25];
   double tmp125_ = mCompCoord[26];
   double tmp126_ = mCompCoord[33];
   double tmp127_ = mCompCoord[34];
   double tmp128_ = mCompCoord[35];
   double tmp129_ = mCompCoord[36];
   double tmp130_ = mCompCoord[37];
   double tmp131_ = mCompCoord[38];
   double tmp132_ = -(1);
   double tmp133_ = (tmp1_) * mLocPolyn5_State_0_0;
   double tmp134_ = (tmp22_) * mLocPolyn5_State_0_0;
   double tmp135_ = tmp133_ + tmp134_;
   double tmp136_ = (tmp55_) * mLocPolyn5_State_0_0;
   double tmp137_ = (tmp71_) * mLocPolyn5_State_0_0;
   double tmp138_ = tmp136_ + tmp137_;
   double tmp139_ = (tmp135_) - (tmp138_);
   double tmp140_ = tmp86_ * mLocPolyn5_State_0_0;
   double tmp141_ = tmp87_ * mLocPolyn5_State_0_0;
   double tmp142_ = tmp140_ + tmp141_;
   double tmp143_ = tmp88_ * mLocPolyn5_State_0_0;
   double tmp144_ = tmp89_ * mLocPolyn5_State_0_0;
   double tmp145_ = tmp143_ + tmp144_;
   double tmp146_ = (tmp142_) - (tmp145_);
   double tmp147_ = tmp6_ * mLocPolyn5_State_0_0;
   double tmp148_ = tmp34_ * mLocPolyn5_State_0_0;
   double tmp149_ = tmp147_ + tmp148_;
   double tmp150_ = tmp60_ * mLocPolyn5_State_0_0;
   double tmp151_ = tmp76_ * mLocPolyn5_State_0_0;
   double tmp152_ = tmp150_ + tmp151_;
   double tmp153_ = (tmp149_) - (tmp152_);
   double tmp154_ = tmp8_ * mLocPolyn5_State_0_0;
   double tmp155_ = tmp37_ * mLocPolyn5_State_0_0;
   double tmp156_ = tmp154_ + tmp155_;
   double tmp157_ = tmp62_ * mLocPolyn5_State_0_0;
   double tmp158_ = tmp78_ * mLocPolyn5_State_0_0;
   double tmp159_ = tmp157_ + tmp158_;
   double tmp160_ = (tmp156_) - (tmp159_);
   double tmp161_ = tmp9_ * mLocPolyn5_State_0_0;
   double tmp162_ = tmp39_ * mLocPolyn5_State_0_0;
   double tmp163_ = tmp161_ + tmp162_;
   double tmp164_ = tmp63_ * mLocPolyn5_State_0_0;
   double tmp165_ = tmp79_ * mLocPolyn5_State_0_0;
   double tmp166_ = tmp164_ + tmp165_;
   double tmp167_ = (tmp163_) - (tmp166_);
   double tmp168_ = tmp10_ * mLocPolyn5_State_0_0;
   double tmp169_ = tmp41_ * mLocPolyn5_State_0_0;
   double tmp170_ = tmp168_ + tmp169_;
   double tmp171_ = tmp64_ * mLocPolyn5_State_0_0;
   double tmp172_ = tmp80_ * mLocPolyn5_State_0_0;
   double tmp173_ = tmp171_ + tmp172_;
   double tmp174_ = (tmp170_) - (tmp173_);
   double tmp175_ = tmp11_ * mLocPolyn5_State_0_0;
   double tmp176_ = tmp44_ * mLocPolyn5_State_0_0;
   double tmp177_ = tmp175_ + tmp176_;
   double tmp178_ = tmp65_ * mLocPolyn5_State_0_0;
   double tmp179_ = tmp81_ * mLocPolyn5_State_0_0;
   double tmp180_ = tmp178_ + tmp179_;
   double tmp181_ = (tmp177_) - (tmp180_);
   double tmp182_ = tmp12_ * mLocPolyn5_State_0_0;
   double tmp183_ = tmp46_ * mLocPolyn5_State_0_0;
   double tmp184_ = tmp182_ + tmp183_;
   double tmp185_ = tmp66_ * mLocPolyn5_State_0_0;
   double tmp186_ = tmp82_ * mLocPolyn5_State_0_0;
   double tmp187_ = tmp185_ + tmp186_;
   double tmp188_ = (tmp184_) - (tmp187_);
   double tmp189_ = tmp13_ * mLocPolyn5_State_0_0;
   double tmp190_ = tmp48_ * mLocPolyn5_State_0_0;
   double tmp191_ = tmp189_ + tmp190_;
   double tmp192_ = tmp67_ * mLocPolyn5_State_0_0;
   double tmp193_ = tmp83_ * mLocPolyn5_State_0_0;
   double tmp194_ = tmp192_ + tmp193_;
   double tmp195_ = (tmp191_) - (tmp194_);
   double tmp196_ = tmp14_ * mLocPolyn5_State_0_0;
   double tmp197_ = tmp50_ * mLocPolyn5_State_0_0;
   double tmp198_ = tmp196_ + tmp197_;
   double tmp199_ = tmp68_ * mLocPolyn5_State_0_0;
   double tmp200_ = tmp84_ * mLocPolyn5_State_0_0;
   double tmp201_ = tmp199_ + tmp200_;
   double tmp202_ = (tmp198_) - (tmp201_);
   double tmp203_ = tmp15_ * mLocPolyn5_State_0_0;
   double tmp204_ = tmp52_ * mLocPolyn5_State_0_0;
   double tmp205_ = tmp203_ + tmp204_;
   double tmp206_ = tmp69_ * mLocPolyn5_State_0_0;
   double tmp207_ = tmp85_ * mLocPolyn5_State_0_0;
   double tmp208_ = tmp206_ + tmp207_;
   double tmp209_ = (tmp205_) - (tmp208_);
   double tmp210_ = tmp90_ * mLocPolyn5_State_0_0;
   double tmp211_ = tmp91_ * mLocPolyn5_State_0_0;
   double tmp212_ = tmp210_ + tmp211_;
   double tmp213_ = tmp92_ * mLocPolyn5_State_0_0;
   double tmp214_ = tmp93_ * mLocPolyn5_State_0_0;
   double tmp215_ = tmp213_ + tmp214_;
   double tmp216_ = (tmp212_) - (tmp215_);
   double tmp217_ = tmp94_ * mLocPolyn5_State_0_0;
   double tmp218_ = tmp95_ * mLocPolyn5_State_0_0;
   double tmp219_ = tmp217_ + tmp218_;
   double tmp220_ = tmp96_ * mLocPolyn5_State_0_0;
   double tmp221_ = tmp97_ * mLocPolyn5_State_0_0;
   double tmp222_ = tmp220_ + tmp221_;
   double tmp223_ = (tmp219_) - (tmp222_);
   double tmp224_ = tmp98_ * mLocPolyn5_State_0_0;
   double tmp225_ = tmp99_ * mLocPolyn5_State_0_0;
   double tmp226_ = tmp224_ + tmp225_;
   double tmp227_ = tmp100_ * mLocPolyn5_State_0_0;
   double tmp228_ = tmp101_ * mLocPolyn5_State_0_0;
   double tmp229_ = tmp227_ + tmp228_;
   double tmp230_ = (tmp226_) - (tmp229_);
   double tmp231_ = tmp102_ * mLocPolyn5_State_0_0;
   double tmp232_ = tmp103_ * mLocPolyn5_State_0_0;
   double tmp233_ = tmp231_ + tmp232_;
   double tmp234_ = tmp104_ * mLocPolyn5_State_0_0;
   double tmp235_ = tmp105_ * mLocPolyn5_State_0_0;
   double tmp236_ = tmp234_ + tmp235_;
   double tmp237_ = (tmp233_) - (tmp236_);
   double tmp238_ = tmp106_ * mLocPolyn5_State_0_0;
   double tmp239_ = tmp107_ * mLocPolyn5_State_0_0;
   double tmp240_ = tmp238_ + tmp239_;
   double tmp241_ = tmp108_ * mLocPolyn5_State_0_0;
   double tmp242_ = tmp109_ * mLocPolyn5_State_0_0;
   double tmp243_ = tmp241_ + tmp242_;
   double tmp244_ = (tmp240_) - (tmp243_);
   double tmp245_ = tmp110_ * mLocPolyn5_State_0_0;
   double tmp246_ = tmp111_ * mLocPolyn5_State_0_0;
   double tmp247_ = tmp245_ + tmp246_;
   double tmp248_ = tmp112_ * mLocPolyn5_State_0_0;
   double tmp249_ = tmp113_ * mLocPolyn5_State_0_0;
   double tmp250_ = tmp248_ + tmp249_;
   double tmp251_ = (tmp247_) - (tmp250_);

  mVal[0] = (mLocPolyn5_State_1_0 + (((tmp17_) * (tmp1_) + tmp18_ * (tmp3_)) - tmp20_ * tmp4_ + tmp23_ * tmp86_ + tmp26_ * tmp5_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp6_ + tmp29_ * tmp8_ + tmp30_ * tmp9_ + tmp32_ * tmp10_ + tmp33_ * tmp11_ + tmp35_ * tmp12_ + tmp38_ * tmp13_ + tmp40_ * tmp14_ + tmp42_ * tmp15_ + tmp43_ * tmp90_ + tmp45_ * tmp94_ + tmp47_ * tmp98_ + tmp49_ * tmp102_ + tmp51_ * tmp106_ + tmp53_ * tmp110_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_1_0 + (((tmp17_) * (tmp22_) + tmp18_ * (tmp25_)) - tmp20_ * tmp28_ + tmp23_ * tmp87_ + tmp26_ * tmp31_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp34_ + tmp29_ * tmp37_ + tmp30_ * tmp39_ + tmp32_ * tmp41_ + tmp33_ * tmp44_ + tmp35_ * tmp46_ + tmp38_ * tmp48_ + tmp40_ * tmp50_ + tmp42_ * tmp52_ + tmp43_ * tmp91_ + tmp45_ * tmp95_ + tmp47_ * tmp99_ + tmp49_ * tmp103_ + tmp51_ * tmp107_ + tmp53_ * tmp111_) * mLocPolyn5_State_0_0) - (mLocPolyn5_State_1_0 + (((tmp17_) * (tmp55_) + tmp18_ * (tmp57_)) - tmp20_ * tmp58_ + tmp23_ * tmp88_ + tmp26_ * tmp59_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp60_ + tmp29_ * tmp62_ + tmp30_ * tmp63_ + tmp32_ * tmp64_ + tmp33_ * tmp65_ + tmp35_ * tmp66_ + tmp38_ * tmp67_ + tmp40_ * tmp68_ + tmp42_ * tmp69_ + tmp43_ * tmp92_ + tmp45_ * tmp96_ + tmp47_ * tmp100_ + tmp49_ * tmp104_ + tmp51_ * tmp108_ + tmp53_ * tmp112_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_1_0 + (((tmp17_) * (tmp71_) + tmp18_ * (tmp73_)) - tmp20_ * tmp74_ + tmp23_ * tmp89_ + tmp26_ * tmp75_) * mLocPolyn5_State_0_0 + (tmp27_ * tmp76_ + tmp29_ * tmp78_ + tmp30_ * tmp79_ + tmp32_ * tmp80_ + tmp33_ * tmp81_ + tmp35_ * tmp82_ + tmp38_ * tmp83_ + tmp40_ * tmp84_ + tmp42_ * tmp85_ + tmp43_ * tmp93_ + tmp45_ * tmp97_ + tmp47_ * tmp101_ + tmp49_ * tmp105_ + tmp51_ * tmp109_ + tmp53_ * tmp113_) * mLocPolyn5_State_0_0);

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = tmp139_;
  mCompDer[0][4] = ((tmp3_) * mLocPolyn5_State_0_0 + (tmp25_) * mLocPolyn5_State_0_0) - ((tmp57_) * mLocPolyn5_State_0_0 + (tmp73_) * mLocPolyn5_State_0_0);
  mCompDer[0][5] = (-(2 * tmp4_) * mLocPolyn5_State_0_0 + -(2 * tmp28_) * mLocPolyn5_State_0_0) - (-(2 * tmp58_) * mLocPolyn5_State_0_0 + -(2 * tmp74_) * mLocPolyn5_State_0_0);
  mCompDer[0][6] = tmp146_;
  mCompDer[0][7] = (tmp5_ * mLocPolyn5_State_0_0 + tmp31_ * mLocPolyn5_State_0_0) - (tmp59_ * mLocPolyn5_State_0_0 + tmp75_ * mLocPolyn5_State_0_0);
  mCompDer[0][8] = 0;
  mCompDer[0][9] = tmp153_;
  mCompDer[0][10] = tmp160_;
  mCompDer[0][11] = tmp167_;
  mCompDer[0][12] = tmp174_;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = 0;
  mCompDer[0][16] = 0;
  mCompDer[0][17] = tmp181_;
  mCompDer[0][18] = tmp188_;
  mCompDer[0][19] = tmp195_;
  mCompDer[0][20] = tmp202_;
  mCompDer[0][21] = tmp209_;
  mCompDer[0][22] = 0;
  mCompDer[0][23] = 0;
  mCompDer[0][24] = 0;
  mCompDer[0][25] = 0;
  mCompDer[0][26] = 0;
  mCompDer[0][27] = tmp216_;
  mCompDer[0][28] = tmp223_;
  mCompDer[0][29] = tmp230_;
  mCompDer[0][30] = tmp237_;
  mCompDer[0][31] = tmp244_;
  mCompDer[0][32] = tmp251_;
  mCompDer[0][33] = 0;
  mCompDer[0][34] = 0;
  mCompDer[0][35] = 0;
  mCompDer[0][36] = 0;
  mCompDer[0][37] = 0;
  mCompDer[0][38] = 0;
  mVal[1] = (mLocPolyn5_State_2_0 + (((tmp114_) * (tmp3_) + tmp18_ * (tmp1_) + tmp19_ * tmp86_) - tmp115_ * tmp5_ + tmp116_ * tmp4_) * mLocPolyn5_State_0_0 + (tmp117_ * tmp6_ + tmp118_ * tmp8_ + tmp119_ * tmp9_ + tmp120_ * tmp10_ + tmp121_ * tmp11_ + tmp122_ * tmp12_ + tmp123_ * tmp13_ + tmp124_ * tmp14_ + tmp125_ * tmp15_ + tmp126_ * tmp90_ + tmp127_ * tmp94_ + tmp128_ * tmp98_ + tmp129_ * tmp102_ + tmp130_ * tmp106_ + tmp131_ * tmp110_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_2_0 + (((tmp114_) * (tmp25_) + tmp18_ * (tmp22_) + tmp19_ * tmp87_) - tmp115_ * tmp31_ + tmp116_ * tmp28_) * mLocPolyn5_State_0_0 + (tmp117_ * tmp34_ + tmp118_ * tmp37_ + tmp119_ * tmp39_ + tmp120_ * tmp41_ + tmp121_ * tmp44_ + tmp122_ * tmp46_ + tmp123_ * tmp48_ + tmp124_ * tmp50_ + tmp125_ * tmp52_ + tmp126_ * tmp91_ + tmp127_ * tmp95_ + tmp128_ * tmp99_ + tmp129_ * tmp103_ + tmp130_ * tmp107_ + tmp131_ * tmp111_) * mLocPolyn5_State_0_0) - (mLocPolyn5_State_2_0 + (((tmp114_) * (tmp57_) + tmp18_ * (tmp55_) + tmp19_ * tmp88_) - tmp115_ * tmp59_ + tmp116_ * tmp58_) * mLocPolyn5_State_0_0 + (tmp117_ * tmp60_ + tmp118_ * tmp62_ + tmp119_ * tmp63_ + tmp120_ * tmp64_ + tmp121_ * tmp65_ + tmp122_ * tmp66_ + tmp123_ * tmp67_ + tmp124_ * tmp68_ + tmp125_ * tmp69_ + tmp126_ * tmp92_ + tmp127_ * tmp96_ + tmp128_ * tmp100_ + tmp129_ * tmp104_ + tmp130_ * tmp108_ + tmp131_ * tmp112_) * mLocPolyn5_State_0_0 + mLocPolyn5_State_2_0 + (((tmp114_) * (tmp73_) + tmp18_ * (tmp71_) + tmp19_ * tmp89_) - tmp115_ * tmp75_ + tmp116_ * tmp74_) * mLocPolyn5_State_0_0 + (tmp117_ * tmp76_ + tmp118_ * tmp78_ + tmp119_ * tmp79_ + tmp120_ * tmp80_ + tmp121_ * tmp81_ + tmp122_ * tmp82_ + tmp123_ * tmp83_ + tmp124_ * tmp84_ + tmp125_ * tmp85_ + tmp126_ * tmp93_ + tmp127_ * tmp97_ + tmp128_ * tmp101_ + tmp129_ * tmp105_ + tmp130_ * tmp109_ + tmp131_ * tmp113_) * mLocPolyn5_State_0_0);

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = (tmp132_ * (tmp3_) * mLocPolyn5_State_0_0 + tmp132_ * (tmp25_) * mLocPolyn5_State_0_0) - (tmp132_ * (tmp57_) * mLocPolyn5_State_0_0 + tmp132_ * (tmp73_) * mLocPolyn5_State_0_0);
  mCompDer[1][4] = tmp139_;
  mCompDer[1][5] = tmp146_;
  mCompDer[1][6] = (-(2 * tmp5_) * mLocPolyn5_State_0_0 + -(2 * tmp31_) * mLocPolyn5_State_0_0) - (-(2 * tmp59_) * mLocPolyn5_State_0_0 + -(2 * tmp75_) * mLocPolyn5_State_0_0);
  mCompDer[1][7] = 0;
  mCompDer[1][8] = (tmp4_ * mLocPolyn5_State_0_0 + tmp28_ * mLocPolyn5_State_0_0) - (tmp58_ * mLocPolyn5_State_0_0 + tmp74_ * mLocPolyn5_State_0_0);
  mCompDer[1][9] = 0;
  mCompDer[1][10] = 0;
  mCompDer[1][11] = 0;
  mCompDer[1][12] = 0;
  mCompDer[1][13] = tmp153_;
  mCompDer[1][14] = tmp160_;
  mCompDer[1][15] = tmp167_;
  mCompDer[1][16] = tmp174_;
  mCompDer[1][17] = 0;
  mCompDer[1][18] = 0;
  mCompDer[1][19] = 0;
  mCompDer[1][20] = 0;
  mCompDer[1][21] = 0;
  mCompDer[1][22] = tmp181_;
  mCompDer[1][23] = tmp188_;
  mCompDer[1][24] = tmp195_;
  mCompDer[1][25] = tmp202_;
  mCompDer[1][26] = tmp209_;
  mCompDer[1][27] = 0;
  mCompDer[1][28] = 0;
  mCompDer[1][29] = 0;
  mCompDer[1][30] = 0;
  mCompDer[1][31] = 0;
  mCompDer[1][32] = 0;
  mCompDer[1][33] = tmp216_;
  mCompDer[1][34] = tmp223_;
  mCompDer[1][35] = tmp230_;
  mCompDer[1][36] = tmp237_;
  mCompDer[1][37] = tmp244_;
  mCompDer[1][38] = tmp251_;
}


void cREgDistDxDy_Polyn5::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cREgDistDxDy_Polyn5 Has no Der Sec");
}

void cREgDistDxDy_Polyn5::SetPolyn5_State_0_0(double aVal){ mLocPolyn5_State_0_0 = aVal;}
void cREgDistDxDy_Polyn5::SetPolyn5_State_1_0(double aVal){ mLocPolyn5_State_1_0 = aVal;}
void cREgDistDxDy_Polyn5::SetPolyn5_State_2_0(double aVal){ mLocPolyn5_State_2_0 = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy1_x(double aVal){ mLocRegDistxy1_x = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy1_y(double aVal){ mLocRegDistxy1_y = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy2_x(double aVal){ mLocRegDistxy2_x = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy2_y(double aVal){ mLocRegDistxy2_y = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy3_x(double aVal){ mLocRegDistxy3_x = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy3_y(double aVal){ mLocRegDistxy3_y = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy4_x(double aVal){ mLocRegDistxy4_x = aVal;}
void cREgDistDxDy_Polyn5::SetRegDistxy4_y(double aVal){ mLocRegDistxy4_y = aVal;}



double * cREgDistDxDy_Polyn5::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Polyn5_State_0_0") return & mLocPolyn5_State_0_0;
   if (aName == "Polyn5_State_1_0") return & mLocPolyn5_State_1_0;
   if (aName == "Polyn5_State_2_0") return & mLocPolyn5_State_2_0;
   if (aName == "RegDistxy1_x") return & mLocRegDistxy1_x;
   if (aName == "RegDistxy1_y") return & mLocRegDistxy1_y;
   if (aName == "RegDistxy2_x") return & mLocRegDistxy2_x;
   if (aName == "RegDistxy2_y") return & mLocRegDistxy2_y;
   if (aName == "RegDistxy3_x") return & mLocRegDistxy3_x;
   if (aName == "RegDistxy3_y") return & mLocRegDistxy3_y;
   if (aName == "RegDistxy4_x") return & mLocRegDistxy4_x;
   if (aName == "RegDistxy4_y") return & mLocRegDistxy4_y;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cREgDistDxDy_Polyn5::mTheAuto("cREgDistDxDy_Polyn5",cREgDistDxDy_Polyn5::Alloc);


cElCompiledFonc *  cREgDistDxDy_Polyn5::Alloc()
{  return new cREgDistDxDy_Polyn5();
}


