// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cREgDistDxDy_DCBrown.h"


cREgDistDxDy_DCBrown::cREgDistDxDy_DCBrown():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,17));
   Close(false);
}



void cREgDistDxDy_DCBrown::ComputeVal()
{
   double tmp0_ = mLocRegDistxy1_y * mLocRegDistxy1_y;
   double tmp1_ = mLocRegDistxy1_x * mLocRegDistxy1_x;
   double tmp2_ = tmp1_ * tmp0_;
   double tmp3_ = mCompCoord[3];
   double tmp4_ = 1 + tmp3_;
   double tmp5_ = mCompCoord[4];
   double tmp6_ = mCompCoord[5];
   double tmp7_ = mCompCoord[6];
   double tmp8_ = mCompCoord[7];
   double tmp9_ = mCompCoord[8];
   double tmp10_ = mLocRegDistxy2_y * mLocRegDistxy2_y;
   double tmp11_ = mCompCoord[9];
   double tmp12_ = mLocRegDistxy2_x * mLocRegDistxy2_x;
   double tmp13_ = mCompCoord[15];
   double tmp14_ = tmp12_ * tmp10_;
   double tmp15_ = mCompCoord[16];
   double tmp16_ = mLocRegDistxy3_y * mLocRegDistxy3_y;
   double tmp17_ = mLocRegDistxy3_x * mLocRegDistxy3_x;
   double tmp18_ = tmp17_ * tmp16_;
   double tmp19_ = mLocRegDistxy4_y * mLocRegDistxy4_y;
   double tmp20_ = mLocRegDistxy4_x * mLocRegDistxy4_x;
   double tmp21_ = tmp20_ * tmp19_;
   double tmp22_ = mLocRegDistxy1_x * mLocRegDistxy1_y;
   double tmp23_ = tmp1_ * mLocRegDistxy1_y;
   double tmp24_ = mLocRegDistxy1_x * tmp0_;
   double tmp25_ = tmp1_ + tmp0_;
   double tmp26_ = mCompCoord[10];
   double tmp27_ = mLocRegDistxy2_x * mLocRegDistxy2_y;
   double tmp28_ = mCompCoord[11];
   double tmp29_ = mCompCoord[12];
   double tmp30_ = tmp12_ * mLocRegDistxy2_y;
   double tmp31_ = mCompCoord[13];
   double tmp32_ = mLocRegDistxy2_x * tmp10_;
   double tmp33_ = mCompCoord[14];
   double tmp34_ = tmp12_ + tmp10_;
   double tmp35_ = mLocRegDistxy3_x * mLocRegDistxy3_y;
   double tmp36_ = tmp17_ * mLocRegDistxy3_y;
   double tmp37_ = mLocRegDistxy3_x * tmp16_;
   double tmp38_ = tmp17_ + tmp16_;
   double tmp39_ = mLocRegDistxy4_x * mLocRegDistxy4_y;
   double tmp40_ = tmp20_ * mLocRegDistxy4_y;
   double tmp41_ = mLocRegDistxy4_x * tmp19_;
   double tmp42_ = tmp20_ + tmp19_;

  mVal[0] = ((tmp4_) * mLocRegDistxy1_x + tmp5_ * mLocRegDistxy1_y + tmp6_ * tmp22_ + tmp7_ * tmp0_ + tmp8_ * tmp23_ + tmp9_ * tmp24_ + tmp11_ * tmp2_ + tmp13_ * (mLocRegDistxy1_x / mLocDCBrown_State_0_0) * tmp2_ + tmp15_ * mLocRegDistxy1_x * (tmp25_) + (tmp4_) * mLocRegDistxy2_x + tmp5_ * mLocRegDistxy2_y + tmp6_ * tmp27_ + tmp7_ * tmp10_ + tmp8_ * tmp30_ + tmp9_ * tmp32_ + tmp11_ * tmp14_ + tmp13_ * (mLocRegDistxy2_x / mLocDCBrown_State_0_0) * tmp14_ + tmp15_ * mLocRegDistxy2_x * (tmp34_)) - ((tmp4_) * mLocRegDistxy3_x + tmp5_ * mLocRegDistxy3_y + tmp6_ * tmp35_ + tmp7_ * tmp16_ + tmp8_ * tmp36_ + tmp9_ * tmp37_ + tmp11_ * tmp18_ + tmp13_ * (mLocRegDistxy3_x / mLocDCBrown_State_0_0) * tmp18_ + tmp15_ * mLocRegDistxy3_x * (tmp38_) + (tmp4_) * mLocRegDistxy4_x + tmp5_ * mLocRegDistxy4_y + tmp6_ * tmp39_ + tmp7_ * tmp19_ + tmp8_ * tmp40_ + tmp9_ * tmp41_ + tmp11_ * tmp21_ + tmp13_ * (mLocRegDistxy4_x / mLocDCBrown_State_0_0) * tmp21_ + tmp15_ * mLocRegDistxy4_x * (tmp42_));

  mVal[1] = (mLocRegDistxy1_y + tmp26_ * tmp22_ + tmp28_ * tmp1_ + tmp29_ * tmp23_ + tmp31_ * tmp24_ + tmp33_ * tmp2_ + tmp13_ * (mLocRegDistxy1_y / mLocDCBrown_State_0_0) * tmp2_ + tmp15_ * mLocRegDistxy1_y * (tmp25_) + mLocRegDistxy2_y + tmp26_ * tmp27_ + tmp28_ * tmp12_ + tmp29_ * tmp30_ + tmp31_ * tmp32_ + tmp33_ * tmp14_ + tmp13_ * (mLocRegDistxy2_y / mLocDCBrown_State_0_0) * tmp14_ + tmp15_ * mLocRegDistxy2_y * (tmp34_)) - (mLocRegDistxy3_y + tmp26_ * tmp35_ + tmp28_ * tmp17_ + tmp29_ * tmp36_ + tmp31_ * tmp37_ + tmp33_ * tmp18_ + tmp13_ * (mLocRegDistxy3_y / mLocDCBrown_State_0_0) * tmp18_ + tmp15_ * mLocRegDistxy3_y * (tmp38_) + mLocRegDistxy4_y + tmp26_ * tmp39_ + tmp28_ * tmp20_ + tmp29_ * tmp40_ + tmp31_ * tmp41_ + tmp33_ * tmp21_ + tmp13_ * (mLocRegDistxy4_y / mLocDCBrown_State_0_0) * tmp21_ + tmp15_ * mLocRegDistxy4_y * (tmp42_));

}


void cREgDistDxDy_DCBrown::ComputeValDeriv()
{
   double tmp0_ = mLocRegDistxy1_y * mLocRegDistxy1_y;
   double tmp1_ = mLocRegDistxy1_x * mLocRegDistxy1_x;
   double tmp2_ = tmp1_ * tmp0_;
   double tmp3_ = mCompCoord[3];
   double tmp4_ = 1 + tmp3_;
   double tmp5_ = mCompCoord[4];
   double tmp6_ = mCompCoord[5];
   double tmp7_ = mCompCoord[6];
   double tmp8_ = mCompCoord[7];
   double tmp9_ = mCompCoord[8];
   double tmp10_ = mLocRegDistxy2_y * mLocRegDistxy2_y;
   double tmp11_ = mCompCoord[9];
   double tmp12_ = mLocRegDistxy2_x * mLocRegDistxy2_x;
   double tmp13_ = mCompCoord[15];
   double tmp14_ = tmp12_ * tmp10_;
   double tmp15_ = mCompCoord[16];
   double tmp16_ = mLocRegDistxy3_y * mLocRegDistxy3_y;
   double tmp17_ = mLocRegDistxy3_x * mLocRegDistxy3_x;
   double tmp18_ = tmp17_ * tmp16_;
   double tmp19_ = mLocRegDistxy4_y * mLocRegDistxy4_y;
   double tmp20_ = mLocRegDistxy4_x * mLocRegDistxy4_x;
   double tmp21_ = tmp20_ * tmp19_;
   double tmp22_ = mLocRegDistxy1_x * mLocRegDistxy1_y;
   double tmp23_ = mLocRegDistxy2_x * mLocRegDistxy2_y;
   double tmp24_ = mLocRegDistxy3_x * mLocRegDistxy3_y;
   double tmp25_ = mLocRegDistxy4_x * mLocRegDistxy4_y;
   double tmp26_ = tmp1_ * mLocRegDistxy1_y;
   double tmp27_ = tmp12_ * mLocRegDistxy2_y;
   double tmp28_ = tmp17_ * mLocRegDistxy3_y;
   double tmp29_ = tmp20_ * mLocRegDistxy4_y;
   double tmp30_ = mLocRegDistxy1_x * tmp0_;
   double tmp31_ = mLocRegDistxy2_x * tmp10_;
   double tmp32_ = mLocRegDistxy3_x * tmp16_;
   double tmp33_ = mLocRegDistxy4_x * tmp19_;
   double tmp34_ = mLocRegDistxy1_x / mLocDCBrown_State_0_0;
   double tmp35_ = mLocRegDistxy2_x / mLocDCBrown_State_0_0;
   double tmp36_ = mLocRegDistxy3_x / mLocDCBrown_State_0_0;
   double tmp37_ = mLocRegDistxy4_x / mLocDCBrown_State_0_0;
   double tmp38_ = tmp1_ + tmp0_;
   double tmp39_ = tmp12_ + tmp10_;
   double tmp40_ = tmp17_ + tmp16_;
   double tmp41_ = tmp20_ + tmp19_;
   double tmp42_ = mCompCoord[10];
   double tmp43_ = mCompCoord[11];
   double tmp44_ = mCompCoord[12];
   double tmp45_ = mCompCoord[13];
   double tmp46_ = mCompCoord[14];
   double tmp47_ = tmp22_ + tmp23_;
   double tmp48_ = tmp24_ + tmp25_;
   double tmp49_ = (tmp47_) - (tmp48_);
   double tmp50_ = tmp26_ + tmp27_;
   double tmp51_ = tmp28_ + tmp29_;
   double tmp52_ = (tmp50_) - (tmp51_);
   double tmp53_ = tmp30_ + tmp31_;
   double tmp54_ = tmp32_ + tmp33_;
   double tmp55_ = (tmp53_) - (tmp54_);
   double tmp56_ = tmp2_ + tmp14_;
   double tmp57_ = tmp18_ + tmp21_;
   double tmp58_ = (tmp56_) - (tmp57_);
   double tmp59_ = mLocRegDistxy1_y / mLocDCBrown_State_0_0;
   double tmp60_ = mLocRegDistxy2_y / mLocDCBrown_State_0_0;
   double tmp61_ = mLocRegDistxy3_y / mLocDCBrown_State_0_0;
   double tmp62_ = mLocRegDistxy4_y / mLocDCBrown_State_0_0;

  mVal[0] = ((tmp4_) * mLocRegDistxy1_x + tmp5_ * mLocRegDistxy1_y + tmp6_ * tmp22_ + tmp7_ * tmp0_ + tmp8_ * tmp26_ + tmp9_ * tmp30_ + tmp11_ * tmp2_ + tmp13_ * (tmp34_) * tmp2_ + tmp15_ * mLocRegDistxy1_x * (tmp38_) + (tmp4_) * mLocRegDistxy2_x + tmp5_ * mLocRegDistxy2_y + tmp6_ * tmp23_ + tmp7_ * tmp10_ + tmp8_ * tmp27_ + tmp9_ * tmp31_ + tmp11_ * tmp14_ + tmp13_ * (tmp35_) * tmp14_ + tmp15_ * mLocRegDistxy2_x * (tmp39_)) - ((tmp4_) * mLocRegDistxy3_x + tmp5_ * mLocRegDistxy3_y + tmp6_ * tmp24_ + tmp7_ * tmp16_ + tmp8_ * tmp28_ + tmp9_ * tmp32_ + tmp11_ * tmp18_ + tmp13_ * (tmp36_) * tmp18_ + tmp15_ * mLocRegDistxy3_x * (tmp40_) + (tmp4_) * mLocRegDistxy4_x + tmp5_ * mLocRegDistxy4_y + tmp6_ * tmp25_ + tmp7_ * tmp19_ + tmp8_ * tmp29_ + tmp9_ * tmp33_ + tmp11_ * tmp21_ + tmp13_ * (tmp37_) * tmp21_ + tmp15_ * mLocRegDistxy4_x * (tmp41_));

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = (mLocRegDistxy1_x + mLocRegDistxy2_x) - (mLocRegDistxy3_x + mLocRegDistxy4_x);
  mCompDer[0][4] = (mLocRegDistxy1_y + mLocRegDistxy2_y) - (mLocRegDistxy3_y + mLocRegDistxy4_y);
  mCompDer[0][5] = tmp49_;
  mCompDer[0][6] = (tmp0_ + tmp10_) - (tmp16_ + tmp19_);
  mCompDer[0][7] = tmp52_;
  mCompDer[0][8] = tmp55_;
  mCompDer[0][9] = tmp58_;
  mCompDer[0][10] = 0;
  mCompDer[0][11] = 0;
  mCompDer[0][12] = 0;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = ((tmp34_) * tmp2_ + (tmp35_) * tmp14_) - ((tmp36_) * tmp18_ + (tmp37_) * tmp21_);
  mCompDer[0][16] = (mLocRegDistxy1_x * (tmp38_) + mLocRegDistxy2_x * (tmp39_)) - (mLocRegDistxy3_x * (tmp40_) + mLocRegDistxy4_x * (tmp41_));
  mVal[1] = (mLocRegDistxy1_y + tmp42_ * tmp22_ + tmp43_ * tmp1_ + tmp44_ * tmp26_ + tmp45_ * tmp30_ + tmp46_ * tmp2_ + tmp13_ * (tmp59_) * tmp2_ + tmp15_ * mLocRegDistxy1_y * (tmp38_) + mLocRegDistxy2_y + tmp42_ * tmp23_ + tmp43_ * tmp12_ + tmp44_ * tmp27_ + tmp45_ * tmp31_ + tmp46_ * tmp14_ + tmp13_ * (tmp60_) * tmp14_ + tmp15_ * mLocRegDistxy2_y * (tmp39_)) - (mLocRegDistxy3_y + tmp42_ * tmp24_ + tmp43_ * tmp17_ + tmp44_ * tmp28_ + tmp45_ * tmp32_ + tmp46_ * tmp18_ + tmp13_ * (tmp61_) * tmp18_ + tmp15_ * mLocRegDistxy3_y * (tmp40_) + mLocRegDistxy4_y + tmp42_ * tmp25_ + tmp43_ * tmp20_ + tmp44_ * tmp29_ + tmp45_ * tmp33_ + tmp46_ * tmp21_ + tmp13_ * (tmp62_) * tmp21_ + tmp15_ * mLocRegDistxy4_y * (tmp41_));

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = 0;
  mCompDer[1][4] = 0;
  mCompDer[1][5] = 0;
  mCompDer[1][6] = 0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = 0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = tmp49_;
  mCompDer[1][11] = (tmp1_ + tmp12_) - (tmp17_ + tmp20_);
  mCompDer[1][12] = tmp52_;
  mCompDer[1][13] = tmp55_;
  mCompDer[1][14] = tmp58_;
  mCompDer[1][15] = ((tmp59_) * tmp2_ + (tmp60_) * tmp14_) - ((tmp61_) * tmp18_ + (tmp62_) * tmp21_);
  mCompDer[1][16] = (mLocRegDistxy1_y * (tmp38_) + mLocRegDistxy2_y * (tmp39_)) - (mLocRegDistxy3_y * (tmp40_) + mLocRegDistxy4_y * (tmp41_));
}


void cREgDistDxDy_DCBrown::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cREgDistDxDy_DCBrown Has no Der Sec");
}

void cREgDistDxDy_DCBrown::SetDCBrown_State_0_0(double aVal){ mLocDCBrown_State_0_0 = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy1_x(double aVal){ mLocRegDistxy1_x = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy1_y(double aVal){ mLocRegDistxy1_y = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy2_x(double aVal){ mLocRegDistxy2_x = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy2_y(double aVal){ mLocRegDistxy2_y = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy3_x(double aVal){ mLocRegDistxy3_x = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy3_y(double aVal){ mLocRegDistxy3_y = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy4_x(double aVal){ mLocRegDistxy4_x = aVal;}
void cREgDistDxDy_DCBrown::SetRegDistxy4_y(double aVal){ mLocRegDistxy4_y = aVal;}



double * cREgDistDxDy_DCBrown::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "DCBrown_State_0_0") return & mLocDCBrown_State_0_0;
   if (aName == "RegDistxy1_x") return & mLocRegDistxy1_x;
   if (aName == "RegDistxy1_y") return & mLocRegDistxy1_y;
   if (aName == "RegDistxy2_x") return & mLocRegDistxy2_x;
   if (aName == "RegDistxy2_y") return & mLocRegDistxy2_y;
   if (aName == "RegDistxy3_x") return & mLocRegDistxy3_x;
   if (aName == "RegDistxy3_y") return & mLocRegDistxy3_y;
   if (aName == "RegDistxy4_x") return & mLocRegDistxy4_x;
   if (aName == "RegDistxy4_y") return & mLocRegDistxy4_y;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cREgDistDxDy_DCBrown::mTheAuto("cREgDistDxDy_DCBrown",cREgDistDxDy_DCBrown::Alloc);


cElCompiledFonc *  cREgDistDxDy_DCBrown::Alloc()
{  return new cREgDistDxDy_DCBrown();
}


