// File Automatically generated by eLiSe
#include "StdAfx.h"
#include "cREgDistVal_Polyn6.h"


cREgDistVal_Polyn6::cREgDistVal_Polyn6():
    cElCompiledFonc(2)
{
   AddIntRef (cIncIntervale("Intr",0,53));
   Close(false);
}



void cREgDistVal_Polyn6::ComputeVal()
{
   double tmp0_ = mLocRegDistValP1_x - mLocPolyn6_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn6_State_0_0;
   double tmp2_ = mLocRegDistValP1_y - mLocPolyn6_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn6_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = tmp4_ * (tmp1_);
   double tmp7_ = (tmp3_) * (tmp1_);
   double tmp8_ = tmp7_ * (tmp1_);
   double tmp9_ = tmp5_ * (tmp1_);
   double tmp10_ = (tmp3_) * tmp5_;
   double tmp11_ = tmp6_ * (tmp1_);
   double tmp12_ = tmp8_ * (tmp1_);
   double tmp13_ = tmp9_ * (tmp1_);
   double tmp14_ = tmp10_ * (tmp1_);
   double tmp15_ = (tmp3_) * tmp10_;
   double tmp16_ = tmp11_ * (tmp1_);
   double tmp17_ = tmp12_ * (tmp1_);
   double tmp18_ = tmp13_ * (tmp1_);
   double tmp19_ = tmp14_ * (tmp1_);
   double tmp20_ = tmp15_ * (tmp1_);
   double tmp21_ = (tmp3_) * tmp15_;
   double tmp22_ = mCompCoord[3];
   double tmp23_ = mCompCoord[4];
   double tmp24_ = mCompCoord[5];
   double tmp25_ = (tmp1_) * (tmp3_);
   double tmp26_ = mCompCoord[6];
   double tmp27_ = tmp16_ * (tmp1_);
   double tmp28_ = tmp17_ * (tmp1_);
   double tmp29_ = tmp18_ * (tmp1_);
   double tmp30_ = tmp19_ * (tmp1_);
   double tmp31_ = tmp20_ * (tmp1_);
   double tmp32_ = tmp21_ * (tmp1_);
   double tmp33_ = (tmp3_) * tmp21_;

  mVal[0] = (mLocPolyn6_State_1_0 + (((1 + tmp22_) * (tmp1_) + tmp23_ * (tmp3_)) - tmp24_ * 2 * tmp4_ + tmp26_ * tmp25_ + mCompCoord[7] * tmp5_) * mLocPolyn6_State_0_0 + (mCompCoord[9] * tmp6_ + mCompCoord[10] * tmp8_ + mCompCoord[11] * tmp9_ + mCompCoord[12] * tmp10_ + mCompCoord[17] * tmp11_ + mCompCoord[18] * tmp12_ + mCompCoord[19] * tmp13_ + mCompCoord[20] * tmp14_ + mCompCoord[21] * tmp15_ + mCompCoord[27] * tmp16_ + mCompCoord[28] * tmp17_ + mCompCoord[29] * tmp18_ + mCompCoord[30] * tmp19_ + mCompCoord[31] * tmp20_ + mCompCoord[32] * tmp21_ + mCompCoord[39] * tmp27_ + mCompCoord[40] * tmp28_ + mCompCoord[41] * tmp29_ + mCompCoord[42] * tmp30_ + mCompCoord[43] * tmp31_ + mCompCoord[44] * tmp32_ + mCompCoord[45] * tmp33_) * mLocPolyn6_State_0_0) - mLocRegDistKnownVal_x;

  mVal[1] = (mLocPolyn6_State_2_0 + (((1 - tmp22_) * (tmp3_) + tmp23_ * (tmp1_) + tmp24_ * tmp25_) - tmp26_ * 2 * tmp5_ + mCompCoord[8] * tmp4_) * mLocPolyn6_State_0_0 + (mCompCoord[13] * tmp6_ + mCompCoord[14] * tmp8_ + mCompCoord[15] * tmp9_ + mCompCoord[16] * tmp10_ + mCompCoord[22] * tmp11_ + mCompCoord[23] * tmp12_ + mCompCoord[24] * tmp13_ + mCompCoord[25] * tmp14_ + mCompCoord[26] * tmp15_ + mCompCoord[33] * tmp16_ + mCompCoord[34] * tmp17_ + mCompCoord[35] * tmp18_ + mCompCoord[36] * tmp19_ + mCompCoord[37] * tmp20_ + mCompCoord[38] * tmp21_ + mCompCoord[46] * tmp27_ + mCompCoord[47] * tmp28_ + mCompCoord[48] * tmp29_ + mCompCoord[49] * tmp30_ + mCompCoord[50] * tmp31_ + mCompCoord[51] * tmp32_ + mCompCoord[52] * tmp33_) * mLocPolyn6_State_0_0) - mLocRegDistKnownVal_y;

}


void cREgDistVal_Polyn6::ComputeValDeriv()
{
   double tmp0_ = mLocRegDistValP1_x - mLocPolyn6_State_1_0;
   double tmp1_ = (tmp0_) / mLocPolyn6_State_0_0;
   double tmp2_ = mLocRegDistValP1_y - mLocPolyn6_State_2_0;
   double tmp3_ = (tmp2_) / mLocPolyn6_State_0_0;
   double tmp4_ = (tmp1_) * (tmp1_);
   double tmp5_ = (tmp3_) * (tmp3_);
   double tmp6_ = tmp4_ * (tmp1_);
   double tmp7_ = (tmp3_) * (tmp1_);
   double tmp8_ = tmp7_ * (tmp1_);
   double tmp9_ = tmp5_ * (tmp1_);
   double tmp10_ = (tmp3_) * tmp5_;
   double tmp11_ = tmp6_ * (tmp1_);
   double tmp12_ = tmp8_ * (tmp1_);
   double tmp13_ = tmp9_ * (tmp1_);
   double tmp14_ = tmp10_ * (tmp1_);
   double tmp15_ = (tmp3_) * tmp10_;
   double tmp16_ = tmp11_ * (tmp1_);
   double tmp17_ = tmp12_ * (tmp1_);
   double tmp18_ = tmp13_ * (tmp1_);
   double tmp19_ = tmp14_ * (tmp1_);
   double tmp20_ = tmp15_ * (tmp1_);
   double tmp21_ = (tmp3_) * tmp15_;
   double tmp22_ = (tmp1_) * (tmp3_);
   double tmp23_ = tmp16_ * (tmp1_);
   double tmp24_ = tmp17_ * (tmp1_);
   double tmp25_ = tmp18_ * (tmp1_);
   double tmp26_ = tmp19_ * (tmp1_);
   double tmp27_ = tmp20_ * (tmp1_);
   double tmp28_ = tmp21_ * (tmp1_);
   double tmp29_ = (tmp3_) * tmp21_;
   double tmp30_ = mCompCoord[3];
   double tmp31_ = mCompCoord[4];
   double tmp32_ = mCompCoord[5];
   double tmp33_ = mCompCoord[6];
   double tmp34_ = (tmp1_) * mLocPolyn6_State_0_0;
   double tmp35_ = tmp22_ * mLocPolyn6_State_0_0;
   double tmp36_ = tmp6_ * mLocPolyn6_State_0_0;
   double tmp37_ = tmp8_ * mLocPolyn6_State_0_0;
   double tmp38_ = tmp9_ * mLocPolyn6_State_0_0;
   double tmp39_ = tmp10_ * mLocPolyn6_State_0_0;
   double tmp40_ = tmp11_ * mLocPolyn6_State_0_0;
   double tmp41_ = tmp12_ * mLocPolyn6_State_0_0;
   double tmp42_ = tmp13_ * mLocPolyn6_State_0_0;
   double tmp43_ = tmp14_ * mLocPolyn6_State_0_0;
   double tmp44_ = tmp15_ * mLocPolyn6_State_0_0;
   double tmp45_ = tmp16_ * mLocPolyn6_State_0_0;
   double tmp46_ = tmp17_ * mLocPolyn6_State_0_0;
   double tmp47_ = tmp18_ * mLocPolyn6_State_0_0;
   double tmp48_ = tmp19_ * mLocPolyn6_State_0_0;
   double tmp49_ = tmp20_ * mLocPolyn6_State_0_0;
   double tmp50_ = tmp21_ * mLocPolyn6_State_0_0;
   double tmp51_ = tmp23_ * mLocPolyn6_State_0_0;
   double tmp52_ = tmp24_ * mLocPolyn6_State_0_0;
   double tmp53_ = tmp25_ * mLocPolyn6_State_0_0;
   double tmp54_ = tmp26_ * mLocPolyn6_State_0_0;
   double tmp55_ = tmp27_ * mLocPolyn6_State_0_0;
   double tmp56_ = tmp28_ * mLocPolyn6_State_0_0;
   double tmp57_ = tmp29_ * mLocPolyn6_State_0_0;

  mVal[0] = (mLocPolyn6_State_1_0 + (((1 + tmp30_) * (tmp1_) + tmp31_ * (tmp3_)) - tmp32_ * 2 * tmp4_ + tmp33_ * tmp22_ + mCompCoord[7] * tmp5_) * mLocPolyn6_State_0_0 + (mCompCoord[9] * tmp6_ + mCompCoord[10] * tmp8_ + mCompCoord[11] * tmp9_ + mCompCoord[12] * tmp10_ + mCompCoord[17] * tmp11_ + mCompCoord[18] * tmp12_ + mCompCoord[19] * tmp13_ + mCompCoord[20] * tmp14_ + mCompCoord[21] * tmp15_ + mCompCoord[27] * tmp16_ + mCompCoord[28] * tmp17_ + mCompCoord[29] * tmp18_ + mCompCoord[30] * tmp19_ + mCompCoord[31] * tmp20_ + mCompCoord[32] * tmp21_ + mCompCoord[39] * tmp23_ + mCompCoord[40] * tmp24_ + mCompCoord[41] * tmp25_ + mCompCoord[42] * tmp26_ + mCompCoord[43] * tmp27_ + mCompCoord[44] * tmp28_ + mCompCoord[45] * tmp29_) * mLocPolyn6_State_0_0) - mLocRegDistKnownVal_x;

  mCompDer[0][0] = 0;
  mCompDer[0][1] = 0;
  mCompDer[0][2] = 0;
  mCompDer[0][3] = tmp34_;
  mCompDer[0][4] = (tmp3_) * mLocPolyn6_State_0_0;
  mCompDer[0][5] = -(2 * tmp4_) * mLocPolyn6_State_0_0;
  mCompDer[0][6] = tmp35_;
  mCompDer[0][7] = tmp5_ * mLocPolyn6_State_0_0;
  mCompDer[0][8] = 0;
  mCompDer[0][9] = tmp36_;
  mCompDer[0][10] = tmp37_;
  mCompDer[0][11] = tmp38_;
  mCompDer[0][12] = tmp39_;
  mCompDer[0][13] = 0;
  mCompDer[0][14] = 0;
  mCompDer[0][15] = 0;
  mCompDer[0][16] = 0;
  mCompDer[0][17] = tmp40_;
  mCompDer[0][18] = tmp41_;
  mCompDer[0][19] = tmp42_;
  mCompDer[0][20] = tmp43_;
  mCompDer[0][21] = tmp44_;
  mCompDer[0][22] = 0;
  mCompDer[0][23] = 0;
  mCompDer[0][24] = 0;
  mCompDer[0][25] = 0;
  mCompDer[0][26] = 0;
  mCompDer[0][27] = tmp45_;
  mCompDer[0][28] = tmp46_;
  mCompDer[0][29] = tmp47_;
  mCompDer[0][30] = tmp48_;
  mCompDer[0][31] = tmp49_;
  mCompDer[0][32] = tmp50_;
  mCompDer[0][33] = 0;
  mCompDer[0][34] = 0;
  mCompDer[0][35] = 0;
  mCompDer[0][36] = 0;
  mCompDer[0][37] = 0;
  mCompDer[0][38] = 0;
  mCompDer[0][39] = tmp51_;
  mCompDer[0][40] = tmp52_;
  mCompDer[0][41] = tmp53_;
  mCompDer[0][42] = tmp54_;
  mCompDer[0][43] = tmp55_;
  mCompDer[0][44] = tmp56_;
  mCompDer[0][45] = tmp57_;
  mCompDer[0][46] = 0;
  mCompDer[0][47] = 0;
  mCompDer[0][48] = 0;
  mCompDer[0][49] = 0;
  mCompDer[0][50] = 0;
  mCompDer[0][51] = 0;
  mCompDer[0][52] = 0;
  mVal[1] = (mLocPolyn6_State_2_0 + (((1 - tmp30_) * (tmp3_) + tmp31_ * (tmp1_) + tmp32_ * tmp22_) - tmp33_ * 2 * tmp5_ + mCompCoord[8] * tmp4_) * mLocPolyn6_State_0_0 + (mCompCoord[13] * tmp6_ + mCompCoord[14] * tmp8_ + mCompCoord[15] * tmp9_ + mCompCoord[16] * tmp10_ + mCompCoord[22] * tmp11_ + mCompCoord[23] * tmp12_ + mCompCoord[24] * tmp13_ + mCompCoord[25] * tmp14_ + mCompCoord[26] * tmp15_ + mCompCoord[33] * tmp16_ + mCompCoord[34] * tmp17_ + mCompCoord[35] * tmp18_ + mCompCoord[36] * tmp19_ + mCompCoord[37] * tmp20_ + mCompCoord[38] * tmp21_ + mCompCoord[46] * tmp23_ + mCompCoord[47] * tmp24_ + mCompCoord[48] * tmp25_ + mCompCoord[49] * tmp26_ + mCompCoord[50] * tmp27_ + mCompCoord[51] * tmp28_ + mCompCoord[52] * tmp29_) * mLocPolyn6_State_0_0) - mLocRegDistKnownVal_y;

  mCompDer[1][0] = 0;
  mCompDer[1][1] = 0;
  mCompDer[1][2] = 0;
  mCompDer[1][3] = -(1) * (tmp3_) * mLocPolyn6_State_0_0;
  mCompDer[1][4] = tmp34_;
  mCompDer[1][5] = tmp35_;
  mCompDer[1][6] = -(2 * tmp5_) * mLocPolyn6_State_0_0;
  mCompDer[1][7] = 0;
  mCompDer[1][8] = tmp4_ * mLocPolyn6_State_0_0;
  mCompDer[1][9] = 0;
  mCompDer[1][10] = 0;
  mCompDer[1][11] = 0;
  mCompDer[1][12] = 0;
  mCompDer[1][13] = tmp36_;
  mCompDer[1][14] = tmp37_;
  mCompDer[1][15] = tmp38_;
  mCompDer[1][16] = tmp39_;
  mCompDer[1][17] = 0;
  mCompDer[1][18] = 0;
  mCompDer[1][19] = 0;
  mCompDer[1][20] = 0;
  mCompDer[1][21] = 0;
  mCompDer[1][22] = tmp40_;
  mCompDer[1][23] = tmp41_;
  mCompDer[1][24] = tmp42_;
  mCompDer[1][25] = tmp43_;
  mCompDer[1][26] = tmp44_;
  mCompDer[1][27] = 0;
  mCompDer[1][28] = 0;
  mCompDer[1][29] = 0;
  mCompDer[1][30] = 0;
  mCompDer[1][31] = 0;
  mCompDer[1][32] = 0;
  mCompDer[1][33] = tmp45_;
  mCompDer[1][34] = tmp46_;
  mCompDer[1][35] = tmp47_;
  mCompDer[1][36] = tmp48_;
  mCompDer[1][37] = tmp49_;
  mCompDer[1][38] = tmp50_;
  mCompDer[1][39] = 0;
  mCompDer[1][40] = 0;
  mCompDer[1][41] = 0;
  mCompDer[1][42] = 0;
  mCompDer[1][43] = 0;
  mCompDer[1][44] = 0;
  mCompDer[1][45] = 0;
  mCompDer[1][46] = tmp51_;
  mCompDer[1][47] = tmp52_;
  mCompDer[1][48] = tmp53_;
  mCompDer[1][49] = tmp54_;
  mCompDer[1][50] = tmp55_;
  mCompDer[1][51] = tmp56_;
  mCompDer[1][52] = tmp57_;
}


void cREgDistVal_Polyn6::ComputeValDerivHessian()
{
  ELISE_ASSERT(false,"Foncteur cREgDistVal_Polyn6 Has no Der Sec");
}

void cREgDistVal_Polyn6::SetPolyn6_State_0_0(double aVal){ mLocPolyn6_State_0_0 = aVal;}
void cREgDistVal_Polyn6::SetPolyn6_State_1_0(double aVal){ mLocPolyn6_State_1_0 = aVal;}
void cREgDistVal_Polyn6::SetPolyn6_State_2_0(double aVal){ mLocPolyn6_State_2_0 = aVal;}
void cREgDistVal_Polyn6::SetRegDistKnownVal_x(double aVal){ mLocRegDistKnownVal_x = aVal;}
void cREgDistVal_Polyn6::SetRegDistKnownVal_y(double aVal){ mLocRegDistKnownVal_y = aVal;}
void cREgDistVal_Polyn6::SetRegDistValP1_x(double aVal){ mLocRegDistValP1_x = aVal;}
void cREgDistVal_Polyn6::SetRegDistValP1_y(double aVal){ mLocRegDistValP1_y = aVal;}



double * cREgDistVal_Polyn6::AdrVarLocFromString(const std::string & aName)
{
   if (aName == "Polyn6_State_0_0") return & mLocPolyn6_State_0_0;
   if (aName == "Polyn6_State_1_0") return & mLocPolyn6_State_1_0;
   if (aName == "Polyn6_State_2_0") return & mLocPolyn6_State_2_0;
   if (aName == "RegDistKnownVal_x") return & mLocRegDistKnownVal_x;
   if (aName == "RegDistKnownVal_y") return & mLocRegDistKnownVal_y;
   if (aName == "RegDistValP1_x") return & mLocRegDistValP1_x;
   if (aName == "RegDistValP1_y") return & mLocRegDistValP1_y;
   return 0;
}


cElCompiledFonc::cAutoAddEntry cREgDistVal_Polyn6::mTheAuto("cREgDistVal_Polyn6",cREgDistVal_Polyn6::Alloc);


cElCompiledFonc *  cREgDistVal_Polyn6::Alloc()
{  return new cREgDistVal_Polyn6();
}


