FROM mambaorg/micromamba:2.4.0-cuda11.8.0-ubuntu22.04

USER root

ARG DEBIAN_FRONTEND=noninteractive

ENV http_proxy ....
ENV https_proxy ....
# Set the working directory
ENV foo /etc/opt/
WORKDIR ${foo}   


#MicMac dependencies
RUN apt-get update && apt-get install -y \
		    build-essential \
		    make \
                    cmake \ 
                    git \
		    python3-pip \
                    proj-bin \
		    exiv2 \
                    exiftool \
                    imagemagick \
		    xorg \
                libx11-dev \
		    wget


RUN git config --global http.proxy ....
RUN git config --global https.proxy ....
# clone micmac_SimLearning 
RUN git clone -b mac_pdal https://github.com/DaliCHEBBI/micmac_SimLearning.git


#ADD ./ ${foo}/micmac_SimLearning

#MicMac build & compile
WORKDIR micmac_SimLearning

RUN mkdir build

WORKDIR build

RUN cmake ../ && make install -j8


# MMVII build & compile 
WORKDIR ${foo}

# copy libtorch library to /etc/opt/micmac_SimLearning/MMVII/libtorch 
ADD ./libtorch ${foo}/micmac_SimLearning/MMVII/libtorch

RUN ls /etc/opt/micmac_SimLearning/MMVII/

WORKDIR ${foo}

RUN apt install -y pkg-config libproj-dev libpdal-dev libgdal-dev libxerces-c-dev && rm -rf /var/lib/apt/lists/*

RUN  cd micmac_SimLearning/MMVII && \
      mkdir build && cd build && \
      cmake ../ -DMMVII_KEEP_LIBRARY_MMV1=on && \
      make  full -j 8

# simlearner3d repository build
WORKDIR ${foo}

RUN git clone -b subpixel_exp https://github.com/DaliCHEBBI/simlearner3d.git

#ADD ./ ${foo}/simlearner3d

WORKDIR simlearner3d

# install torch inference requirements
RUN export http_proxy=.....
RUN export https_proxy=.....



RUN micromamba config set proxy_servers.http=.......
RUN micromamba config set proxy_servers.https=.....


RUN micromamba env create -n simlearner3d -f environment_minimal.yml  -y

#MicMac add environmental variable to executables
ENV PATH=${foo}micmac_SimLearning/bin:${foo}micmac_SimLearning/MMVII/bin:${PATH}
RUN echo ${foo}micmac_SimLearning/bin:${foo}micmac_SimLearning/MMVII/bin:${PATH}