#include "StdAfx.h"
const char * (theNameVar_ParamDigeo[242]) = {
"<GenCpp>\n",
"\n",
"<Verbatim  File=\".h\">\n",
"#include \"StdAfx.h\"\n",
"#ifndef Define_NotDigeo\n",
"#define Define_NotDigeo\n",
"</Verbatim>\n",
"<Verbatim File=\".cpp\">\n",
"#include \"cParamDigeo.h\"\n",
"</Verbatim>\n",
"\n",
"<Verbatim File=\".h\">\n",
"#include \"XML_GEN/all.h\"\n",
"\n",
"\n",
"</Verbatim>\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"//\n",
"</Verbatim>\n",
"\n",
"\n",
"   <enum Name=\"eTypeTopolPt\">\n",
"         <eTtpSommet>     </eTtpSommet>  \n",
"         <eTtpCuvette>    </eTtpCuvette> \n",
"         <eTtpCol>        </eTtpCol>\n",
"         <eTtpCorner>      </eTtpCorner>\n",
"         <eSiftMaxDog>     </eSiftMaxDog>\n",
"         <eSiftMinDog>     </eSiftMinDog>\n",
"   </enum>\n",
"\n",
"   <enum Name=\"eReducDemiImage\">\n",
"         <eRDI_121>     </eRDI_121>  \n",
"         <eRDI_010>     </eRDI_010>  \n",
"         <eRDI_11>     </eRDI_11>  \n",
"   </enum>\n",
"\n",
"   <enum Name=\"eTest12345\">\n",
"         <eTest12345_A>     </eTest12345_A>  \n",
"         <eTest12345_B>     </eTest12345_B>  \n",
"         <eTest12345_C>     </eTest12345_C>  \n",
"   </enum>\n",
"\n",
"\n",
"\n",
"   <ParamExtractCaracIm  Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"        <SzMinImDeZoom Nb=\"?\" Type=\"int\" Def=\"500\">  </SzMinImDeZoom>\n",
"   </ParamExtractCaracIm>\n",
"\n",
"\n",
"   <ParamVisuCarac  Nb=\"1\" Class=\"true\" ToReference=\"true\" AccessorFils=\"false\">\n",
"        <!-- Nombre de niveau gris alloues a  la visualisation en gris -->\n",
"        <DynGray Nb=\"?\" Type=\"int\" Def=\"128\">  </DynGray>\n",
"        <Dir Nb=\"1\" Type=\"std::string\"> </Dir>\n",
"        <Zoom Nb=\"?\" Def=\"1\" Type=\"int\"> </Zoom>\n",
"        <Dyn Nb=\"1\"  Type=\"double\"> </Dyn>\n",
"        <Prefix Nb=\"?\" Type=\"std::string\" Def=\"VisuCarac_\"></Prefix>\n",
"        <ShowCaracEchec Nb=\"?\" Def=\"false\" Type=\"bool\"></ShowCaracEchec>\n",
"   </ParamVisuCarac>\n",
"   \n",
"\n",
"\n",
"   <ParamDigeo  Nb=\"1\" Class=\"true\">\n",
"\n",
"        <DicoLoc  Nb=\"?\" \n",
"                  RefType=\"ChantierDescripteur\" \n",
"                  RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </DicoLoc>\n",
"\n",
"        <DigeoSectionImages Nb=\"1\">\n",
"           <ImageDigeo Nb=\"*\">\n",
"\n",
"\n",
"              <VisuCarac Nb=\"?\"  RefType=\"ParamVisuCarac\" > </VisuCarac>\n",
"\n",
"              <KeyOrPat Nb=\"1\" Type=\"std::string\"> </KeyOrPat>\n",
"              <!-- Pas utilise pour l'instant, sans doute prevu pour modele geometrique -->\n",
"              <KeyCalcCalib Nb=\"?\" Type=\"std::string\"> </KeyCalcCalib>\n",
"              <!-- La BoxImR1 est donnee / a la resol 1 -->\n",
"              <BoxImR1 Nb=\"?\" Type=\"Box2di\">  </BoxImR1>\n",
"              <!-- ResolInit=0.5 signifie des images deux fois plus grandes -->\n",
"              <ResolInit Nb=\"?\" Type=\"double\" Def=\"1.0\"> </ResolInit>\n",
"\n",
"              <!-- Pour l'instant pas utilise, mais pour pouvoir commencer\n",
"                  a organiser la structure -->\n",
"              <PredicteurGeom Nb=\"?\" UnionType=\"true\">\n",
"                     <Unused Nb=\"?\" Type=\"std::string\"> </Unused> \n",
"              </PredicteurGeom>\n",
"              <!-- Si la taille mémoire de l'image est inférieure a ce seuil, le fichier est lu en 1 bloc-->\n",
"              <NbOctetLimitLoadImageOnce Nb=\"?\" Type=\"double\" Def=\"1e8\"> </NbOctetLimitLoadImageOnce>\n",
"           </ImageDigeo>\n",
"           <PyramideImage Nb=\"1\">\n",
"              <TypeNumeriqueOfNiv Nb=\"*\">\n",
"                 <Type  Nb=\"1\"  Type=\"eTypeNumerique\"> </Type>\n",
"                 <Niv Nb=\"1\" Type=\"int\"> </Niv>\n",
"              </TypeNumeriqueOfNiv>\n",
"\n",
"            <!-- En maximisant la dynamique compatible avec le type d'image,\n",
"                 permet d'avoir une plus grande precision; Def = true pour (u_)?int[12] -->\n",
"\n",
"              <MaximDyn Nb=\"?\" Type=\"bool\"> </MaximDyn>\n",
"              <!-- Parfois l'image contient des valeurs \"parasites\" qui \n",
"                  rendent inoperante la MaximDyn, si c'est le cas on peut fixer un \n",
"                  max theorique (par ex 1<<12) en cam Dyn\n",
"              -->\n",
"              <ValMaxForDyn Nb=\"?\" Type=\"double\"> </ValMaxForDyn>\n",
"             \n",
"              <ReducDemiImage Nb=\"?\" Type=\"eReducDemiImage\" Def=\"eRDI_121\"> </ReducDemiImage>\n",
"\n",
"              <TypePyramide Nb=\"1\" UnionType=\"true\">\n",
"                  <NivPyramBasique Nb=\"?\" Type=\"int\"> </NivPyramBasique>\n",
"                  <PyramideGaussienne  Nb=\"?\">\n",
"                       <NbByOctave Def=\"3\" Nb=\"?\"  Type=\"int\"> </NbByOctave>\n",
"\n",
"                       <Sigma0 Nb=\"?\" Type=\"double\" Def=\"1.6\"> </Sigma0>\n",
"                       <!-- le papier de Lowe semble indiquer un smooting identique à chaque octave -->\n",
"                       <SigmaN Nb=\"?\" Type=\"double\"> </SigmaN>\n",
"\n",
"                       <NbInLastOctave Nb=\"?\"  Type=\"int\"> </NbInLastOctave>\n",
"                       <!-- Pour la premiere octave on peut supprimer ou rajouter \n",
"                           (avec val<0) des frequence grace a ce tag -->\n",
"                       <IndexFreqInFirstOctave Nb=\"?\" Type=\"int\" Def=\"0\"> </IndexFreqInFirstOctave>\n",
"                       <NivOctaveMax  Nb=\"1\"  Type=\"int\">  </NivOctaveMax> <!-- Par ex 8, 32 ..-->\n",
"\n",
"                       <!-- A priori ca me semble + \"logique\" du point de vue de la continuite\n",
"                            vis a vis de l'echelle que la toute premiere image soit convoluee\n",
"                            par le sigma initial, mais c'est pas tres clair, donc ce parametre\n",
"                            permet de regler ca :\n",
"                                - si il vaut 0 pas de convolution;\n",
"                                - si il vaut -1 : convolution par le sigma initial (1.0 si\n",
"                                 IndexFreqInFirstOctave est pas specifie)\n",
"                                - si >0 convolution par la valeur\n",
"                                - sinon erreur\n",
"                       -->\n",
"                       <ConvolFirstImage Nb=\"?\" Type=\"double\" Def=\"-1\"> </ConvolFirstImage>\n",
"                       <EpsilonGauss Nb=\"?\" Type=\"double\" Def=\"1e-3\"> </EpsilonGauss>\n",
"                       <NbShift  Nb=\"?\" Type=\"int\" Def=\"15\"> </NbShift>\n",
"                       <SurEchIntegralGauss Nb=\"?\" Type=\"int\" Def=\"10\"> </SurEchIntegralGauss>\n",
"                       <ConvolIncrem Nb=\"?\" Type=\"bool\" Def=\"true\"> </ConvolIncrem>\n",
"                  </PyramideGaussienne>\n",
"              </TypePyramide>\n",
"           </PyramideImage>\n",
"        </DigeoSectionImages>\n",
"       \n",
"        <SectionCaracImages Nb=\"1\">\n",
"           <!-- Juste pour pouvoir eventuellement squeezer en amont tout le calcul\n",
"           -->\n",
"           <ComputeCarac Nb=\"1\" Type=\"bool\"> </ComputeCarac>\n",
"           <CaracTopo Nb=\"?\">\n",
"                <OneCarac Nb=\"*\">\n",
"                    <Type Nb=\"1\" Type=\"eTypeTopolPt\"> </Type>\n",
"                </OneCarac>\n",
"           </CaracTopo>\n",
"           <SiftCarac Nb=\"?\">\n",
"               <DoMax Nb=\"?\" Type=\"bool\" Def=\"true\"> </DoMax>\n",
"               <DoMin Nb=\"?\" Type=\"bool\" Def=\"true\"> </DoMin>\n",
"\n",
"               <NivEstimGradMoy Nb=\"?\" Def=\"4\" Type=\"int\"></NivEstimGradMoy>\n",
"               <!-- 8 Correspond a peu pres a la valeur 10 de Tr 2 / det de Lowe -->\n",
"               <RatioAllongMin Nb=\"?\" Def=\"8.0\" Type=\"double\"> </RatioAllongMin>\n",
"               <RatioGrad Nb=\"?\" Def=\"0.01\" Type=\"double\"> </RatioGrad>\n",
"\n",
"           </SiftCarac>\n",
"        </SectionCaracImages>\n",
"\n",
"        <!-- Cette section gère les fonctionnalites permettant de faire\n",
"             des tests de perfomances ou de bon fonctionnement\n",
"        -->\n",
"            \n",
"        <SectionTest Nb=\"?\">\n",
"             <GenereRandomRect Nb=\"?\">\n",
"                  <NbRect Nb=\"1\" Type=\"int\"></NbRect>\n",
"                  <SzRect Nb=\"1\" Type=\"int\"></SzRect>\n",
"             </GenereRandomRect>\n",
"             <GenereCarroyage Nb=\"?\">\n",
"                  <PerX Nb=\"1\" Type=\"int\"></PerX>\n",
"                  <PerY Nb=\"1\" Type=\"int\"></PerY>\n",
"             </GenereCarroyage>\n",
"             <GenereAllRandom Nb=\"?\">\n",
"                  <SzFilter Nb=\"1\" Type=\"int\"> </SzFilter>  \n",
"             </GenereAllRandom>\n",
"\n",
"             <VerifExtrema Nb=\"?\" Type=\"bool\" Def=\"false\"></VerifExtrema>\n",
"        </SectionTest>\n",
"\n",
"        <SectionWorkSpace Nb=\"1\">\n",
"           <DirectoryChantier Nb=\"?\"  Type=\"std::string\" Def=\"\">  </DirectoryChantier>\n",
"           <SauvPyram Nb=\"?\">\n",
"              <Dir Nb=\"?\" Type=\"std::string\" Def=\"\"> </Dir>\n",
"              <Glob Nb=\"?\" Type=\"bool\" Def=\"true\"> </Glob>\n",
"              <Key Nb=\"?\" Type=\"std::string\" Def=\"Key-Assoc-Pyram-MM\"> </Key>\n",
"              <!-- <=0 si pas used -->\n",
"              <StripTifFile Nb=\"?\" Type=\"int\" Def=\"100\"> </StripTifFile>\n",
"              <Force8B Nb=\"?\" Type=\"bool\" Def=\"false\">   </Force8B>\n",
"              <Dyn  Nb=\"?\" Type=\"double\" Def=\"1.0\"> </Dyn>\n",
"            </SauvPyram>\n",
"\n",
"           <DigeoDecoupageCarac Nb=\"?\">\n",
"                <SzDalle Nb=\"1\" Type=\"int\"> </SzDalle>\n",
"                <Bord Nb=\"1\" Type=\"int\">    </Bord>\n",
"           </DigeoDecoupageCarac>\n",
"\n",
"<!-- A priori, on a interet a ce que tous les convol soit compilees; on se fait\n",
"insulter si ce n'est pas le cas; sauf si ExigeCodeCompile indique que c'est sciemment -->\n",
"            <ExigeCodeCompile Nb=\"?\" Type=\"bool\" Def=\"true\"></ExigeCodeCompile>\n",
"            <GenereCodeConvol Nb=\"?\"  AccessorFils=\"false\">\n",
"                   <Dir Nb=\"?\" Type=\"std::string\" Def=\"src/uti_image/Digeo/\"> </Dir>\n",
"                   <File Nb=\"?\" Type=\"std::string\" Def=\"GenConvolSpec\"> </File>\n",
"                   <ModifGCC Nb=\"*\"  Container=\"std::vector\">\n",
"                       <NbByOctave Nb=\"1\" Type=\"int\"> </NbByOctave>\n",
"                       <ConvolIncrem Nb=\"1\" Type=\"bool\"> </ConvolIncrem>\n",
"                       <TypeNum Nb=\"1\" Type=\"eTypeNumerique\"> </TypeNum>\n",
"                   </ModifGCC>\n",
"            </GenereCodeConvol>\n",
"\n",
"\n",
"           <ShowTimes Nb=\"?\" Type=\"int\" Def=\"0\"> </ShowTimes>\n",
"           <FenVisu Nb=\"*\">\n",
"                 <Name Nb=\"1\" Type=\"std::string\"> </Name>\n",
"                 <Sz  Nb=\"1\" Type=\"Pt2di\"> </Sz>\n",
"           </FenVisu>\n",
"\n",
"           <!-- Pas de raison, hors mis au point/test, de changer cette val -->\n",
"           <ShowConvolSpec Nb=\"?\" Type=\"bool\" Def=\"false\"> </ShowConvolSpec>\n",
"\n",
"\n",
"	   <Verbose Nb=\"?\" Type=\"bool\" Def=\"false\"> </Verbose>\n",
"        </SectionWorkSpace>\n",
"   </ParamDigeo>\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"// };\n",
"</Verbatim>\n",
"<Verbatim File=\".h\">\n",
"#endif // Define_NotDigeo\n",
"</Verbatim>\n",
"\n",
"\n",
"</GenCpp>\n",
"","//#_-=+{}@$##$##@"};
