#include "StdAfx.h"
const char * (theNameVar_SuperposImage[1198]) = {
"<GenCpp>\n",
"\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"// #include \"general/all.h\"\n",
"// #include \"private/all.h\"\n",
"</Verbatim>\n",
"<Verbatim  File=\".h\">\n",
"#ifndef Define_NotSupIm\n",
"#define Define_NotSupIm\n",
"</Verbatim>\n",
"<Verbatim File=\".cpp\">\n",
"// #include \"XML_GEN/SuperposImage.h\"\n",
"#include \"StdAfx.h\"\n",
"</Verbatim>\n",
"\n",
"\n",
"<Verbatim File=\".h\">\n",
"// #include \"general/all.h\"\n",
"// #include \"private/all.h\"\n",
"// #include \"XML_GEN/ParamChantierPhotogram.h\"\n",
"</Verbatim>\n",
"<Verbatim File=\".h.cpp\">\n",
"// \n",
"</Verbatim>\n",
"\n",
"    <enum Name=\"eTypeSurfaceAnalytique\">\n",
"         <eTSA_CylindreRevolution >     </eTSA_CylindreRevolution>\n",
"    </enum>\n",
"\n",
"    <enum Name=\"eModeBoxFusion\">\n",
"         <eMBF_Union >     </eMBF_Union>\n",
"         <eMBF_Inter >     </eMBF_Inter>\n",
"         <eMBF_First >     </eMBF_First>\n",
"    </enum>\n",
"\n",
"\n",
"\n",
"    <LutConvertion  Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"         <IntervLutConvertion Nb=\"+\"  Container=\"std::vector\">\n",
"              <NivIn  Nb=\"1\" Type=\"int\"> </NivIn>\n",
"              <NivOut Nb=\"1\" Type=\"int\"> </NivOut>\n",
"         </IntervLutConvertion>\n",
"    </LutConvertion>\n",
"\n",
"\n",
"\n",
"    <WindowSelection Nb=\"1\" UnionType=\"true\"  Class=\"true\" ToReference=\"true\">\n",
"            <AllPts Nb=\"?\"  Type=\"std::string\"> </AllPts>\n",
"            <PtsCenter Nb=\"?\"  Type=\"std::string\"> </PtsCenter>\n",
"            <Percent Nb=\"?\"  Type=\"double\"> </Percent>\n",
"    </WindowSelection>\n",
"\n",
"     <MasqTerrain Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"            <Image Nb=\"1\" Type=\"std::string\"> </Image>\n",
"            <XML   Nb=\"1\" Type=\"std::string\"> </XML>\n",
"            <SelectPts Nb=\"1\" RefType=\"WindowSelection\"> </SelectPts>\n",
"     </MasqTerrain>\n",
"<!--\n",
"-->\n",
"\n",
"    <!--  Pour creer une composition coloree -->\n",
"\n",
"    <ImageCmpCol   Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"    <!--  Si c'est la premiere image  (<ImMaitresse>), interpretee literallemenent.\n",
"         Sinon : - si le fichier existe, interprete literallemnet\n",
"                 - si existe pas, cle de calcul a partir du maitre\n",
"    -->\n",
"	<NameOrKey Type=\"std::string\" Nb=\"1\"> </NameOrKey>\n",
"        <TypeTmpIn Nb=\"?\" Type=\"eTypeNumerique\">  </TypeTmpIn>\n",
"\n",
"	<!-- Il est possible (cas courant avec Gray/RGB) que l'image ayant servie\n",
"	a la mise en geometrie soit diff de celle de la composition, d'ou le role\n",
"	de cette correspondance -->\n",
"	<KeyCalcNameImOfGeom Type=\"std::string\" Nb=\"?\"> </KeyCalcNameImOfGeom>\n",
"\n",
"         <!-- Box definissant les pixels mort -->\n",
"         <BoxPixMort Nb=\"?\">\n",
"               <HautG Type=\"Pt2di\" Nb=\"1\"> </HautG>\n",
"               <BasD  Type=\"Pt2di\" Nb=\"1\"> </BasD>\n",
"          </BoxPixMort>\n",
"\n",
"           <FlattField Nb=\"?\">\n",
"               <NameFile Nb=\"1\" Type=\"std::string\"> </NameFile>\n",
"               <RefValue Nb=\"+\" Type=\"double\"  Container=\"std::vector\"> </RefValue>\n",
"           </FlattField>\n",
"<!-- Pour chaque image, on specifier le contribution de chaque canal \n",
"     Exemple : cannaux separes-> RVB : on aura pour chaque ImageCmpCol R : In 0 Out 0 , V  R : In 0 Out 1, ...\n",
"               RVB -> Gray   un seul ImageCmpCol avec 2 ChannelCmpCol   In 0 Out 0, In 1 Out 0 , .....\n",
"-->\n",
"\n",
"	<ChannelCmpCol Nb=\"*\"> \n",
"	     <Dyn Nb=\"?\" Type=\"double\" Def=\"1.0\"> </Dyn>\n",
"	     <Offset Nb=\"?\" Type=\"double\" Def=\"0.0\"> </Offset>\n",
"	     <In  Nb=\"1\" Type=\"int\">  </In>\n",
"	     <Out  Nb=\"1\" Type=\"int\"> </Out>\n",
"	     <Pds  Nb=\"?\" Type=\"double\" Def=\"1.0\"> </Pds>\n",
"             <ParamBiCub Nb=\"?\" Type=\"double\"> </ParamBiCub> \n",
"	</ChannelCmpCol>\n",
"        <NbFilter  Nb=\"?\" Type=\"int\" Def=\"0\"> </NbFilter>\n",
"        <SzFilter  Nb=\"?\" Type=\"int\" Def=\"1\"> </SzFilter>\n",
"    </ImageCmpCol>\n",
"\n",
"    <CreateCompColoree  Nb=\"1\"  Class=\"true\">\n",
"\n",
"        <DicoLoc  Nb=\"?\" RefType=\"ChantierDescripteur\"\n",
"                   RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </DicoLoc>\n",
"        <MapCCC Nb=\"*\"\n",
"                RefType=\"CmdMappeur\"\n",
"                RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </MapCCC>\n",
"\n",
"<!--  APPAREMENT PAS UTILISE\n",
"        <TypeTmpOut Nb=\"?\" Type=\"eTypeNumerique\" Def=\"eTN_u_int1\"> </TypeTmpOut>\n",
"-->\n",
"\n",
"        <!-- Si pas donne, Bi Lin -->\n",
"        <ParamBiCub Nb=\"?\" Type=\"double\"> </ParamBiCub>\n",
"\n",
"\n",
"\n",
"       <!-- Le modele de deformation est transforme en un grille dont\n",
"       le pas est fixe par StepGrid\n",
"       -->\n",
"        <StepGrid Nb=\"1\" Type=\"double\"> </StepGrid>\n",
"        <WorkDir Nb=\"1\" Type=\"std::string\">   </WorkDir>   \n",
"\n",
"       <!-- Pour eviter les outliers dans la moyenne log -->\n",
"        \n",
"        <ShowCalibsRel Nb=\"*\" >\n",
"            <Channel Nb=\"*\" Type=\"int\" Container=\"std::vector\">>  </Channel>\n",
"            <MaxRatio Nb=\"?\" Type=\"double\" Def=\"2.0\">     </MaxRatio>\n",
"<!--\n",
"-->\n",
"        </ShowCalibsRel>\n",
"\n",
"        <ResultCompCol Nb=\"*\">\n",
"            <GamaExport Nb=\"?\" Type=\"double\"> </GamaExport>\n",
"            <RefGama Nb=\"?\" Type=\"double\" Def=\"256.0\"> </RefGama>\n",
"\n",
"            <LutExport  Nb=\"?\" RefType=\"LutConvertion\"> </LutExport>\n",
"<!--\n",
"-->\n",
"\n",
"\n",
"	    <KeyName  Nb=\"1\" Type=\"std::string\"> </KeyName>\n",
"            <Type Nb=\"?\" Type=\"eTypeNumerique\" Def=\"eTN_u_int1\"> </Type>\n",
"            <ImResultCC Nb=\"1\" UnionType=\"true\">\n",
"                <ImResultCC_Gray Nb=\"?\" AccessorFils=\"false\">\n",
"                     <Channel Nb=\"?\" Type=\"int\" Def=\"0\"> </Channel>\n",
"                </ImResultCC_Gray>\n",
"                <ImResultCC_RVB Nb=\"?\" AccessorFils=\"false\">\n",
"                     <Channel Nb=\"?\" Type=\"Pt3di\"  Def=\"0,1,2\"> </Channel>\n",
"                </ImResultCC_RVB>\n",
"                <ImResultCC_Cnes Nb=\"?\" AccessorFils=\"false\">\n",
"                    <!-- SzF/ValueF sont utilise ssi NbIterFCSte est N.I. -->\n",
"                     <ModeMedian Nb=\"?\" Type=\"bool\" Def=\"false\"> </ModeMedian>\n",
"                     <SzF Nb=\"?\" Type=\"Pt2di\" Def=\"3,3\"> </SzF>\n",
"                     <ValueF Nb=\"?\" Type=\"std::string\" Def=\"1 2 1 2 4 2 1 2 1\"> </ValueF>\n",
"                     <ChannelHF Nb=\"?\" Type=\"int\" Def=\"3\"> </ChannelHF>\n",
"                     <ChannelBF Nb=\"?\" Type=\"std::vector<int>\"> </ChannelBF>\n",
"\n",
"                      <NbIterFCSte Nb=\"?\" Type=\"int\" Def=\"1\"> </NbIterFCSte>\n",
"                      <SzIterFCSte Nb=\"?\" Type=\"int\"> </SzIterFCSte>\n",
"                </ImResultCC_Cnes>\n",
"\n",
"                <ImResultCC_PXs Nb=\"?\" AccessorFils=\"false\">\n",
"                     <!-- Defaut 0,1,2 : RGB , 3 : Panchro -->\n",
"                     <Channel Nb=\"?\" Type=\"std::vector<int>\"> </Channel>\n",
"                     <AxeRGB Nb=\"?\" Type=\"Pt3dr\" Def=\"1.0,1.0,1.0\"> </AxeRGB>\n",
"                     <Cste Nb=\"?\" Type=\"double\" Def=\"0\"> </Cste>\n",
"                     <ApprentisageAxeRGB Type=\"bool\" Def=\"false\" Nb=\"?\"> </ApprentisageAxeRGB>\n",
"                     <!-- R,G,B ou C (pour cste) -->\n",
"                     <UnusedAppr Type=\"std::string\" Nb=\"*\"> </UnusedAppr>\n",
"                </ImResultCC_PXs>\n",
"                <ImResultCC_Thom Nb=\"?\" AccessorFils=\"false\">\n",
"                      <PondThom Nb=\"1\"  UnionType=\"true\">\n",
"                           <PondExp Nb=\"?\" Type=\"double\"> </PondExp>\n",
"                           <PondCste Nb=\"?\" Type=\"int\"> </PondCste>\n",
"                      </PondThom>\n",
"                      <NbIterPond  Nb=\"?\" Type=\"int\" Def=\"1\"> </NbIterPond>\n",
"                      <SupressCentre  Nb=\"?\" Type=\"bool\" Def=\"false\"> </SupressCentre>\n",
"                      <ChannelHF Nb=\"?\" Type=\"int\" Def=\"3\"> </ChannelHF>\n",
"                      <ChannelBF Nb=\"?\" Type=\"std::vector<int>\"> </ChannelBF>\n",
"                      <ThomAgreg Nb=\"1\"  UnionType=\"true\">\n",
"                           <ThomBidouille Nb=\"?\">\n",
"                                 <VMin Nb=\"1\" Type=\"double\"> </VMin>\n",
"                                 <PourCent Nb=\"1\" Type=\"double\"> </PourCent>\n",
"                           </ThomBidouille>\n",
"                           <MPDBidouille Nb=\"?\">\n",
"                                 <EcartMin Nb=\"1\" Type=\"double\"> </EcartMin>\n",
"                           </MPDBidouille>\n",
"                      </ThomAgreg>\n",
"\n",
"                </ImResultCC_Thom>\n",
"            </ImResultCC>\n",
"        </ResultCompCol>\n",
"\n",
"	<KeyCalcNameCalib Type=\"std::string\" Nb=\"1\"> </KeyCalcNameCalib>\n",
"	<FileChantierNameDescripteur Nb=\"?\" Type=\"string\"> \n",
"	</FileChantierNameDescripteur>\n",
"\n",
"	<ImMaitresse Nb=\"1\" RefType=\"ImageCmpCol\"> </ImMaitresse>\n",
"\n",
"\n",
"    <!-- Calcul des espace de travail,  -->\n",
"\n",
"\n",
"        <EspaceResultSuperpCol Nb=\"1\" UnionType=\"true\">\n",
"             <EnglobImMaitre Nb=\"?\" Type=\"std::string\"> </EnglobImMaitre> <!-- Val Unused -->\n",
"             <EnglobAll Nb=\"?\" Type=\"std::string\"> </EnglobAll> <!-- Val Unused -->\n",
"             <EnglobBoxMaitresse  Nb=\"?\" Type=\"Box2di\"> </EnglobBoxMaitresse>\n",
"        </EspaceResultSuperpCol>\n",
"\n",
"        <BoxCalc  Nb=\"?\" Type=\"Box2di\"> </BoxCalc>\n",
"        <TailleBloc Nb=\"?\" Type=\"int\"> </TailleBloc>\n",
"        <KBoxParal Nb=\"?\" Type=\"int\"> </KBoxParal> <!-- USAGE INTERNE DONT TOUCH -->\n",
"        <ByProcess Nb=\"?\" Type=\"int\"> </ByProcess>\n",
"\n",
"\n",
"	<!-- Est ce que l'espace de calcul est l'union des boite? -->\n",
"	<!-- Est ce que l'espace commun est corrige de la distorsion ? -->\n",
"	<CorDist Nb=\"?\" Type=\"bool\" Def=\"false\"> </CorDist>\n",
"	<ScaleFus Nb=\"?\" Type=\"double\" Def=\"1.0\"> </ScaleFus>\n",
"	\n",
"	<ImSec Nb=\"+\" >\n",
"	    <Im  Nb=\"1\" RefType=\"ImageCmpCol\"> </Im>\n",
"\n",
"          <!-- Peut etre soit une grille soit des points homologues -->\n",
"	    <KeyCalcNameCorresp  Type=\"std::string\" Nb=\"1\"> </KeyCalcNameCorresp>\n",
"            <OffsetPt Nb=\"?\" Type=\"Pt2dr\"> </OffsetPt>\n",
"         <!-- En theorie pas utile car devrait pourvoir etre pris en compt\n",
"	 par les mecanisme de type SubDirAutomake, mais ceux-ci ne sont pas\n",
"	 utilises par MicMac et si on veut reprendre les Key -->\n",
"	    <DirCalcCorrep Type=\"std::string\" Nb=\"?\" Def=\"\"> </DirCalcCorrep>\n",
"\n",
"	    <VerifHoms Nb=\"?\">\n",
"	          <NameOrKeyHomologues  Type=\"std::string\" Nb=\"1\"> </NameOrKeyHomologues>\n",
"		  <VisuEcart Nb=\"?\">\n",
"		       <SzW Nb=\"1\" Type=\"double\"> </SzW>\n",
"		       <Exag Nb=\"1\" Type=\"double\"> </Exag>\n",
"                       <NameFile Nb=\"?\" Type=\"std::string\"></NameFile>\n",
"		       <Images2Verif Nb=\"?\">\n",
"		          <X Nb=\"1\" Type=\"std::string\"> </X>\n",
"		          <Y Nb=\"1\" Type=\"std::string\"> </Y>\n",
"		          <ExagXY Nb=\"1\" Type=\"double\"> </ExagXY>\n",
"		       </Images2Verif>\n",
"		  </VisuEcart>\n",
"	    </VerifHoms>\n",
"            <NbTestRansacEstimH Nb=\"?\" Type=\"int\" Def=\"30000\"> </NbTestRansacEstimH>\n",
"            <NbPtsRansacEstimH Nb=\"?\" Type=\"int\" Def=\"1000\"> </NbPtsRansacEstimH>\n",
"	    <L2EstimH Nb=\"?\" Type=\"bool\" Def=\"false\"> </L2EstimH>\n",
"	    <L1EstimH Nb=\"?\" Type=\"bool\" Def=\"false\"> </L1EstimH>\n",
"\n",
"             <!-- Pour la ponderation iteree, x-> seuil, y -> poids\n",
"                  en  1/sqrt(1+E2/y2)  -->\n",
"             <PonderaL2Iter Nb=\"*\" Type=\"Pt2dr\"> </PonderaL2Iter>\n",
"            \n",
"	</ImSec>\n",
"    </CreateCompColoree>\n",
"\n",
"    <!-- Pour creer un modele analytique (par ex radial) a partir\n",
"    d'images de deformations -->\n",
"\n",
"<!--\n",
"    -->\n",
"    <GenereModeleRaster2Analytique  Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"        <Dir Nb=\"1\" Type=\"std::string\">   </Dir>   \n",
"        <Im1 Nb=\"1\" Type=\"std::string\">   </Im1>   \n",
"        <Im2 Nb=\"1\" Type=\"std::string\">   </Im2>   \n",
"	<!-- En general on a tout interet a sous echantillonner les images -->\n",
"	<SsResol  Nb=\"1\" Type=\"double\">  </SsResol>\n",
"	<!-- Pas des images -->\n",
"	<Pas Nb=\"1\"  Type=\"Pt2dr\">      </Pas>\n",
"	<!-- Offset a rajouter aux images, utile en debayerisation \n",
"	     Si AutoCalcTr0 il est calcule par moyenne\n",
"	     Si RoundTr0 il est arrondi au 1/2 pixel (cas Bayer)\n",
"	-->\n",
"	<Tr0 Nb=\"?\"  Type=\"Pt2dr\" Def=\"0,0\">      </Tr0>\n",
"	<AutoCalcTr0 Nb=\"?\" Type=\"bool\" Def=\"false\"> </AutoCalcTr0>\n",
"	<RoundTr0  Nb=\"?\" Type=\"double\" Def=\"0.5\">    </RoundTr0>\n",
"\n",
"\n",
"\n",
"	<DegPoly Nb=\"1\" Type=\"int\">  </DegPoly>\n",
"	<CLibre  Nb=\"1\" Type=\"bool\"> </CLibre>\n",
"	<Dequant  Nb=\"1\" Type=\"bool\">  </Dequant>\n",
"	\n",
"	<SauvegardeMR2A Nb=\"?\">\n",
"             <NameSauvMR2A Nb=\"1\" Type=\"std::string\">   </NameSauvMR2A>\n",
"	     <StepGridMR2A Nb=\"1\" Type=\"double\">    </StepGridMR2A>\n",
"	     <SauvImgMR2A Nb=\"?\" Type=\"std::string\"> </SauvImgMR2A>\n",
"	</SauvegardeMR2A>\n",
"    </GenereModeleRaster2Analytique>\n",
"\n",
"   <!--\n",
"\n",
"   <GridDeform2D Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"       <Origine Nb=\"1\" Type=\"Pt2dr\"> </Origine>\n",
"       <Step    Nb=\"1\" Type=\"Pt2dr\"> </Step>\n",
"       <ImX     Nb=\"1\" Type=\"Im2D_REAL8\">       </ImX>\n",
"       <ImY     Nb=\"1\" Type=\"Im2D_REAL8\">       </ImY>\n",
"   </GridDeform2D>\n",
"\n",
"   <GridDirecteEtInverse  Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"        <Directe Nb=\"1\" RefType=\"GridDeform2D\"> </Directe>\n",
"        <Inverse Nb=\"1\" RefType=\"GridDeform2D\"> </Inverse>\n",
"	<AdaptStep Nb=\"1\" Type=\"bool\">  </AdaptStep>\n",
"   </GridDirecteEtInverse>\n",
"   -->\n",
"\n",
"   <BayerGridDirecteEtInverse  Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"         <Ch1  Nb=\"1\" Type=\"std::string\"> </Ch1>\n",
"         <Ch2  Nb=\"1\" Type=\"std::string\"> </Ch2>\n",
"         <Grid Nb=\"1\" RefType=\"GridDirecteEtInverse\" RefFile=\"ParamChantierPhotogram.xml\"> </Grid>\n",
"   </BayerGridDirecteEtInverse>\n",
"\n",
"   <BayerCalibGeom Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"        <Grids Nb=\"*\" RefType=\"BayerGridDirecteEtInverse\"> </Grids>\n",
"\n",
"         <!-- Balance des blancs -->\n",
"	<WB Nb=\"?\" Type=\"Pt3dr\"> </WB> \n",
"         <!-- Poids pour le gris  -->\n",
"	<PG Nb=\"?\" Type=\"Pt3dr\"> </PG>   \n",
"   </BayerCalibGeom>\n",
"\n",
"<!--\n",
"     R = r0 + r1 R + r2 R2 +..   Degre own\n",
"        + v V + b B              Degre other\n",
"        + rv RV  +v2 V2  ....\n",
"\n",
"\n",
"\n",
"-->\n",
"\n",
"   <SpecifEtalRelOneChan Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"        <DegreOwn Nb=\"1\" Type=\"int\">      </DegreOwn>\n",
"        <DegreOther Nb=\"1\" Type=\"int\">    </DegreOther>\n",
"   </SpecifEtalRelOneChan>\n",
"\n",
"   <SpecifEtalRadiom Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"           <Channel Nb=\"*\" RefType=\"SpecifEtalRelOneChan\"> </Channel>\n",
"   </SpecifEtalRadiom>\n",
"\n",
"   <EtalRelOneChan Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"        <PolyNRadiom Nb=\"*\" Container=\"std::vector\"> \n",
"                    <Degre Nb=\"+\" Type=\"int\"  Container=\"std::vector\"> </Degre>\n",
"                    <Val Nb=\"1\" Type=\"double\"> </Val>\n",
"       </PolyNRadiom>\n",
"   </EtalRelOneChan>\n",
"\n",
"   <ColorCalib Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"         <CalibChannel Nb=\"+\" RefType=\"EtalRelOneChan\"  Container=\"std::vector\"> </CalibChannel>\n",
"   </ColorCalib>\n",
"\n",
"  <!--\n",
"         Evaluation de grille par composition\n",
"  -->\n",
"\n",
"   <EvalComposeGrid   Nb=\"1\"  Class=\"true\">\n",
"        <Directory Nb=\"?\" Type=\"std::string\" Def=\"\"> </Directory>\n",
"        <Dyn  Nb=\"1\" Type=\"double\"> </Dyn>\n",
"        <Resol  Nb=\"1\" Type=\"double\"> </Resol>\n",
"        <OneGridECG Nb=\"+\">\n",
"            <Name Nb=\"1\" Type=\"std::string\"> </Name>\n",
"            <Direct Nb=\"1\" Type=\"bool\">      </Direct>\n",
"        </OneGridECG>\n",
"	<NameNorm Nb=\"?\" Type=\"std::string\"> </NameNorm>\n",
"   </EvalComposeGrid>\n",
"\n",
"\n",
"   <CalcNomFromCouple Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"        <Pattern2Match Nb=\"1\" Type=\"std::string\"> </Pattern2Match>\n",
"	<Separateur Nb=\"?\" Type=\"std::string\" Def=\"\">    </Separateur>\n",
"	<NameCalculated Nb=\"1\" Type=\"std::string\"> </NameCalculated>\n",
"   </CalcNomFromCouple>\n",
"\n",
"   <CalcNomFromOne Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"        <Pattern2Match Nb=\"1\" Type=\"std::string\"> </Pattern2Match>\n",
"	<NameCalculated Nb=\"1\" Type=\"std::string\"> </NameCalculated>\n",
"   </CalcNomFromOne>\n",
"\n",
"\n",
"   <ReSynchronImage  Nb=\"1\"  Class=\"true\"  ToReference=\"true\">\n",
"       <OneResync Nb=\"+\">\n",
"           <Dir Nb=\"1\"  Type=\"std::string\">        </Dir>\n",
"	   <PatSel Nb=\"1\"  Type=\"std::string\">     </PatSel>\n",
"	   <!-- <RefIm  Nb=\"1\"  Type=\"std::string\">     </RefIm>  -->\n",
"\n",
"           <!--  Matche sur  Nom@Num -->\n",
"	   <PatRename Nb=\"1\"  Type=\"std::string\">  </PatRename>\n",
"	   <Rename    Nb=\"1\"  Type=\"std::string\">  </Rename>\n",
"       </OneResync>\n",
"       <EcartMin  Nb=\"1\"  Type=\"double\">  </EcartMin>\n",
"       <EcartMax  Nb=\"1\"  Type=\"double\">  </EcartMax>\n",
"\n",
"       <!-- Fontion de ponderation pour le calcul auto des diff\n",
"            \n",
"       -->\n",
"       <EcartRechAuto Nb=\"?\" Type=\"double\" Def=\"4.0\"> </EcartRechAuto>\n",
"       <SigmaRechAuto Nb=\"?\" Type=\"double\" Def=\"1.0\"> </SigmaRechAuto>\n",
"       <EcartCalcMoyRechAuto  Nb=\"?\" Type=\"double\" Def=\"1.5\"> </EcartCalcMoyRechAuto>\n",
"\n",
"   </ReSynchronImage>\n",
"\n",
"\n",
"    <!-- \n",
"    CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA \n",
"  \n",
"       Calcul Automatique de Surfaces Analytiques.\n",
"\n",
"    CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA CASA \n",
"    -->\n",
"\n",
"<!-- P0, P1 : axe of the cylinder, POnCyl : a point of the cylinder\n",
"     fixing radius and origins of cylindrics coordinates -->\n",
"\n",
"    <XmlCylindreRevolution   Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"        <!-- P0-P1 , deux points sur la droite -->\n",
"         <P0 Nb=\"1\" Type=\"Pt3dr\">  </P0>\n",
"         <P1 Nb=\"1\" Type=\"Pt3dr\">  </P1>\n",
"         <POnCyl  Nb=\"1\" Type=\"Pt3dr\"> </POnCyl>\n",
"    </XmlCylindreRevolution>\n",
"\n",
"     <XmlOrthoCyl  Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"          <Repere Nb=\"1\" RefType=\"RepereCartesien\"  RefFile=\"ParamChantierPhotogram.xml\"> </Repere>\n",
"          <P0 Nb=\"1\" Type=\"Pt3dr\"> </P0>\n",
"          <P1 Nb=\"1\" Type=\"Pt3dr\"> </P1>\n",
"          <AngulCorr Nb=\"1\" Type=\"bool\"> </AngulCorr>\n",
"     </XmlOrthoCyl>\n",
"\n",
"     <XmlDescriptionAnalytique Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"               <Cyl Nb=\"?\" RefType=\"XmlCylindreRevolution\"> </Cyl>\n",
"               <OrthoCyl Nb=\"?\" RefType=\"XmlOrthoCyl\"> </OrthoCyl>\n",
"     </XmlDescriptionAnalytique>\n",
"      <XmlOneSurfaceAnalytique Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"            <XmlDescriptionAnalytique Nb=\"1\" UnionType=\"true\" RefType=\"XmlDescriptionAnalytique\"> </XmlDescriptionAnalytique>\n",
"            <!--  Ici ne rajouteront des descripteur geometrique\n",
"                 d'emprise -->\n",
"             <Id Nb=\"1\" Type=\"std::string\"> </Id>\n",
"             <VueDeLExterieur Nb=\"1\" Type=\"bool\"> </VueDeLExterieur>\n",
"      </XmlOneSurfaceAnalytique>\n",
"\n",
"\n",
"    <XmlModeleSurfaceComplexe Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"       <XmlOneSurfaceAnalytique Nb=\"+\" RefType=\"XmlOneSurfaceAnalytique\"> </XmlOneSurfaceAnalytique>\n",
"<!--\n",
"       <XmlOneSurfaceAnalytique Nb=\"+\">\n",
"            <XmlDescriptionAnalytique Nb=\"1\" UnionType=\"true\" RefType=\"XmlDescriptionAnalytique\"> </XmlDescriptionAnalytique>\n",
"             <Id Nb=\"1\" Type=\"std::string\"> </Id>\n",
"             <VueDeLExterieur Nb=\"1\" Type=\"bool\"> </VueDeLExterieur>\n",
"       </XmlOneSurfaceAnalytique>\n",
"-->\n",
"    </XmlModeleSurfaceComplexe>\n",
"\n",
"\n",
"    <MapName2Name  Nb=\"1\"  Class=\"true\" ToReference=\"true\"  UnionType=\"true\">\n",
"          \n",
"          <MapByKey Nb=\"?\">\n",
"               <Key Nb=\"1\" Type=\"std::string\"> </Key>\n",
"               <DefIfFileNotExisting Nb=\"?\" Type=\"bool\" Def=\"false\"> </DefIfFileNotExisting>\n",
"          </MapByKey>\n",
"          <MapN2NByAutom Nb=\"?\">\n",
"               <OneAutomMapN2N Nb=\"*\" Container=\"std::vector\">\n",
"                      <MatchPattern Nb=\"1\" Type=\"cElRegex_Ptr\" > </MatchPattern>\n",
"                      <AutomSel Nb=\"?\" Type=\"cElRegex_Ptr\" > </AutomSel>\n",
"                      <Result Nb=\"1\" Type=\"std::string\"> </Result>\n",
"               </OneAutomMapN2N>\n",
"           </MapN2NByAutom>\n",
"    </MapName2Name>\n",
"\n",
"\n",
"    <XML_ParamNuage3DMaille Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"         <!-- Indique un facteur de sous resolution par rapport a une \"hypotetique\"\n",
"         valeur d'acquisition , la ref est la resol 1 en cas de correl; en correl\n",
"         les sous ech auront pour valeur 1 2 4 8 16 ...\n",
"         -->\n",
"         <SsResolRef Nb=\"?\" Type=\"double\" Def=\"1.0\"> </SsResolRef>\n",
"         <Empty Nb=\"?\" Type=\"bool\" Def=\"false\"> </Empty>  <!-- Pour traiter le cas des nuage vide -->\n",
"         <NbPixel Nb=\"1\" Type=\"Pt2di\"> </NbPixel>\n",
"         <PN3M_Nuage Nb=\"1\"   UnionType=\"true\">\n",
"             <Image_Point3D Nb=\"?\" AccessorFils=\"false\"> \n",
"                   <Image  Nb=\"1\" Type=\"std::string\"> </Image>\n",
"                   <Masq  Nb=\"1\" Type=\"std::string\"> </Masq>\n",
"             </Image_Point3D>\n",
"             <Image_Profondeur Nb=\"?\" AccessorFils=\"false\">\n",
"                   <Image  Nb=\"1\" Type=\"std::string\"> </Image>\n",
"                   <Masq  Nb=\"1\" Type=\"std::string\"> </Masq>\n",
"                   <Correl  Nb=\"?\" Type=\"std::string\"> </Correl>\n",
"                   <OrigineAlti Nb=\"1\" Type=\"double\"> </OrigineAlti>\n",
"                   <ResolutionAlti Nb=\"1\" Type=\"double\"> </ResolutionAlti>\n",
"                   <!-- PL2XmlTree evite que l'appelle ToXMLTree ait une portee globale -->\n",
"                   <GeomRestit Nb=\"1\" Type=\"eModeGeomMNT\" PL2XmlTree=\"\"> </GeomRestit>\n",
"             </Image_Profondeur>\n",
"<!--\n",
"             <Image_MNT Nb=\"?\" AccessorFils=\"false\"> \n",
"                   <Image  Nb=\"1\" Type=\"std::string\"> </Image>\n",
"                   <Masq  Nb=\"1\" Type=\"std::string\"> </Masq>\n",
"                   <OrigineAlti Nb=\"1\" Type=\"double\"> </OrigineAlti>\n",
"                   <ResolutionAlti Nb=\"1\" Type=\"double\"> </ResolutionAlti>\n",
"                   <OriginePlani Nb=\"1\" Type=\"Pt2dr\"> </OriginePlani>\n",
"                   <ResolutionPlani Nb=\"1\" Type=\"Pt2dr\"> </ResolutionPlani>\n",
"             </Image_MNT>\n",
"-->\n",
"         </PN3M_Nuage>\n",
"         <AttributsNuage3D Nb=\"*\">\n",
"                 <NameFileImage Nb=\"1\" Type=\"std::string\"> </NameFileImage>\n",
"                 <AddDir2Name Nb=\"?\" Type=\"bool\" Def=\"true\"> </AddDir2Name>\n",
"                 <Dyn Nb=\"?\" Type=\"double\" Def=\"1.0\">        </Dyn>\n",
"                 <Scale Nb=\"?\" Type=\"double\" Def=\"1.0\">      </Scale>\n",
"         </AttributsNuage3D>\n",
"\n",
"\n",
"          <!-- Parametre qui se rajoutent +ou-  a l'orientation : Rep Glob, Anam (a venir) -->\n",
"          <!-- Devrait etre une union -->\n",
"          <RepereGlob Nb=\"?\" RefType=\"RepereCartesien\"  RefFile=\"ParamChantierPhotogram.xml\"> </RepereGlob>\n",
"          <Anam Nb=\"?\" RefType=\"XmlOneSurfaceAnalytique\"> </Anam>\n",
"\n",
"\n",
"          <!-- Les infos d'origine plani et alti sont contenus dans la similitude\n",
"               de l'Orientation\n",
"           -->\n",
"          <Orientation  Nb=\"1\"   \n",
"                        RefType=\"OrientationConique\"\n",
"                        RefFile=\"ParamChantierPhotogram.xml\"\n",
"           >\n",
"           </Orientation>\n",
"\n",
"          <!-- Devrait tjrs etre init, mais pb compatibilite anterieure -->\n",
"           <RatioResolAltiPlani Nb=\"?\" Type=\"double\" Def=\"1.0\"> </RatioResolAltiPlani>\n",
"\n",
"\n",
"          <!-- Parametre specifique a un mode calcul des points, non\n",
"              inclu dans l'orientation (qui ne decrit qu'un capteur)\n",
"          -->\n",
"\n",
"          <PM3D_ParamSpecifs Nb=\"1\" UnionType=\"true\">\n",
"              <ModeFaisceauxImage Nb=\"?\">\n",
"                  <DirFaisceaux Nb=\"1\" Type=\"Pt3dr\"> </DirFaisceaux>\n",
"                  <ZIsInverse   Nb=\"1\" Type=\"bool\"> </ZIsInverse>\n",
"                  <IsSpherik    Nb=\"?\" Type=\"bool\" Def=\"false\"> </IsSpherik>\n",
"                  <DirTrans     Nb=\"?\" Type=\"Pt2dr\"> </DirTrans>\n",
"              </ModeFaisceauxImage>\n",
"              <NoParamSpecif Nb=\"?\" Type=\"std::string\"> </NoParamSpecif>\n",
"          </PM3D_ParamSpecifs>\n",
"\n",
"\n",
"           <TolVerifNuage Nb=\"?\" Type=\"double\" Def=\"1e-3\"> </TolVerifNuage>\n",
"           <VerifNuage Nb=\"*\">\n",
"                 <IndIm      Nb=\"1\" Type=\"Pt2dr\"> </IndIm>\n",
"                 <Profondeur Nb=\"1\" Type=\"double\"> </Profondeur>\n",
"                 <PointEuclid      Nb=\"1\" Type=\"Pt3dr\">   </PointEuclid>\n",
"           </VerifNuage>\n",
"\n",
"\n",
"    </XML_ParamNuage3DMaille>\n",
"\n",
"   <MasqMesures Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"         <NameFile Nb=\"1\" Type=\"std::string\"> </NameFile>\n",
"         <NameMTD Nb=\"1\" Type=\"std::string\"> </NameMTD>\n",
"   </MasqMesures>\n",
"\n",
"    <XML_ParamOmbrageNuage  Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"        <ScaleMaxPyr Nb=\"?\" Type=\"int\" Def=\"128\"> </ScaleMaxPyr>\n",
"        <StepScale      Nb=\"?\" Type=\"double\" Def=\"1.414\"> </StepScale>\n",
"        <RatioOct       Nb=\"?\" Type=\"double\" Def=\"2.0\"> </RatioOct>\n",
"        <CielVisible Nb=\"?\">\n",
"                <UnUsed Nb=\"?\" Type=\"std::string\"> </UnUsed>\n",
"        </CielVisible>\n",
"<!--\n",
"-->\n",
"    </XML_ParamOmbrageNuage>\n",
"<!--\n",
"-->\n",
"\n",
"\n",
"    <Fichier_Trajecto  Nb=\"1\"  Class=\"true\" ToReference=\"true\">\n",
"         <!-- Nom initial , pour tracabilite -->\n",
"         <NameInit Nb=\"1\" Type=\"std::string\"> </NameInit>\n",
"         \n",
"         <!-- Parametre de rotation permettant de revenir aux  coordonnees \n",
"             initiales, par exemple si passe de RGF a tangent local -->\n",
"          <FTrajParamInit2Actuelle Nb=\"1\">\n",
"               <Lambda Nb=\"1\" Type=\"double\"> </Lambda>\n",
"               <Orient Nb=\"1\"\n",
"                       RefType=\"OrientationExterneRigide\"\n",
"                       RefFile=\"ParamChantierPhotogram.xml\"\n",
"               >\n",
"               </Orient>\n",
"               \n",
"          </FTrajParamInit2Actuelle>\n",
"          <PtTrajecto Nb=\"*\" \n",
"                      Container=\"std::map\" \n",
"                      KeyType=\"std::string\" \n",
"                      KeyGetVal=\"IdImage\"\n",
"          > \n",
"<!-- \n",
"<PtTrajecto Nb=\"*\" Container=\"std::vector\">\n",
"-->\n",
"              <Pt Nb=\"1\" Type=\"Pt3dr\"> </Pt>\n",
"              <IdImage Nb=\"1\" Type=\"std::string\">  </IdImage>\n",
"              <IdBande Nb=\"1\" Type=\"std::string\">  </IdBande>\n",
"              <Time Nb=\"1\" Type=\"double\"> </Time>\n",
"          </PtTrajecto>\n",
"    </Fichier_Trajecto>\n",
"\n",
"\n",
"<!--    \n",
"      ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO\n",
"      ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO\n",
"      ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO - ORTHO\n",
"-->\n",
"\n",
"    <CreateOrtho  Nb=\"1\"  Class=\"true\">\n",
"        <!-- Truc +ou- genreaux a ttes les applis -->\n",
"        <DicoLoc  Nb=\"?\" RefType=\"ChantierDescripteur\"\n",
"                   RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </DicoLoc>\n",
"	<FileChantierNameDescripteur Nb=\"?\" Type=\"string\"> </FileChantierNameDescripteur>\n",
"        <WorkDir Nb=\"1\" Type=\"std::string\">   </WorkDir>   \n",
"\n",
"         <KBox0 Nb=\"?\" Type=\"int\" Def=\"0\"> </KBox0>\n",
"\n",
"\n",
"        <SectionEntree Nb=\"1\">\n",
"           <FileMNT Nb=\"?\" Type=\"std::string\" > </FileMNT>\n",
"           <KeySetIm Nb=\"1\" Type=\"std::string\"> </KeySetIm>\n",
"           <KeyAssocMetaData  Nb=\"1\" Type=\"std::string\"> </KeyAssocMetaData>\n",
"           <KeyAssocNamePC  Nb=\"1\" Type=\"std::string\"> </KeyAssocNamePC>\n",
"           <KeyAssocNameIncH  Nb=\"1\" Type=\"std::string\"> </KeyAssocNameIncH>\n",
"\n",
"            <!-- Plus la valeur est faible plus c'est prioritaire -->\n",
"           <KeyAssocPriorite  Nb=\"?\" Type=\"std::string\" Def=\"Key-Priorite-Ortho\"> </KeyAssocPriorite>\n",
"\n",
"           <!-- Permet de rejouter un (ou plusieurs qui s'accumulent) masque binaire  qui sont utilises\n",
"                pour selectionner les points utilises pour les mesures : ca ne masque pas l'ortho finale\n",
"             -->\n",
"           <ListMasqMesures Nb=\"*\" RefType=\"MasqMesures\"> </ListMasqMesures> \n",
"            <!-- Idem MasqMesures, mais fichier a charger -->\n",
"           <FileExterneMasqMesures Nb=\"*\" Type=\"std::string\"></FileExterneMasqMesures>\n",
"\n",
"        </SectionEntree>\n",
"\n",
"         <SectionFiltrageIn Nb=\"1\">\n",
"             <!-- When this value is specified for any pixel with any channel over this threshold, it will be out of mask -->\n",
"             <SaturThreshold Nb=\"?\" Type=\"double\"> </SaturThreshold>\n",
"             <SzDilatPC Nb=\"?\" Type=\"int\" Def=\"1\"> </SzDilatPC>\n",
"             <SzOuvPC Nb=\"?\" Type=\"int\" Def=\"2\"> </SzOuvPC>\n",
"\n",
"             <BoucheTrou Nb=\"?\">\n",
"                <SeuilVisib Nb=\"?\" Type=\"int\" Def=\"10\"> </SeuilVisib>\n",
"                <SeuilVisibBT Nb=\"?\" Type=\"int\" Def=\"3\"> </SeuilVisibBT>\n",
"                <CoeffPondAngul Nb=\"?\" Type=\"double\" Def=\"1.57\"> </CoeffPondAngul>\n",
"             </BoucheTrou>\n",
"         </SectionFiltrageIn>\n",
"\n",
"         <SectionSorties Nb=\"1\">\n",
"             <!-- Pour Debug uniquement -->\n",
"             <TestDiff Nb=\"?\" Type=\"bool\" Def=\"false\"> </TestDiff>\n",
"             <NameOrtho Nb=\"1\" Type=\"std::string\"> </NameOrtho>\n",
"             <NameLabels Nb=\"?\" Type=\"std::string\"> </NameLabels>\n",
"             <BoxCalc Nb=\"?\" Type=\"Box2di\">        </BoxCalc>\n",
"             <SzDalle   Nb=\"1\"  Type=\"int\">        </SzDalle>\n",
"             <SzBrd  Nb=\"1\"  Type=\"int\">           </SzBrd>\n",
"             <SzTileResult Nb=\"?\" Type=\"int\" Def=\"17000\"> </SzTileResult>\n",
"\n",
"             <Show Nb=\"?\" Type=\"bool\" Def=\"false\"> </Show>\n",
"\n",
"             <DynGlob Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DynGlob>\n",
"         </SectionSorties>\n",
"\n",
"         <SectionSimulImage Nb=\"?\">\n",
"              <Per1 Nb=\"1\" Type=\"Pt2dr\"> </Per1>\n",
"              <Per2 Nb=\"?\" Type=\"Pt2dr\"> </Per2>\n",
"              <Ampl Nb=\"?\" Type=\"double\" Def=\"1.0\"> </Ampl>\n",
"              <NoiseSSI Nb=\"*\">\n",
"                    <Ampl Nb=\"1\" Type=\"double\"> </Ampl>\n",
"                    <Unif Nb=\"1\" Type=\"bool\"> </Unif>\n",
"                    <Iter Nb=\"1\" Type=\"int\">    </Iter>\n",
"                    <Sz Nb=\"1\" Type=\"int\">    </Sz>\n",
"              </NoiseSSI>\n",
"         </SectionSimulImage>\n",
"\n",
"\n",
"         <SectionEgalisation Nb=\"?\">\n",
"               <MasqApprent Nb=\"?\" RefType=\"MasqTerrain\"> </MasqApprent>\n",
"\n",
"               <PeriodEchant Nb=\"?\" Type=\"int\"> </PeriodEchant>\n",
"               <NbPEqualMoyPerImage Nb=\"?\" Type=\"double\" Def=\"1e4\"> </NbPEqualMoyPerImage>\n",
"               <SzVois  Nb=\"1\" Type=\"int\"> </SzVois>\n",
"               <NameFileMesures Nb=\"1\" Type=\"std::string\"></NameFileMesures>\n",
"               <UseFileMesure Nb=\"?\" Type=\"bool\" Def=\"false\"> </UseFileMesure>\n",
"               <DegresEgalVois Nb=\"+\" Type=\"Pt2di\"  Container=\"std::vector\"> </DegresEgalVois>\n",
"               <!-- Si au - un fixe les degres des canaux apres le 1er, -->\n",
"               <DegresEgalVoisSec Nb=\"*\" Type=\"Pt2di\"  Container=\"std::vector\"> </DegresEgalVoisSec>\n",
"               <PdsRappelInit Nb=\"?\" Type=\"double\" Def=\"1e-3\"> </PdsRappelInit>\n",
"               <PdsSingularite Nb=\"?\" Type=\"double\" Def=\"1e-6\"> </PdsSingularite>\n",
"               <GlobRappInit Nb=\"1\"> \n",
"                    <DoGlob Nb=\"?\" Type=\"bool\" Def=\"true\"> </DoGlob>\n",
"                    <Degres Nb=\"+\" Type=\"Pt2di\"  Container=\"std::vector\"> </Degres>\n",
"                    <!-- Si cannaux independant et ne joue pas le meme role (par ex aprs LAB)\n",
"                    fixe les degres des cannaux \"secondaire\" (=apres le premier) -->  \n",
"                    <DegresSec Nb=\"*\" Type=\"Pt2di\"  Container=\"std::vector\"> </DegresSec>\n",
"                    <PatternApply Nb=\"?\" Type=\"std::string\" Def=\".*\"> </PatternApply>\n",
"                    <!-- Si vrai, le rappel ne se fait sur les signaux eux meme mais\n",
"                    sur le resultat d'une egalisation basique (une seule cste mult) +ou-\n",
"                    ce qu'on obtient avec prise en compte de ISO,Diaph,Vitesse mais\n",
"                    + general\n",
"                    -->\n",
"                    <RapelOnEgalPhys Nb=\"?\" Type=\"bool\" Def=\"true\"> </RapelOnEgalPhys>\n",
"\n",
"               </GlobRappInit>\n",
"               <!-- Si true les cannau sont egalise globalement (pour l'instant sur la somme -->\n",
"               <EgaliseSomCh Nb=\"1\" Type=\"bool\"> </EgaliseSomCh>\n",
"\n",
"\n",
"               <!-- Filtrage des points par correlation  : abandonne pour l'instant-->\n",
"                <SzMaxVois Nb=\"?\" Type=\"int\" Def=\"5\"> </SzMaxVois>\n",
"                <Use4Vois Nb=\"?\" Type=\"bool\" Def=\"true\"> </Use4Vois>\n",
"                <CorrelThreshold Nb=\"?\" Type=\"double\" Def=\"0.7\"> </CorrelThreshold>\n",
"\n",
"               <!-- Filtrage robuste par couple -->\n",
"                <AdjL1ByCple Nb=\"?\" Type=\"bool\" Def=\"true\"> </AdjL1ByCple>\n",
"                <PercCutAdjL1 Nb=\"?\" Type=\"double\" Def=\"70\"> </PercCutAdjL1>\n",
"                 <!-- Possibilite de limiter le facteur de coupe -->\n",
"                <FactMajorByCutGlob Nb=\"?\" Type=\"double\" Def=\"1.5\"> </FactMajorByCutGlob>\n",
"\n",
"         </SectionEgalisation>\n",
"    </CreateOrtho>\n",
"\n",
"  <MetaDataPartiesCachees Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"       <Done  Nb=\"1\" Type=\"bool\"> </Done>\n",
"       <Offset Nb=\"1\" Type=\"Pt2di\"> </Offset>\n",
"       <Sz Nb=\"1\" Type=\"Pt2di\"> </Sz>\n",
"       <Pas Nb=\"1\" Type=\"double\">  </Pas>\n",
"       <SeuilUse  Nb=\"1\" Type=\"int\">  </SeuilUse>\n",
"       <SsResolIncH Nb=\"?\" Type=\"double\"> </SsResolIncH>\n",
"  </MetaDataPartiesCachees>\n",
"\n",
"  <PVPN_Orientation Nb=\"1\" UnionType=\"true\"  Class=\"true\" ToReference=\"true\">\n",
"       <!-- 1- Basique,  on donne directement les trois angle du cardan -->\n",
"         <AngleCardan Nb=\"?\" Type=\"Pt3dr\"> </AngleCardan>  \n",
"  </PVPN_Orientation>\n",
"\n",
"  <ParamVisuProjNuage Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"       <WorkDir Nb=\"1\" Type=\"std::string\">   </WorkDir>   \n",
"       <DicoLoc  Nb=\"?\" RefType=\"ChantierDescripteur\"\n",
"                   RefFile=\"ParamChantierPhotogram.xml\"\n",
"       >\n",
"       </DicoLoc>\n",
"       <FileChantierNameDescripteur Nb=\"?\" Type=\"string\"> \n",
"       </FileChantierNameDescripteur>\n",
"\n",
"\n",
"       <PVPN_ImFixe Nb=\"?\">\n",
"           <Orient Nb=\"1\" RefType=\"PVPN_Orientation\"> </Orient>\n",
"           <Name Nb=\"1\"  Type=\"std::string\"></Name>\n",
"       </PVPN_ImFixe>\n",
"       <PVPN_Camera Nb=\"1\">\n",
"            <NbPixel Nb=\"1\" Type=\"Pt2di\"> </NbPixel>\n",
"            <!-- En radian -->\n",
"            <AngleDiag Nb=\"1\" Type=\"double\"> </AngleDiag> \n",
"       </PVPN_Camera>\n",
"       <PVPN_Fond Nb=\"1\"  UnionType=\"true\">\n",
"             <!-- RVB entre 0 et 1 -->\n",
"             <FondConstant Nb=\"?\" Type=\"Pt3dr\"> </FondConstant>  \n",
"       </PVPN_Fond>\n",
"       <PVPN_Nuages Nb=\"*\">\n",
"             <Name Nb=\"1\" Type=\"std::string\"> </Name>\n",
"       </PVPN_Nuages>\n",
"\n",
"       <!-- Sous echantillonage utilise pour accelerer certaine operation -->\n",
"       <SousEchQuickN Nb=\"?\" Type=\"double\" Def=\"10\"> </SousEchQuickN>\n",
"\n",
"  </ParamVisuProjNuage>\n",
"\n",
"  <PoinAvionJaune  Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"          <x Nb=\"1\" Type=\"double\"> </x>\n",
"          <y Nb=\"1\" Type=\"double\"> </y>\n",
"  </PoinAvionJaune>\n",
"  <ValueAvionJaune Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"       <unit Nb=\"1\" Type=\"std::string\"></unit>\n",
"       <source Nb=\"?\" Type=\"std::string\"></source>\n",
"       <biaisCorrige Nb=\"?\" Type=\"double\"></biaisCorrige>\n",
"       <value Nb=\"1\" Type=\"double\"></value>\n",
"  </ValueAvionJaune>\n",
"  <ValueXYAvionJaune Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"       <unit Nb=\"1\" Type=\"std::string\"></unit>\n",
"       <source Nb=\"?\" Type=\"std::string\"></source>\n",
"       <biaisCorrige Nb=\"?\" Type=\"double\"></biaisCorrige>\n",
"       <xvalue Nb=\"1\" Type=\"double\"></xvalue>\n",
"       <yvalue Nb=\"1\" Type=\"double\"></yvalue>\n",
"  </ValueXYAvionJaune>\n",
"\n",
"\n",
"  <AvionJauneDocument Nb=\"1\" Class=\"true\" ToReference=\"true\">\n",
"          <numeroImage Nb=\"1\" Type=\"std::string\" ></numeroImage>\n",
"          <navigation Nb=\"1\">\n",
"               <systemeGeodesique Nb=\"1\" Type=\"std::string\"></systemeGeodesique>\n",
"               <projection  Nb=\"1\" Type=\"std::string\"></projection>\n",
"               <sommet Nb=\"1\" RefType=\"PoinAvionJaune\"> </sommet>\n",
"               <altitude Nb=\"1\" RefType=\"ValueAvionJaune\"> </altitude>\n",
"               <capAvion Nb=\"1\" RefType=\"ValueAvionJaune\"> </capAvion>\n",
"               <roulisAvion Nb=\"1\" RefType=\"ValueAvionJaune\"> </roulisAvion>\n",
"               <tangageAvion Nb=\"1\" RefType=\"ValueAvionJaune\"> </tangageAvion>\n",
"               <tempsAutopilote Nb=\"1\" RefType=\"ValueAvionJaune\"> </tempsAutopilote>\n",
"          </navigation>\n",
"          <image Nb=\"1\">\n",
"               <focale Nb=\"1\" RefType=\"ValueAvionJaune\"></focale>\n",
"               <ouverture Nb=\"1\" RefType=\"ValueAvionJaune\"> </ouverture>\n",
"               <tempsDExposition Nb=\"1\" RefType=\"ValueAvionJaune\"> </tempsDExposition>\n",
"          </image>\n",
"          <geometrieAPriori Nb=\"1\">\n",
"               <hauteur Nb=\"1\" RefType=\"ValueAvionJaune\"> </hauteur>\n",
"               <resolution Nb=\"1\" RefType=\"ValueXYAvionJaune\"> </resolution>\n",
"               <orientationAPN Nb=\"1\" RefType=\"ValueAvionJaune\"> </orientationAPN>\n",
"               <coin Nb=\"+\"  RefType=\"PoinAvionJaune\" Container=\"std::vector\"> </coin>\n",
"          </geometrieAPriori>\n",
"   </AvionJauneDocument>\n",
"\n",
"\n",
"<!--\n",
"-->\n",
"\n",
"  <TrAJ2_GenerateOrient Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"                  <Teta1FromCap Nb=\"?\" Type=\"bool\" Def=\"false\"> </Teta1FromCap>\n",
"                  <CorrecDelayGps Nb=\"?\" Type=\"double\"> </CorrecDelayGps>\n",
"\n",
"                  <ModeMatrix Nb=\"?\" Type=\"bool\" Def=\"false\"> </ModeMatrix>\n",
"                  <KeyName Nb=\"+\" Type=\"std::string\"> </KeyName>\n",
"                  <SysCible Nb=\"1\" RefType=\"SystemeCoord\" RefFile=\"ParamChantierPhotogram.xml\"> </SysCible>\n",
"                  <NameCalib Nb=\"1\" Type=\"std::string\"> </NameCalib>\n",
"                  <AltiSol Nb=\"1\" Type=\"double\">        </AltiSol>\n",
"  </TrAJ2_GenerateOrient>\n",
"\n",
"   \n",
"  <TrAJ2_ModeliseVitesse Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"                       <DeltaTimeMax Nb=\"1\" Type=\"double\"> </DeltaTimeMax>\n",
"  </TrAJ2_ModeliseVitesse>\n",
"\n",
"\n",
"  <Param_Traj_AJ  Nb=\"1\" Class=\"true\">\n",
"        <DicoLoc  Nb=\"?\" RefType=\"ChantierDescripteur\"\n",
"                         RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </DicoLoc>\n",
"\n",
"        <TrAJ2_SectionImages Nb=\"*\">\n",
"              <ConvOrCam Nb=\"?\" Type=\"eConventionsOrientation\" Def=\"eConvOriLib\"> </ConvOrCam>\n",
"              <OrientationCamera Nb=\"1\" RefType=\"RotationVect\" RefFile=\"ParamChantierPhotogram.xml\"> </OrientationCamera>\n",
"              <KeySetIm Nb=\"1\" Type=\"std::string\"> </KeySetIm>\n",
"              <Id Nb=\"1\" Type=\"std::string\"> </Id>\n",
"        </TrAJ2_SectionImages>\n",
"\n",
"        <TraceImages Nb=\"?\" Type=\"cElRegex_Ptr\"> </TraceImages>\n",
"        <TraceLogs Nb=\"?\" Type=\"cElRegex_Ptr\"> </TraceLogs>\n",
"\n",
"\n",
"        <TrAJ2_SectionLog Nb=\"*\">\n",
"\n",
"             <GenerateTabExemple Nb=\"*\">\n",
"                    <Name Nb=\"1\" Type=\"std::string\"> </Name>\n",
"                    <Nb  Nb=\"1\" Type=\"Pt3di\"> </Nb>\n",
"                    <ZMin  Nb=\"?\" Type=\"double\"> </ZMin>\n",
"                    <ZMax  Nb=\"?\" Type=\"double\"> </ZMax>\n",
"                    <DIntervZ  Nb=\"?\" Type=\"double\" Def=\"0.0\"> </DIntervZ>\n",
"                    <RandomXY Nb=\"?\" Type=\"bool\" Def=\"true\"> </RandomXY>\n",
"                    <RandomZ  Nb=\"?\" Type=\"bool\" Def=\"true\"> </RandomZ>\n",
"             </GenerateTabExemple>\n",
"\n",
"             <TimeMin Nb=\"?\" Type=\"double\"> </TimeMin> <!-- Vire les temps <, Serait utile avec Learn Stat si plein de 0 au depart -->\n",
"             <KLogT0 Nb=\"?\" Type=\"int\" Def=\"0\"> </KLogT0>  <!-- Indice du log donnant temps a soustraire, pour ramner des valeurs raisonnable -->\n",
"             <File Nb=\"1\" Type=\"std::string\">   </File>\n",
"             <Autom  Nb=\"1\" Type=\"std::string\">   </Autom>\n",
"             <SysCoord Nb=\"1\" RefType=\"SystemeCoord\" RefFile=\"ParamChantierPhotogram.xml\"> </SysCoord>\n",
"             <Id Nb=\"1\" Type=\"std::string\"> </Id>\n",
"\n",
"             <SectionTime Nb=\"1\"  UnionType=\"true\">\n",
"                   <NoTime Nb=\"?\" Type=\"std::string\"> </NoTime>  <!-- Typiquement si la log contient -->\n",
"                   <KTime Nb=\"?\" Type=\"int\"> </KTime>  <!-- Mode Avion jaune , 1 seul double de temps -->\n",
"                   <FullDate Nb=\"?\">\n",
"                           <!-- Moi annees jours sont optionnels -->\n",
"                           <KYear Nb=\"?\" Type=\"int\">   </KYear>\n",
"                           <DefYear Nb=\"?\" Type=\"int\" Def=\"2011\"> </DefYear>\n",
"\n",
"                           <KMonth Nb=\"?\" Type=\"int\">  </KMonth>\n",
"                           <DefMonth Nb=\"?\" Type=\"int\" Def=\"1\"> </DefMonth>\n",
"\n",
"                           <KDay Nb=\"?\" Type=\"int\">    </KDay>\n",
"                           <DefDay Nb=\"?\" Type=\"int\" Def=\"1\"> </DefDay>\n",
"\n",
"                           <KHour Nb=\"1\" Type=\"int\">    </KHour>\n",
"                           <KMin  Nb=\"1\" Type=\"int\">    </KMin>\n",
"                           <KSec  Nb=\"1\" Type=\"int\">    </KSec>\n",
"                           <DivSec Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DivSec>  <!-- Convention Survey en 1/100 sec -->\n",
"                           <KMiliSec  Nb=\"?\" Type=\"int\">    </KMiliSec>\n",
"                           <DivMiliSec Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DivMiliSec>\n",
"\n",
"                   </FullDate>\n",
"             </SectionTime>\n",
"\n",
"             <KCoord1 Nb=\"1\" Type=\"int\"> </KCoord1>     <!-- Longitude -->\n",
"             <DivCoord1 Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DivCoord1>\n",
"             <KCoord2 Nb=\"1\" Type=\"int\">  </KCoord2>  <!-- Latitude  -->\n",
"             <DivCoord2 Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DivCoord2>\n",
"             <KCoord3 Nb=\"1\" Type=\"int\">  </KCoord3>\n",
"             <DivCoord3 Nb=\"?\" Type=\"double\" Def=\"1.0\"> </DivCoord3>\n",
"\n",
"             <!--  -->\n",
"             <UnitesCoord Nb=\"*\" Type=\"eUniteAngulaire\" RefFile=\"ParamChantierPhotogram.xml\" Container=\"std::vector\"> </UnitesCoord>\n",
"\n",
"             <TrajAngles Nb=\"?\">\n",
"                 <Unites Nb=\"1\" Type=\"eUniteAngulaire\" RefFile=\"ParamChantierPhotogram.xml\"> </Unites>\n",
"                 <ConvOr Nb=\"1\" Type=\"eConventionsOrientation\" RefFile=\"ParamChantierPhotogram.xml\"> </ConvOr>\n",
"                 <KTeta1  Nb=\"1\" Type=\"int\"> </KTeta1>       <!-- = Teta Z = Teta12   = Yaw = ? Cap -->\n",
"                 <!-- Si <0, Teta2 et Teta3 valent 0.0 -->\n",
"                 <KTeta2  Nb=\"1\" Type=\"int\"> </KTeta2>       <!-- = Teta Y = Teta13   = Pitch =? Roulis -->\n",
"                 <KTeta3  Nb=\"1\" Type=\"int\"> </KTeta3>       <!-- = Teta X = Teta23   = Roll  =? Tangage  -->\n",
"\n",
"                  <!-- Pour la declinaison magnetique : EN RADIAN !!!!!     -->\n",
"                 <OffsetTeta1 Nb=\"?\" Type=\"double\" Def=\"0\"> </OffsetTeta1>\n",
"                 <OffsetTeta2 Nb=\"?\" Type=\"double\" Def=\"0\"> </OffsetTeta2>\n",
"                 <OffsetTeta3 Nb=\"?\" Type=\"double\" Def=\"0\"> </OffsetTeta3>\n",
"\n",
"                 <!-- Souvent les angles sont donnes par rapport a un systeme different du systeme carto\n",
"                      Donne une matrice de passage INS -> Carto \n",
"                 -->\n",
"                 <RefOrTrajI2C Nb=\"?\" RefType=\"RotationVect\" RefFile=\"ParamChantierPhotogram.xml\"> </RefOrTrajI2C>\n",
"             </TrajAngles>\n",
"\n",
"              <!-- Pour les cas faciles ou les logs contiennent deja un identifiant d'image -->\n",
"             <GetImInLog Nb=\"?\">\n",
"                   <KIm Nb=\"1\" Type=\"int\"> </KIm>\n",
"             </GetImInLog>\n",
"\n",
"      </TrAJ2_SectionLog>\n",
"\n",
"\n",
"\n",
"        <!-- Section de Match par le temps -->\n",
"       \n",
"        <TrAJ2_SectionMatch Nb=\"*\">\n",
"              <IdIm Nb=\"1\" Type=\"std::string\">  </IdIm>\n",
"              <IdLog Nb=\"1\" Type=\"std::string\"> </IdLog>\n",
"\n",
"              <!-- Requis par tous les algo de match sur le temps , interdit en MatchByName -->\n",
"              <LearnOffset Nb=\"?\" UnionType=\"true\">\n",
"                    <LearnByExample Nb=\"?\">\n",
"                          <!-- Im0-Log0 est un couple pour lequel on est sur du match -->\n",
"                          <Im0 Nb=\"1\" Type=\"std::string\">   </Im0>\n",
"                          <Log0 Nb=\"1\" Type=\"int\">  </Log0>\n",
"                          <DeltaMinRech  Nb=\"1\" Type=\"int\">     </DeltaMinRech>\n",
"                          <DeltaMaxRech  Nb=\"1\" Type=\"int\">     </DeltaMaxRech>\n",
"                          <Show  Nb=\"?\" Type=\"bool\" Def=\"false\">     </Show>\n",
"                          <ShowPerc  Nb=\"?\" Type=\"bool\" Def=\"true\">     </ShowPerc>\n",
"                    </LearnByExample>\n",
"                    <!-- L'offset est simplement le temps qui maximise le nombre\n",
"                         de match comrise entre t1 et  t2+Ofs+[-MaxEcart,MaxEcart]\n",
"                    -->\n",
"                    <LearnByStatDiff Nb=\"?\">\n",
"                           <MaxEcart Nb=\"?\" Type=\"double\" Def=\"0.52\"> </MaxEcart>\n",
"                    </LearnByStatDiff>\n",
"              </LearnOffset>\n",
"\n",
"              <AlgoMatch  Nb=\"1\" UnionType=\"true\">\n",
"                  <MatchNearestIm Nb=\"?\">\n",
"                          <!-- Pour etre \"sur\", on va prendre par exe TolMatch= 0.6 \n",
"                               et TolAmbig = 0.8, afin de selectionner des match bon et non ambigus\n",
"                          -->\n",
"                          <TolMatch  Nb=\"1\" Type=\"double\">     </TolMatch>\n",
"                          <TolAmbig  Nb=\"1\" Type=\"double\">     </TolAmbig>\n",
"                   </MatchNearestIm>\n",
"                   <MatchByName Nb=\"?\">\n",
"                        <KeyLog2Im Nb=\"1\" Type=\"std::string\"> </KeyLog2Im>\n",
"                   </MatchByName>\n",
"              </AlgoMatch>\n",
"              <ModeliseVitesse Nb=\"?\" RefType=\"TrAJ2_ModeliseVitesse\"> </ModeliseVitesse>\n",
"              <GenerateOrient Nb=\"?\" RefType=\"TrAJ2_GenerateOrient\"> </GenerateOrient>\n",
"        </TrAJ2_SectionMatch>\n",
"\n",
"\n",
"        <TrAJ2_ConvertionAppuis Nb=\"*\">\n",
"             <Id Nb=\"1\" Type=\"std::string\"> </Id>\n",
"\n",
"             <TraJ2_FilesInputi_Appuis Nb=\"+\">\n",
"                  <KeySetOrPat Nb=\"1\" Type=\"std::string\"> </KeySetOrPat>\n",
"                  <Autom Nb=\"1\" Type=\"cElRegex_Ptr\"> </Autom>\n",
"                  <GetMesTer Nb=\"1\" Type=\"bool\">   </GetMesTer>\n",
"                  <GetMesIm Nb=\"1\" Type=\"bool\">   </GetMesIm>\n",
"                  <KIdPt Nb=\"1\" Type=\"int\">  </KIdPt>\n",
"             </TraJ2_FilesInputi_Appuis>\n",
"\n",
"\n",
"             <!-- Si les deux meme, alors Concat ds le meme fichier -->\n",
"             <OutMesTer Nb=\"?\" Type=\"std::string\"> </OutMesTer>\n",
"             <OutMesIm Nb=\"?\" Type=\"std::string\"> </OutMesIm>\n",
"\n",
"             <AutomComment  Nb=\"?\" Type=\"cElRegex_Ptr\">   </AutomComment>\n",
"\n",
"             <UnitesCoord Nb=\"*\" Type=\"eUniteAngulaire\" RefFile=\"ParamChantierPhotogram.xml\" Container=\"std::vector\"> </UnitesCoord>\n",
"\n",
"             <KIncertPlani Nb=\"?\" Type=\"int\" Def=\"-1\">  </KIncertPlani>\n",
"             <KIncertAlti Nb=\"?\" Type=\"int\" Def=\"-1\">  </KIncertAlti>\n",
"             <ValIncertPlani Nb=\"?\" Type=\"double\" Def=\"1.0\"> </ValIncertPlani>\n",
"             <ValIncertAlti Nb=\"?\" Type=\"double\" Def=\"1.0\"> </ValIncertAlti>\n",
"             <KxTer Nb=\"1\" Type=\"int\">  </KxTer>\n",
"             <KyTer Nb=\"1\" Type=\"int\">  </KyTer>\n",
"             <KzTer Nb=\"1\" Type=\"int\">  </KzTer>\n",
"             <KIIm Nb=\"1\" Type=\"int\">  </KIIm>\n",
"             <KJIm Nb=\"1\" Type=\"int\">  </KJIm>\n",
"             <KIdIm  Nb=\"1\" Type=\"int\">  </KIdIm>\n",
"\n",
"             <OffsetIm Nb=\"?\" Type=\"Pt2di\" Def=\"Pt2di(0,0)\">    </OffsetIm>\n",
"             <KeyId2Im  Nb=\"1\"  Type=\"std::string\"> </KeyId2Im>\n",
"             <SystemeIn Nb=\"1\" RefType=\"SystemeCoord\" RefFile=\"ParamChantierPhotogram.xml\"> </SystemeIn>\n",
"             <SystemeOut Nb=\"1\" RefType=\"SystemeCoord\" RefFile=\"ParamChantierPhotogram.xml\"> </SystemeOut>\n",
"        </TrAJ2_ConvertionAppuis>\n",
"\n",
"        <TrAJ2_ExportProjImage Nb=\"*\">\n",
"              <NameFileOut Nb=\"1\" Type=\"std::string\"> </NameFileOut>\n",
"              <KeySetOrPatIm Nb=\"1\" Type=\"std::string\"> </KeySetOrPatIm>\n",
"              <NameAppuis Nb=\"1\" Type=\"std::string\"> </NameAppuis> <!-- Flottants -->\n",
"              <KeyAssocIm2Or Nb=\"1\" Type=\"std::string\"> </KeyAssocIm2Or>\n",
"                          <!-- Im@App@I@J@X@Y@Z -->\n",
"              <KeyGenerateTxt Nb=\"?\" Type=\"std::string\"> </KeyGenerateTxt>\n",
"        </TrAJ2_ExportProjImage>\n",
"\n",
"\n",
"  </Param_Traj_AJ>\n",
"\n",
"  <!-- Pour generer un ensemble de chaine; est l'union des KeySet (ensembles de filtres \n",
"       sur des fichiers existant) et des chaine literrale KeyString; encapsulee par GetStrFromGenStr\n",
"  -->\n",
"  <ParamGenereStr Nb=\"1\"  Class=\"true\"  ToReference=\"true\"  UnionType=\"true\">\n",
"         <KeySet Nb=\"*\"  Type=\"std::string\"> </KeySet> \n",
"         <KeyString Nb=\"*\"  Type=\"std::string\"> </KeyString> \n",
"  </ParamGenereStr>\n",
"\n",
"   <!--  Pour genere les chaines de caracters \"voisine\" d'une autre; ces voisins sont fait des voisins\n",
"        \"fixes\", calcule comme ParamGenereStr, et de voisin \"variable\" calcules par KeyRel;\n",
"         encapsule dans la fonction GetStrFromGenStrRel\n",
"    -->\n",
"  <ParamGenereStrVois Nb=\"1\"  Class=\"true\"  ToReference=\"true\"  UnionType=\"true\">\n",
"         <KeyRel Nb=\"*\"  Type=\"std::string\"> </KeyRel> \n",
"         <KeyString Nb=\"*\"  Type=\"std::string\"> </KeyString> \n",
"         <KeySet Nb=\"*\"  Type=\"std::string\"> </KeySet> \n",
"         <UseIt Nb=\"?\" Type=\"bool\" Def=\"false\"> </UseIt> <!-- Pour anihilier dans EtapeMEC -->\n",
"  </ParamGenereStrVois>\n",
"\n",
"\n",
"  <ParamFiltreDetecRegulProf Nb=\"1\" Class=\"true\"   ToReference=\"true\">\n",
"         <SzCC Nb=\"?\" Type=\"int\" Def=\"2\"> </SzCC>\n",
"         <PondZ Nb=\"?\" Type=\"double\" Def=\"2.0\"> </PondZ>\n",
"         <Pente Nb=\"?\" Type=\"double\" Def=\"0.5\"> </Pente>\n",
"         <SeuilReg Nb=\"?\" Type=\"double\" Def=\"0.5\"> </SeuilReg>\n",
"         <V4 Nb=\"?\" Type=\"bool\" Def=\"false\"> </V4>\n",
"         <NbCCInit Nb=\"?\" Type=\"int\" Def=\"5\"> </NbCCInit>\n",
"         <NameTest Nb=\"?\" Type=\"std::string\"> </NameTest>\n",
"  </ParamFiltreDetecRegulProf>\n",
"\n",
"  <ParamFusionMNT  Nb=\"1\" Class=\"true\">\n",
"       <DicoLoc  Nb=\"?\" RefType=\"ChantierDescripteur\"\n",
"                         RefFile=\"ParamChantierPhotogram.xml\"\n",
"        >\n",
"        </DicoLoc>\n",
"\n",
"       <SectionName Nb=\"1\">\n",
"\n",
"             <!-- calcule le nuage carte de prof input a partir de deux noms de fichiers l'un venant de\n",
"                  GenereRes , l'autre de GenereInput \n",
"             -->\n",
"             <KeyNuage Type=\"std::string\" Nb=\"1\"> </KeyNuage>\n",
"             <!-- Doit genere le nom du fichier XML-resultat, a partir d'un declencheur -->\n",
"             <KeyResult   Type=\"std::string\" Nb=\"1\"> </KeyResult>\n",
"\n",
"             <!-- Definit le modele de geometrie resultant, c'est un cle d'association\n",
"                 par defaut il sera pris sur le premier input-->\n",
"             <ModeleNuageResult Type=\"std::string\" Nb=\"?\"> </ModeleNuageResult>\n",
"       </SectionName>\n",
"\n",
"       <!-- Pour gerer le score pas toujours simple fonction de correlation -->\n",
"       <SectionScoreQualite Nb=\"?\" UnionType=\"true\">\n",
"           <ScoreMM1P Nb=\"?\">\n",
"                 <MakeFileResult Nb=\"?\" Type=\"bool\" Def=\"false\"> </MakeFileResult>\n",
"                 <PdsAR Nb=\"?\" Type=\"double\" Def=\"1.0\"> </PdsAR>\n",
"\n",
"                 <PdsDistor Nb=\"?\" Type=\"double\" Def=\"0.5\"> </PdsDistor>\n",
"                 <AmplImDistor Nb=\"?\" Type=\"double\" Def=\"100.0\"> </AmplImDistor>\n",
"                 <!-- Score = Seuil/ (Seuil+Dist) -->\n",
"                 <SeuilDist  Nb=\"?\"  Type=\"double\" Def=\"0.5\"> </SeuilDist>\n",
"                 \n",
"                 <PdsDistBord Nb=\"?\" Type=\"double\" Def=\"0.25\"> </PdsDistBord>\n",
"                 <!-- Score = Min(1, D/Seuil) -->\n",
"                 <SeuilDisBord  Nb=\"?\" Type=\"double\" Def=\"3.0\"> </SeuilDisBord>\n",
"           </ScoreMM1P>\n",
"       </SectionScoreQualite>\n",
"\n",
"\n",
"       <ParamAlgoFusionMNT Nb=\"1\">\n",
"           <FMNTSeuilCorrel Nb=\"1\" Type=\"double\"> </FMNTSeuilCorrel>\n",
"           <FMNTGammaCorrel Nb=\"1\" Type=\"double\"> </FMNTGammaCorrel>\n",
"           <SpecAlgoFMNT Nb=\"1\">\n",
"                <SigmaPds  Type=\"double\" Nb=\"1\"> </SigmaPds>\n",
"                <SigmaZ    Type=\"double\" Nb=\"?\"> </SigmaZ> <!-- Par defaut SigmaZ=SigmaPds -->\n",
"                <SeuilMaxLoc Type=\"double\" Nb=\"1\"> </SeuilMaxLoc> <!-- Utilise pour selction MaxLoc -->\n",
"                <SeuilCptOk Type=\"double\" Nb=\"1\"> </SeuilCptOk> <!-- Utilise pour Compteur Nb Image -->\n",
"                <MaxDif Type=\"double\" Nb=\"?\" Def=\"1e9\">  </MaxDif> <!-- Inutilise pour l'instant-->\n",
"                <NBMaxMaxLoc Type=\"int\" Nb=\"?\" Def=\"5\"> </NBMaxMaxLoc>\n",
"\n",
"                <QuickExp Nb=\"?\" Type=\"bool\" Def=\"false\"> </QuickExp>\n",
"                <FMNT_ProgDyn Nb=\"?\">\n",
"                       <Regul Nb=\"1\" Type=\"double\"> </Regul>\n",
"                            <!-- Le cout de regul pour dun delta Z = D est\n",
"                                 (sqrt(1 +D/S0) -1) * 2S0  ; c.a.d un cout concave, qui\n",
"                                 en 0 est nul et de pente 1\n",
"                             -->\n",
"                       <Sigma0 Nb=\"1\" Type=\"double\"> </Sigma0>\n",
"                       <NbDir Nb=\"1\" Type=\"int\"> </NbDir>\n",
"                       <FMNT_GesNoVal Nb=\"?\">\n",
"                            <PenteMax Nb=\"1\" Type=\"double\"> </PenteMax>\n",
"                                <!-- GainNoVal : proportion du gain max; Gain 0 privilegie le NoVal -->\n",
"                            <CostNoVal Nb=\"1\" Type=\"double\"> </CostNoVal>\n",
"                             <Trans Nb=\"1\" Type=\"double\"> </Trans>\n",
"                        </FMNT_GesNoVal>\n",
"                </FMNT_ProgDyn>\n",
"                <ParamRegProf RefType=\"ParamFiltreDetecRegulProf\" Nb=\"?\"> </ParamRegProf>\n",
"           </SpecAlgoFMNT>\n",
"       </ParamAlgoFusionMNT>\n",
"\n",
"\n",
"       <!-- Decrit tout les fichiers qui vont declencher un calcul, le nom du resultat sera\n",
"           calculer avec KeyResult  -->\n",
"       <GenereRes Nb=\"1\" RefType=\"ParamGenereStr\"> </GenereRes>\n",
"          \n",
"       <!-- Pour chaque declencheur, genere les inputs -->\n",
"       <GenereInput Nb=\"1\" RefType=\"ParamGenereStrVois\"> </GenereInput>\n",
"\n",
"      <!-- Gestion du // par MkF -->\n",
"\n",
"       <SectionGestionChantier Nb=\"1\">\n",
"             <SzDalles Nb=\"?\" Type=\"int\" Def=\"2000\"> </SzDalles>\n",
"             <RecouvrtDalles Nb=\"?\" Type=\"int\" Def=\"40\"> </RecouvrtDalles>\n",
"             <ParalMkF Nb=\"?\" Type=\"std::string\"> </ParalMkF>\n",
"             <ByProcess Nb=\"?\" Type=\"bool\" Def=\"false\"> </ByProcess>\n",
"\n",
"             <!-- Ne pas utiliser, usage interne a la paralellisation -->\n",
"             <InterneCalledByProcess  Nb=\"?\" Type=\"bool\" Def=\"false\"> </InterneCalledByProcess>\n",
"             <InterneSingleImage Nb=\"?\" Type=\"std::string\" Def=\"\"> </InterneSingleImage>\n",
"             <InterneSingleBox Nb=\"?\" Type=\"int\" Def=\"-1\"> </InterneSingleBox>\n",
"             <WorkDirPFM Nb=\"?\" Type=\"std::string\"> </WorkDirPFM>\n",
"             <BoxTest Nb=\"?\" Type=\"Box2di\"> </BoxTest>\n",
"       </SectionGestionChantier>\n",
"\n",
"\n",
"  </ParamFusionMNT>\n",
"\n",
"  <!-- Pourra servir pour construire des affinite, homographie ... -->\n",
"\n",
"  <XmlAffinR2ToR  Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"         <CoeffX Nb=\"1\" Type=\"double\">   </CoeffX>\n",
"         <CoeffY Nb=\"1\" Type=\"double\">   </CoeffY>\n",
"         <Coeff1 Nb=\"1\" Type=\"double\">   </Coeff1>\n",
"  </XmlAffinR2ToR>\n",
"\n",
"\n",
"   <XmlHomogr  Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"        <X Nb=\"1\" RefType=\"XmlAffinR2ToR\">   </X>\n",
"        <Y Nb=\"1\" RefType=\"XmlAffinR2ToR\">   </Y>\n",
"        <Z Nb=\"1\" RefType=\"XmlAffinR2ToR\">   </Z>\n",
"   </XmlHomogr>\n",
"\n",
"\n",
"   <XmlRHHResLnk  Nb=\"1\" Class=\"true\"  ToReference=\"true\">\n",
"        <Hom12 Nb=\"1\"  RefType=\"XmlHomogr\">  </Hom12>\n",
"        <Ok Nb=\"1\"  Type=\"bool\">               </Ok>\n",
"        <Qual Nb=\"1\"  Type=\"double\">           </Qual>\n",
"        <NbPts Nb=\"1\"  Type=\"int\">           </NbPts>\n",
"        <EchRepP1 Nb=\"*\" Type=\"Pt3dr\" Container=\"std::vector\"> </EchRepP1>\n",
"        <PRep Nb=\"1\" Type=\"Pt3dr\"> </PRep>\n",
"   </XmlRHHResLnk>\n",
"\n",
"<Verbatim File=\".h.cpp\">\n",
"// };\n",
"</Verbatim>\n",
"<Verbatim File=\".h\">\n",
"#endif // Define_NotSupIm\n",
"</Verbatim>\n",
"\n",
"</GenCpp>\n",
"\n",
"\n",
"\n",
"","//#_-=+{}@$##$##@"};
