FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --fix-missing --install-recommends \
x11proto-core-dev make cmake libx11-dev mercurial subversion imagemagick gcc g++ \
exiv2 libimage-exiftool-perl libgeo-proj4-perl \ 
mesa-common-dev libgl1-mesa-dev libglapi-mesa libglu1-mesa \
qt5-default doxygen opencl-headers swig python3-dev graphviz cmake-curses-gui pkg-config


