list(APPEND Yann_Src_Files
		${YANN_DIR}/EstimHomogr.cpp
       	${YANN_DIR}/ExcludeSats.cpp
		${YANN_DIR}/gnss/SP3NavigationSlot.cpp
		${YANN_DIR}/gnss/Observation.cpp
		${YANN_DIR}/gnss/Observation.h
		${YANN_DIR}/gnss/AtmosphericModel.h
		${YANN_DIR}/gnss/ENUCoords.h
		${YANN_DIR}/gnss/ENUCoords.cpp
		${YANN_DIR}/gnss/SP3NavigationSlot.h
		${YANN_DIR}/gnss/SP3Reader.h
		${YANN_DIR}/gnss/AtmosphericModel.cpp
		${YANN_DIR}/gnss/ECEFCoords.h
		${YANN_DIR}/gnss/ECEFCoords.cpp
		${YANN_DIR}/gnss/RinexReader.h
		${YANN_DIR}/gnss/NavigationDataSet.h
		${YANN_DIR}/gnss/SP3NavigationData.h
		${YANN_DIR}/gnss/SP3NavigationData.cpp
		${YANN_DIR}/gnss/NavigationDataSet.cpp
		${YANN_DIR}/gnss/GPSTime.cpp
		${YANN_DIR}/gnss/GPSTime.h
		${YANN_DIR}/gnss/GloNavigationData.h
		${YANN_DIR}/gnss/GloNavigationData.cpp
		${YANN_DIR}/gnss/ObservationSlot.h
		${YANN_DIR}/gnss/NavigationSlot.h
		${YANN_DIR}/gnss/NavigationData.h
		${YANN_DIR}/gnss/GloNavigationSlot.h
		${YANN_DIR}/gnss/NavigationSlot.cpp
		${YANN_DIR}/gnss/SP3Reader.cpp
		${YANN_DIR}/gnss/ObservationData.h
		${YANN_DIR}/gnss/ObservationData.cpp
		${YANN_DIR}/gnss/NavigationData.cpp
		${YANN_DIR}/gnss/Statistics.h
		${YANN_DIR}/gnss/Statistics.cpp
		${YANN_DIR}/gnss/Solution.cpp
		${YANN_DIR}/gnss/Algorithms.h
		${YANN_DIR}/gnss/GeoCoords.h
		${YANN_DIR}/gnss/GeoCoords.cpp
		${YANN_DIR}/gnss/Solution.h
		${YANN_DIR}/gnss/ObservationSlot.cpp
		${YANN_DIR}/gnss/Algorithms.cpp
		${YANN_DIR}/gnss/GloNavigationSlot.cpp
		${YANN_DIR}/gnss/Utils.h
		${YANN_DIR}/gnss/Utils.cpp
		${YANN_DIR}/gnss/RinexReader.cpp
		${YANN_DIR}/gnss/Trajectory.h
		${YANN_DIR}/gnss/Trajectory.cpp
		${YANN_DIR}/gnss/Gnss.h
    )

list(APPEND Elise_Src_Files ${Yann_Src_Files})
