/*Header-MicMac-eLiSe-25/06/2007

    MicMac : Multi Image Correspondances par Methodes Automatiques de Correlation
    eLiSe  : ELements of an Image Software Environnement

    www.micmac.ign.fr


    Copyright : Institut Geographique National
    Author : Marc Pierrot Deseilligny
    Contributors : Gregoire Maillet, Didier Boldo.

[1] M. Pierrot-Deseilligny, N. Paparoditis.
    "A multiresolution and optimization-based image matching approach:
    An application to surface reconstruction from SPOT5-HRS stereo imagery."
    In IAPRS vol XXXVI-1/W41 in ISPRS Workshop On Topographic Mapping From Space
    (With Special Emphasis on Small Satellites), Ankara, Turquie, 02-2006.

[2] M. Pierrot-Deseilligny, "MicMac, un lociel de mise en correspondance
    d'images, adapte au contexte geograhique" to appears in
    Bulletin d'information de l'Institut Geographique National, 2007.

Francais :

   MicMac est un logiciel de mise en correspondance d'image adapte
   au contexte de recherche en information geographique. Il s'appuie sur
   la bibliotheque de manipulation d'image eLiSe. Il est distibue sous la
   licences Cecill-B.  Voir en bas de fichier et  http://www.cecill.info.


English :

    MicMac is an open source software specialized in image matching
    for research in geographic information. MicMac is built on the
    eLiSe image library. MicMac is governed by the  "Cecill-B licence".
    See below and http://www.cecill.info.

Header-MicMac-eLiSe-25/06/2007*/
#include "StdAfx.h"

int ascii2tif(int argc,char ** argv)
{
    std::string aPat("Ree*.tif");
    std::list<std::string> mLFile;
    bool aC2K(true);

    ElInitArgMain
            (
                argc,argv,
                LArgMain()  << EAMC(aPat,"ascii image pattern, images generated by irbis software (variocam hd thermal camera)",eSAM_IsPatFile),
              LArgMain()
                 << EAM(aC2K,"C2K", true, "conversion from cercius value to kelvin value *100, in order to got integer value instead of float.")
                );


    cInterfChantierNameManipulateur * aICNM = cInterfChantierNameManipulateur::BasicAlloc("./");
    // create the list of images starting from the regular expression (Pattern)
    mLFile = aICNM->StdGetListOfFile(aPat);

    std::cout << mLFile.size() << " ascii images detected\n";

    int SzX(1024), SzY(768);

    for (auto & aName : mLFile){


    std::cout << "Ascii to tif, image  " <<aName <<"\n";
    // crée une image Ram de taille adéquate
    Im2D_REAL4 aImRAM(SzX,SzY);

    // lecture du fichier ascii
    ifstream ascii(aName);
    std::string output;
    double aVal(0);
    // passe l'entête
    for (int i(0); i<(10-1);i++){ ascii >> output;}

    for (int l(0); l < SzY; l++)
    {
        for (int col(0); col < SzX; col++)
        {
           Pt2di aPos(col,l);
           ascii >> output;
           output[2]='.';
           FromString(aVal,output);
          // std::cout << "Valeur lue: " << aVal <<" , position " << aPos <<  "\n";
           aImRAM.SetR(aPos,aVal);
        }
    }

    if (aC2K)
    {

        std::cout << "conversion celcius vers Kelvin et multiplication par 100.\n";
        ELISE_COPY
                (
                    aImRAM.all_pts(),
                    100*(273.15+aImRAM.in()),
                    aImRAM.out()
                    );

    }

    std::string aNameTiff=aName.substr(0, aName.size()-3) + "tif";
    std::cout << "Ecriture de  " <<aNameTiff <<"\n";
    // sauve l'image
    ELISE_COPY
            (
                aImRAM.all_pts(),
                aImRAM.in(),
                Tiff_Im
                         (
                             aNameTiff.c_str(),
                             aImRAM.sz(),
                             GenIm::u_int2,
                             Tiff_Im::No_Compr,
                             Tiff_Im::BlackIsZero
                         ).out()
                );

    }

    return EXIT_SUCCESS;
}




int main_ascii2tif(int argc,char ** argv)
{
   ascii2tif(argc,argv);
   return EXIT_SUCCESS;
}



/*Footer-MicMac-eLiSe-25/06/2007

Ce logiciel est un programme informatique servant à la mise en
correspondances d'images pour la reconstruction du relief.

Ce logiciel est régi par la licence CeCILL-B soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL-B telle que diffusée par le CEA, le CNRS et l'INRIA
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'ucApplitilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant
donné sa spécificité de logiciel libre, qui peut le rendre complexe à
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement,
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité.

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
pris connaissance de la licence CeCILL-B, et que vous en avez accepté les
termes.
Footer-MicMac-eLiSe-25/06/2007*/


