set(uti_phgrm_ReducHom_Src_Files
    ${UTI_PHGRM_REDUCHOM_DIR}/CalcHcImage.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/cAppliReduc.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/cImagH.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/cPtHom.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/IndexAppli.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/SimulMerge.cpp
    ${UTI_PHGRM_REDUCHOM_DIR}/cParamMerge.cpp
)
